### ISSUE TITLE
Support for Vite?

### ISSUE THREAD

**Issue by flowt-au** [badeball/cypress-cucumber-preprocessor#1000]
I am wondering if there is any progress on supporting Vite? I see [this issue](https://github.com/badeball/cypress-cucumber-preprocessor/issues/698) related to component testing has been dormant for a year. 

I have a Quasar 2 (Vue3) Vite project that works with Cypress e2e testing. I would now like to use this cucumber plugin which I was able to do with previous Vue 2 projects.

Any thoughts?
Thanks,
Murray

**Comment by badeball** [comment]
You need to

- use the existing issue for questions about the issue
- further explain why vue2 works and vue3 doesn’t

**Comment by flowt-au** [comment]
Ok, Ta. 

1. The existing issue seems to be about component testing Cucumber with Vite (which, if I understand it, doesn't yet work). I am interested to know about Cucumber Vite e2e testing.
2. Quasar with Vue 2 used Webpack. Quasar with Vue 3 offers Vite. Vue 2 worked because webpack is supported. I am wondering whether Vite is supported because as I mentioned, that is what I am using: Quasar on top of Vue3 using Vite.

It might well be that I am missing something and can use one of your examples, but I cannot see one that will work with Vite.

Thanks for taking over this project. BDD is, IMO, a great way to go.

Cheers,
Murray

**Comment by flowt-au** [comment]
PS: I got a possible answer here: [https://stackoverflow.com/questions/76030846/how-to-get-cypress-cucumber-preprocessor-working-with-quasar-2-vue-3-and-vite/76032632#76032632](https://stackoverflow.com/questions/76030846/how-to-get-cypress-cucumber-preprocessor-working-with-quasar-2-vue-3-and-vite/76032632#76032632). I will close this issue once I check it out.
Thanks again.

**Comment by badeball** [comment]
There's no reason for you to think that you need Vite support in the preprocessor just because you're testing a Quasar application, assuming we're talking about E2E testing. What bundler you chose to bundle your tests simpy isn't affected by the test subject. I think you're misunderstanding something here.

**Comment by flowt-au** [comment]
@badeball Yes, you are correct, I **was** misunderstanding that the test bundler needed to match the dev bundler. I now have it working as per the [ SO answer](https://stackoverflow.com/questions/76030846/how-to-get-cypress-cucumber-preprocessor-working-with-quasar-2-vue-3-and-vite)

Thanks for your help. :-)
