### ISSUE TITLE
Update @cucumber/gherkin to dedupe

### ISSUE THREAD

**Issue by quinnturner** [badeball/cypress-cucumber-preprocessor#1004]
Current dependencies:

"@cucumber/cucumber": ^8.11.1
"@cucumber/gherkin": ^24.0.0

"@cucumber/cucumber": ^8.11.1 depends on "@cucumber/gherkin": 26.0.3

For cleanliness, this repository should also update its dependencies to use "@cucumber/gherkin": ^26.0.3

**Comment by badeball** [comment]
I don't consider this to be an issue and I definitely don't intend to make sure of this in the future. The gherkin module is published independently of Cucumber, which means that their latest versions doesn't necessarily match.
