### ISSUE TITLE
stepDefinitions not working as expected

### ISSUE THREAD

**Issue by erwanriou** [badeball/cypress-cucumber-preprocessor#1005]
### Current behavior

My folder structure is the current one and i am looking forward to change the default path for the `steps_definitions` as i don't use don't want to use the `cypress/support` default folder but instead a more classic `src/helpers` folder.

![Screenshot from 2023-04-25 02-50-00](https://user-images.githubusercontent.com/30130006/234148365-fa7c41a3-3b12-45bb-b7da-2a0ad9cc780b.png)

![Screenshot from 2023-04-25 02-50-22](https://user-images.githubusercontent.com/30130006/234148390-2f58c1e7-d38c-4724-9463-ee6cc4c8fb48.png)

Then after trying all the configurations i couldn't make this work:

![Screenshot from 2023-04-25 02-48-55](https://user-images.githubusercontent.com/30130006/234148289-4c3d1330-26ec-4b6a-8a53-446ab6689a68.png)

### Desired behavior

should work like the documentation describe here --> https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is answered in the document you linked to.

**Comment by erwanriou** [comment]
For the one like me that will struggle with this incredible documentation, here the information that the owner would never spoil.
 it only work if you add **MULTIPLE PATHS** and not one alone and you somehow are required to add these other [filepath] links even if you don't use them...

Here what i managed to make work with cypress 10:

```json
  "cypress-cucumber-preprocessor": {
    "stepDefinitions": [
      "src/tests/features/[filepath]/**/*.{js,ts}",
      "src/tests/features/[filepath].{js,ts}",
      "src/tests/step_definitions/**/*.{js,ts}"
    ]
  }
  ```

**Comment by badeball** [comment]
You stumbled upon the caveat explained at the bottom of the page.
