### ISSUE TITLE
Tests failing to to Cypress Task timeout

### ISSUE THREAD

**Issue by mattrlong** [badeball/cypress-cucumber-preprocessor#1006]
### Current behavior

Intermittently tests are failing with the following error: 
CypressError: `cy.task('cypress-cucumber-preprocessor:test-step-started')` timed out after waiting `60000ms`.

https://on.cypress.io/api/task

<img width="269" alt="image" src="https://user-images.githubusercontent.com/8707115/234213600-c306f754-69b4-4e08-8b97-1171eb0c5558.png">

### Desired behavior

Timeout issue does not occur. 

### Versions

* **Cypress version**: 12.1.0
* **Preprocessor version**: 16.0.3
* **Node version**: 16.17.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by mattrlong** [comment]
Thanks for the speedy response @badeball, given the issue is intermittent it's hard to share something reproducible. My setup was slightly different from the [cjs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/esbuild-cjs/cypress.config.js) example in your documentation, I'll try this and see if it helps. 

The issue appears 1 or 2 times in a run of ~80 scenarios.

**Comment by mattrlong** [comment]
Upon further investigation I believe this is due to steps taking longer than the taskTimeout configuration from Cypress. Extending this I am no longer seeing an issue, so will close.
