### ISSUE TITLE
Hook before is executed before the  background

### ISSUE THREAD

**Issue by freef1** [badeball/cypress-cucumber-preprocessor#1008]
### Current behavior
Hook `before` is executed before the  `background`
![2023-04-26_23-45-55](https://user-images.githubusercontent.com/91634349/234702674-30b662d5-c4fe-4c7c-9ebc-7ea7b9dcb08a.png)

### Desired behavior
Hook `before` is executed after the `background` and before the scenario."

### Test code to reproduce
I'm using the `before` hook as a tag `@createthreeusers` before the scenario, but it seems to be executing before the `background` instead of after it. I've searched everywhere for an answer but couldn't find one. Is there a solution to this? Thank you in advance for your help!"
![2023-04-26_23-44-15](https://user-images.githubusercontent.com/91634349/234702791-513c888a-9a6a-474c-8dae-d1fb81ca4666.png)
![2023-04-26_23-45-38](https://user-images.githubusercontent.com/91634349/234702819-69d2d061-5547-48c6-a1dd-2df60839b797.png)

### Versions

* **Cypress version**: 12.11.0
* **Preprocessor version**: 16.0.3
* **Node version**: 18.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is the intended behaviour of hooks.

**Comment by freef1** [comment]
> Это предполагаемое поведение хуков.

Thanks for the answer!
