### ISSUE TITLE
What is the process for writing back from the step definition to the feature file?

### ISSUE THREAD

**Issue by psaraogi** [badeball/cypress-cucumber-preprocessor#1010]
### Current behavior

Since we are integrating an API with UI automation, passing variable names in the feature file datatable . However, we require that the report should display the actual values that are returned from the API and be validated in the step definition.

  Feature Description

    Scenario: Log in to the app
    Given User is logged in to the application
    When I enter the following user information:
    | Name   | Email              |
    | <name> | <email_placeholder>|

Current Report
 When I enter the following user information:
    | Name   | Email              |
    | <name> | <email_placeholder>|

### Desired behavior
Desired cucumber html report

 When I enter the following user information:
    | Name   | Email              |
    | abc    | abc@gmail.com|

### Test code to reproduce
When('I enter the following user information:', function (dataTable) {
    dataTable.hashes().forEach((row) => {
      let name = "abc"; // Hardcoded value for name
      let email = "abc@gmail.com"; // Hardcoded value for email
      cy.wrap(email).as(`actualEmail_${name}`);
      cy.wrap(name).as(`actualName_${name}`);
      cy.get('@dataTableRows').then((rows) => {
        cy.log("step def -1 ");
        rows.push({          
          name: name,
          email: email,
          actualValue: '42' // Set the actual value here
        });
      });
    });
  });

### Versions

* **Cypress version**: 
*  "@badeball/cypress-cucumber-preprocessor": "^12.0.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    "cucumber-html-reporter": "^6.0.0",
    "cypress": "^12.11.0",

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This isn't a support forum, but FYI what you're talking about doesn't make any sense.
