### ISSUE TITLE
Cannot find module '@badeball/cypress-cucumber-preprocessor/esbuild'

### ISSUE THREAD

**Issue by johnpick1** [badeball/cypress-cucumber-preprocessor#1012]
### Current behaviour:
1. Update devDependencies `@badeball/cypress-cucumber-preprocessor`, from **v16.0.3** to **v17.0.0**.
2. Inspect the cypress.config.ts; `import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";`
3. Users will see error message '`Cannot find module '@badeball/cypress-cucumber-preprocessor/esbuild' or its corresponding type declarations.`'
4. Refer to guide: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md#example-setup

### Test code to reproduce:
1. Update `@badeball/cypress-cucumber-preprocessor` from v16.0.3 to v17.0.0.
2. Inspect the cypress.config.ts listed in; https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md
3. **Note**: if users rollback the version of `@badeball/cypress-cucumber-preprocessor` from **v17.0.0** to **v16.0.3**, they will no longer face the import/module issue.

### Versions:
```
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^17.0.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    "cypress": "^12.6.0",
   "ts-loader": "^9.4.2"
}
```

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#i-get-cannot-find-module-badeballcypress-cucumber-preprocessoresbuild

**Comment by johnpick1** [comment]
Thanks @badeball, great work by the way
