### ISSUE TITLE
Questions - Screenshot on every step and how to re-use the steps

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#1015]
I would like to clarify the below points.

- I can see the screenshot is available on the report when the tests fail. However, I would like to have a screenshot at every step. Is this configurable?

- In BDD-Java, usually, I can call the function because it will be inside a `public void function()` with an annotation. However, in Javascript it normally looks like below

```javascript
Given("I am a customer", () => {
  cy.log("INFO: User Login");
  initilizeRun();
});
```
Is there any way for me to call this step when the cucumber step definition is slightly different or I need to combine multiple steps?

**Comment by badeball** [comment]
Not a support forum.

**Comment by rakeshnambiar** [comment]
Thanks @badeball , may I ask where do I get the answers for these questions please? Do you have any gitter channel?

**Comment by rakeshnambiar** [comment]
I found that I will have to ask through Cypress discord :)
