### ISSUE TITLE
ct-vite-react-ts example - doesn't work with React 17. Is that expected?

### ISSUE THREAD

**Issue by enroly-mike** [badeball/cypress-cucumber-preprocessor#1016]
### Current behavior

I cloned the current repo and modified the package.json to use React 17 and then changed the mount import statement to use the cypress/react library.

### Desired behavior

Was hoping the minimal example would work with React 17 in much the same way it does with React 18. If React 18 is a hard dependency that fine as well, I just didn't know whether you were expecting that as i see you only made the commit to get it working yesterday.

Anyway either way thanks for your awesome work

### Test code to reproduce

Could do this is required, but its just 3 lines to change as per the current behaviour

### Versions

* **latest**:
* **latest**:
* **18**:

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Works seemingly fine when I try.

**Comment by enroly-mike** [comment]
Oh right ... sorry, then that's really odd. I'll try again and maybe move the conversation to the discussion forum. Thanks for checking it out

**Comment by enroly-mike** [comment]
Right you are, in my defence it was late last night :-) closing issue

**Comment by enroly-mike** [comment]
Just in case anyone finds themselves on this page in the future I continued to have strange issues with React 17, CT and the Cypress Cucumber plugin. I was getting the following error on anything more than the most basic example.

```
[plugin:vite:import-analysis] Failed to resolve import "scheduler/unstable_mock" from "node_modules/.vite/deps/cypress_react.js?v=8ba4ff1a". Does the file exist?
/Users/mike/dev/enroly/cas-shield/typescript/frontend/uni/student-list-beta/node_modules/.vite/deps/cypress_react.js:1:45
1  |  import * as __require_for_vite_aeyS19 from 'scheduler/unstable_mock';
   |                                              ^
2  |  import {
3  |    require_object_assign
```

To resolve this issue I needed to manually install **scheduler** as a DevDependency.
