### ISSUE TITLE
Unable to generate JSON report when hook is defined

### ISSUE THREAD

**Issue by aartajew** [badeball/cypress-cucumber-preprocessor#1017]
### Current behavior

If you define an After or Before hook in your step definition files, there is no way to generate JSON report - the parser fails.

### Desired behavior

Proper JSON report should be generated when using hooks.

### Test code to reproduce

https://github.com/aartajew/cypress-cucumber-bug-hooks

### Versions

* **Cypress version**: v12.12.0
* **Preprocessor version**: v17.1.0
* **Node version**: v18.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey @aartajew, thanks for putting together an example for me. This is caused by reload-behavior seen when `baseUrl` is _not_ defined and this has been a headache, to put it mildly. As a workaround, you can specify `baseUrl`, provided that you only have a single domain to test.

**Comment by badeball** [comment]
Solving this means getting rid of [this](https://github.com/badeball/cypress-cucumber-preprocessor/blob/v17.1.0/lib/registry.ts#L61) undeterministic part.

**Comment by aartajew** [comment]
Yes, it works with `baseUrl` defined, and it must actually match the site you are visiting in the test 😄 
Thanks for quick reply, I'll use it as a quick workaround!

**Comment by badeball** [comment]
This fixed with v17.1.1.
