### ISSUE TITLE
The configuration option "omitFiltered" isn't respected by the Cucumber HTML report

### ISSUE THREAD

**Issue by hammzj** [badeball/cypress-cucumber-preprocessor#1018]
### Current behavior

To begin, my framework has the preprocessor configured in the `package.json` as such:
```json
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "omitFiltered": true,
    "messages": {
      "enabled": true,
      "output": "reports/cucumber-messages.ndjson"
    },
    "html": {
      "enabled": true,
      "output": "reports/cucumber-report.html"
    }
  },
```

I have a feature with four scenarios in it. I decided to target running only one using a `@focus` tag. When I execute it with `cypress run`, the STDOUT is showing only one scenario being executed; this is the desired behavior:

<img width="881" alt="Screenshot 2023-05-12 at 2 08 19 PM" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/ed63ded5-cd51-4c8c-bf41-bf05a80e32c9">

***

However, when I open the Cucumber HTML report, it shows that only 25% of the scenarios passed: 1 passed, and 3 unknown of 4 total executed:

<img width="1437" alt="Screenshot 2023-05-12 at 2 05 55 PM" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/5893da6f-19e7-429b-aa33-2159c2869d7e">

This is incorrect, as I only executed one scenario.

### Desired behavior

When `omitFiltered=true` and HTML reports are enabled, we should not see any unknown scenarios print out. Only the passed and failed scenarios should be displayed.

### Test code to reproduce

Set preprocessor configuration:
```json
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "omitFiltered": true,
    "messages": {
      "enabled": true,
      "output": "reports/cucumber-messages.ndjson"
    },
    "html": {
      "enabled": true,
      "output": "reports/cucumber-report.html"
    }
  },
```

Have a feature with more than one scenario in it. Tag a scenario with `@focus` , then run `cypress run --env TAGS='@focus'`

 View generated HTML report.

### Versions

* **Cypress version**: 12.9.0
* **Preprocessor version**: 16.0.3
* **Node version**:v16.19.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hi @hammzj, I've fixed this with v17.1.1.
