### ISSUE TITLE
v17.0.0 not working

### ISSUE THREAD

**Issue by kyogitq** [badeball/cypress-cucumber-preprocessor#1020]
### Current behavior

We just bumped the version from 16.0.3 to 17.0.1. Now when we run the cypress run command we get
`Cucumber preprocessor detected that you returned a native promise from a function handler, this is not supported. Using async / await is generally speaking not supported when using Cypress, period, preprocessor or not.`

`at runStepWithLogGroup ([webpack:///../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/cypress.js:16](http://localhost:62455/__/#))
    at Context.eval ([webpack:///../../node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:246](http://localhost:62455/__/#))
From previous event:
    at Context.thenFn (http://localhost:62455/__cypress/runner/cypress_runner.js:139218:63)
    at Context.then (http://localhost:62455/__cypress/runner/cypress_runner.js:139640:21)
    at wrapped (http://localhost:62455/__cypress/runner/cypress_runner.js:157508:19)
    at <unknown> (http://localhost:62455/__cypress/runner/cypress_runner.js:156244:15)
From previous event:`

### Versions

* **Cypress version: *10.11.0*:
* **Preprocessor version: 17.0.1**:
* **Node version:18.*:

**Comment by badeball** [comment]
Intended behavior as far as I can tell. Read the error.

**Comment by kyogitq** [comment]
It's working fine for the version 16.0.3 but the issue started when we upgraded version to 17.0.1. Also there is no any native promise returned from function in our code. Is it the issue with cypress version?

**Comment by badeball** [comment]
> Also there is no any native promise returned from function in our code.

I highly doubt that this is true.

In any case, if you think you've found a bug, you need to provide a reproducible example like the issue template suggested (which you conveniently ignored).

**Comment by GarciaDan** [comment]
@kyogitq try searching in your definition steps a code like the following:

```gherkin
Given(
  "my step with my {string} parameter",
  async (myParameter: string) => { /* code */ })
```
My past me coded a step in that way (don't ask me why 🤷) and, as you said, it has been working in the previous versions but it started failing from the 17.0.1 on. 

However, removing that `async`, as the error states, fixed my test and now everything is working.

**Comment by kyogitq** [comment]
@GarciaDan Thankyou. Yeah there was a code using async. After I removed it , it worked fine with new 17 version. Once again thankyou.
