### ISSUE TITLE
How can I set retry mechnism for the entire FF?

### ISSUE THREAD

**Issue by huiyangns** [badeball/cypress-cucumber-preprocessor#1021]
I'm wondering how I can go about using custom configurations for the entire FF, as is [described here in the Cypress documentation](https://docs.cypress.io/guides/guides/test-retries#Custom-Configurations) Test Suite(s) part. Specifically I'm looking to set test retries for the entire feature file instead of individual scenario.

I have read https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/test-configuration.md and @retries(5) tag takes effect for failed individual scenarios. But I want to rerun the entire FF if one scenario fails.

Is it possible or how to set this?

**Comment by badeball** [comment]
Not possible AFAIK.

**Comment by badeball** [comment]
For reference: this plugin is limited to Cypress’ scope and can’t do anything that you couldn’t normally do with Cypress.

**Comment by huiyangns** [comment]
Copy that...
Thanks for the reply
