### ISSUE TITLE
Inability to Select Menu Item in Cypress Test due to POM Parameterisation Limitation

### ISSUE THREAD

**Issue by ecvanlare** [badeball/cypress-cucumber-preprocessor#1022]
### Current behavior

When attempting to navigate to the Admin levels by selecting the 'Admin' menu item using the Cypress test, the following error occurs: "Timed out =retrying after 10000ms: Cannot read properties of undefined (reading 'toLowerCase')". This issue is believed to be caused by a limitation encountered when trying to parametrise the string value from the BDD step down to the page element in the Cypress test. 

### Desired behavior

The 'Clubs' menu item should be successfully selected without any errors.

### Test code to reproduce

Run the Cypress test with the following feature scenario:
vbnet

Feature: Admin Menu Navigation

   Scenario: Navigate Clubs Page
    And I select the 'Clubs' tab
Observe the Cypress Test Runner GUI.
Expected Result:
The 'Clubs' menu item should be successfully selected without any errors, allowing navigation to the Clubs Page.

Expected Behavior:
Upon selecting the "Clubs" tab, it should successfully navigate to the corresponding page without any errors.

Actual Behavior:
The "Clubs" tab selection fails, and the expected navigation does not occur. The test execution does not proceed as expected, leading to a test failure.

Additional Information:

This issue is believed to be a limitation experienced when trying to parametrise the string value from the BDD step down to the page element in the Cypress test.

The parameter value provided in the BDD step is not being passed correctly or is not matching the element on the page, resulting in the undefined property error.

The test code consists of the following files:

players_page.feature

```
javascript

import { When } from 'cypress-cucumber-preprocessor/steps';
import { playersPageDefinitions } from './playersPageDefinitions';

When('I select the {string} tab', (menuItem) => {
	PlayersPageDefinitions.selectMenu(menuItem)
})

```
playersPageDefinitions.js

```
javascript

import playersPage from './playersPage';

export const playersPageDefinitions = {
  selectMenu(sideMenu) {
    cy.get(navigationMenu.menuElements.menuBar(menuItem))
      .should('be.visible')
      .click();
  },
};
```
navigationMenu.js

```
javascript

const navigationMenu = {
	get pageElements() {
		return {
			menuBar(menu) {
				return cy.xpath(`//a[@role='menuitem'][.='${menu}']`)
			},
		}



export default adminPage;
```
The error occurs at the line cy.get(navigationMenu.menuElements.menuBar(menuItem)).should('be.visible').click(); in the playersPageDefinitions.js file.

Manually inspecting the page confirms that the menu item with the label "Clubs" exists and is visible.

Code Snippets:
Step 14: And I select the 'Clubs' tab
15: xpath//a[@role='menuitem'][.='Clubs']
16: get{specwindow: <window>, chainerid: ch-[https://www.premierleague.com-167}](https://www.premierleague.com-167%7D/)
17: assertexpected { Object (0, length) } to be visible
18: get.fantasySignInLabel
19: assertexpected <span.fantasySignInLabel> to be visible

### Cypress Version

12.12.0

### Node version

19.2

### Operating System

mac OS Ventura 13.3.1

### Other

Additional Information:

This issue may be related to a limitation in parameterising the string value from the BDD step down to the page element in Cypress tests.
The relevant code consists of the following files:

players_page.feature with the step definition for selecting the menu.
playersPageDefinitions.js with the method for selecting the menu item using the page object.
playersPage.js defining the page object with the menu item selector.
Manually inspecting the page confirms the existence and visibility of the 'Clubs' menu item.
In the third testcase i've shown the workaround in the step 'And I navigate to the 'Clubs' page'

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by ecvanlare** [comment]
as requested reproducible example [CypressPrem-Tiny.zip](https://github.com/badeball/cypress-cucumber-preprocessor/files/11565567/CypressPrem-Tiny.zip)

**Comment by badeball** [comment]
Neither of those tests yield the error you've described in your post. Have you even tried running the example yourself?

Furthermore, you're not actually using this library, but an old implementation (explained [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

Lastly, have you tried googling the error? Because I did and found what I presume to be the answer to your problem.

**Comment by ecvanlare** [comment]
Thank you for your response regarding the issue I raised. I apologise for any confusion caused by my initial bug report. Unfortunately, I was unable to share the original code due to it being proprietary to my organisation. However, I have created a small repository that replicates the issue I am experiencing.

Regarding your suggestions, I understand that the provided code snippets may not reflect the exact implementation or usage of the library. I appreciate your clarification and will ensure to use the appropriate implementation moving forward.

Additionally, I did attempt to search for a resolution by googling the error but was unable to find a suitable solution. It is possible that my search queries did not yield the desired result.

To assist in resolving the issue, I have updated the repository with a simplified test case that reproduces the problem consistently. 
[CypressPrem-Tiny.zip](https://github.com/badeball/cypress-cucumber-preprocessor/files/11611384/CypressPrem-Tiny.zip)


I kindly request you to take another look at the replicated issue in the provided repository. It should help in identifying the root cause and finding a resolution. If you require any further information or assistance, please let me know, and I'll be happy to provide it.

Thank you for your attention to this matter, and I look forward to your continued support in resolving the issue.

**Comment by badeball** [comment]
You're still not using this library. You're asking for support for a different library. And this is indeed a support request, you have not found a "limitation". This however is not a support forum. I encourage you to take a closer look at your own code and see if you're violating the interfaces of any Cypress commands.

Closing as not an issue with the preprocessor.
