### ISSUE TITLE
Task 'test-step-finished' failed with timeout

### ISSUE THREAD

**Issue by samixchoumi** [badeball/cypress-cucumber-preprocessor#1027]
### Current behavior
Got a timeout for a step of the plugin on one test, then the other test crash at the start and all the feature file is avoided.

First test : 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/22171928/a110c18a-9353-47fc-b98c-3c53268810af)

Second test : 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/22171928/6028d58d-8a44-4e9b-8469-ff2b341acb37)

Got it from the CI build, no problem yesterday. Retried it, got the same problem.
When launching the command using `cypress open`, I don't reproduce it.
Same when launching the command using `cypress run`.

### Desired behavior

No bug.

### Test code to reproduce

Can't send our test code because of some credential used to access the preprod env.

### Versions

* **Cypress version**: `"^12.12.0",`
* **Preprocessor version**: `"^17.1.0"` (didn't upgraded because on the 17.1.1, I got another bug, it create a cucumber folder that make my reporting fail using mocha)
* **Node version**: `v18.12.1`

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> Can't send our test code because of some credential used to access the preprod env.

Read through ["Reduced test case"](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) one more time and try again.

**Comment by samixchoumi** [comment]
@badeball I don't reproduce it when launching in local, I could try to make a reduced test case if I could reproduce it, at least, in local.
I'm updating to the last version, it add a fix to the step failing, I hope it will fix it 👍

**Comment by badeball** [comment]
It should come as no surprise that I can't help you here. Feel free to open up another issue if you can reproduce it locally.

**Comment by samixchoumi** [comment]
I understand, for your information, it seem to works using `--browser electron` instead of `--browser chrome`, very strange because nothing change on these test about 2/3 weeks now.

**Comment by samixchoumi** [comment]
Found a way to avoid the problem (if anyone got it too), add a `cy.wait()` of 1 second, for example at the end of your last step, and it will pass. I tried a lot of thing to make it works properly but the only solution was to use that.

Maybe it's a regression linked to the use of `cypress-recurse` plugin (it's the only test that i have that use it as a last step) and it's under a `foreach`.
