### ISSUE TITLE
Step Implementation Error then {} function 

### ISSUE THREAD

**Issue by awaiskhalil** [badeball/cypress-cucumber-preprocessor#1029]
### Desired behavior

User should be able to run any cucumber feature file with default configuration setting instead of changing and adding file name in stepDefinitions every time. 

### Test code to reproduce
https://github.com/awaiskhalil/TestAutomation

### Versions

* **Cypress version**: 10.11.0
* **Preprocessor version**: 4.3.1
* **Node version**: v18.13.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm using `cypress-cucumber-preprocessor@4.3.1`

**Comment by awaiskhalil** [comment]
Error
Step implementation missing for "315 Add container in demo".

We tried searching for files containing step definitions using the following search pattern templates:

- cypress/e2e/AddPaymentGTD/*.{js,ts}
- cypress/e2e/[filepath].{js,ts}
- cypress/support/step_definitions/*.{js,ts}

These templates resolved to the following search patterns:

- cypress\e2e\AddPaymentGTD\.{js,ts}
- cypress\e2e\cypress\e2e\AddTruckerKeyApmt.{js,ts}
- cypress\support\step_definitions\.{js,ts}

These patterns matched the following files:

- cypress\e2e\AddPaymentGTD\AddPaymentGTD.spec.js

However, none of these files contained a step definition matching "315 Add container in demo".

You can implement it using the suggestion(s) below.

Given("{int} Add container in demo", function (int) {
return "pending";
});

Given("{float} Add container in demo", function (float) {
return "pending";
});
[node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:300:1](https://demopremium.emodal.com/__/#)
<img width="473" alt="then function error in cypress cucumber" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/17334723/ed9de09e-de6e-4729-8c7c-b0f17ccf53f6">

**Comment by badeball** [comment]
You need to provide a complete, runnable example and not just your configuration.

**Comment by awaiskhalil** [comment]
I tried to upload again more files but due to file restrictions i'm not able to add 'node_modules' folder as it contains more than 100 files. If you can check with newly added files. 
Yowza, that’s a lot of files. Try uploading fewer than 100 at a time.

**Comment by badeball** [comment]
You should read the documentation on [step definitions](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md). Closing as not an issue with the preprocessor.
