### ISSUE TITLE
Attempting to run mytest.js results in Error: Unexpected state in beforeSpecHandler: before-spec (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

### ISSUE THREAD

**Issue by mraphael2101** [badeball/cypress-cucumber-preprocessor#1031]
### Current behavior

An error was thrown in your plugins file while executing the handler for the before:spec event.

The error we received was:

Error: Unexpected state in beforeSpecHandler: before-spec (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
    at createError (/Users/id/Documents/workspace_javascript/cypress_complete_crash_course/node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/error.js:9:12)
    at beforeSpecHandler (/Users/id/Documents/workspace_javascript/cypress_complete_crash_course/node_modules/@badeball/cypress-cucumber-preprocessor/dist/plugin-event-handlers.js:197:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Desired behavior

The test executes in the WebStorm IDE as normal (Build #WS-231.9011.35, built on May 16, 2023)

### Test code to reproduce

    it("Test to parse WebTables", function () {
        cy.visit("https://rahulshettyacademy.com/AutomationPractice/")

        cy.get("tr td:nth-child(2)").each(($el1, index, $list) => {

            const text = $el1.text()

            if (text.includes('Python')) {

                cy.get("tr td:nth-child(2)")
                    .eq(index)
                    .next()
                    .then(function (price) {
                        const priceText = price.text()
                        expect(priceText).to.equal('25')
                    })
            }

        })
    })

})

[1] https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case

-->

### Versions

    "@badeball/cypress-cucumber-preprocessor": "^17.2.0",
    "@cypress/browserify-preprocessor": "latest",
    "cypress": "^12.12.0"
* **Node version**: v19.0.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hi @mraphael2101, can you try updating to the latest version?

**Comment by mraphael2101** [comment]
"@badeball/cypress-cucumber-preprocessor": "^17.2.1",
    "@cypress/browserify-preprocessor": "latest",
    "cypress": "^12.13.0"
Upgrading to the above versions and reinstalling cypress solved the issue, thanks.
