### ISSUE TITLE
Error: spawn cucumber-json-formatter ENOENT

### ISSUE THREAD

**Issue by awaiskhalil** [badeball/cypress-cucumber-preprocessor#1032]
### Current behavior

An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

Error: spawn cucumber-json-formatter ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
### Desired behavior
I want to generate cucumber html report

### Test code to reproduce

my index.js file includes following: 
/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

/**
 * @type {Cypress.PluginConfig}
 */
// eslint-disable-next-line no-unused-vars
//module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
// return config;
//}

//const xlsx_methods = require("@emodal/cypress/common/xlsx-methods")
const cucumber = require('cypress-cucumber-preprocessor').default
const fs = require('fs');

module.exports = (on, config) => {
  on('file:preprocessor', cucumber()),
  on('after:run', (results) => {
    if (results) {
      fs.mkdirSync("cypress/.run", { recursive: true });
      fs.writeFile("cypress/.run/results.json", JSON.stringify(results));
    }
  })
}
  
### Versions

* **Cypress version**: 10.11.0
* **Preprocessor version**: 4.3.1
<img width="575" alt="cucumber json formatter error" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/17334723/9c0f020d-e58b-4221-8b5f-bec07c35bf20">

* **Node version**: v18.13.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
The package has moved to `@badeball/cypress-cucumber-preprocessor`, read more about the transfer [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689), IE. you're not using the most recent version, but you should.

**Comment by badeball** [comment]
@awaiskhalil, in the future you need to provide runnable examples. Your posted code doesn't even reference `cucumber-json-formatter`, so what in the world am I supposed to do with this.

**Comment by awaiskhalil** [comment]
@badeball ok thanks for the sharing the info. let me update and if i require any help i will log the issue again.

**Comment by badeball** [comment]
This is not a support forum.
