### ISSUE TITLE
Sequential tests crashing after first test is finished when enabling Pretty output

### ISSUE THREAD

**Issue by RazvanVuscan** [badeball/cypress-cucumber-preprocessor#1033]
### Current behavior

Currently, once enabling the following feature in the cypress.config.ts file

```
reporter: require.resolve(
            '@badeball/cypress-cucumber-preprocessor/pretty-reporter'
        ),
```

, when running several tests in succession the following error being thrown once the first test finishes:

<img width="1186" alt="Screenshot 2023-06-14 at 13 25 53" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/4265489/ed98cc83-3f20-452c-a8f2-ea85308e81c4">

When running only a single test, everything works as expected - the steps are shown in order and the test finishes successfully.

### Desired behavior

Users should be able to run tests in succession when enabling Pretty output.

### Test code to reproduce

cypress.conf.js file looks like this:

<img width="535" alt="Screenshot 2023-06-14 at 13 29 04" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/4265489/bdcc17cf-1d00-47cf-ba97-811bc6de62b2">

tsconfig.json looks like this:

<img width="1014" alt="Screenshot 2023-06-14 at 13 29 46" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/4265489/441474ab-fbcc-48c1-865b-cd5e16ba7297">

The only issue is when actually adding  

```
reporter: require.resolve(
            '@badeball/cypress-cucumber-preprocessor/pretty-reporter'
        ),
```

to the cypress.conf.ts file. Setting everything else up without the specific config will run the tests just fine, but the Pretty steps will not be output (as expected).

NOTE: I am using @badeball/cypress-cucumber-preprocessor in correlation with @bahmutov/cypress-esbuild-preprocessor v2.2.0.

### Versions

* **Cypress version**: 12.14.0
* **Preprocessor version**:18.0.0
* **Node version**:19.8.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. I'm not able to reproduce the issue given the provided information. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by RazvanVuscan** [comment]
@badeball I have found the issue.

If you have a block of code like this in your _cypress.conf.ts_ file:

```
async setupNodeEvents(
            on: Cypress.PluginEvents,
            config: Cypress.PluginConfigOptions
        ): Promise<Cypress.PluginConfigOptions> {
            await addCucumberPreprocessorPlugin(on, config);
            
            on(
                'after:spec',
                (spec: Cypress.Spec, results: CypressCommandLine.RunResult) => {
                    deleteVideoForSuccessfulRuns(results);
                }
            );

            return config;
});
```

Where:

```
export const deleteVideoForSuccessfulRuns = (
    results: CypressCommandLine.RunResult
): any => {
    if (results?.video) {
        // Do we have failures for any retry attempts?
        const failures = results.tests.some(({ attempts }) =>
            attempts.some(({ state }) => state === 'failed')
        );
        if (!failures) {
            // delete the video if the spec passed and no tests retried
            rimraf(results.video)
                .then(() => {
                    console.log(
                        `Video deleted after successful test run: ${results.video}`
                    );
                })
                .catch((error: any) => {
                    console.error(`Error deleting file: ${error}`);
                });
        }
    }
};
```


Then, the above error I mentioned in the original message occurs.

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md

**Comment by RazvanVuscan** [comment]
Thank you @badeball , I missed that part in the docs! So it was because I was overwriting the event handler.
