### ISSUE TITLE
Cucumber html report showing incorrect metrics and attached images

### ISSUE THREAD

**Issue by ijaved** [badeball/cypress-cucumber-preprocessor#1034]
### Current behavior

Currently, only failed screenshots are attached in the html report and I am looking to also add screenshots to passing scenarios. I have added an `After` hook to take a screenshot for passing tests and the Cypress `screenshotOnFailure` is default to `true` which will take a screenshot for failing scenarios as the `After` hook is skipped in failed tests. In the example, there are 2 tests in the feature file one fails and the other passes. The html report shows this as `1 FAILED` and `1 SKIPPED` with `0% passed`. The failed test has attached images for both tests and the passing test has the correct image attached.

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/5762fc13-5894-4c0f-93e7-5f3d6c5c5d18)

### Desired behavior

Cucumber html report should show correct metrics for passing/failing tests along with a single attached image

### Reproduce issue

Added example to: https://github.com/ijaved/cypress-cucumber-preprocessor-reporting-example/tree/main

### Versions

* **Cypress version: 14.14.0**:
* **Preprocessor version: 18.0.0**:
* **Node version: 16.16.0**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by ijaved** [comment]
Hi, @badeball, I have added a minimal example to https://github.com/ijaved/cypress-cucumber-preprocessor-reporting-example/tree/main

**Comment by badeball** [comment]
I've fixed and released this as v18.0.1.
