### ISSUE TITLE
Cucumber html report and command line metrics not correct when feature has a pending scenario

### ISSUE THREAD

**Issue by ijaved** [badeball/cypress-cucumber-preprocessor#1035]
### Current behavior
Currently, when a feature has a pending scenario the html report includes this as an `executed` test rather than skipping it. In the screenshot, it should be 2 executed. Also, the remaining steps in the undefined scenario are being shown as skipped but should also be pending. The first step in the undefined scenario has an attached image (due to the scenario being executed and reporting a fail) which should not be present as the scenario should not be executed.
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/d4e6ee63-4732-4f00-9152-1386160d7c1f)

On the command line, the undefined test scenario is counted as a failed test
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/9441ca59-1966-4e3f-85e6-c9bf7d35916c)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/d7d5273a-5169-4213-8209-b4621f163ba0)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/35183d9a-9d5a-4b99-84c7-fdca5ff4ac37)

If a feature has 2 tests which pass with 1 undefined scenario the report shows the run as undefined rather than a pass (red underscore)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/50fa91d2-37b6-46ff-b876-e61de562477d)

Command line showing undefined scenario as a fail
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/0ecb86f1-e720-491f-ad79-a5f7d3844096)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/82070e8e-df55-4911-950e-1a3d40176d68)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/494f7102-0b88-4d32-926a-bc74a1f2222e)

### Desired behavior
Cucumber html report and command line runner should report the correct metrics when a feature is run and pass or fails with an undefined scenario

### Test code to reproduce
Run examples in README: https://github.com/ijaved/cypress-cucumber-preprocessor-reporting-example

### Versions
* **Cypress version: 14.14.0**:
* **Preprocessor version: 18.0.1**:
* **Node version: 16.16.0**:

### Checklist
- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> Currently, when a feature has a pending scenario the html report includes this as an `executed` test rather than skipping it. In the screenshot, it should be 2 executed.

Why do you think so?

> If a feature has 2 tests which pass with 1 undefined scenario the report shows the run as undefined rather than a pass (red underscore)

Are you implying that it shouldn't? If so, why?

**Comment by ijaved** [comment]
@badeball 

> Currently, when a feature has a pending scenario the html report includes this as an executed test rather than skipping it. In the screenshot, it should be 2 executed.

There's an argument that the test scenario steps do not have matching step definitions to run so although the test is included in the test run it hasn't actually run. However, the current working way is fine.

> If a feature has 2 tests which pass with 1 undefined scenario the report shows the run as undefined rather than a pass (red underscore)

Again, this is probably correct behaviour as all tests passing will show the green icon with a tick beside the accordion header `feature/<feature-name>.feature` and in the example there is an undefined scenario which is why it has the yellow icon with question mark.

Although, the command line metrics in the screenshots showing undefined tests as failing should be addressed.. Should also consider skipped tests which may show as failing although I haven't tested this...

**Comment by badeball** [comment]
Closing as not an issue with the preprocessor.

**Comment by ijaved** [comment]
@badeball 
For the undefined scenario, the remaining 3 steps are showing the `skipped` icon but should all show the `undefined` icon as they do **not** have any associated step definitions.

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/02db145c-d0e0-4d79-84a3-77337b8e0ff9)
