### ISSUE TITLE
Cucumber html report does not show test results when after hook fails

### ISSUE THREAD

**Issue by ijaved** [badeball/cypress-cucumber-preprocessor#1037]
### Current behavior

If the cypress after hook fails then the html report is not showing test results and metrics. 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/86f02d39-2990-4412-932a-f938e955e3cc)

In the command line, the example has 2 passing tests but the 2nd test is shown as `failing` due to the after hook failing but the test ran before the after hook and is passing
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/2241a176-8630-4fd5-8d1c-34d1d7fafed2)

### Desired behavior
Cucumber html report should show tests results/metrics if the after hooks fails

### Test code to reproduce
Run example `Pass/After hook fail report:` in README: https://github.com/ijaved/cypress-cucumber-preprocessor-reporting-example

### Versions
* **Cypress version: 14.14.0**:
* **Preprocessor version: 18.0.1**:
* **Node version: 16.16.0**:

### Checklist
- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is intended behaviour. The message doesn’t specifically mention HTML reports, but it should.
