### ISSUE TITLE
NPM installing @badeball/cypress-cucumber-preprocessor failing on windows 

### ISSUE THREAD

**Issue by Ankith-K** [badeball/cypress-cucumber-preprocessor#1038]
### Current behavior

- Attempting to install @badeball/cypress-cucumber-preprocessor version 12.0.1 from npm registry. https://www.npmjs.com/package/@badeball/cypress-cucumber-preprocessor/v/12.0.1 .
- Works on macs but now windows machines. 
- Error: 
<img width="1334" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/66974569/53e62968-5a47-4c1d-a4c7-5d444f327926">

- Does not work with other versions of badeball (13, 14, 15, 16)
- Am able to install fine on macs/linux machines, but not windows machines.

### Desired behavior

- @badeball/cypress-cucumber-preprocessor should install with npm install.

### Test code to reproduce

- Run `npm install @badeball/cypress-cucumber-preprocessor@12.0.1` in the terminal of your node project's root directory to install this package into your package.json.
- Can run with different versions of the package as well: `npm install @badeball/cypress-cucumber-preprocessor@<different package version>`

### Versions

* **Cypress version**: cypress v. 12.3.0
* **Preprocessor version**: @cypress/webpack-preprocessor v. ^5.17.1
* **Node version**: node v. 16.19.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This isn’t something I can help you with. For reference, that’s esbuild erroring.

**Comment by badeball** [comment]
Possibly related issue: https://github.com/evanw/esbuild/issues/467#issuecomment-1148404256

**Comment by Ankith-K** [comment]
Ok, thanks @badeball !
