### ISSUE TITLE
Cucumber tests metrics incorrect when there is an undefined scenario and after hooks fail

### ISSUE THREAD

**Issue by ijaved** [badeball/cypress-cucumber-preprocessor#1039]
@badeball 
Please refer to https://github.com/cypress-io/cypress/issues/27064 and also raised https://github.com/badeball/cypress-cucumber-preprocessor/issues/1035 for reference

Maybe the following code in `/lib/registry.ts` which checks for matching step definitions should not throw an error?
```
    if (matchingStepDefinitions.length === 0) {
      throw new MissingDefinitionError(
        `Step implementation missing for: ${text}`
      );
```

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by ijaved** [comment]
@badeball I believe this should be re-opened as the [cucumber documentation](https://cucumber.io/docs/cucumber/api/?lang=javascript) has the following for scenario steps:

>Undefined
When Cucumber can’t find a matching step definition, the step gets marked as undefined (yellow), and all subsequent steps in the scenario are skipped.

> Failed Steps
When a step definition’s function is executed and raises an error, the step is marked as failed (red).

**Comment by badeball** [comment]
What are you implying is wrong now?

**Comment by ijaved** [comment]
@badeball If a scenario contains a test step which is undefined, it should **not** show as **failing** in the command line rather it should be **undefined** which is currently not a column in the Spec table once the run has finished.

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/c15da70f-764e-41c0-bf8a-bc2465f93fbc)

**Comment by badeball** [comment]
Plugins have a limited scope to work within and that output is outside of a plugin's control.
