### ISSUE TITLE
HTML report shows as Unknown for a scenario using @skip tag

### ISSUE THREAD

**Issue by ijaved** [badeball/cypress-cucumber-preprocessor#1041]
### Current behavior
As per Smart tagging in: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md

Scenario with `@skip` shows as as Unknown in HTML report. 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/eb19e249-2177-43f2-b863-c57513af19aa)

Command line also shows the scenario as `Pending` but should be `Skipped`
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/7203790/d1463d70-087d-4db2-bfac-ff88fc0c224c)

### Desired behavior

Scenarios with `@skip` tag should show as `Skipped` in the HTML report and on command line when tests have run

### Test code to reproduce

Run Skipped report as detailed in: https://github.com/ijaved/cypress-cucumber-preprocessor-reporting-example/blob/main/README.md

### Versions

* **Cypress version: 12.14.0**:
* **Preprocessor version: 18.0.1**:
* **Node version: 16.16.0**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> Command line also shows the scenario as `Pending` but should be `Skipped`

No, this is part of Cypress nomenclature outside of my control, EG. discussed [here](https://github.com/cypress-io/cypress/issues/3092).

As far as the HTML report go - you're right, skipping isn't handled gracefully in terms of reporting. This includes returning `"skipped"` from hooks & steps, as well as any tag filtering in general.

For future reference, skipping steps in cucumber-js is partially described [here](https://github.com/cucumber/cucumber-js/blob/main/features/skipped_steps.feature) and then there's some [undescribed functionality](https://github.com/cucumber/cucumber-js/issues/1312#issuecomment-1044117393).

**Comment by badeball** [comment]
This will likely depend on the existence of a `test:after:run` event, as described [here](https://github.com/cypress-io/cypress/issues/2283). The referenced MR never made it into mainline it seems, despite the completion status.

I've tried to inquiry about its status, but given my history with Cypress so far, I assume it's never going to happen.

**Comment by badeball** [comment]
This can be tracked [here](https://github.com/cypress-io/cypress/issues/27175).

**Comment by badeball** [comment]
I found away around the above-mentioned proposal and I've fixed this issue with v20.1.0.
