### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Mathiarasan3** [badeball/cypress-cucumber-preprocessor#1045]
### Current behavior

When I use Cucumber to launch Cypress, it throws me error like 'Cannot read properties of undefined (reading 'name')'.

I have created a beforeEach method in a separate js file and it will have the test data from fixtures.
beforeEach(function(){
cy.fixture('example').then(function(data){
    this.data = data;
})
})

I dont know why I am getting this error. Pls help
My project structure is
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/82944178/4f073b17-62b0-4abf-9a78-afd2dc9bfd98)

my package.json looks like this
{
  "name": "cypressautomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "npx cypress run",
    "test_headed": "npm run test -- --headed",
    "test_record": "npm run test -- --record --key 4cd089db-56dc-47ec-94e1-b805784fb482 --spec cypress\\integration\\examples\\test4.js --headed --browser chrome",
    "test_single": "npm run test -- --spec cypress\\integration\\examples\\test4.js"
  },
  "cypress-cucumber-preprocessor": { 
    "nonGlobalStepDefinitions": true },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@cypress/browserify-preprocessor": "^3.0.2",
    "cypress": "^12.14.0",
    "cypress-iframe": "^1.0.1"
  },
  "dependencies": {
    "@cypress/browserify-preprocessor": "^3.0.2",
    "@badeball/cypress-cucumber-preprocessor": "^18.0.1"
  }
}

### Desired behavior

When I run the feature file, it is giving me error like this,
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/82944178/14d632df-6009-492b-a3ca-c034793c4a42)

### Test code to reproduce

Feature file looks like this:
Feature: Sample feature file for E-Commerce 

    Sample e-commerce validation

    Scenario: E-Commerce products delivery
    Given I open Ecommerce page
    When I add items to cart
    And Validate the total prices
    Then Select the country submit and verify thank you
    
    and step def like this :
    /// <reference types="Cypress" />

import {Given, When, Then} from "@badeball/cypress-cucumber-preprocessor";
import HomePage  from "../../../PageObjects/HomePage";
import ProductPage from "../../../PageObjects/ProductPage";
const home_page = new HomePage()
const product_page = new ProductPage();

Given("I open Ecommerce page", function(){
    cy.visit(Cypress.env('url')+"/angularpractice/");
})

When("I add items to cart", function(){
    home_page.getShopButton().click()
    this.data.productName.forEach(function(element) {
     cy.SelectProduct(element) 
    });
    product_page.getCheckoutButton().click()
})

Then("Validate the total prices", function(){
    var sum =0;
    cy.get('.table.table-hover>tbody>tr>td:nth-child(4)>strong').each(function(el,index,list){
        cy.log(el.text())
        var amount =el.text().split(" ")
        amount= amount[1].trim();
        cy.log(amount)
        sum=Number(amount)+sum
       }).then(function(){
        cy.log(sum)
       })
       cy.get('h3>strong').then(function(ele){
        var total = ele.text().split(" ")
        total = Number(total[1].trim())
        expect(sum).to.equal(total)
    
       })
})

Then("Select the country submit and verify thank you", function(){
    cy.contains('Checkout').click();
   cy.get('#country').type('ind')
   cy.get('.suggestions>ul>li>a').each((el,index,list)=>{
    if(el.text()==='India'){
        cy.wrap(el).click()
    }
})
    cy.get('input#checkbox2').click({force:true});///using this, because checkbox is covered by other label
    cy.get('input[type="submit"]').click();
    cy.get('.alert.alert-success.alert-dismissible').then(function(ele){
        const text = ele.text();
        expect(text).to.include('Success')
    })
})

### Versions

* **Cypress version**:"^12.14.0",
* **Preprocessor version**: "^18.0.1"
* **Node version**:

**Comment by badeball** [comment]
> I have created a beforeEach method in a separate js file

Is it a js file though?

**Comment by Mathiarasan3** [comment]
Yes. BeforeEach is a js file

**Comment by Mathiarasan3** [comment]
> > I have created a beforeEach method in a separate js file
> 
> Is it a js file though?

Yes. BeforeEach is a js file. It has only beforeEach method in it

**Comment by badeball** [comment]
It looks extensionless from your screenshot.

**Comment by Mathiarasan3** [comment]
> It looks extensionless from your screenshot.

Sorry. I have added the extension.
Please check now. its still the same.
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/82944178/4f01cef3-b5d3-476e-9ab5-ca11a3bc92b7)

and the result is 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/82944178/e695fa50-cd37-4ef3-bb07-ea28b0a5d618)

**Comment by Mathiarasan3** [comment]
Cucumber should automatically identify and run the beforeEach.js and then it should carry out the stepDef, right ?
Dont know what I am missing here

**Comment by badeball** [comment]
I don't know and I don't care. You're too much of a pain in the ass breaking every [guideline](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports), which you obviously skipped.

Also this isn't a support forum. This doesn't mean you can't get any support, but you have to help me to help you.
