### ISSUE TITLE
Grouping Scenarios in .feature Files Using Multiple 'Feature' Keywords

### ISSUE THREAD

**Issue by jasp402** [badeball/cypress-cucumber-preprocessor#1047]
###🤔 **What's the problem you're trying to solve?**
I'm looking for a way to implement `context(name, config, fn)` with the aim of grouping tests according to a name or category.

###✨ **What's your proposed solution?**
I've noticed that within the **.feature** files there is a keyword called "`Feature`" that allows grouping "`Scenarios`". The idea would be to use "`Feature`" multiple times to perform this grouping.

###⛏ **Have you considered any alternatives or workarounds?**
I believe that the solution that generates the best impact is to be able to use "`Feature`" multiple times and that it only serves to group the scenarios that are below.

```gherkin
Feature: description 1

  Scenario: description 1
  When step of when
  Then step of them

Feature: description 2

  Scenario: description 2
  When step of when
  Then step of them

```

###📚 *Any additional context?*
I have some example images that I will provide in the final Issue post.
![image](https://github.com/cucumber/common/assets/8978470/2821f086-01d6-455c-94b0-2055e012b486)
![image](https://github.com/cucumber/common/assets/8978470/ec0a285c-e0f7-4a7f-ab90-8b9bbc61243f)

### Versions

* **Cypress version**:^12.2.0
* **Preprocessor version**: "@badeball/cypress-cucumber-preprocessor": "^13.0.2"
* **Node version**: v16.15.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This package is merely a consumer of the [gherkin language](https://github.com/cucumber/gherkin) and the language is not developed here.

**Comment by jasp402** [comment]
This is the response I've gotten from the Cucumber team: [comment link](https://github.com/cucumber/common/issues/2151#issuecomment-1611720350).

The most similar option seems to be using '`rules`'. However, it appears that rule handling isn't implemented within the preprocessor.

**Comment by badeball** [comment]
> However, it appears that rule handling isn't implemented within the preprocessor.

It is afaik.
