### ISSUE TITLE
Step implementation missing for [step that no longer exists]

### ISSUE THREAD

**Issue by javier-crowdar** [badeball/cypress-cucumber-preprocessor#1049]
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/138053661/23c00e75-a3cd-4c4e-a8d4-08382252ca7e)

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/138053661/30778f32-415b-46a8-b29c-571af3d335d9)

That step was previously called as image 1 but I changed the name of the step to image 2 but now it is still looking for the step image 1

-->

### Versions

* **Cypress version**: 12.13.0
* **Preprocessor version**: 18.0.1
* **Node version**: v18.16.0

**Comment by badeball** [comment]
Not a support forum. If you think something is wrong, then you need to properly follow the template like everyone else.
