### ISSUE TITLE
Incorrect status being reported for skipped, pending, failed steps v16.0.3

### ISSUE THREAD

**Issue by richardforjoejnr** [badeball/cypress-cucumber-preprocessor#1052]
### Versions

* **Cypress version**:
* "cypress": "^12.16.0"
* **Preprocessor version**:
* "@badeball/cypress-cucumber-preprocessor": "16.0.3",
* **Node version**:
16

### Current behavior

I have "json": {"enabled": true,} and noticed a couple of issues regarding the status values in the json output file which seem incorrect

Wanted to check if these are expected or incorrect

Summary
1] I have a step that **fails** - steps[0].result.status = 'failed' but in the after block steps[1].result.status = '**skipped**'
2] I have a step that is **pending** - steps[0].result.status = 'failed' ("error_message": "pending") but in the after block steps[1].result.status = '**skipped**'
3] I have a step that returns **skipped** steps[0].result.status = 'passed' and the after block steps[1].result.status = '**passed**'
4] I have a step that is **undefined** - steps[0].result.status = 'passed' but in the after block steps[1].result.status = '**passed**' 

### Desired behavior
1] I have a step that fails - steps[0].result.status = 'failed' after block steps[1].result.status = 'failed' - whole scenario failed
2] I have a step that is pending - steps[0].result.status = 'failed' ("error_message": "pending") but in the after block steps[1].result.status = "pending"
3] I have a step that returns skipped steps[0].result.status = 'skipped' and the after block steps[1].result.status = 'skipped'
4] I have a step that is undefined - steps[0].result.status = 'pending' but in the after block steps[1].result.status = 'pending' 

Scenario
step - passed
step - failed
step skipped
=> scenario failed (worst status)

Scenario
step - passed
step - passed
step - skipped
=> scenario skipped (worst status)

Scenario
step - skipped
step - passed
step - pending
=> scenario pending (worst status)

Scenario
step - passed
step - undefined
step - passed
=> scenario undefined (worst status)

### Test code to reproduce
1. Install '.cypress": "^12.16.0' using "@badeball/cypress-cucumber-preprocessor": "16.0.3",
2. Create a feature file with the below Feature & step defs
Feature
```
Feature: Example feature

  Scenario: Test various statuses - Pass
    Given I have a step that passes

  Scenario: Test various statuses - Fail
    Given I have a step that fails

  Scenario: Test various statuses - Undefined
    Given I have a step that is undefined

  Scenario: Test various statuses - Pending
    Given I have a step that is pending

  Scenario: Test various statuses - skipped
    Given I have a step that returns skipped

  Scenario: Test various statuses - undefined
    Given I have a step that returns undefined
```

```
// cypress/support/step_definitions/exampleSteps.js

import { Given } from '@badeball/cypress-cucumber-preprocessor';

Given('I have a step that passes', () => {
  cy.log('This step passes');
});

Given('I have a step that fails', () => {
  cy.log('This step fails');
  expect(true).to.be.false;
});

Given('I have a step that is undefined', () => {
  // Leave this step undefined
});

Given('I have a step that is pending', () => {
  // In Cucumber JS, you can use 'return "pending"' to mark a test as pending,
  // but Cypress doesn't support this directly. You could, for instance,
  // throw a specific error to denote a pending test and then handle this
  // in your test result reporting.
  throw new Error('pending');
});

Given('I have a step that returns pending', () => {
  // In Cucumber JS, you can use 'return "pending"' to mark a test as pending,
  // but Cypress doesn't support this directly. You could, for instance,
  // throw a specific error to denote a pending test and then handle this
  // in your test result reporting.
  return 'pending';
});

Given('I have a step that returns skipped', () => {
  // In Cucumber JS, you can use 'return "pending"' to mark a test as pending,
  // but Cypress doesn't support this directly. You could, for instance,
  // throw a specific error to denote a pending test and then handle this
  // in your test result reporting.
  return 'skipped';
});

Given('I have a step that returns undefined', () => {
  // In Cucumber JS, you can use 'return "pending"' to mark a test as pending,
  // but Cypress doesn't support this directly. You could, for instance,
  // throw a specific error to denote a pending test and then handle this
  // in your test result reporting.
  return 'undefined';
});

```
4. In your package.json. ensure you have
```
"cypress-cucumber-preprocessor": {
    "stepDefinitions": "test/e2e/**/*.{js,ts}",
    "commonPath": "test/e2e/commonSteps",
    "json": {
      "enabled": true,
      "output": "reports/cucumber-report.json"
    },...
```
7. Run cypress and check the json file generated

Json output
```
{
    "description": "",
    "elements": [
      {
        "description": "",
        "id": "example-feature;test-various-statuses---pass",
        "keyword": "Scenario",
        "line": 3,
        "name": "Test various statuses - Pass",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 4,
            "name": "I have a step that passes",
            "match": {
              "location": "not available:0"
            },
            "result": {
              "status": "passed",
              "duration": 8000000
            }
          },
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 4000000
            }
          }
        ],
        "tags": [],
        "type": "scenario"
      },
      {
        "description": "",
        "id": "example-feature;test-various-statuses---fail",
        "keyword": "Scenario",
        "line": 6,
        "name": "Test various statuses - Fail",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 7,
            "name": "I have a step that fails",
            "match": {
              "location": "not available:0"
            },
            "result": {
              "status": "failed",
              "duration": 0,
              "error_message": "expected true to be false"
            },
            "embeddings": [
              {}
            ]
          },
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "skipped",
              "duration": 0
            }
          }
        ],
        "tags": [],
        "type": "scenario"
      },
      {
        "description": "",
        "id": "example-feature;test-various-statuses---undefined",
        "keyword": "Scenario",
        "line": 9,
        "name": "Test various statuses - Undefined",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 10,
            "name": "I have a step that is undefined",
            "match": {
              "location": "not available:0"
            },
            "result": {
              "status": "passed",
              "duration": 4000000
            }
          },
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 3000000
            }
          }
        ],
        "tags": [],
        "type": "scenario"
      },
      {
        "description": "",
        "id": "example-feature;test-various-statuses---pending",
        "keyword": "Scenario",
        "line": 12,
        "name": "Test various statuses - Pending",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 13,
            "name": "I have a step that is pending",
            "match": {
              "location": "not available:0"
            },
            "result": {
              "status": "failed",
              "duration": 0,
              "error_message": "pending"
            },
            "embeddings": [
              {}
            ]
          },
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "skipped",
              "duration": 0
            }
          }
        ],
        "tags": [],
        "type": "scenario"
      },
      {
        "description": "",
        "id": "example-feature;test-various-statuses---skipped",
        "keyword": "Scenario",
        "line": 15,
        "name": "Test various statuses - skipped",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 16,
            "name": "I have a step that returns skipped",
            "match": {
              "location": "not available:0"
            },
            "result": {
              "status": "passed",
              "duration": 5000000
            }
          },
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 3000000
            }
          }
        ],
        "tags": [],
        "type": "scenario"
      },
      {
        "description": "",
        "id": "example-feature;test-various-statuses---undefined",
        "keyword": "Scenario",
        "line": 18,
        "name": "Test various statuses - undefined",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 19,
            "name": "I have a step that returns undefined",
            "match": {
              "location": "not available:0"
            },
            "result": {
              "status": "passed",
              "duration": 4000000
            }
          },
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "passed",
              "duration": 4000000
            }
          }
        ],
        "tags": [],
        "type": "scenario"
      }
    ],
    "id": "example-feature",
    "line": 1,
    "keyword": "Feature",
    "name": "Example feature",
    "tags": [],
    "uri": "test/e2e/Example/test.feature"
  }
```

### Versions

* **Cypress version**:
* "cypress": "^12.16.0"
* **Preprocessor version**:
* "@badeball/cypress-cucumber-preprocessor": "16.0.3",
* **Node version**:
16

### Other + Additional information:

Comment from mpkorstanje
Generally speaking the way to determine the result of a scenario is to take the worst status of its steps.

https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-core/src/main/java/io/cucumber/core/runner/TestCaseState.java#L54C1-L54C1

The order being

    PASSED,
    SKIPPED,
    PENDING,
    UNDEFINED,
    AMBIGUOUS,
    FAILED
https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-java/src/main/java/io/cucumber/java/Status.java

If a scenario has no steps implementations currently vary a bit on what the outcome should be.

https://github.com/cucumber/gherkin/issues/11
### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> 1] I have a step that **fails** - steps[0].result.status = 'failed' but in the after block steps[1].result.status = '**skipped**'
> 2] I have a step that is **pending** - steps[0].result.status = 'failed' ("error_message": "pending") but in the after block steps[1].result.status = '**skipped**'
> 3] I have a step that returns **skipped** steps[0].result.status = 'passed' and the after block steps[1].result.status = '**passed**'
> 4] I have a step that is **undefined** - steps[0].result.status = 'passed' but in the after block steps[1].result.status = '**passed**' 

1) This is intended behavior. Why would the after-step be marked as failed here?

2) You don't mark a step as pending by throwing `Error("pending")`, you simply return the string `"pending"`. This is supported, as seen [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/4cb4f1e32f50d438cbc3eb99caee6cc5da4d87ca/features/reporters/json.feature#L117-L139).

3) Returning `"skipped"` is not supported p.t.

4) Returning `"undefined"` doesn't mean anything, neither here nor in cucumber-js.

**Comment by richardforjoejnr** [comment]
Thanks for confirming @badeball . RE 1] is the after step the overall status of the scenario or the status of the last step?

if its the overall status of the scenario, then for the below scenario, the step was skipped because of the failure? so overall status should be failed not skipped i would have thought?

Scenario:
step - passed
step - failed
step - skipped
=> scenario failed (worst status)

What is "After" by the way, incase i've misunderstood it.

**Comment by richardforjoejnr** [comment]
```
"name": "Test various statuses - Fail",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 7,
            "name": "I have a step that fails",
            "match": {
              "location": "not available:0"
            },
            "result": {
              "status": "failed",
              "duration": 0,
              "error_message": "expected true to be false"
            },
            "embeddings": [
              {}
            ]
          },
          {
            "keyword": "After",
            "hidden": true,
            "result": {
              "status": "skipped",
              "duration": 0
            }
          }
        ],
```

**Comment by badeball** [comment]
You can think of After(..) as a step that runs at the end of every test. Its status is its status alone and not a reflection of the test as whole.

**Comment by richardforjoejnr** [comment]
Ah got it, status of the after hook. That clarifies this. Thank you
