### ISSUE TITLE
Missing preprocessor event handlers while integrating Cypress with badeball/cucumber-preprocessor-plugin

### ISSUE THREAD

**Issue by dheerajpiplani** [badeball/cypress-cucumber-preprocessor#1060]
@badeball - Here's the issue - 
### Current behavior

**Error while running the tests - Missing preprocessor event handlers**
### Desired behavior

Tests in .Feature file should run

### Test code to reproduce

Cypress.config.js file below - 
Note - Integrating cypress cucumber preprocessor plugin and my framework is capable to run on multiple environments

const { defineConfig } = require("cypress");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const nodePolyfills = require("@esbuild-plugins/node-modules-polyfill").NodeModulesPolyfillPlugin;
const addCucumberPreprocessorPlugin = require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const setConfigFile = require('./cypress/support/setConfigFile');

async function setupNodeEvents (on, config) {
await addCucumberPreprocessorPlugin(on, config);
const file = config.env.configFile || "";
on(
'file:preprocessor',
createBundler({
plugins: [nodePolyfills(), createEsbuildPlugin(config)],
})
);

on("before:browser:launch", (browser = {}, launchOptions) => {
if (browser.family === "chromium" && browser.name !== "electron") {
launchOptions.args.push("--incognito");
}

if (browser.name === "electron") {
  launchOptions.preferences.incognito = true;
}
return launchOptions;
});
return setConfigFile(file);
}

module.exports = defineConfig({
e2e: {
setupNodeEvents,
specPattern: '**/.{feature,features}',
excludeSpecPattern: '.js'
},
defaultCommandTimeout: 15000,
taskTimeout: 100000,
pageLoadTimeout: 150000,
viewportWidth: 1280,
viewportHeight: 720
});

Necessary info from package.json -

cypress-cucumber-preprocessor: "^17.1.1",
cypress-esbuild-preprocessor: "^2.1.3",
esbuild-plugins/node-modules-polyfil": "^0.1.4",
"cypress-cucumber-preprocessor": {
"stepDefinitions": [
"cypress/e2e/[filepath].{js,ts}",
"cypress/support/step_definitions/**/*.{js,ts}"
]
}

-->

### Versions

* **Cypress version**: 12.17.1
* **Preprocessor version**: 17.1.1 (this issue is happening with all latest versions)
* **Node version**: 18.15.0

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
It's glaringly obvious from your ticket, that you have not yourself gone through the process of trying to reproduce the issue using the information that you've provided me. Instead, you're just assuming you've provided me with everything that's relevant and you're leaving it up to me to test that assumption. This is a huge waste of my time, as almost everyone fails to provide the relevant information. This is why I'm asking everyone in the [contributing guidelines](https://github.com/badeball/cypress-cucumber-preprocessor/blob/67479d397388f3abbfbcd10f1f52dfe39b68eb31/CONTRIBUTING.md), to provide me with a _runable example_. If it doesn't run, then you've clearly not tested it.

**Comment by dheerajpiplani** [comment]
@badeball 
I feel that i've provided enough information. here're the detailed steps to reproduce -
1. Install cypress latest version
2. Create sample BDD and stepsdefination
3. Integrate code for running on multiple environments...code is already in cypress.config.js file (code for setConfigFile.js - 

const fs = require("fs-extra");
const path = require("path");

const fetchConfigurationByFile = file => {
  const pathOfConfigurationFile = `config/cypress.${file}.json`;

  return (
    file && fs.readJson(path.join(__dirname, "../", pathOfConfigurationFile))
  );
};
module.exports = setConfigFile;
5. Integrate cucumber-preprocessor-plugin and put the code in cypress.config.js as mentioned in description.
6. Run cypress test in your feature file

Actual - You will face this issue

Expected - Tests should run fine

Let me know in case of anything else is required

Note - I'm facing this issue and blocked (not able to move forward) and that's why reporting this.

**Comment by badeball** [comment]
> I feel that i've provided enough information.

You didn’t, the crucial piece was what you provided now.

You’re overwriting configuration values written by the plugin. It’s stated in every example that this must be returned. You need to merge instead of replace, specifically the env-portion of the configuration.
