### ISSUE TITLE
createEsbuildPlugin is not a function 

### ISSUE THREAD

**Issue by Maxime-p** [badeball/cypress-cucumber-preprocessor#1061]
### Current behavior

Got the error `createEsbuildPlugin is not a function`  when trying to run cypress cucumber e2e tests

### Desired behavior

I found the issue #868 and tried recommandations from F.A.Q : 
- `"esModuleInterop": true`
- `import * as createBundler from "@bahmutov/cypress-esbuild-preprocessor";`
- set `moduleResolution` to `node16`
- adding the path
```
"paths": {
    "@badeball/cypress-cucumber-preprocessor/*": ["./node_modules/@badeball/cypress-cucumber-preprocessor/dist/subpath-entrypoints/*"]
}
```
- changing preprocessor

Nothing worked

### Test code to reproduce

Create a new react typecript project with vite
Install cypress and cucumber

My _cypress.config.ts_
```ts
import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import pkg from '@badeball/cypress-cucumber-preprocessor';
const { addCucumberPreprocessorPlugin } = pkg;
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor";

export default defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    supportFile: false,
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config);
      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );
      return config;
    },
  },
});
```

### Versions

* **Cypress version**: 12.17.1
* **Preprocessor version**: 18.0.1
* **Node version**: 19.7.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You don't think providing me with a complete example is necessary?

**Comment by Maxime-p** [comment]
I'm not sure I understand what else I can provide.

**Comment by badeball** [comment]
This is thoroughly explained in the [contributing guidelines](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case).

**Comment by Maxime-p** [comment]
I created a [repo](https://github.com/Maxime-p/ts-cypress-cucumber) with vite : react typescript, adding deps : `npm i -D cypress @badeball/cypress-cucumber-preprocessor @bahmutov/cypress-esbuild-preprocessor`

I setuped the cypress config with some fixes (supportFile: false, import of addCucumberPreprocessorPlugin)
```ts
import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import pkg from '@badeball/cypress-cucumber-preprocessor';
const { addCucumberPreprocessorPlugin } = pkg;
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

export default defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    supportFile: false,
    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions
    ): Promise<Cypress.PluginConfigOptions> {
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await addCucumberPreprocessorPlugin(on, config);

      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );

      // Make sure to return the config object as it might have been modified by the plugin.
      return config;
    },
  },
});
```

Editing the tsconfig don't resolve the error
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "node16", // Trying to put node16
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,

    "paths": { // Trying to add the path
      "@badeball/cypress-cucumber-preprocessor/*": ["./node_modules/@badeball/cypress-cucumber-preprocessor/dist/subpath-entrypoints/*"]
    }
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

I also tried `import * as` and `esModuleInterop": true`

**Comment by badeball** [comment]
I can't be your guide through TypeScript shenanigans. I recommend that you use any of the examples as a starting point, as they all work. From there, add properties incrementally until you see what property is the culprit.

**Comment by JJ-Kamminga** [comment]
I ran into a similar issue, and found this thread. As badeball said, it's TypeScript shenanigans and certainly isn't an issue with the preprocessor. However, TypeScript shenanigans are a reality in most projects, so maybe this helps someone.

First of all, don't use `paths` in tsconfig.ts if you can set `module`/`moduleResolution` to  `Node16`. It is described in the FAQ as a workaround if you need to stick to another setting for `module`/`moduleResolution`. 

Secondly, Typescript docs say: "Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.ts" - yours is set to ESNext.

Regarding the imports: it's extremely useful in resolving these errors (note to self, as well) to understand how JS imports work, especially:
- [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) (which this package uses)
- [ESModules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) and [why they sometimes cause problems in Node.js based applications](https://www.typescriptlang.org/docs/handbook/esm-node.html) (this is the background story of why you need to set `module` in your tsconfig.json)

It takes a read of the documentation of each of your tsconfig settings to see how you need to import. Some possible complicating factors for module resolution, which may require additional configuration (or another build tool):
- Other conflicting tsconfigs in the project
- Npm or similar workspaces/modules
- Your project doesn't support Node.js 16 (or even earlier versions)
- You have multiple versions of the same package installed (maybe as peer deps)

Just from reading a config file like yours, it's hard to say anything (just to remove paths from your tsconfig as said above). Your createBundler import looks OK, I think you should look to your Typescript settings. 

I quickly tried your `addCucumberPreprocessorPlugin` import, for me it gives: `this expression is not callable`. I solved this by importing like this:
```
import cypressCucumberPreprocessor from '@badeball/cypress-cucumber-preprocessor';
const addCucumberPreprocessorPlugin = cypressCucumberPreprocessor.addCucumberPreprocessorPlugin;
```

Hope it helps.
