### ISSUE TITLE
Json report created only when test started via terminal, not when started via Cypress UI

### ISSUE THREAD

**Issue by TomDvorsky** [badeball/cypress-cucumber-preprocessor#1062]
### Current behavior
As the title says, the report json file is created only if I run a test via terminal. Not when I open Cypress UI and click on test there.
The cucumber-messages.ndjson file is created immediately when test is started via command line, not when test starts when clicked in cy UI.
I have a lot of .feature files - placed in many folders, so to retype command is really time consuming. Clicking in the UI is much easier, not everyone likes command line ...

### Desired behavior

That a json file would be created also when someone executes a test via the Cypress UI.
Another, even more awesome - yet that would be a feature request - would be if the json would take ie. the name of the feature file that was executed ... The old setting for the other cypress-cucumber-preprocessor did that, the settings then were in cypress.json (yes, I am not having this in my cy 12 project, only in the .cypress-cucumber-preprocessorrc.json),
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/reports-cucumber",
      "filePrefix": "",
      "fileSuffix": ""
    }
  }
Now I have few options - run whole suite - huge project, runs over 10 hours, output would be 1 json file. Report would contain few failed tests. To green them up, I'd need to adjust those, rerun the whole suite ...
Run folder by folder - and rename the .json everytime so I could compile it to 1 report file.
Best would be truly having a json fer every feature ... then only the particular test would need to run, huge time saving ... 

### Test code to reproduce

My .cypress-cucumber-preprocessorrc.json settings:
{
  "stepDefinitions": ["cypress/support/step_definitions/**/*.{js,ts}"],
  "json": {
    "enabled": true,
    "output": "reports-cucumber/cucumber-report.json"  (already found out that not specifying the filename doesn't work)
  }
}

### Versions

* **Cypress version**: 12.17.1
* **Preprocessor version**: 18.0.1
* **Node version**: 18.16.1

### Checklist

- [X ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
The reason for lack of reports in interactive mode is explained in the FAQ.

**Comment by TomDvorsky** [comment]
Pity that a non-programmer doesn't understand what is written in FAQ nor how to use the cypress-on-fix ... Broke my project, had to return it to the previous state.
