### ISSUE TITLE
cannot save variables using nested steps and cy.fixture

### ISSUE THREAD

**Issue by Javier-bat** [badeball/cypress-cucumber-preprocessor#1063]
### Current behavior

When using nested steps the variables are not stored when using a cy.fixture. This doesn't happen if I don't use nested steps. I put 2 examples, the first fails the second passes successfully. behavior is different

### Desired behavior

I expected the variables to be stored just like when nested steps are not used

### Test code to reproduce

```
Feature: nesten steps

  Scenario: invoking step from another step
    Given a file named "cypress/e2e/a.feature" with:
      """
      Feature: a feature name

        Scenario: nested steps with cy.fixture 
          Given a nested step

      Scenario: no nested steps
          Given first nasted step
           And second nasted step
      """
    And a file named "cypress/fixtures/anyFixture.json" with:
    """
          {}
    """
    And a file named "cypress/e2e/a.js" with:
      """
      const { Given, Step } = require("@badeball/cypress-cucumber-preprocessor");
      Given("a nested step", function() {
        Step(this, "first nasted step");
        Step(this,"second nasted step")
      });
      Given("first nasted step", function() {
      cy.fixture("anyFixture").then((fixtureJson)=>{
                     this.randomText = "Hello world"
          })
      });
      Given("second nasted step", function() {
        expect(this.randomText).to.equal("Hello world");
      });

      """
    When I run cypress
    Then it passes

```

### Versions

* **Cypress version**: 12.17.1
* **Preprocessor version**: 18.0.1
* **Node version**: v18.16

### Checklist

- [x ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hi @Javier-bat, thanks for reporting the issue and putting together an example for me. I've fixed and released this with v18.0.2.
