### ISSUE TITLE
stepDefinitions in explicitConfiguration are ignored when using type-specific configuration

### ISSUE THREAD

**Issue by fabkru** [badeball/cypress-cucumber-preprocessor#1065]
### Current behavior

`stepDefinitions` defined in `explicitConfiguration` (e.g. `.cypress-cucumber-preprocessorrc.json`) seem to be ignored when using [type-specific configuration](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md#type-specific-configuration), causing cypress-cucumber-preprocessor to fall back to the defaults.

### Desired behavior

Projects with both Cypress `e2e` and `ct` can have different requirements for `stepDefinitions` for each, requiring an `explicitConfiguration` (e.g. `.cypress-cucumber-preprocessorrc.json`) as follows:

```
{
	"e2e": {
		"stepDefinitions": ["cypress/e2e/[filepath].js", "someFolder/cypress/support/step_definitions/*.js"]
	}
}
```
Preferably, these would override the defaults.

### Test code to reproduce

Here's an isolated, minimal reproduction demonstrating the behaviour of `combineIntoConfiguration`:
https://github.com/fabkru/cypress-cucumber-preprocessor-config-bug-repro/blob/master/src/index.test.ts#L27

Test outputs the following:
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/3511147/2c75b97d-978b-4fa1-a6a1-ad5a9722c7cc)

### Versions

* **Cypress version**: - 
* **Preprocessor version**: 18.0.0
* **Node version**: -

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hi @fabkru, thanks for reporting this issue. I've fixed this with v18.0.3.
