### ISSUE TITLE
Angular 16 implementation error

### ISSUE THREAD

**Issue by heloufir** [badeball/cypress-cucumber-preprocessor#1067]
### Current behavior

I got the following error after I try to run my tests with cypress 

```
The following error originated from your test code, not from Cypress.

  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```

Below is the content of `e2e/cypress.config.ts` file:

```typescript
import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}


export default defineConfig({
  
  e2e: {
    baseUrl: 'http://localhost:4200',
    specPattern: ["**/*.feature","cypress/e2e/**/*.cy.{js,jsx,ts,tsx}"],
    setupNodeEvents,

  },
  
  component: {
    devServer: {
      framework: 'angular',
      bundler: 'webpack',
    },
    specPattern: ["**/*.feature","cypress/e2e/**/*.cy.{js,jsx,ts,tsx}"],
  }
  
})
```

And for the `e2e/tsconfig.e2e.json` file, I added the `moduleResolution` and `esModuleInterop` like said in the docs:

```json
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "chai", 
      "cucumber",
      "node"
    ],
    "moduleResolution": "Node16",
    "esModuleInterop": true
  }
}
```

Features folder:

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/6197875/b84e6a92-02a2-42a6-9753-a00e5bea868b)

An example of a **feature** file, `cypress/features/page-403.feature`

```
#language: fr
Fonctionnalité: Redirige vers page 403

  La page pour le traitement de l'erreur 403 est affichée lorsqu'un utilisateur qui n'a pas de droits
  pour utiliser Fonctions allégées accède à l'interface web

  Scénario: Un utilisateur n'a pas les droits pour fa-iw
    Étant donné qu'un utilisateur n'a pas les droits de fa-iw
    Quand il se connecte à fa-iw
    Alors l'utilisateur est redirigé vers la page 403

  Scénario: Un utilisateur a les droits pour fa-iw
    Étant donné qu'un utilisateur a les droits de fa-iw
    Quand il se connecte à fa-iw
    Alors l'utilisateur est redirigé vers la page de recherche
```

> It's written in French language, I am working to migrate from Protractor to Cypress our Angular project

Test example, `cypress/e2e/steps/sx5-connection.steps.cy.ts`:

```typescript
import { Given } from '@badeball/cypress-cucumber-preprocessor';
import { Sx5PageConnection } from '../page-objects/sx5-connecter.po';
import { OutilsElement } from '../outils/outils-elements';
import { environment } from '../../../src/environments/environment';

const sx5Page: Sx5PageConnection = new Sx5PageConnection();

Given('l\'utilisateur existe dans SX5', () => {
    sx5Page.aller();
    const buttonSx5 = sx5Page.obtenirBouttonConnection();
    OutilsElement.ajouterAttent(buttonSx5);
    if (buttonSx5) {
        OutilsElement.executerEventement(OutilsElement.evenements.click, buttonSx5);
        const champUtilisateur = sx5Page.obtenirChampUtilisateur();
        OutilsElement.ajouterAttent(champUtilisateur);
        OutilsElement.executerEventement(OutilsElement.evenements.sendKeys, champUtilisateur, environment.utilisateurTestSx5);

        const champMotDePasse = sx5Page.obtenirChampMotDePasse();
        OutilsElement.ajouterAttent(champMotDePasse);
        if (champMotDePasse) {
            OutilsElement.executerEventement(OutilsElement.evenements.sendKeys, champMotDePasse, environment.motDePasseTestSx5);
        }
        const buttonSeConnecter = sx5Page.obtenirButtonSeConnecter();
        OutilsElement.ajouterAttent(buttonSeConnecter);
        if (buttonSeConnecter) {
            OutilsElement.executerEventement(OutilsElement.evenements.click, buttonSeConnecter);
        }
        cy.wait(3000);
    }
});

```

Cypress dependancies:

```
// ...
"devDependencies": {
   // ...
    "@badeball/cypress-cucumber-preprocessor": "latest",
    "@bahmutov/cypress-esbuild-preprocessor": "latest",
    "@cypress/schematic": "latest",
    "cypress": "latest",
    "cypress-xpath": "^2.0.1",
   // ...
}
// ...
```

### Versions

* **Cypress version**: latest
* **Preprocessor version**: latest
* **Node version**: 18

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need however to adhere to the guidelines for [reporting issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports). Please read through it, specifically about reduced test cases, and update your issue accordingly.

**Comment by heloufir** [comment]
> Hey, and thanks for reporting this issue. You need however to adhere to the guidelines for [reporting issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports). Please read through it, specifically about reduced test cases, and update your issue accordingly.

Hello @badeball, thanks for the fast reply, I just updated the issue content

**Comment by badeball** [comment]
This is still not what I mean by a reduced test case. I suspect from your ticket, that you have not yourself gone through the process of trying to reproduce the issue using the information that you've provided me. Instead, it appears you're assuming you've provided me with everything that's relevant and you're leaving it up to me to test that assumption. This is a huge waste of my time, as almost everyone fails to provide the relevant information. This is why I'm asking everyone in the [contributing guidelines](https://github.com/badeball/cypress-cucumber-preprocessor/blob/67479d397388f3abbfbcd10f1f52dfe39b68eb31/CONTRIBUTING.md), to provide me with a _runable example_. If it doesn't run, then you've probably not tested it.

**Comment by heloufir** [comment]
I understand, but I didn't have time to make a reproducible project sorry.
Anyway, I got it to work, it was a wrong configuration I did 😅 

But I think if you can put (or I can make a PR) an example of Angular configuration it would be great, for my problem it was just a file that was in the wrong folder.

You can close the issue.

**Comment by badeball** [comment]
I don't think an angular+webpack-example is going to look any different than say react+webpack-example, but you're welcome to see and create a PR if there's any relevant differences.
