### ISSUE TITLE
createEsbuildPlugin is not compatible with esbuild versions after 0.18.13 and the esbuild-ts example can't build

### ISSUE THREAD

**Issue by runenielsen** [badeball/cypress-cucumber-preprocessor#1068]
### Current behavior

Something was changed in `esbuild` version 0.18.14, that makes it incompatible with `cypress-cucumber-preprocessor`'s `createEsbuildPlugin` method, which causes the esbuild-ts example build to fail.

### Desired behavior

The esbuild-ts example should build succesfully. Preferably by making `cypress-cucumber-preprocessor` compatible with the newest version of `esbuild` (which is currently 0.19.0)

### Test code to reproduce

The issue can be reproduced like this from the example code in this repository:

```
% git clone git@github.com:badeball/cypress-cucumber-preprocessor.git
% cd cypress-cucumber-preprocessor/examples/esbuild-ts
% npm install
% npx tsc

cypress.config.ts:16:17 - error TS2322: Type 'import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").Plugin' is not assignable to type 'import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/esbuild/lib/main").Plugin'.
  Types of property 'setup' are incompatible.
    Type '(build: import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<...>' is not assignable to type '(build: import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/esbuild/lib/main").PluginBuild) => void | Promise<void>'.
      Types of parameters 'build' and 'build' are incompatible.
        Type 'import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/esbuild/lib/main").PluginBuild' is not assignable to type 'import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").PluginBuild'.
          The types of 'initialOptions.loader' are incompatible between these types.
            Type '{ [ext: string]: import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/esbuild/lib/main").Loader; }' is not assignable to type '{ [ext: string]: import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").Loader; }'.
              'string' index signatures are incompatible.
                Type 'import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/esbuild/lib/main").Loader' is not assignable to type 'import("/private/tmp/cypress-cucumber-preprocessor/examples/esbuild-ts/node_modules/@badeball/cypress-cucumber-preprocessor/node_modules/esbuild/lib/main").Loader'.
                  Type '"local-css"' is not assignable to type 'Loader'.

16       plugins: [createEsbuildPlugin(config)],
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in cypress.config.ts:16

```

### Versions

* **Cypress version**: 12.17.3
* **Preprocessor version**: 18.0.3
* **Node version**: v18.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hi @runenielsen, thanks for reporting this. I've updated the dependency on esbuild and released v18.0.4.

**Comment by runenielsen** [comment]
Excellent, thanks a lot for the quick fix!

**Comment by QuantariusRay** [comment]
I'm seeing this as an issue now:

<img width="915" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/31900736/27a8cd3f-c948-4b6f-911a-5d6aed2b0044">


I'm assuming similar issue. Is there something here that stands out as something I could have wrong during migration?

**Comment by danielSoellerAtBearP** [comment]
@QuantariusRay I am facing the same issue, did you resolve it?

**Comment by vpopaheaven** [comment]
@badeball Getting the same issue again, can you please take a look? Should we reopen this issue?

**Comment by baptiste-rx** [comment]
Hi, I still have this issue using @bahmutov/cypress-esbuild-preprocessor": "^2.2.2" and @badeball/cypress-cucumber-preprocessor": "^20.1.1"

**Comment by badeball** [comment]
I've updated all dependencies, including esbuild, with v20.1.2.

**Comment by paschdan** [comment]
hey, wasn't this a breaking change, as it introduced glob@11 which drops node support pre 20?

**Comment by badeball** [comment]
Sure. The supported node versions however is tracked rather weakly and have been so throughout the library's history. It would be nice to have a matrix of node versions corresponding to the supported cypress versions and tested accordingly. This is not the case though, not yet at least.

**Comment by badeball** [comment]
Support for node v18 has been re-introduced with v21.0.0.
