### ISSUE TITLE
CustomWorld help

### ISSUE THREAD

**Issue by adam-wood-traka** [badeball/cypress-cucumber-preprocessor#1069]
Hi,

At the bottom of this documentation under the "TypeScript" section, it mentions "you can get optimum type safety and completion based": 
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/state-management.md

By completion do you mean auto-completion in vscode e.g. when I type "this." I should see a dropdown including "CustomWorld"?

I tried this but I wasn't getting auto-completion after creating the declarations.d.ts but I wanted to check if this is the expected behaviour?

**Comment by badeball** [comment]
You can get autocompletion like the example illustrates. Remember to avoid using arrow functions.

**Comment by davemeehanRGA** [comment]
@adam-wood-traka What worked for me was:
```typescript
declare global {
  namespace Mocha {
    interface Context extends MyInterfaceHere {}
  }
}
```
