### ISSUE TITLE
Unable to upgrade to the latest version from version `16.0.0`

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#1072]
### Current behavior

Unable to upgrade to the latest version from version `16.0.0`

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module `node_modules/@badeball/cypress-cucumber-preprocessor/dist/subpath-entrypoints/browserify.js.js' imported from /cypress-retry/cypress.config.mjs`
```
I tried importing `import browserify from "browserify";` but still that didn't solve the issue
### Desired behavior

It should able to migrate successfully without any error

### Test code to reproduce

https://github.com/rakeshnambiar/cypress-prep-migration.git

### Versions

* **Cypress version**: `12.17.1`
* **Preprocessor version**: `18.0.4`
* **Node version**: `v20.5.1`

**Comment by badeball** [comment]
Remove the extension from the import statement.

**Comment by rakeshnambiar** [comment]
Right. That solve the issue. Many thanks @badeball
