### ISSUE TITLE
Retry is not working in run mode eventhough the configuration is correct

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#1073]
### Current behavior

Retry is not working in run mode eventhough the configuration is correct. My configuration looks like below.
```json
  retries: {
    "runMode": 1,
    "openMode": 1
  }
  ```
It is working fine in the UI/open mode as shown below

![Screenshot 2023-08-17 at 21 46 35](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20258636/49346964-ae7b-472b-94c0-a0e5c4a88e78)

### Desired behavior

It should works as per the configuration in the run mode the same as open mode

### Test code to reproduce

https://github.com/rakeshnambiar/cypress-retry-prep.git

### Versions

* **Cypress version**: 12.17.1
* **Preprocessor version**: 16.0.0
* **Node version**: v20.5.1

Note: I couldn't migrate to the latest version due to https://github.com/badeball/cypress-cucumber-preprocessor/issues/1072

**Comment by badeball** [comment]
What are you seeing in run-mode that you think is incorrect?

**Comment by rakeshnambiar** [comment]
@badeball Aa you can see it on the screenshot ut is retrying when the tests fails. However on the terminal, it sating trying 1 out of 2 but even uf the tests fails it is not retrying. You can see the same issue on the repo I mentioned.

**Comment by rakeshnambiar** [comment]
I tried this on version `18.0.4` as well and it didn't work

```
Test
    ✓ test1 (1919ms)
    (Attempt 1 of 2) test1
    1) test1


  1 passing (5s)
  1 failing
```

**Comment by badeball** [comment]
What do you expect to see there?

**Comment by rakeshnambiar** [comment]
(Attempt 2 of 2) test1 for failing tests

![Screenshot 2023-08-18 at 08 16 50](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20258636/972ad6e2-b0b0-4e7b-b720-37929d4fb639)

You can see the retry in the UI mode above. In case you are not familiar with the cypress retry pls refer to https://docs.cypress.io/guides/guides/test-retries

**Comment by badeball** [comment]
GIven the following documentation, why do you expect this?

From https://docs.cypress.io/guides/guides/test-retries:

![](https://docs.cypress.io/img/guides/test-retries/cli-error-message.png)

**Comment by rakeshnambiar** [comment]
@badeball the issue here it is not at all retrying when the test is failed. The screenshot you attached, it is clearly retrying 3 times (I believe the retry value set in the config is 2 in this case) and it is mentioned in the console like:
```
(Attempt 1 of 3)
(Attempt 2 of 3)
(Attempt 3 of 3)
```

Also as per the documentation, I have configured the global configuration sepately for Open and Run mode which you can see it on the sample repo provided.

Hope this helps and let me know if you need any additional details from me.

**Comment by badeball** [comment]
> The screenshot you attached, it is clearly retrying 3 times (I believe the retry value set in the config is 2 in this case) and it is mentioned in the console like:
> 
> ```
> (Attempt 1 of 3)
> (Attempt 2 of 3)
> (Attempt 3 of 3)
> ```

Where in the screenshot does it say `(Attempt 3 of 3)`?

**Comment by rakeshnambiar** [comment]
Right, I got your point. So you are saying it won't say 2 of 2 or 3/3 at all though it retries. Let me add some logging to confirm it is actually retrying.

**Comment by rakeshnambiar** [comment]
Looks fine, is actually very confusing. I might raise with the cypress team :) 

```
  Test
    ✓ test1 (1815ms)
INFO: Failing tests begins
    (Attempt 1 of 2) test1
INFO: Failing tests begins
    1) test1
    ```
