### ISSUE TITLE
I can't add plugin cypress-mongodb along with the cucumber plugin

### ISSUE THREAD

**Issue by YasmineeAkramm** [badeball/cypress-cucumber-preprocessor#1076]
Hello All 

My project was importing cypress-mongodb with no probelms until i added cucumebr plugin the project always fails and gives me missing package imports although it works fine when i remove cucumber plugin

` e2e: {
    specPattern: "cypress/e2e/BDD-Features/**/*.feature",
    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions
    ): Promise<Cypress.PluginConfigOptions> {
     // mongo.configurePlugin(on)
     await addCucumberPreprocessorPlugin(on, config);
  
      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );

      return config;
    },`

Adding mongo.configurePlugin(on) and adding 
const mongo = require('cypress-mongodb');
mongo.addCommands();

in e2e.js file gives missing package imports 

I followeh the steps from here https://www.npmjs.com/package/cypress-mongodb

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need however to adhere to the guidelines for [reporting issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports). Please read through it and update your issue accordingly.

**Comment by Javier-bat** [comment]
https://github.com/Zaista/cypress-mongodb/issues/42

**Comment by badeball** [comment]
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.
