### ISSUE TITLE
JSON Report [cucumber-report.json] doesn't have any data when I add `after:spec` for deleting the video

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#1077]
### Current behavior
JSON Report [cucumber-report.json] doesn't have any data when I add `after:spec` for deleting the video. I was following the step mentioned here https://docs.cypress.io/api/plugins/after-spec-api. The video is getting deletd when the test is pass which aparently save the Compressing time. However, the cucumber-report.json is not showing any data. You can first try the below mentioned repo by comment out the below code from `cypress.config.mjs` to check the json report generation.

```javascript
      on('after:spec', (spec, results) => {
        if (results && results.video) {
          // Do we have failures for any retry attempts?
          const failures = results.tests.some((test) =>
              test.attempts.some((attempt) => attempt.state === 'failed')
          )
          if (!failures) {
            // delete the video if the spec passed and no tests retried
            fs.unlinkSync(results.video)
          }
        }
      })
  ```    

### Desired behavior

The `cucumber-report.json` file should generate with data at any case.

### Test code to reproduce

https://github.com/rakeshnambiar/cypress-prep-migration.git

### Versions

* **Cypress version**: `12.17.1`
* **Preprocessor version**: `18.0.4`
* **Node version**: `v20.5.1`
### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

`Note: Ask me if you need any details and fix ONLY if you want to improve this utility`

**Comment by badeball** [comment]
You need to go through the checklist that you omitted.

**Comment by rakeshnambiar** [comment]
by reading the FAQ I would like to confirm that - this particular issue reported is for `run` mode and not for the `open` (anyways the report generation in the `open` mode is a known issue I guess)

**Comment by badeball** [comment]
Keep reading it.

**Comment by rakeshnambiar** [comment]
Thanks. `await afterSpecHandler(config, spec, results);` did the trick
