### ISSUE TITLE
The esbuild-ts example can't build

### ISSUE THREAD

**Issue by runenielsen** [badeball/cypress-cucumber-preprocessor#1080]
### Current behavior

Something changed in a dependency, so both the base project and the esbuild-ts example can't build.

It fails on `"moduleResolution": "node16"` in combination with `"module": "CommonJS"` in `tsconfig.json`.

### Desired behavior

It should build.

### Test code to reproduce

The issue can be reproduced like this from the example code in this repository:

```
% git clone git@github.com:badeball/cypress-cucumber-preprocessor.git
% cd cypress-cucumber-preprocessor
% npm install
% npm run build

> @badeball/cypress-cucumber-preprocessor@18.0.4 build
> tsc

tsconfig.json:14:15 - error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

14     "module": "CommonJS",
                 ~~~~~~~~~~


Found 1 error in tsconfig.json:14

```

### Versions

* **Cypress version**: 12.17.4
* **Preprocessor version**: 18.0.4
* **Node version**: 18

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Right. It appears [something ](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#module-and-moduleresolution-must-match-under-recent-node-js-settings)did change with the most recent release.

For end-users - the example referenced works by changing `moduleResolution` to `module`. However, this can have unexpected consequences for some projects.

For library-developers - I'll wait and see if [my](https://github.com/microsoft/TypeScript/pull/54567#issuecomment-1695874991) inquiry gets any response.

**Comment by badeball** [comment]
I've updated the examples and replaced `moduleResolution: node16` with `module: nodenext`. It seems like the correct thing, however I'm not entirely sure of the implications, as my exposure to real-world Cypress use is non-existent these days.

End-users experiencing problems with this should feel free to provide example of so.

**Comment by runenielsen** [comment]
Thank you, Jonas.

**Comment by runenielsen** [comment]
@badeball : Will you release a new version?

**Comment by badeball** [comment]
It doesn’t seem like this warrants a new release as the compile output remains the same.

**Comment by runenielsen** [comment]
Ok, thanks.
