### ISSUE TITLE
Unable to resolve path to module '@badeball/cypress-cucumber-preprocessor/esbuild'

### ISSUE THREAD

**Issue by KauanCS** [badeball/cypress-cucumber-preprocessor#1082]
### Current behavior
I'm trying to configure cypress / cucumber in my Create-React-App v3 project but I'm receiving this error:
`Unable to resolve path to module '@badeball/cypress-cucumber-preprocessor/esbuild'`
![Captura de Tela 2023-08-28 às 10 13 49](https://github.com/badeball/cypress-cucumber-preprocessor/assets/51250330/3a4148f8-2279-4cd7-9814-ff6c2adec3b6)

If I try to run with `npx cypress open`, i got:
`Error: ENOENT: no such file or directory, stat '/Users/my_user/Library/Application Support/Cypress/cy/production/projects/project_folder+id/bundles/cypress/e2e/login/login.feature'`
But, It's probably caused by the first error.

I create a new `create-react-app` in version 5 and I also tested on v3 and it worked. So I believe It's something related to my app, but I'm having difficult to limit the scope of the problem
**I'm not using typrescript**

Cypress.config.js
```
module.exports = defineConfig({
  e2e: {
    baseUrl: BASE_URL,
    specPattern: '**/*.feature',
    supportFile: './cypress/support/e2e.js',
    video: false,
    chromeWebSecurity: false,
    async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config);

      const bundler = createBundler({
        plugins: [createEsbuildPlugin.default(config)],
      });

      on('file:preprocessor', bundler);

      return config;
    },
  },
});
```

package.json
```
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^18.0.4",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    "@cypress/webpack-preprocessor": "^5.17.1",
    "cypress": "^12.17.4",
    "esbuild": "^0.19.2",
    ...
 }
```

### Desired behavior

Run the tests without errors

### Test code to reproduce
It's a little hard to reduce the test case since my app is already in production.
We created a very small typescript app to test without any other framework and it worked, the problema is when I try to add the configuration in a existing app

### Versions

* **Cypress version**: 12.17.4
* **Preprocessor version**: 18.0.4
* **Node version**: v16.20.0

### Checklist

- [ X ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ X ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ X ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by KauanCS** [comment]
I just tried again and it worked!
Thanks @badeball for you attention.
