### ISSUE TITLE
cypress-cucumber-preprocessor 17.1.1 does not work with cypress-support pro

### ISSUE THREAD

**Issue by Gardosen** [badeball/cypress-cucumber-preprocessor#1085]
### Current behavior

when using the version 17.1.1 or higher from cypress-cucumber-preprocessor, cypress-support pro is not able to debug the cypress execution anymore.

### Desired behavior

when i want to debug the code with the help of cypress support pro, it should stop at the breakpoints i set.

### Test code to reproduce
https://github.com/Gardosen/automation-test/
branch: main <-- broken one with version 17.1.1
branch: debugger-fix-up <--- working one with version 17.1.0

### Versions

* **Cypress version**: 12.17.4
* **Preprocessor version**: 17.1.0 / 17.1.1
* **Node version**: 20.4.0

###Additional Note: 

I am also going to open up a bug report on the side of cypress support pro that it can be evaluated if the issue might be on the side of cypress support pro. Link: https://github.com/mbolotov/intellij-cypress/issues/122

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is not something I can help you with. If anyone can point out somewhere in which this library is misbehaving, feel free to do so and I will have a look. I will keep this issue open in the meanwhile.

**Comment by Gardosen** [comment]
helllo @badeball ,

this is sadly the same for the opposite site. he sais if the preprocessor is doing some kind of miss transformation, the debugger would not be able to find the breakpoint. 

i would try to help if possible to nail the issue down, but i have some struggles finding the right changes which have happened between 17.1.0 and 17.1.1 (because this version jump is what broke cypress support pro)

**Comment by badeball** [comment]
It's pretty easy to build and install from ref. You can eg. use git-bisect for this.

```
$ git checkout <ref>
$ npm run clean
$ npm run build
& npm run pack
```

Then from your own repository:

```
$ npm i <path to .tgz>
```

**Comment by badeball** [comment]
Closing, as this isn't something I'm going to spend time on.
