### ISSUE TITLE
cy.task('cypress-cucumber-preprocessor:append-messages')

### ISSUE THREAD

**Issue by pat-convex** [badeball/cypress-cucumber-preprocessor#1086]
### Current behavior

I upgraded to the latest badeball version 18.0.5
"@badeball/cypress-cucumber-preprocessor": "^18.0.5",
and my esbuild version is
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    
    Node version is = v18.11.0

  
  After upgrading to cypress 13, ran npm install everything was fine, try to run a test then i get the error below
### Desired behavior
taskcypress-cucumber-preprocessor:append-messages, Array[17], {log: false}

cy.task('cypress-cucumber-preprocessor:append-messages') failed with the following error:

The task 'cypress-cucumber-preprocessor:append-messages' was not handled in the setupNodeEvents method. The following tasks are registered: cypress-cucumber-preprocessor:spec-envelopes, cypress-cucumber-preprocessor:test-case-started, cypress-cucumber-preprocessor:test-step-started, cypress-cucumber-preprocessor:test-step-finished, cypress-cucumber-preprocessor:test-case-finished, cypress-cucumber-preprocessor:create-string-attachment, generateOTP

Fix this in your setupNodeEvents method here:
/Users/pat/Desktop/automation/companyName/e2e_tests/cypress/AllTest/cypress.config.js

Because this error occurred during a after all hook we are skipping all of the remaining test

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by pat-convex** [comment]
Thanks for the response but i dont know how to create an example. This issue is very easy to reproduce.

package.json file contains
{
"devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^18.0.5",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    "cypress": "^13.0.0",
    "cypress-on-fix": "^1.0.2",
    "cypress-otp": "^1.0.3",
    "cypress-recurse": "^1.35.2",
    "esbuild": "^0.17.18"
  },
  "cypress-cucumber-preprocessor": {
    "filterSpecs": true,
    "omitFiltered": true,
    "stepDefinitions": [
      "cypress/test/inRisk/stepDefinitions/**/*.{js,ts}",
      "cypress/test/workflow/stepDefinitions/**/*.{js,ts}",
      "cypress/test/orca/stepDefinitions/**/*.{js,ts}",
      "cypress/test/duw/stepDefinitions/**/*.{js,ts}",
      "[filepath]/**/*.{js,ts}",
      "[filepath].{js.ts}",
      "cypress/test/common/stepDefinitions/**/*.{js,ts}"
    ],
    "html": {
      "enabled": true
    }
  },
  "dependencies": {
    "chance": "^1.1.11",
    "cypress-plugin-api": "^2.11.1",
    "dayjs": "^1.11.9"
  }
}

my cypress.config file is below

const { defineConfig } = require("cypress");
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const fs = require("fs");
const addCucumberPreprocessorPlugin =
    require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const createEsbuildPlugin =
    require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;

module.exports = defineConfig({
  defaultCommandTimeout: 40000,
  requestTimeout: 60000,
  responseTimeout: 60000,
  pageLoadTimeout: 120000,
  watchForFileChanges:false,
  viewportWidth: 1940,
  viewportHeight: 1240,
  downloadsFolder: "report/downloads",
  screenshotsFolder: "report/screenshots",
  videosFolder: "report/videos",
  retries: {
    "runMode": 1,
    "openMode": 0
  },

  e2e: {
    async setupNodeEvents(cypressOn, config) {
      const on = require('cypress-on-fix')(cypressOn)
 
      const bundler = createBundler({
        plugins: [createEsbuildPlugin(config)],
      });
      on("file:preprocessor", bundler);
            await addCucumberPreprocessorPlugin(on, config);

      on('before:browser:launch', (browser, launchOptions) => {
        if (browser.family === 'chromium') {
          console.log('Adding Chrome flag: --disable-dev-shm-usage');
          launchOptions.args.push('--disable-dev-shm-usage');
        }
        return launchOptions;
      });

      on('after:spec', (spec, results) => {
        if (results && results.video) {
          // Do we have failures for any retry attempts?
          const failures = results.tests.some((test) =>
              test.attempts.some((attempt) => attempt.state === 'failed')
          )
          if (!failures) {
            // delete the video if the spec passed and no tests retried
            fs.unlinkSync(results.video)
          }
        }
      })

      on("task", {
        generateOTP: require("cypress-otp")
      });

      switch (config.env.test_environment.toUpperCase()) {
        case 'DEV':
          config.env.jiraAppUrl = "https://yahoo.com"
          break

        case 'INTEGRATION':
           config.env.jiraAppUrl = "https://yahoo.com"
          break

        case 'PREPROD':
          config.env.jiraAppUrl = "https://yahoo.com"
          break

        default:
         throw new Error(`Add environment details for ${config.env.test_environment.toUpperCase()} environment in the cypress config file`)
      }
      return config;
    },

    specPattern: "cypress/test/**/*.feature",
    excludeSpecPattern: "*.js",
    chromeWebSecurity: false,
    experimentalMemoryManagement: true,
    numTestsKeptInMemory: 10,
    experimentalRunAllSpecs: true,
    projectId: 'XXXXXX',
    env: {
      test_environment: "preprod",
        hideCredentials: true,
        hideCredentialsOptions: {
          headers: ['Host', 'Authorization', 'X-Amz-Target'],
          body: ['ClientId', 'AuthFlow', 'AuthParameters.PASSWORD'],
        },
      snapshotOnly: true
    },
    baseUrl: "https://yahoo.com"
  },
});

and then when you run cypress in open mode and try to run any of your feature file test, you will get the error

**Comment by pat-convex** [comment]
i even tried to use the npm lib: "cypress-on-fix" but didn't work.

The event "cypress-cucumber-preprocessor:append-messages" is coming from badeball and how would i handle that event in the setupNodeEvents inside the config file ?

thanks

**Comment by badeball** [comment]
I can't reproduce your issue given the provided information. Furthermore, the referenced task (`cypress-cucumber-preprocessor:append-messages`) ceiced to exist in v17.0.0 and beyond, which makes me think there's something else going on here.

**Comment by badeball** [comment]
> Thanks for the response but i dont know how to create an example.

This is explained in the [contributing guidelines](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md) guidelines:

> Any of the many [examples](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples) can serve as a good starting point for creating a minimal, reproducible example. Take one, modify it and use it to illustrate what you think is wrong. Upload it to EG. Github and link to it from your bug report.

**Comment by kduret** [comment]
It happens on my side when updating baseUrl in `before` hook (before run twice, second time with an other state)

**Comment by jasp402** [comment]
I have a problem with `cypress-cucumber-preprocessor:create-string-attachment.`

It is more aesthetic than functional, but it has brought me some complications. We have chosen to have a more exhaustive record, so within our logs we have included `attach()` to save information in the reports. That has been wonderful for all of us. The team is happy about it.

However now when running the tests, it appears:
`taskcypress-cucumber-preprocessor:create-string-attachment`
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/8978470/e62272a9-09ee-4e62-b166-6e3008f6521c)
This makes a lot of noise for the team because they have a lot of unwanted information to interpret. I can usually control this with the tasks **options** and set `{log:false}`.


However, attach does not have configuration options.
It may be too much to ask, I have already done some tests to implement it and it works. There is not much that has to be changed.

> entrypoint-browser.js

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/8978470/422c1bcd-4cc4-447b-b7fd-f796a8783098)

and in the end it would be like this. It is not a mandatory field anyway. It is only a configuration issue for advanced users.
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/8978470/701023bb-228d-4305-b6bc-0a675b4e03ba)
I hope that improvement can be included. Thank you!

**Comment by badeball** [comment]
@jasp402, this will be fixed in one of the upcoming releases.

Edit: this has been fixed with v19.0.0.

**Comment by mysticdevx** [comment]
Hi, this is a valid issue and difficult to reproduce in a repo bc it happens on a local computer bc of cached cypress data :) 
The solution is to delete the cypress cache from your local machine completely. (On Mac, the location is /Users/<yourusername>/Library/Application Support/Cypress/) You can first try to delete the projects folder inside the cy dir; if it does not help, try deleting the cy and even the Cypress folder itself. 
FYI: cypress may require you to verify as if u run the app for the first time upon starting it again.

**Comment by RealByron** [comment]
> @jasp402, this will be fixed in one of the upcoming releases.
> Edit: this has been fixed with v19.0.0.

@badeball 
using enabled settings 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/1749192/f0c03c90-c47d-43df-a305-14889a2245b5)
I always get some annoying cy.task logs on V19.1.1
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/1749192/7f3f109e-c28d-4265-9e4f-b5458c17fbd1)
it's seems that {log: false} options are ignored....

**Comment by badeball** [comment]
You need to open up a separate issue as this has nothing to do with OPs problem (and remember to fill out the template properly).

**Comment by RealByron** [comment]
@badeball 
I will do that, I just try to make a scrap project and I don't see the same behavior, It may be related to other stuff in my projects

**Comment by badeball** [comment]
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.
