### ISSUE TITLE
Execution Test Sequence Management

### ISSUE THREAD

**Issue by kushal-omnius** [badeball/cypress-cucumber-preprocessor#1087]
### Current behavior
So I recently observed why my few test cases always fail, despite re-running them individually resulting in passing ( as there is some dependency of test data on previous tests.
Note - I know all the tests should be run in isolation but there is no other way because creating data takes an hour at least in the product and for every test creating their own test data is just not feasible.)

So basically I have arranged all my tests in folders and sub-folders so that all the tests run in a sequence that is optimal. I looked at the sequence of test executions and how they are run and found the problem.

The current execution sequence is all tests residing at the same level in **API** and **UI** both get executed first and then the next hierarchy level tests are executed including both **API and UI** folder and so on.

Directory structure:
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/116175686/70161d62-695e-4f40-8c44-cbf26eb95123)

Execution sequence:
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/116175686/ac91a6a5-1e82-4843-8b1b-a329d46423a6)

### Desired behavior

In the above tree, I would expect all the tests in the **API** folder to run first and then the first sub-folder and every subfolder inside it and so on, and once everything inside **API** folders is executed test execution will move to **UI** folder. So my question is, is this coming from preprocessor; and is there a way to change the execution sequence?

### Versions

* **Cypress version**: any
* **Preprocessor version**:  18.0.5
* **Node version**: 20

### Checklist

- [ yes] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [yes ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ yes] I'm not using `cypress-cucumber-preprocessor@4.3.1` (the package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> So my question is, is this coming from preprocessor; and is there a way to change the execution sequence?

Who knows. Fill out the remaining piece of the template and maybe I’ll have a look.

**Comment by kushal-omnius** [comment]
@badeball please find here a simple reproduction of this issue:

**Code Repo:**

https://github.com/far11ven/Cypress-TestFramework/tree/develop/v13

**Action run:**
https://github.com/far11ven/Cypress-TestFramework/actions/runs/6058696205/job/16441070392

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/116175686/753f139d-ead8-4edb-9fa2-d9215d575c83)

**Features DIR tree:**
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/116175686/de75d125-ac30-4bc1-8fb8-b4593a60e734)

**Comment by badeball** [comment]
This appears to be dependant on some locally running database, which I don't have. You need to reduce the example into something more minimal. From the contributing guidelines:

> Any of the many [examples](https://github.com/badeball/cypress-cucumber-preprocessor/blob/2c9c8b8d78176fd65e334635cb241abac683c5ca/examples) can serve as a good starting point for creating a minimal, reproducible example. Take one, modify it and use it to illustrate what you think is wrong. Upload it to EG. Github and link to it from your bug report.

**Comment by kushal-omnius** [comment]
@badeball Even I don't have that DB anymore. The question here is not that all tests should pass, but rather the tests should follow a proper predefined sequence. 

In the above sample, my expectation is:
1) All tests in "API" and then its subdirectory "GET" should execute first
2) Then all tests inside "DB" and at last UI directory

But that's not the case **API/GET/*** tests get executed at the very last.

**Comment by badeball** [comment]
> In the above sample, my expectation is:

Is the described expectation something you see with vanilla Cypress?

**Comment by kushal-omnius** [comment]
@badeball I was also able to reproduce with vanilla Cypress. Guess this issue lies with them.

Raised it here:

https://github.com/cypress-io/cypress/issues/27736
