### ISSUE TITLE
Cucumber tests fail in Gitlab CI/CD only

### ISSUE THREAD

**Issue by sscaff1** [badeball/cypress-cucumber-preprocessor#1094]
### Current behavior

Locally all of my tests run fine. In Gitlab, they fail because they fail to resolve react. Below is an error message:

![Screenshot 2023-09-11 at 3 30 06 PM](https://github.com/badeball/cypress-cucumber-preprocessor/assets/1554424/fe1815a5-e004-4980-a65b-639da13d899d)

Here is my cypress config:

```ts
import { join } from 'path';
import { defineConfig } from 'cypress';
import { initPlugin } from 'cypress-plugin-snapshots/plugin';
import { devServer } from '@cypress/vite-dev-server';
import { defineConfig as defineViteConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { createRollupPlugin } from '@badeball/cypress-cucumber-preprocessor/rollup';
import { viteCommonjs } from '@originjs/vite-plugin-commonjs';
import tsconfigPaths from 'vite-tsconfig-paths';

type TRollupConfig = Partial<Parameters<typeof defineConfig>[0]>;
type TViteConfig = Partial<Parameters<typeof defineViteConfig>[0]>;

// eslint-disable-next-line import/prefer-default-export
export const getCypressConfig = ({
  customConfig,
  customViteConfig,
}: { customConfig?: TRollupConfig; customViteConfig?: TViteConfig } = {}) =>
  defineConfig({
    component: {
      indexHtmlFile: join(__dirname, 'component-index.html'),
      specPattern: 'tests/cypress/cucumber/**/*.feature',
      devServer(devServerConfig) {
        return devServer({
          ...devServerConfig,
          framework: 'react',
          viteConfig: {
            plugins: [
              react(),
              createRollupPlugin(devServerConfig.cypressConfig),
              viteCommonjs(),
              nodePolyfills(),
              tsconfigPaths(),
            ],
            ...customViteConfig,
          },
        });
      },
      async setupNodeEvents(on, config) {
        initPlugin(on, config);
        await addCucumberPreprocessorPlugin(on, config);
        return config;
      },
    },
    fixturesFolder: false,
    retries: {
      openMode: 0,
      runMode: 2,
    },
    video: false,
    ...customConfig,
  });
```

(we've abstracted it into a function - most of the time this function is called with nothing). Locally everything runs fine. I've tried doing fresh clones of the repo and even running it inside the same docker image that gitlab is using - it all passes locally.

### Desired behavior

For the tests to pass in Gitlab CI/CD env.

### Versions

* **Cypress version**: 12.17.3
* **Preprocessor version**: 18.0.1
* **Node version**: 18

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I fail to see how this is any of my concern. You should also know that I rarely, if ever, involve myself in issues wherein the template is not filled out properly.
