### ISSUE TITLE
Importing code from this library makes VS Code show types conflict between Jest and Cypress

### ISSUE THREAD

**Issue by ghost** [badeball/cypress-cucumber-preprocessor#1095]
### Current behavior

This issue is a duplicate from [another one I created in a different repo](https://github.com/nrwl/nx/issues/19132) but I would like your input on the matter.

Importing code from this library in a Cypress component test file makes VS Code's TypeScript Language Server show typing errors in the Jest test files of my project. TypeScript configuration files seems to be configured appropriately and I get no runtime errors.

I'm assuming the problem comes from the fact that your `tsconfig.json` contains `"types": ["cypress"]` but I don't understand why this would affect the Jest test files of my project which have their specific TypeScript configuration to avoid typing conflicts with Cypress.

### Desired behavior

I would like to be able to use this library without causing typing conflicts between Jest and Cypress.

### Test code to reproduce

Here is a repository that replicates the issue: https://github.com/zilia-gmethot/jest-cypress-conflict.

1. Open the repository with the latest version of VS Code
2. Open the file `apps/frontend-device/src/app/app.component.spec.ts` and notice the typing errors.
3. Open the file `apps/frontend-device/src/app/app.component.cy.ts` and comment out line 3, which contains `import '@badeball/cypress-cucumber-preprocessor';`
4. Open the file `apps/frontend-device/src/app/app.component.spec.ts` and notice that the typing errors are gone.

### Versions

* **Cypress version**: 12.17.4
* **Preprocessor version**: 18.0.5
* **Node version**: 16.19.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This isn't something I can help you with. Jest and Cypress' types are just conflicting. See https://github.com/cypress-io/cypress/issues/22059 and https://docs.cypress.io/guides/component-testing/faq#How-do-I-get-TypeScript-to-recognize-Cypress-types-and-not-Jest-types.
