### ISSUE TITLE
Getting error while running ,cypress with browserify CJS example setup files.

### ISSUE THREAD

**Issue by Ljsam6** [badeball/cypress-cucumber-preprocessor#1096]
### Current behavior
Getting below error while making changes to cypress.config.js  to incorporate cucumber framework to my existing test suite.

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/29755073/9b06d0c0-5607-494a-b4dc-ec1c6797ad3a)

My package.json file screenshot.
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/29755073/59f3089f-fd8c-465b-ba87-8e56005dc6cd)

My cypress.config.js  screenshot.
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/29755073/f5f7a66b-ff30-4743-9dc7-a94c01b4918f)

### Desired behavior

After installing 
"@badeball/cypress-cucumber-preprocessor": "^18.0.5",
    "@cypress/browserify-preprocessor": "^3.0.2"

and setting up the config file , we should be able to see .feature files in cypress test runner.

Failure to provide this only serves to waste the maintainer's time. Try not to do this.

[1] https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case

-->

### Versions

* **Cypress version**:^12.17.3
* **Preprocessor version**:^18.0.5
* **Node version**:12.15.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Update your node version.
