### ISSUE TITLE
Unable to generate HTML report.

### ISSUE THREAD

**Issue by Ljsam6** [badeball/cypress-cucumber-preprocessor#1098]
### Current behavior

Not able to generate HTML Reports . Please do let me know If I am missing any steps , and any resource to refer the same.

### Desired behavior

Should Be able to generate HTML reports

### Test code to reproduce

-Added as suggested by the documentation , attached details to Package.json
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/29755073/eb103e4d-b4bf-4d8d-bfa2-e1dc423a26ba)

-I tried running my .feature file using cypress run/open .
-No HTML reports were generated for passed/failed TC .

### Versions

* **Cypress version**:^12.17.3
* **Preprocessor version**:^18.0.5
* **Node version**: 20.6.0

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md

**Comment by Ljsam6** [comment]
> https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md
hey
I tried keeping the configuration as shown in the example.still not working :(

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/29755073/85cf7282-cedf-4e8b-88ee-93303cac82fb)

**Comment by badeball** [comment]
Then you need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by Ljsam6** [comment]
Hey please find details below:

Issue : 
Unable to Generate Json , HTML report after setting value as true in package.json file for the test suite.

Expected : 
Should see a report generated in root folder after running npx cypress open/run once Test suite pass or fail


package.json
```
{
  "name": "minimal-code-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^18.0.6",
    "@cypress/browserify-preprocessor": "^3.0.2",
    "cypress": "^13.2.0"
  },
  "cypress-cucumber-preprocessor": {
    "json": {
      "enabled": true
    }
  }
}
```
cypress.config.js
```
const { defineConfig } = require("cypress");
const {
  addCucumberPreprocessorPlugin,
} = require("@badeball/cypress-cucumber-preprocessor");
const {
  preprocessor,
} = require("@badeball/cypress-cucumber-preprocessor/browserify");

async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await addCucumberPreprocessorPlugin(on, config);

  on("file:preprocessor", preprocessor(config));

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

module.exports = defineConfig({
  e2e: {
    baseUrl: "https://duckduckgo.com",
    specPattern: "**/*.feature",
    setupNodeEvents,
  },
});
```

Path for below files  .\Minimal Code example\cypress\e2e
duckduckgo.feature 

```
Feature: duckduckgo.com
    Scenario: visiting the frontpage
        When I visit duckduckgo.com
        Then I should see a search bar
```

duckduckgo.js
```
const { When, Then } = require("@badeball/cypress-cucumber-preprocessor");

When("I visit duckduckgo.com", () => {
  cy.visit("https://duckduckgo.com/");
});

Then("I should see a search bar", () => {
  cy.get("input[type=text]")
    .should("have.attr", "placeholder")
    .and(
      "match",
      /Search the web without being tracked|Search without being tracked/
    );

  assert.deepEqual({}, {});
});

```

**Comment by badeball** [comment]
You need to provide a complete and runnable example, preferably in the form of a repository I can clone.

**Comment by Ljsam6** [comment]
Hello , 
Issue :
Unable to Generate Json , HTML report after setting value as true in package.json file for the test suite.

Expected :
Should see a report generated in root folder after running npx cypress open/run once Test suite pass or fail

Version
Preprocessor version:^18.0.6
Node version: 20.6.0

Code:
Please have a look  here https://github.com/Ljsam6/Minimal-Code-Example.git

**Comment by Ljsam6** [comment]
> You need to provide a complete and runnable example, preferably in the form of a repository I can clone.

Hey hope , you are doing good have you had a chance to look into above repo . Thanks

**Comment by badeball** [comment]
Your example correctly generates a JSON report upon `cypress run`, which is expected. So what's the problem?

**Comment by Ljsam6** [comment]
> Your example correctly generates a JSON report upon `cypress run`, which is expected. So what's the problem?

sorry my bad yes it is!!! but when I tried with cypress open it didn't work apparently .

**Comment by badeball** [comment]
> but when I tried with cypress open it didn't work apparently .

Reports aren’t generated in interactive mode and this is explained in the FAQ.
