### ISSUE TITLE
cucumber-js reporting service with cypress-cucumber-preprocessor 

### ISSUE THREAD

**Issue by s1mrankaur** [badeball/cypress-cucumber-preprocessor#1100]
👓 What did you see?
**cucumber-js publish

Cucumber report being published with 0 scenarios**

```
0 scenarios
0 steps
0m00.001s (executing steps: 0m00.000s) 
```
✅ What did you expect to see?
We are using Cypress with Cucumber and have following configuration:

```
"cypress-cucumber-preprocessor": {
   "nonGlobalStepDefinitions": true,
   "stepDefinitions": "cypress/e2e/",
   "cucumberJson": {
     "generate": true,
     "outputFolder": "cypress/cucumber-json",
     "filePrefix": "",
     "fileSuffix": ".cucumber"
   }
}
```
 
There are JSON files in cypress/cucumber-json and I expected a report with the correct stats to be published on running
cucumber-js publish

📦 Which tool/library version are you using?
```
"cypress": "12.12.0",
"cypress-cucumber-preprocessor": "^4.3.1",
"cypress-js": "9.5.1"
```

📚 Any additional context?
My understanding was that cucumber-js would just publish the report based on JSON outputs. What additional steps may be needed to get this working?

**Comment by badeball** [comment]
`$ cucumber-js publish` probably doesn't do what you think it does. It merely searches for features in `publish/` and runs them (it found zero). Additionally, you need to fill it the issue template for any future tickets.
