### ISSUE TITLE
Cucumber task will time out when iterating over a large list of items

### ISSUE THREAD

**Issue by hammzj** [badeball/cypress-cucumber-preprocessor#1102]
### Current behavior

I have a test which validates a website that displays a configuration page of feature flags for a given organization. These feature flags are displayed as a list of divs that include a title, description, and value. In one example, there are 90 items I need to validate in a single step, using the backend contents and checking that they're accurate on the webpage.

Whenever I try to validate these through `cypress open`, the testrunner freezes for a slight bit, will complete the validation, but fail due to an error with a Cypress task not being completed in 60 seconds.

##### Testrunner output
<img width="520" alt="Screenshot 2023-10-09 at 11 07 30 AM" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/7e42eabe-3f06-4c2d-9fd1-4e3f7af9a382">

##### Test error
<img width="520" alt="Screenshot 2023-10-09 at 11 07 41 AM" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/85999f51-83c8-4431-902a-e79f93f4a5aa">

### Desired behavior

Add ability to set the task timeout of the task either using a Cypress configuration option or environment variable.

Secondly, allow debugging to be enabled for the Cypress Cucumber internal tasks.

### Test code to reproduce

_Note: this test case can cause problems with Chrome and crash the browser occasionally! As well, the length of the list of items may need to changed based on your computer's internal memory. I'm able to recreate this without crashing on a MacOS with Ventura 13.6 and 16GB of RAM at 70 iterations, but Chrome crashes above that._

I have a test project with a branch here that can be forked: https://github.com/hammzj/cypress-testing/tree/dev/cypress-issue-task-timeout

### Versions

* **Cypress version**: 12.12.0
* **Preprocessor version**: 18.0.2 (also on 18.0.6)
* **Node version**: 18.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by hammzj** [comment]
I do see that adding a small `cy.wait` in the `for each` block seems to avoid the testrunner freezing as frequently and causing the task to timeout, so that is definitely a way to avoid this issue without code changes. However, this shows that Cypress has issues with many sequential commands that do not have a gap between them.

**Comment by badeball** [comment]
The task seen failing isn't run unless messages or pretty reporting is turned on, which I can't see that it is in your repository. Can you make the necessary changes and _confirm_ that you see the error using the code you're providing me?

**Comment by hammzj** [comment]
It had been happening earlier, but I'll see about making those changes. This might be intermittent due to it relying on hardware architecture as well.

However, based on my proposed solution, is it possible to allow configuring the timeout of Cucumber tasks from an environment variable instead of it being hard set at 60 seconds?

**Comment by badeball** [comment]
You can configure task timeouts using [`taskTimeout`](https://docs.cypress.io/guides/references/configuration#Timeouts). However, I'm not going to make any changes to the library until it is evident that it actually is a task timeout happening as opposed to Cypress misreporting where time is spent (this has come up [before](https://github.com/cypress-io/cypress/issues/25326)).

**Comment by hammzj** [comment]
Is `taskTimeout` configurable via a tag pattern, like in the [test-configuration.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/test-configuration.md)? I could utilize that, though I am finding a short 100 ms wait is helping mitigate these problems.

I am still working on a more consistent reproducible example as well.

**Comment by badeball** [comment]
> Is `taskTimeout` configurable via a tag pattern, like in the [test-configuration.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/test-configuration.md)? I could utilize that, though I am finding a short 100 ms wait is helping mitigate these problems.

 No, I don’t think so. The tag pattern is merely a bridge to test configuration as described here: https://docs.cypress.io/guides/references/configuration#Test-Configuration

This library doesn’t contain any knowledge of valid tags and will simply propagate “anything”. If Cypress doesn’t recognise a property, I suppose it will silently ignored it, albeit unrecognised tags aren’t tested so I’m not entirely sure.

**Comment by hammzj** [comment]
Right, I've understood that but not so much as what the preprocessor offers in terms of abstracting tags to the Cypress configuration.

In this case, would it be possible that a new tag is added for `@taskTimeout(X)` in lines with how `@defaultCommandTimeout(X)` and others operate? That would work best in fixing this issue until https://github.com/cypress-io/cypress/issues/25326 is resolved. I am going to make a note there as well on the slowdown.

**Comment by badeball** [comment]
> In this case, would it be possible that a new tag is added for `@taskTimeout(X)` in lines with how `@defaultCommandTimeout(X)` and others operate?

No. As I tried to say, this library doesn’t concern itself with what tags you write, it merely translates them. You can write your above-mentioned tag but it’s just not going to do anything, because it’s not a recognised test-specific property by Cypress.

**Comment by hammzj** [comment]
It _is_ possible to set the `taskTimeout` with a tag 😄 :

<details>
<summary>Feature</summary>

<img width="1434" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/ab5e360b-800b-4809-94a6-95fd5af5041b">
</details>

<details>
<summary>Testrunner</summary>

<img width="1552" alt="Screenshot 2023-10-10 at 2 52 56 PM" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/24662706/d9613df1-1354-4c6e-9df3-7b8eabf44125">
</details>

The property for `taskTimeout` is included in [`Cypress.TestConfigOverrides`](https://github.com/cypress-io/cypress/blob/9f3d5b4565b7791d0b829c4953ab270c7252dc8a/cli/types/cypress.d.ts#L3283C13-L3283C32) which is returned within the function [`tagToCypressOptions`](https://github.com/badeball/cypress-cucumber-preprocessor/blob/c465d824bea8c78ec9d99f95ecca39f3dea7ef24/lib/helpers/tag-parser/index.ts#L3). Only thing that will need updated is the markdown doc for "test-configuration".

**Comment by badeball** [comment]
> Only thing that will need updated is the markdown doc for "test-configuration".

No, That page is only intended to be a mirror of Cypress' documentation. If it's wrong, then Cypress' documentation is wrong. If you have found that there's additional, undocumented configuration options available, then you need to direct your attention appropriately.

**Comment by hammzj** [comment]
I would have been happy to make that change in the markdown document as much as I'm happy to address it with Cypress. There's always room for clarity, however, and there's definitely more encouraging ways to address developers raising attention to issues without negative reinforcement.

**Comment by hammzj** [comment]
https://github.com/cypress-io/cypress-documentation/issues/5532

**Comment by hammzj** [comment]
Documentation has been updated on Cypress' side with the PR listed above!

Edit: I meant to add that I could open a PR here to update the docs with that tag since the documentation has been updated on Cypress' side. Not to be persistent, but it is a good callout in case others need to toggle that option per scenario. Let me know if that works!

**Comment by badeball** [comment]
I managed to reproduce the issue eventually. Furthermore, I managed to reproduce it without using the preprocessor, as seen [here](https://github.com/badeball/reproducible-issues/tree/master/cypress/task-timeout). In other words, it has nothing to with the preprocessor. The error also appears to disappear with Cypress v13.0.0. Considering this resolved, thus closing.
