### ISSUE TITLE
The "cy.readFile("path/to/file.png") timed out" error message is displayed in the "afterEach" hook when the scenario fails

### ISSUE THREAD

**Issue by artem-sokorskyi** [badeball/cypress-cucumber-preprocessor#1105]
### Current behavior

The "cy.readFile("path/to/file.png") timed out" error message is displayed in the "afterEach" hook when the scenario fails. Note that timeout happens immediately without any miliseconds to pass away

### Desired behavior

The cy.readFile("path/to/file.png") can be successfully used in the "afterEach" hook when the scenario fails

### Test code to reproduce
Link to already prepared repo with a reduces test case inside the "**bug**" branch
https://github.com/artem-sokorskyi/cypress-test-tiny/tree/bug

### Versions

* **Cypress version**: 13.3.1
* **Preprocessor version**: 18.0.6
* **Node version**: 18.17.1

### Checklist

- [ x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by artem-sokorskyi** [comment]
I bypassed that issue by using `cy.task('readFile', args)`. Though still I believe this issue should be reported and fixed

**Comment by badeball** [comment]
This seems to happen regardless of whether you use this preprocessor or not. The same error can be seen by changing `spec.cy.js` to

```js
describe('page', () => {
  it('works', () => {
    throw new Error('intended')
    cy.visit('https://example.cypress.io')
  })
})

afterEach(() => {
  cy.readFile('Sample-png-image-200kb.png').then(res => {})
})
```

.. and running said spec. Therefore this doesn't pertain to the preprocessor and you should create a ticket with Cypress.
