### ISSUE TITLE
The "attach" function attaches two screenshot instead of only one

### ISSUE THREAD

**Issue by artem-sokorskyi** [badeball/cypress-cucumber-preprocessor#1107]
### Current behavior

The "**attach**" function attaches two screenshots instead of only one

Here's the log result in the `messages.ndjson`:
```
{"attachment":{"testCaseStartedId":"bcd95cfe-9f09-4243-a4b1-89c8eb94e339","testStepId":"845a81a2-ade3-4c39-8479-2688933e4524","body":"iVBORwP8xnm82bevJl...SuQmCC","mediaType":"image/png","contentEncoding":"BASE64"}}
{"attachment":{"testCaseStartedId":"bcd95cfe-9f09-4243-a4b1-89c8eb94e339","testStepId":"845a81a2-ade3-4c39-8479-2688933e4524","body":"zGjRtPLI/HzbNTp2EyEpfrMi...azghd4","mediaType":"image/png","contentEncoding":"BASE64"}}
```

### Desired behavior

The "attach" function attaches one screenshot

### Test code to reproduce

```
  cy.screenshot({
    capture: 'runner',
    onAfterScreenshot($el, props) {
      const rootProjectFolder = Cypress.config('fileServerFolder');
      const pathToScreenshot = props.path.replace(`${rootProjectFolder}/`, '');
      cy.readFile(pathToScreenshot, 'base64').then((content) => {
        attach(content, 'base64:image/png');
      });
    },
  });

```

### Versions

* **Cypress version**: 13.2.0
* **Preprocessor version**: 18.0.6
* **Node version**: 18.17.1

### Checklist

- [ x ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ x ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by artem-sokorskyi** [comment]
I just want to add that step which has duplicated screenshots isn't failed so it's not that there's a mix of **failed screenshot** (screenshotOnRunFailure) and my **cy.screenshot**

**Comment by badeball** [comment]
Screenshots are automatically added to reports, as per [docs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md). You're adding it a second time, thus this seems like expected behavior.

**Comment by artem-sokorskyi** [comment]
oh missed that part, thanks))
