### ISSUE TITLE
Missing current step in window.testState

### ISSUE THREAD

**Issue by midhunchalakkal** [badeball/cypress-cucumber-preprocessor#1108]
### Current behavior

In preprocessor v18.0.6, window.testState object contains currentStep index that can be used to identify which step is currently running at the time and used to get the tag names used in the current test.  Which Couldn't find the latest preprocessor version.

Is there any way to get the tag names used in the cucumber  before method hooks like mentioned below ? 
window.testState.pickle.tags.map(tag => tag.name)

### Desired behavior

testState object should contains current step information to make it easy to debug at each step level.

### Versions

* **Cypress version**: 13.2.0
* **Preprocessor version**: 18.0.6
* **Node version**: v20.0.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/979

**Comment by badeball** [comment]
> Is there any way to get the tag names used in the cucumber before method hooks like mentioned below ?

With v19.0.0, `Before` hooks are invoked with some [parameters](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/cucumber-basics.md#scenario-hooks), including pickle, from which tags also can be retrieved.
