### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /ee-auto-ui-test/cypress.config.ts

### ISSUE THREAD

**Issue by Yangfan2016** [badeball/cypress-cucumber-preprocessor#1109]
### Current behavior

When I run `cypress open` ,It's catch a error
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/17830872/a070fed1-7af9-40b2-8bbe-bdd6b16a8301)

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /ee-auto-ui-test/cypress.config.ts

### Desired behavior

no error

### Test code to reproduce

```ts
import { defineConfig } from "cypress";
import clipboardy from "clipboardy";
import * as fs from "fs";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import { createEsbuildPlugin } from "@badeball/cypress-cucumber-preprocessor/esbuild";

export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await addCucumberPreprocessorPlugin(on, config);

      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
          // tsconfig: "./tsconfig.json",
        })
      );
      // on('after:run', (results) => {});
      on("task", {
        // Clipboard test plugin
        getClipboard: () => {
          const clipboard = clipboardy.readSync();
          return clipboard;
        },
        // reset for timeout
        writeFile({ filename, data }) {
          fs.writeFileSync(filename, data);
          return null;
        },
      });
      return config;
    },
    specPattern: "cypress-client/integration/features/**/*.spec.{js,feature}",
    // pageLoadTimeout: 100e3,
    // defaultCommandTimeout: 6e3,
    // responseTimeout: 6e3,
    fixturesFolder: "cypress-client/fixtures",
    supportFile: "cypress-client/support/e2e.ts",
    numTestsKeptInMemory: 0,
    video: false,
    // watchForFileChanges: false,
    redirectionLimit: 3,
    testIsolation: false,
    experimentalMemoryManagement: true,
  },
});


```

### Versions

* **Cypress version**:  v12.17.4
* **Preprocessor version**: 
* **Node version**: v14.17.4

"@badeball/cypress-cucumber-preprocessor": "^18.0.6",
"@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by Yangfan2016** [comment]
> Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

download this gitrepo, swtich to branch 'dev-yf' . run `npm run c`
 
https://github.com/Yangfan2016/demo-cypress/tree/dev-yf

**Comment by badeball** [comment]
You need to install `typescript`, as per all the examples.

**Comment by Yangfan2016** [comment]
hello ，I catch other error， help me ，thx ~ 

<img width="1706" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/17830872/10720423-71ea-42dd-9dc6-7f9a0fd0d8a5">


cypress-cucumber-preprocessor.config.js
```js
module.exports = {
  cucumberJson: {
    generate: true,
    outputFolder: "cypress-client/cucumber-json",
    filePrefix: "",
    fileSuffix: ".cucumber",
  },
  stepDefinitions: `cypress-client/support/step_definitions`,
  // commonPath: `cypress-client/integration/common/`,
};


```

<img width="1004" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/17830872/3ba39c8a-a29e-4a72-a32d-008b653bd898">


@badeball

**Comment by badeball** [comment]
This is not a support forum and I'm not going to help you as long as you keep making it this difficult. There's only one thing I'm interested in and that's [minimal, reproducible examples](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case).
