### ISSUE TITLE
Request to remove deprecated "cucumber" dependency

### ISSUE THREAD

**Issue by FirstOrangutan** [badeball/cypress-cucumber-preprocessor#1111]
### Current behavior

Hello, currently cucumber package, which is listed as a dependency is marked as deprecated and has been moved to "@cucumber/cucumber".

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/46435477/43bc1ab6-e879-475c-8bff-fd780288689c)

### Desired behavior

I would like to request a change to the new "@cucumber/cucumber" dependency. The reason to request this change is that cucumber has a dependency called "colors" listed with version "^1.1.2" 

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/46435477/0d11c837-d7e9-4a1e-8db9-47ee0b515460)

Colors package recently had some issue and had to remove a previously listed version "1.4.2" - which is what "^1.1.2" was resolving to, earlier. Now the latest available version of "colors" is "1.4.0", which causes issues in our pipeline during build and install. We don't have a direct dependency to "colors", only to "cypress-cucumber-preprocessor". And since "cucumber" is already deprecated, our only option to request a change here. Also, this won't be an issue with the new "@cucumber/cucumber" because "colors" is not listed as a dependency there. 

### Test code to reproduce

Not applicable because this is a dependency change request. 

### Versions

* **Cypress version**: "^12.8.1",
* **Preprocessor version**: "^4.2.0",
* **Node version**: "16.14.2"

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
The package has moved to `@badeball/cypress-cucumber-preprocessor`, read more about the transfer [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689), IE. you're not using the most recent version, but you should. The recent versions have already made this change.
