### ISSUE TITLE
No longer possible to use Step() in beforeEach and afterEach hooks

### ISSUE THREAD

**Issue by dmbartle** [badeball/cypress-cucumber-preprocessor#1112]
### Current behavior

If a user attempts to use Step() in a beforeEach or afterEach hook, for example: 

```
afterEach(() => {
  expect(1).to.eql(1)
  Step(this, 'I do some post hypothetical test cleanup')
})
```

Then this will cause an error when attempting to run the test. 

`Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)`

### Desired behavior

Using Step() actions like this in beforeEach and afterEach hooks used to be supported in previous versions of cypress. 
I know for sure it worked in this version, but not sure exactly when it started giving this error.
"@badeball/cypress-cucumber-preprocessor": "16.0.3"

Note: 
It is still possible to use Step() in Before() and After() hooks, I've included this in the minimum example. I'm using an afterEach hook as I want test clean-up to happen even when a test fails.

### Workaround
Remove the Step() action and call the commands directly.

### Test code to reproduce

https://github.com/dmbartle/aftereach-step-hook-issue-min-example

### Versions

* **Cypress version**: 13.4.0
* **Preprocessor version**: 18.0.6
* **Node version**: v20.1.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
It might very well have worked before, but this was never intended to be supported. I see no reason to complicate teardown by doing this.
