### ISSUE TITLE
Type support for named hooks

### ISSUE THREAD

**Issue by mysticdevx** [badeball/cypress-cucumber-preprocessor#1113]
### Current behavior

As of v19.0.0 named hooks are supported as mentioned [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/cucumber-basics.md#named-hooks). Although the functionality works as expected, the type definition for the name property is missing. See: 

<img width="1087" alt="name-res" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/49609497/e2c7514e-3f1f-4e5e-a333-86661c0bac4f">

### Desired behavior

Optional name property type should also be resolved, like tags.

@badeball if no release is planned sooner, and if it's ok, I can create a minimal pull request for this.

### Test code to reproduce
no need, see above ss.

### Versions

* **Cypress version**: 13.4.0
* **Preprocessor version**: 19.0.0
* **Node version**: 18.17.1

### Checklist

- [ x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version; see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Good catch, @mysticdevx. I've updated the type members with v19.0.1.
