### ISSUE TITLE
If you run Cucumber and standard Cypress you cannot use not tags

### ISSUE THREAD

**Issue by PaulDotmatics** [badeball/cypress-cucumber-preprocessor#1116]
### Current behavior

If I have a test like 

describe('My First Test', () => {
  it('Does not do much!', () => {
    expect(true).to.equal(true)
  })
})

and also have cucumber scenarios if I run the suite with

cypress open -env TAGS='not @Test'

then My first test wont appear in the run at all. If I dont pass -env TAGS='not @test' then they appear

### Desired behavior

Should allow the use of not tags and still allow other tests to appear that arent cucumber scenarios

### Test code to reproduce

describe('My First Test', () => {
  it('Does not do much!', () => {
    expect(true).to.equal(true)
  })
})

Feature: duckduckgo.com
@Test
  Scenario: visiting the frontpage
    When I visit duckduckgo.com
    Then I should see a search bar

### Versions

* **Cypress version**: 13.5.0
* **Preprocessor version**:19.1.0 
* **Node version**:v20.5.0

**Comment by badeball** [comment]
I don't feel strongly about the behavior here and absence of other requirements, I'm inclined to agree. I've fixed this with v19.1.1.

**Comment by badeball** [comment]
I've sort of reverted 0b2702b and introduced an [option](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md#tag-filters-and-non-cucumber-specs) to control this behavior. If you want negative expressions to include non-Cucumber specs, you now need to set `filterSpecsMixedMode` to `"empty-set"`.
