### ISSUE TITLE
 Invalid or unexpected token when using createEsbuildPlugin

### ISSUE THREAD

**Issue by LukasLewandowski** [badeball/cypress-cucumber-preprocessor#1118]
### Current behavior

Cypress fails to start the test at the first run in headed mode but rerunn is working fine.  

### Desired behavior

Cypress should start tests for the first time in headed mode. 

### Test code to reproduce

Previously I was using browserify and everything works as expected but I wanted to give a shot with Esbuild, so I followed example for it from https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/esbuild-ts/cypress.config.ts 
and I have observed that Cypress GUI lunches faster but after clicking on any of the test it will fail for the first run with Unexpected token error emmited from outside of Cypress code. Second execution will start the test without an error.

```
Cypress
SpecRunner
Passed:
--
Failed:
1
Pending:
--
[payFacMastercardTrx.feature](https://local.com:8000/__/#)42ms
An uncaught error was detected outside of a testfailed
No commands were issued in this test.
SyntaxError
The following error originated from your test code, not from Cypress.



  > Invalid or unexpected token



When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.



Cypress could not associate this error to any specific test.



We dynamically generated a new test to display this failure.
View stack trace
 Print to console
at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (.com:8000/__cypress/runner/cypress_runner.js:3486:19)
at Promise._then (8000/__cypress/runner/cypress_runner.js:1239:17)
at Promise.then (8000/__cypress/runner/cypress_runner.js:1132:17)
at runScriptsFromUrls (.com:8000/__cypress/runner/cypress_runner.js:110809:136)
at Object.runScripts (8000/__cypress/runner/cypress_runner.js:110850:12)
at $Cypress.onSpecWindow (.com:8000/__cypress/runner/cypress_runner.js:40878:67)


ChromeChrome 119

```
<img width="495" alt="image" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/11457876/8f61fe0a-3eb7-4d05-855e-e5560ec7e177">

Maybe I am doing smth wrong?

### Versions

* **Cypress version**: 13.5.0
* **Preprocessor version**: 19.1.0
* **Node version**: 20.9.0
* I am using TypeScript. 

My tsconfig.json:
```
{
    "compilerOptions": {
        "baseUrl": "./",
        "target": "ESNext",
        "lib": ["ESNext", "DOM"],
        "types": [
            "cypress",
            "./cypress/support/index.d.ts",
            "@testing-library/cypress",
            "node",
            "cypress-real-events",
            "cypress-file-upload"
        ],
        "allowJs": false,
        "noEmit": true,
        "noFallthroughCasesInSwitch": true,
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "resolveJsonModule": true,
        "isolatedModules": false,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true
    },
    // workaround for cypress bug
    "ts-node": {
        "compilerOptions": {
            "module": "ESNext",
            "moduleResolution": "Node"
        }
    },
    "include": ["./**/*.ts"],
    "exclude": ["node_modules", "dist", "reports"]
}
```

my cypress.config.ts:
`import { defineConfig } from 'cypress';
import createBundler from '@bahmutov/cypress-esbuild-preprocessor';
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor';
import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild';
// import browserify from '@badeball/cypress-cucumber-preprocessor/browserify';
import { readFileSync } from 'fs';
import { Client } from 'pg';
import { getDownloads, readPdf, createJsonFile } from 'cypress/support/utils/cypressTasks';

async function setupNodeEvents(
    on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions,
): Promise<Cypress.PluginConfigOptions> {
    /* This is required for the preprocessor to be able to generate JSON reports after each run, and more, */
    await addCucumberPreprocessorPlugin(on, config);

    on(
        'file:preprocessor',
        createBundler({
            plugins: [createEsbuildPlugin(config)],
        }),
    );
    // on(
    //     'file:preprocessor',
    //     browserify(config, {
    //         typescript: require.resolve('typescript'),
    //     }),
    // );
    on('task', {
        readPdf,
        getDownloads,
        createJsonFile,
    });
    .
    .
    .
    `

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by rijine** [comment]
Getting same issue with esbuild! @LukasLewandowski are you able to fix this?

**Comment by Diplodokus** [comment]
Same here to with esbuild.
But I don't know if with Webpack or Browserify is better...

**Comment by badeball** [comment]
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.

**Comment by rijine** [comment]
Upgrading the typescript version to > 4.5 fixed the issue.

**Comment by Diplodokus** [comment]
I am not using TypeScript :(
