### ISSUE TITLE
Error occured for cypress+cucumber

### ISSUE THREAD

**Issue by wanghaomiao27** [badeball/cypress-cucumber-preprocessor#1121]
### Current behavior

when I configurate cypress+BDD,it has error like below,the script couldn't be executed successfully!
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20040189/882d8ba7-bc57-4280-9f35-5adba477cfda)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20040189/ede8ab6b-de6f-4ca3-b720-d222628a94b7)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20040189/8de3900a-9a67-461e-9772-3543e0d55874)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20040189/8b4b2b77-60d7-4100-8902-a5254377c750)

### Desired behavior

login.feature was supposed to be executed successfully!

### Test code to reproduce

import {loginURL} from "../../testData/initHomePage.data";
import {Given, Then, When} from "@badeball/cypress-cucumber-preprocessor";
//import {Given,When,Then} from "@badeball/cypress-cucumber-preprocessor";

Given('User is at the login page',()=>{
    cy.initHomePage(loginURL[0].URL);
})

When('User enters username as {string} and password as {string}',(username,password)=>{
   cy.get('#login_username').type(username);
   cy.get('#login_password').type(password);
})

When('User clicks on login button',()=>{
    cy.get('button[type=button]').click()
})

Then('User is able to see the page"product center" ',()=>{
    cy.url().should('include','/aimarketer/usercenter/productcenter')
})

Make sure to read the section titled "Reduced test case" under the contributing guidelines [1]. Your
report should contain everything necessary in order for us to reproduce the issue. Preferably link
to another, minimal Git repository that illustrates the issue.

Failure to provide this only serves to waste the maintainer's time. Try not to do this.

[1] https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case

-->

### Versions

* **Cypress version**: V13.4.0
* **Preprocessor version**:19.1.0
* **Node version**:18.18.2

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by wanghaomiao27** [comment]
@badeball  please kindly help,the cypress+BDD couldn't be executed successfully

**Comment by badeball** [comment]
Move contents of `cypress/plugins/index.js` into `cypress.config.js`. And read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports) until next time.
