### ISSUE TITLE
negative filters should allow to opt-in/out for non-feature files

### ISSUE THREAD

**Issue by OleksiiKachan** [badeball/cypress-cucumber-preprocessor#1125]
### Current behavior

After this update https://github.com/badeball/cypress-cucumber-preprocessor/issues/1116 unable to separate feature and non-feature files anymore

I am in a middle of migration to cucumber and I have 3 groups for cypress tests
- legacy - regular cypress tests. ran with `--spec 'cypress/e2e/**/*.{js,jsx,ts,tsx}'` flag
- smoke - *.feature specs with `tags='@smoke'`
- extended - *.feature specs with `tags='not @smoke'`

After updating to `v19.1.1` extended group also includes all the legacy group tests since it is not .feature. I tried running negative filter and adding `--spec 'cypress/e2e/**/*.feature` flag but it looks like it is completely ignored

### Desired behavior

Be able to run feature specs separately. if needed

### Test code to reproduce

command for extended tests
```
yarn cypress run --browser chrome --env tags='not @smoke' --parallel --record --group extended-tests --ci-build-id ${CIRCLE_WORKFLOW_ID} --tag "staging,pr" --spec 'cypress/e2e/**/*.feature'
```

command for extended tests
```
yarn cypress run --browser chrome --parallel --record --group legacy-tests --ci-build-id ${CIRCLE_WORKFLOW_ID} --spec 'cypress/e2e/**/*.{js,jsx,ts,tsx}' --tag "staging,pr"
```

### Versions

* **Cypress version**: 13.5.1
* **Preprocessor version**: 19.1.1
* **Node version**: 20.9.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> I tried running negative filter and adding --spec 'cypress/e2e/**/*.feature flag but it looks like it is completely ignored

Code running in `setupNodeEvents` (like this plugin) unfortunately doesn't appear to have access to `--spec <files>` information. I've tried making in inquiry in their discord, but I highly doubt I'll get an answer.

The best alternative I can imagine right now, is to introduce an option (a mode) to control filtering of non-features when using `filterSpecs`.

**Comment by badeball** [comment]
I've added an [option](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md#tag-filters-and-non-cucumber-specs) to control this behavior with v19.2.0. By default, non-Cucumber specs are hidden when using tag expressions and `filterSpecs: true`.
