### ISSUE TITLE
Cannot see error logs details in Cypress UI debugger

### ISSUE THREAD

**Issue by avi-ran** [badeball/cypress-cucumber-preprocessor#1132]
### Current behavior

Hi! Thank you for the amazing work on the cypress-cucumber-preprocessor!

Using the preprocessor, I unfortunately cannot see the error logs details normally printed by Cypress debugger.

```gherkin
Scenario: As a software developper, I successfully see Cypress error logs on test script failure
    Given I have cloned the minimal reproductible example provided
    When I run the test "cypress/no_gherkin/duckduckgo.spec.ts" with cypress-cucumber-preprocessor enabled
    # npm run testv-cucumber
```

### Desired behavior

```gherkin
    Then I can see the error logs details normally printed by pure Cypress
```

This GIF shows:

1. the error result with cucumber enabled
2. then, cucumber preprocessor is disabled and the error log is more rich:
![no_error_preview_using_cucumber](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84993870/619c0ad3-094f-4325-afda-0e016ac1bd0e)

### Test code to reproduce

You can find the minimal, reproductible example in this dedicated project: 

https://github.com/avi-ran/cucumber-cypress-fail-without-log-example.git

### Versions

* **Cypress version**:  13.6.0
* **Preprocessor version**: 19.2.0
* **Node version**: v18.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hi, this is due to sourcemaps being disabled by default in esbuild. You can control this behavior like shown below.

```js
on(
  "file:preprocessor",
  createBundler({
    plugins: [createEsbuildPlugin(config)],
    sourcemap: "inline"
  })
);
```
