### ISSUE TITLE
cypress-cucumber-preprocessor support cypress-vite

### ISSUE THREAD

**Issue by refaeli-io** [badeball/cypress-cucumber-preprocessor#1135]
### The current state that there is a preprocessor for causing the e2e tests to be run and it is called: 
[cypress vite](https://www.npmjs.com/package/cypress-vite)

### Desired behavior
The Desired behavior is to support the cypress-cucumber-preprocessor for the cypress-vite preprocessor.
It would be great if you could provide an example of that.

The reasons for that I ask for support vite are: 
1) esbuild doesn't work well, as I tested.
2) webpack with endless errors and very slove if it works.
3) browserify is out to date.
4) Vite builds on rollup bundle 

I want to be able to use this cypress-vite preprocessor with cucumber, it is an amazing solution in my opinion, and also for future use

### Versions

* **Cypress version**: 13.6.1
* **Node version**: 16*

### Checklist

- [*] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [*] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [*] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I can’t show you how right now, but encourage anyone to make an example, if possible.

**Comment by badeball** [comment]
> 1. esbuild doesn't work well, as I tested.

This would probably be a lot more helpful if you would share more about this. Right now I suspect this screams XY: https://xyproblem.info/

**Comment by alixsep** [comment]
Any update on this?!

Edit: I would love to know how to setup this package (@badeball/cypress-cucumber-preprocessor) with cypress-vite.

**Comment by badeball** [comment]
> Any update on this?!

No. Neither of you have convinced me that this is necessary.

> I would love to know how to setup this package (@badeball/cypress-cucumber-preprocessor) with cypress-vite.

Why do you want to use cypress-vite?
