### ISSUE TITLE
esbuild always get installed even we want to use webpack

### ISSUE THREAD

**Issue by ellyxc** [badeball/cypress-cucumber-preprocessor#1136]
### Current behavior

If we want to use webpack as bundled esbuild still installed and making the install process longer in CI/CD setup for example

### Desired behavior

Add more flexible option to install bundler so that npm install run quicker

### Test code to reproduce

none, only run npm install

### Versions

* **Cypress version**: 13.6.1
* **Preprocessor version**: 19.2.0
* **Node version**: 18.17

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
`esbuild` is a regular dependency, used in [dry run](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/diagnostics.md). Hence, it is installed independently of what bundler your chose.
