### ISSUE TITLE
Error: Unexpected state in specEnvelopesHandler: initial (this might be a bug, please report at ...)

### ISSUE THREAD

**Issue by refaeli-io** [badeball/cypress-cucumber-preprocessor#1138]
### Current behavior

"before all" hook for *******
When I run the test on **open** mode., the test passes and works great.
But when I run the test on **run** mode'', the test fails with the error:

 CypressError: `cy.task('cypress-cucumber-preprocessor:spec-envelopes')` failed with the following error:
 Unexpected state in specEnvelopesHandler: initial (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
https://on.cypress.io/api/task

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: ******* ...`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail

### Desired behavior

When I run npx cypress, all works if it is with .ts, .js or.feature file.
Also, I want it to be support with cypress-cloud plugin, because I use sorry cypress

### Test code to reproduce

`npx cypress run -b chrome --e2e --config-file cypress/config/cypress.different.config.ts`
`const options = {
        webpackOptions: {
            resolve: {
                extensions: [".ts", ".js"]
            },
            module: {
                rules: [
                    {
                        test: /\.ts$/,
                        use: [
                            {
                                loader: "ts-loader",
                                options: {
                                    transpileOnly: true
                                }
                            }
                        ],
                        exclude: [/\/node_modules\//]
                    },
                    {
                        test: /\.feature$/,
                        use: [
                            {
                                loader: "@badeball/cypress-cucumber-preprocessor/dist/subpath-entrypoints/webpack",
                                options: config,
                            },
                        ],
                    },
                ]
            }
        }
    }`

OS Machine: Red Hat 7.6
Node Version: v16.20.2
Cypress package version: 12.17.4
Cypress binary version: 12.17.4
Electron version: 21.0.0
Bundled Node version: 16.16.0
"@badeball/cypress-cucumber-preprocessor": "^19.2.0",
"@cypress/webpack-prepro

- [x ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Did you not find anything related to this in the FAQ?

**Comment by DianaPlesa92** [comment]
Hi, I also get this error with **run**:

An error was thrown in your plugins file while executing the handler for the before:spec event.
The error we received was:

Error: Unexpected state in beforeSpecHandler: received-envelopes (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)


I am not using any of the plugins mentioned here, so adding cypress-on-fix might not help.
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md


Node version:v18.13.0
Cypress version: 13.6.0
 "@badeball/cypress-cucumber-preprocessor": "^19.2.0",

**Comment by badeball** [comment]
@DianaPlesa92, you need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

Edit:

> I am not using any of the plugins mentioned here, so adding cypress-on-fix might not help.

Have you not even tried?

**Comment by refaeli-io** [comment]
@badeball 
hi, Is there any update ?

**Comment by badeball** [comment]
No, read the FAQ.

**Comment by refaeli-io** [comment]
@badeball 
This is not an appropriate answer ...
The docs is problematic

**Comment by QaGermanRomero** [comment]
@ShaharM7 I  encounter the same issue, although the FAQ says it is due your code registering on event handlers used by the preprocessor; I did find that it also happens if the cypress.config.js have single quotes in ALL the requires instead of double quotes. 
I assume this is more of a Node thing so probably not a bug of the preprocessor

Hope this helps someone with the same issue
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/143838418/5f3554ba-39f7-4644-bc7a-477bdd1e17d4)

**Comment by refaeli-io** [comment]
@QaGermanRomero 
Hi
I resolve it by c[ypress-on-fix](https://github.com/bahmutov/cypress-on-fix)
Thank you :)
