### ISSUE TITLE
Error occured while using cypress+BDD

### ISSUE THREAD

**Issue by wanghaomiao27** [badeball/cypress-cucumber-preprocessor#1141]
Hello,
Could you please help me with this issue?
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/20040189/b244d8e7-fd44-4df9-bd64-670ea7054e30)

**Comment by wanghaomiao27** [comment]
@badeball  hello,master,I tried to configurate cypress+cucumber,but it pops up above issue,could u please help？

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need however to adhere to the guidelines for [reporting issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports). Please read through it and update your issue accordingly.
