### ISSUE TITLE
An error was thrown in your plugins file while executing the handler for the before:spec event

### ISSUE THREAD

**Issue by DianaPlesa92** [badeball/cypress-cucumber-preprocessor#1142]
### Current behavior

When running tests with cypress + badeball/cypress-cucumber-preprocessor integrated, and **run** command, I get this error:

_An error was thrown in your plugins file while executing the handler for the before:spec event.
The error we received was:
Error: Unexpected state in beforeSpecHandler: received-envelopes (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
    at createError (C:\InvoiceAutomation\AutoTest\node_modules\@badeball\cypress-cucumber-preprocessor\dist\helpers\error.js:9:12)
    at beforeSpecHandler (C:\InvoiceAutomation\AutoTest\node_modules\@badeball\cypress-cucumber-preprocessor\dist\plugin-event-handlers.js:190:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)_

Command:
node_modules\.bin\cypress run -spec 'cypress/e2e/duckduckgo.feature' --headless --env fileConfig=stage

I have tried cypress-on-fix and it does not help.
I am using before and beforeEach in my test cases in which I am visiting the url. 

Visiting the url outside before/beforeEach hooks works fine with run command.
Using cypress open works fine.
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/96479644/12267236-fb2b-4572-bfcf-647a50604c3d)

### Desired behavior

No errors when running tests configured with before and beforeEach hooks with cypress run.

### Test code to reproduce

Repository link: https://github.com/DianaPlesa92/AutoTest/tree/main

### Versions

* **Cypress version**:13.6.2
* **Preprocessor version**:20.0.0
* **Node version**:v18.13.0

### Checklist

- I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by pbochnak** [comment]
Same error appears for after:run event

**Comment by badeball** [comment]
> Same error appears for after:run event

This is likely not the same issue and won't be affected by the fix for the original issue. You should open up a separate issue and make sure to provide a reproducible example.

**Comment by badeball** [comment]
Hi @DianaPlesa92, thanks for putting together the example for me. I've fixed and released this with v20.0.1.

**Comment by DianaPlesa92** [comment]
Hello @badeball, it is fixed. Thank you!

**Comment by topesho** [comment]
Hi @badeball I am having the same issue with error  Error: Expected there to be a timestamp for current step (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a `after each` hook we are skipping the remaining tests in the current suite:

I am using the following
 **package.json.**

{
  "name": "xx",
  "version": "1.0.0",
  "description": "xx",
  "main": "index.js",
  "scripts": {
    "remove-cucumber-json-formatter": "rm -f tools/cucumber-json-formatter",
    "download-cucumber-json-formatter": "curl -L https://github.com/cucumber/cucumber-json-formatter/releases/download/vX.Y.Z/cucumber-json-formatter-linux-amd64 -o tools/cucumber-json-formatter && chmod +x tools/cucumber-json-formatter",
    "full_regression": "npm run download-cucumber-json-formatter && npx cypress run -e TAGS='@home' --headed && node cucumber-html-report.js; npm run remove-cucumber-json-formatter"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^20.1.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.1",
    "cypress": "^13.12.0",
    "multiple-cucumber-html-reporter": "^3.6.2",
    "ts-loader": "^9.5.1"
  },
  "cypress-cucumber-preprocessor": {
    "stepDefinitions": "cypress/support/step_definitions/**/*.js",
    "html": {
      "enabled": true,
      "output": "cypress/reports/cucumber-html/cucumber-report.html"
    },
    "json": {
      "enabled": true,
      "formatter": "cucumber-json-formatter",
      "output": "cypress/reports/cucumber-json/cucumber-report.json"
    }
  }
}


**CYPRESS.CONFIG.ts**

import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import { createEsbuildPlugin } from "@badeball/cypress-cucumber-preprocessor/esbuild";

export default defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions
    ): Promise<Cypress.PluginConfigOptions> {
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await addCucumberPreprocessorPlugin(on, config);

      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );

      // Make sure to return the config object as it might have been modified by the plugin.
      return config;
    },
  },
});
