### ISSUE TITLE
Very constantly getting this error : An error was thrown in your plugins file while executing the handler for the after:run event.

### ISSUE THREAD

**Issue by akshaygupta5233** [badeball/cypress-cucumber-preprocessor#1147]
I will share the cypress.config.ts file with you here!

`import { defineConfig } from "cypress";
import * as createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import {
  addCucumberPreprocessorPlugin,
  beforeRunHandler,
  afterRunHandler,
  beforeSpecHandler,
  afterSpecHandler
  // afterScreenshotHandler,
} from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

export default defineConfig({
  env: {
    baseUrl:
      "A working URL",
    hideXhr: true,
  },
  viewportWidth: 1600,
  viewportHeight: 900,
  numTestsKeptInMemory: 0,
  e2e: {
    defaultCommandTimeout: 45000,
    experimentalRunAllSpecs: true,
    experimentalMemoryManagement: true,
    specPattern: "**/*.feature",
    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions
    ): Promise<Cypress.PluginConfigOptions> {
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await addCucumberPreprocessorPlugin(on, config, {
        omitBeforeRunHandler: true,
        omitAfterRunHandler: true,
        omitBeforeSpecHandler: true,
        omitAfterSpecHandler: true,
        // omitAfterScreenshotHandler: true,
      });

      on("before:run", async (details) => {
        await beforeRunHandler(config);
      });

      on("after:run", async (results) => {
        await afterRunHandler(config);
      });

      on("before:spec", async (spec) => {
        await beforeSpecHandler(config, spec);
      });

      on("after:spec", async (spec, results) => {
        await afterSpecHandler(config, spec, results);
      });

      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );

      // Make sure to return the config object as it might have been modified by the plugin.
      return config;
    },
  },
});`

![Screenshot 2024-01-11 at 10 41 23](https://github.com/badeball/cypress-cucumber-preprocessor/assets/37623102/bb925a22-5321-4435-ab8c-17c7dcb8e219)

### Desired behavior

I want my tests to not through this error, or if any checks that I can do in my config.ts file, kindly recommend them.
### Test code to reproduce

An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

TypeError: Cannot destructure property 'message' of 'testStepResult' as it is undefined.
    at JsonFormatter.getStepData (/Users/nineleaps/Documents/MPI_Automation/node_modules/@cucumber/cucumber/src/formatter/json_formatter.ts:281:13)
    at /Users/nineleaps/Documents/MPI_Automation/node_modules/@cucumber/cucumber/src/formatter/json_formatter.ts:161:23
    at Array.map (<anonymous>)
    at /Users/nineleaps/Documents/MPI_Automation/node_modules/@cucumber/cucumber/src/formatter/json_formatter.ts:159:58
    at Array.map (<anonymous>)
    at /Users/nineleaps/Documents/MPI_Automation/node_modules/@cucumber/cucumber/src/formatter/json_formatter.ts:155:30
    at Array.map (<anonymous>)
    at JsonFormatter.onTestRunFinished (/Users/nineleaps/Documents/MPI_Automation/node_modules/@cucumber/cucumber/src/formatter/json_formatter.ts:147:59)
    at EventEmitter.<anonymous> (/Users/nineleaps/Documents/MPI_Automation/node_modules/@cucumber/cucumber/src/formatter/json_formatter.ts:92:14)
    at EventEmitter.emit (node:events:539:35)
    at EventEmitter.emit (node:domain:475:12)
    at afterRunHandler (/Users/nineleaps/Documents/MPI_Automation/node_modules/@badeball/cypress-cucumber-preprocessor/dist/plugin-event-handlers.js:134:30)
  cypress:cli child event fired { event: 'exit', code: 1, signal: null } +1h

### Versions

* **Cypress version**: 13.6.2
* **Preprocessor version**: 18.0.6
* **Node version**: 18+

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by akshaygupta5233** [comment]
I tried explaining how this config file looks,
is there anything more I need to check in after:run block

**Comment by badeball** [comment]
You need to read [this section](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) **thoroughly**. I'm not going to involve myself until you can provide minimal, reproducible examples.

**Comment by badeball** [comment]
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.
