### ISSUE TITLE
Issue with cypress-esbuild-preprocessor: TypeError - (0 , cypress_esbuild_preprocessor_1.default) is not a function

### ISSUE THREAD

**Issue by ahmadrymera** [badeball/cypress-cucumber-preprocessor#1150]
### Current behavior

I am encountering an issue with the `cypress-esbuild-preprocessor` plugin when running Cypress tests. The error I am facing is:

```
TypeError: (0 , cypress_esbuild_preprocessor_1.default) is not a function
    at C:\Users\Administrator\Documents\Playground\CypressTS\cypress.config.ts:15:18
    at step (C:\Users\Administrator\Documents\Playground\CypressTS\cypress.config.ts:33:23)
    at Object.next (C:\Users\Administrator\Documents\Playground\CypressTS\cypress.config.ts:14:53)
    at fulfilled (C:\Users\Administrator\Documents\Playground\CypressTS\cypress.config.ts:5:58)
```
![Error Screenshot](https://github.com/badeball/cypress-cucumber-preprocessor/assets/80019156/04833478-0b5e-4ab8-9668-83f9d1cc7735)

### Desired behavior

I expect the Cypress tests to run without encountering the mentioned `TypeError`.

### Versions

- **Cypress version**: 13.6.3
- **Preprocessor version**: 20.0.1
- **Node version**: [Your Node.js version]

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Additional Information:**
1. This is the version of the plugins I am using:
   - `@badeball/cypress-cucumber-preprocessor`: ^20.0.1
   - `@bahmutov/cypress-esbuild-preprocessor`: ^2.2.0
   - `cypress`: ^13.6.3
   - `typescript`: ^5.3.3
2. I have followed the quick start guide and implemented the TypeScript configurations as recommended.

**Comment by badeball** [comment]
Omitting to provide a reproducible example is completelly inappropriate.

Secondly, saying "I have [..] implemented the TypeScript configurations as recommended" means nothing to me, as I don't know how you've interpreted any recommendation.

Furthermore, the code you initially provided, but edited away, does not constitute a reproducible example. You need to read the [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports) again before opening up any more issues.

Lastly, this is answered in the FAQ.
