### ISSUE TITLE
Cannot find module '@badeball/cypress-cucumber-preprocessor/browserify' or its corresponding type declarations.

### ISSUE THREAD

**Issue by varundev30** [badeball/cypress-cucumber-preprocessor#1156]
### Current behavior

Cannot find module '@badeball/cypress-cucumber-preprocessor/browserify' or its corresponding type declarations

### Desired behavior

there shouldn't be this error

### Versions

* **Cypress version**: 13.6.4
* **Preprocessor version**: 20.0.1
* **Node version**: 18.9.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Omitting to fill out the template properly is completely inappropriate. You need to provide reproducible examples to your issues.

**Comment by varundev30** [comment]
@badeball , sorry for the inconvenience. The issue was with my tsconfig file as cypress.config.ts was not included. Now it is resloved. Thanks for your quick response.

**Comment by leordancarmona07** [comment]
Hello, 

Any update on this issue?

Encountered this when importing **@badeball/cypress-cucumber-preprocessor/browserify** in my cypress.config.ts file.

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/65150446/76fd1b54-4cef-44bd-aa59-efcc1082eba7)

dependencies used: 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/65150446/cc475aed-9883-48ae-bafd-0743110cfb08)

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/browserify-ts/tsconfig.json
