### ISSUE TITLE
cypress-cucumber-preprocessor:test-case-started

### ISSUE THREAD

**Issue by maykicn** [badeball/cypress-cucumber-preprocessor#1167]
I'm using **Cypress.Promise((resolve, reject)** in my function. When I run my test with "cypress open" command, it can continue with next scenario after catching error. But with "cypress run" command it can not continue with next scenario. 

**Error with "cypress open"  command :**
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/39223504/0fa3b655-6071-4a63-b468-134b6df8d796)

**Error with with "cypress run" command:**
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/39223504/4e3b8348-0089-4255-9f77-febeaa4c6fdd)

**Desired behavior:** The steps should continue after throwing error

**Script:**
findDomain() {
    return new Cypress.Promise((resolve, reject) => {
.........
     if (this.totalDomainsChecked<101){
                resolve(this.findDomain());
              }else{
                **reject(new Error('Not found'));**
              }
              .
              .
              .

### Versions

* **Cypress version**:"12.3.0"
* **Preprocessor version**:"no20.0.1"
* **Node version**:v20.10.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
What do you expect from me here?

**Comment by maykicn** [comment]
Could you help me to solve this error?

**Comment by badeball** [comment]
It's glaringly obvious that you didn't read the [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports) at all. You can start by doing that and update your issue accordingly. Make sure to pay attention to the section about reduced test case.
