### ISSUE TITLE
Close to console output for unselected tags

### ISSUE THREAD

**Issue by nurullahsahin44** [badeball/cypress-cucumber-preprocessor#1168]
Hi, Actually I want to ask a question. When I run my cypress project with tag, project searching to all project and running, but I dont want to see unselected tags in console output. Look at my picture for example I was run @alarm tag and it could not find test in Merchant Settings, after then it found in flexible link.feature file 1 test , actually I dont want to see Blue rows for it has not @alarm tag,
How can I resolve my problem, Do you have any suggestion ? or any Development for this ?

![tests](https://github.com/badeball/cypress-cucumber-preprocessor/assets/37590020/231b1025-47c8-46a2-ad8d-535ea0185639)

**Comment by badeball** [comment]
Relevant options are documented at https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md
