### ISSUE TITLE
Useless logs after each step with cypress-if

### ISSUE THREAD

**Issue by triori** [badeball/cypress-cucumber-preprocessor#1175]
### Current behavior

I added cypress-if plugin into my project and I can see some new logs after each step
<img width="1300" alt="314367661-c0cc9215-ba98-4615-a4ac-6d77877ffa9f" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/33620036/67cb9049-1d7a-40a5-881a-e423c17d152f">
And this type of logs so long after huge failed scenario.
<img width="774" alt="Screenshot 2024-04-05 at 10 46 01" src="https://github.com/badeball/cypress-cucumber-preprocessor/assets/33620036/9ee33ff6-63c4-4895-85e0-2d92842c09a6">

### Desired behavior

I looking for solution to turn off this logs or something like that.

### Test code to reproduce

https://github.com/triori/badeball_cypress-if

This is a small repo with three of useless test.
The modules and structure used are the same as in my work project.
You can run it like npx cypress run and at the end of failed test log you can see this type of logs.

### Versions

* **Cypress version**:  13.6.6
* **Preprocessor version**: 20.0.2
* **Node version**: 20.10.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
These logs _are_ hidden by default. I can't say why `cypress-if` makes hidden commands appear, nor do I feel like debugging it on their behalf.
