### ISSUE TITLE
Json & HTML report are not generated

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#1178]
### Current behavior

Upon execution, JSON & HTML report are not generated. Followed the same process as described in the documentation.

### Desired behavior

Json & HTML report should be generated when executed

### Test code to reproduce
Sample Replicable repo: https://github.com/sadhishsk/Cypress-cucumber-bdd/tree/main

### Versions

* **Cypress version**: 13.7.3
* **Preprocessor version**: 20.0.3
* **Node version**: 20.12.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#json-reports-arent-generated-in-open--interactive-mode

**Comment by sadhishsk** [comment]
@badeball I tried it in run mode but still JSON and HTML aren't generated. Please check my above sample repo and let me know if I did anything wrong!

**Comment by badeball** [comment]
```omitAfterRunHandler: true```

...

```afterSpecHandler(config, spec, results);```

.. I expect you to see the error here.
