### ISSUE TITLE
Dependency on Deprecated Version of reflect-metadata in @cucumber/messages@22.0.0

### ISSUE THREAD

**Issue by Chris-Belga-NF** [badeball/cypress-cucumber-preprocessor#1180]
### Current behavior

The cypress-cucumber-preprocessor package relies on @cucumber/messages@22.0.0, which in turn depends on an outdated version of [reflect-metadata](https://www.npmjs.com/package/reflect-metadata/v/0.2.1). This outdated version triggers a critical bug in fallback handling, as indicated by the warning message: "This version has a critical bug in fallback handling. Please upgrade to reflect-metadata@0.2.2 or newer."

### Desired behavior

I would like the cypress-cucumber-preprocessor package to use an updated version of @cucumber/messages(24.1.0) that uses an updated version of reflect-metadata that resolves "This version has a critical bug in fallback handling. Please upgrade to reflect-metadata@0.2.2 or newer.".

### Versions

* **Cypress version**: cypress@13.8.1
* **Preprocessor version**: @badeball/cypress-cucumber-preprocessor@20.0.4
* **Node version**: 20.12.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by shieldsi** [comment]
I am also experiencing this issue using @badeball/cypress-cucumber-preprocessor@20.0.4

**Comment by badeball** [comment]
Hi @Chris-Belga-NF, I've fixed this with v20.0.5.
