### ISSUE TITLE
Run with tag is not working on Windows 11 but in MacOs yes

### ISSUE THREAD

**Issue by luiseps** [badeball/cypress-cucumber-preprocessor#1181]
https://github.com/luiseps/cypress-bdd-typescrit

Using latest plugin version and latest cypress

> npx cypress run --env tags='@login'

DevTools listening on ws://127.0.0.1:60181/devtools/browser/913f5068-1293-40fc-b760-2d491ea3756c
Couldn't find tsconfig.json. tsconfig-paths will be skipped
Can't run because no spec files were found.

We searched for specs inside of this folder:

  > C:\Users\Luis_Perez1\Documents\Study\cypress-bdd-typescrit

**Comment by badeball** [comment]
This likely doesn't have anything to do with the preprocessor, but rather the behavior of your windows terminal, presumably cmd.exe. Try using double quotes instead.

**Comment by luiseps** [comment]
@badeball I just changed to doble quotes the tag parameter and it’s working fine in windows. This issue can be closed.
