### ISSUE TITLE
Allure result is failed to be generated when use allure-cypress 

### ISSUE THREAD

**Issue by dimas-rymera** [badeball/cypress-cucumber-preprocessor#1182]
### Current behavior

Use cypress cucumber and allure cypress https://allurereport.org/docs/cypress/ to make the allure-results JSON files failed to be generated when run `npx cypress run` via terminal

### Desired behavior

allure-results JSON should be generated after the test is done

### Test code to reproduce
1. Install Cypress 13.x 
2. install and use cucumber for cypress @badeball/cypress-cucumber-preprocessor
3. Install allure plugins and set it up
const { defineConfig } = require("cypress");
const { allureCypress } = require("allure-cypress/reporter");
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor');
const preprocessor = require('@badeball/cypress-cucumber-preprocessor');
const createEsbuildPlugin = require('@badeball/cypress-cucumber-preprocessor/esbuild');

```
async function setupNodeEvents(on, config) {
  allureCypress(on);

  await preprocessor.addCucumberPreprocessorPlugin(on, config);
  on(
    'file:preprocessor',
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
    })
  );

  return config;
}

module.exports = defineConfig({
  e2e: {
    setupNodeEvents
  },
});

```
4. via terminal exec `npx cypress run` 

### Versions

* **Cypress version**: 13.x
* **Preprocessor version**: 20.0.4
* **Node version**: 20.11.0

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is answered in the FAQ.
