### ISSUE TITLE
explicit user configuration is not loaded in 20.0.5

### ISSUE THREAD

**Issue by yodarx** [badeball/cypress-cucumber-preprocessor#1185]
### Current behavior

Since version `20.0.5` no explicit user configuration is loaded from `package.json` is loaded. 
When I place the configuration in  `.cypress-cucumber-preprocessorrc.json` within the cypress directory it works.

Debug Log with Version `20.0.5`:

`cypress-cucumber-preprocessor resolved no explicit user configuration +1ms`

Debug Log with Version `20.0.4`

```
cypress-cucumber-preprocessor resolved explicit user configuration { stepDefinitions: [ './integration/common/*.ts' ] } +2ms
```

### Desired behavior

User configuration in `package.json` is recognized.

### Test code to reproduce

Structure of my project

- project
  - package.json 
  - projects/
    - project-e2e/
       - integration/
          - common/
             - Common Step Definitions.ts

My configuration in `package.json`:

```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": [
      "./integration/common/*.ts"
    ]
  },
```

Run `DEBUG=cypress:electron,cypress-configuration,cypress-cucumber-preprocessor cypress open`, the explicit user configuration is not loaded.

### Versions

* **Cypress version**: 13.6.6
* **Preprocessor version**: 20.0.5
* **Node version**: 20.11.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Works seemingly fine as far as I can see. You need to provide a minimal, reproducible example.

**Comment by rujorgensen** [comment]
I'm experiencing a similar issue (common step definitions not found), although our custom configuration is placed in cypress-cucumber-preprocessor.config.js, and not in package.json 🙂. Downgrading to 20.0.4 fixes it.

**Comment by badeball** [comment]
[Here's](https://github.com/badeball/reproducible-issues/tree/master/cypress-cucumber-preprocessor/config/package-json) an example illustrating configuration using `package.json` and [here's](https://github.com/badeball/reproducible-issues/tree/master/cypress-cucumber-preprocessor/config/config-file) a similar example using `cypress-cucumber-preprocessor.config.js`. They both work, so I'm guessing you're doing _something_ that you're not telling me about.

The purpose of a reproducible example is that it's unambiguous and you need to provide it.

**Comment by florianbnd** [comment]
Hello,

I think this issue is linked to cosmicconfig package version 8.3.6 to 9.0.0 and the structure of your project.
`searchStrategy` is none by default and your configuration is located in root package.json.

Can you try creating a package.json file located in project-e2e with your configuration :
`
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": [
      "./integration/common/*.ts"
    ]
  }`

@badeball Could you please have a look also ? :)

More details here : https://github.com/cosmiconfig/cosmiconfig/blob/main/CHANGELOG.md#900

**Comment by warri93** [comment]
@badeball based on what @florianbnd said, are you planning on adding the option to set `searchStrategy` to `project`? 

Creating separate package.json files for all my e2e projects feels like a lot off overkill right now.

Thank you!

**Comment by badeball** [comment]
@florianbnd, I'm aware of the changelog, but I don't make any changes based on a hunch. Instead, I'd really like for someone to just provide some information indicating that that is indeed the issue being observed. @warri93 has done so now, hence the change. This has been added with v20.0.6.
