### ISSUE TITLE
Stack trace is not working

### ISSUE THREAD

**Issue by ivanharalampiev** [badeball/cypress-cucumber-preprocessor#1188]
### Current behavior

Ever since we upgraded from v4.3.1 to latest stack trace is not useful at all. Every error comes with Context.eval() showing lines far beyond the length of the file.
 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/145998069/ad9344d3-3f86-46d9-8ae5-4e18e5a4615e)

### Desired behavior

The previous working implementation that was showing useful data.

### Test code to reproduce

https://github.com/ivanhar/stacktraceexample

### Versions

* **Cypress version**: 13.6.6
* **Preprocessor version**: 20.0.1
* **Node version**: v18.18.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/1132#issuecomment-1837461550
