### ISSUE TITLE
Cypress-cucumber-preprocessor with Cypress-split

### ISSUE THREAD

**Issue by ludo550** [badeball/cypress-cucumber-preprocessor#1189]
Hi @badeball ,

Hope you are doing great. Our team is trying to use the latest version of cypress cucumber implementation with **cypress-split** , However, we are having issues making it happen. All tests run in a single container as opposed to the vanilla cypress splitting it's specs up successfully. I have come to find out that **addCucumberPreprocessorPlugin** and **cypress-split** cannot be used together as cypress cucumber requires the former. Using the latter before the former doesn't do anything and using the former before the latter throws an error that the preprocessor events are being overwritten. Can you please help on this issue or advise for the same?
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/33823327/37f3c8f0-8e40-49e8-b59b-b42224950558)

Here's my setupNodeEvents function that causes the issue above. Removal of `cypressSplit(on, config)` resolves the issue but makes it unusable with cypressSplit.
```
async setupNodeEvents(on, config) {
      await addCucumberPreprocessorPlugin(on, config, {
        omitBeforeRunHandler: true,
        omitAfterRunHandler: true,
        omitBeforeSpecHandler: true,
        omitAfterSpecHandler: true,
        omitAfterScreenshotHandler: true,
      });
      on('before:run', async (details) => {
        console.log('override before:run');
        await beforeRunHandler(config);
      });
      on("before:spec", async (spec) => {
        await beforeSpecHandler(config, spec);
      });
      on("after:run", async (results) => {
        console.log(results);
      });
      on('after:spec', (spec, results) => {
        afterSpecHandler(config, spec, results);
        if (results && results.stats.failures === 0 && results.video) {
          return del.del(results.video, { force: true })
        }
      });
      on('before:browser:launch', (browser, launchOptions) => {
          if (browser.name === 'chrome') {
            launchOptions.args.push('--js-flags=--expose-gc');
          }
          return launchOptions;
      });
      on(
        "file:preprocessor",
        createBundler({
          plugins: [esbuild.esbuild.createEsbuildPlugin(config)],
        })
      );
      cypressSplit(on, config);
      return config;
    }

**Comment by ludo550** [comment]
I have some things to confirm. I will reopen, once my doubts are confirmed

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md

**Comment by ludo550** [comment]
Thank you @badeball !
