### ISSUE TITLE
Enhancement request: remove reversal of After hooks order

### ISSUE THREAD

**Issue by drcthrive** [badeball/cypress-cucumber-preprocessor#1193]
The reversal of the After hooks order in this pr - https://github.com/badeball/cypress-cucumber-preprocessor/pull/1128 - really is not logical, you put in an order 1,2,3 and it processes it runtime as 3,2,1; if you set an order you expect it to process in the order you state, not have to work out things backwards

Would you be open to a PR that removes this?

Also there is no mention of order in the documentation, will add that if this gets a greenlight

**Comment by badeball** [comment]
This was not introduced in the mentioned PR, but is mentioned in the changelog. It is sufficiently logical.

Edit: it is briefly mentioned under [hooks ordering](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/cucumber-basics.md#hook-ordering).

**Comment by drcthrive** [comment]
Oh my bad sorry thought it was in that pr.  Thanks for pointing out the docs missed that too, was at silly oclock in the day and the brain was swimming.  I will have to try and wrap my brain around 1,2,3 equals 3,2,1
