### ISSUE TITLE
Remove deprecated Browserify Preprocessor

### ISSUE THREAD

**Issue by artursopelnik** [badeball/cypress-cucumber-preprocessor#1199]
### Current behavior
Currently we are installing Webpack and also the deprecated Browserify preprocessor.

### Desired behavior
Install only the Webpack preprocessor.

Removing "@cypress/browserify-preprocessor": "^3.0.2" from package.json 

### Background
The dependency "@cypress/browserify-preprocessor" install old and vulnerability dependencies

**Comment by badeball** [comment]
[`@cypress/browserify-preprocessor`](https://www.npmjs.com/package/@cypress/browserify-preprocessor) still has nearly 400k weekly downloads and is obviously still used, hence I am not removing support for it.

It is merely a peer dependency of this project and an optional peerdep even. If your package manager is installing it, it is doing something wrong (or you are), ref. https://github.com/npm/rfcs/issues/221. In any case, you don't have to install it if you don't want to.
