### ISSUE TITLE
Display Tests as 'Pending' in Command Line When Using '@only' or '@skip' Tags

### ISSUE THREAD

**Issue by mar1ogz** [badeball/cypress-cucumber-preprocessor#1204]
Hello!

### Current behavior
Since now we have the opportunity to use the tags `@only` and `@skip` to upload tests with the status "Skipped" using [cypress-xray-plugin](https://github.com/Qytera-Gmbh/cypress-xray-plugin), I would like the tests to be shown as "Skipped" instead of "Pending" in the command line when using those tags.

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/91192508/67dbf5e5-ff6d-4ce4-a3a5-8ff430222b3e)

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/91192508/077ed232-caea-4542-9f71-e46b21872a97)

### Desired behavior

It would be cool to have the tests shown in the section "Skipped" instead to "Pending"

### Test code to reproduce

Nothing special to add here :D

### Versions

* **Cypress version**: 13.10.0
* **Preprocessor version**: 20.1.0
* **Node version**:  20.14.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
No, this is part of Cypress nomenclature outside of my control, EG. discussed https://github.com/cypress-io/cypress/issues/3092.
