### ISSUE TITLE
Step implementation missing

### ISSUE THREAD

**Issue by veerakumar123789** [badeball/cypress-cucumber-preprocessor#1211]
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84904899/179fdcfb-ad67-4f48-a343-8cb424a7db5c)   
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84904899/ea7a0853-045f-431c-9efb-f08cd84b8a3d)
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84904899/17422e2f-3870-4352-989c-2abae8d0910f) 

this my cypress.js file 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84904899/2690df3d-92c8-4a7e-93e8-9240a97af0c8)

also pakage.json 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84904899/5bebd061-9630-4f94-82ee-e35b54edad69)

Error Message : 
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84904899/d0719157-7408-45f6-b82b-fd0a16a9757b)
I don't know how to face this problem please help me

**Comment by badeball** [comment]
You're mixing two libraries, `cypress-cucumber-preprocessor` and `@badeball/cypress-cucumber-preprocessor`. Chose one or the other. The former is deprecated and replaced by the latter. This is an issue tracker exclusively for `@badeball/cypress-cucumber-preprocessor`. Everything you need to know about step definitions can be found in the documentation.
