### ISSUE TITLE
Bug - Cucumber reports getting overwritten when a new feature file is executed

### ISSUE THREAD

**Issue by refaeli-io** [badeball/cypress-cucumber-preprocessor#1212]
### Current behavior
When I am running multi-feature files - using a specific config file of cypress:

```
import {defineConfig} from 'cypress'
import defu from 'defu';
import defaultConfig from "../../cypress.config";

export default defineConfig(
    defu({
            e2e: {
                specPattern: [
                    'cypress/e2e/letters-tests/a-letter-tests/a*'
                ]
            },
        },
        defaultConfig
    )
);
```

Then after the running, I see the test results generate a JSON file (because I enabled it before), but I run for example 10 tests but I see only one test result - it shows only the last test that was run and not all the tests that were run.

### Desired behavior
See in the JSON file report - all the tests that I run for specific cypress config file

### Test code to reproduce
Please try to run an example: 
`npx cypress run -b chrome -C cypress/config/a.config.ts`
the file: **a.config.ts** you can see above - all the tests are cucumber tests 
-->

### Versions

* **Cypress version - 12.17.4**:
* **Preprocessor version - 20.10.0**:
* **Node version - 20.11.1**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (the package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> [..] but I run for example 10 tests but I see only one test result

When you say "run 10 tests" here, do you mean invoking `$ cypress run` (or similar) 10 times?

**Comment by badeball** [comment]
In any case, you need to provide a [reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case).

**Comment by refaeli-io** [comment]
@badeball 
I mean that - O run one time : 
> npx cypress run

And the test result continues only the result of the last test

**Comment by badeball** [comment]
Then you need to provide a [reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by badeball** [comment]
Closing due to lack of a reproducible example. Feel free to open up another issue if anything changes in this regard.
