### ISSUE TITLE
How to use cypress-cucumber-preprocessor with another file:preprocessor?

### ISSUE THREAD

**Issue by J7mbo** [badeball/cypress-cucumber-preprocessor#1219]
Hi, I'm trying to use `badeball/cypress-cucumber-preprocessor` with `cypress-await`: https://github.com/bahmutov/cypress-await
but it seems that cypress [doesn't allow multiple](https://github.com/cypress-io/cypress/issues/5832) `file:preprocessor`s? 

Is there any way whatsoever I can use this file:preprocessor with another one?

**Comment by badeball** [comment]
There's nothing stopping from configuring the browserify-preprocessor yourself and adding multiple transformers.

You can see how browserify is initialized [here](https://github.com/bahmutov/cypress-await/blob/main/src/preprocessor.js). This preprocessor's transform function is available [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/lib/subpath-entrypoints/browserify.ts#L13-L43).

However, I'm unsure if it's going to work, I suspect it will fail similarly to [this](https://github.com/bahmutov/cypress-await/issues/55) issue. I reckon you at the very least would have to use the sync mode.
