### ISSUE TITLE
Tags execution is not working

### ISSUE THREAD

**Issue by magarwal19** [badeball/cypress-cucumber-preprocessor#1220]
### Current behavior

When i run my tests using command
npx cypress run --env "tags=@JIRA-22"
then it is not executing specific tests with tags, and executing all tests within folders

### Desired behaviour
It should be executing only for the tag given in command

### Versions

* **Cypress version**:  13.13.2
* **Preprocessor version**: latest
* **Node version**: 20.15.1

### Checklist
i have checked documentation and it share the same steps but it seems not working
https://github.com/badeball/cypress-cucumber-preprocessor/blob/dbd0df0ed75ed4891ce846f93f0c268c732b8599/docs/tags.md

**Comment by badeball** [comment]
You need to read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports) one more time. Update  your issue with an example and attach debug information.

**Comment by magarwal19** [comment]
is there a working solution for tags which i can refer?

**Comment by badeball** [comment]
You can look at any of the tests: https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/features/tags

**Comment by magarwal19** [comment]
able to resolve issue..
was missing config for "filterSpecs": true,

i had added it in cypress config file, but able to figure out that it needs to be added in package.json for cypress-cucumber-preprocessor
