### ISSUE TITLE
Retrieve cucumber files according tag

### ISSUE THREAD

**Issue by juannavalonribas** [badeball/cypress-cucumber-preprocessor#1226]
Any idea how can I retrieve the .feature files involved by tag before the execution in order to define how many github matrixs to configure? I am using cypress-split plugin by bahmutov

**Comment by badeball** [comment]
Generally speaking, I'd say it shouldn't matter. No matter what files are resolved, they will be split evenly among your runners when using cypress-split. This library doesn't offer any solution to count files before execution.
