### ISSUE TITLE
Error with stepDefinitions

### ISSUE THREAD

**Issue by AlbaSS18** [badeball/cypress-cucumber-preprocessor#1227]
Hello,

First of all, I want to apologize because this is not really an issue or bug. I search help with migration.

I am trying to migrate Cypress to v10.11.0. In this app, I have installed v20.1.0 cucumber. The problem is when I try to run a test, the next error appears:
![image](https://github.com/user-attachments/assets/1c784233-51fe-422d-96c4-09fddbcc5bb3)
Mi folder system is:
```
cypress
└── e2e
    ├── Wiring
    │   ├── Wiring.feature
    │   └── Wiring.js
```
My cypress configuration file is:
```
const { defineConfig } = require("cypress");
const cucumber = require("cypress-cucumber-preprocessor").default;

module.exports = defineConfig({
  viewportHeight: 1080,
  viewportWidth: 1080,
  chromeWebSecurity: false,
  e2e: {
    setupNodeEvents(on, config) {
      on("file:preprocessor", cucumber());
    },
    baseUrl: 'https://sis.tsk.cloud',
    specPattern: 'cypress/e2e/**/*.feature',
  }
});
```
And my package.json is:
```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/e2e/Wiring/*.js"
  },
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "@badeball/cypress-cucumber-preprocessor": "^20.1.0",
    "@types/systemjs": "^6.1.0",
    "babel-eslint": "^11.0.0-beta.2",
    "babel-loader": "^8.0.6",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^5.0.4",
    "cypress": "10.11.0",
    "cypress-cucumber-preprocessor": "^4.3.1",
    "cypress-downloadfile": "^1.2.3",
    "cypress-file-upload": "^5.0.8",
    "eslint": "^6.7.2",
    "eslint-config-important-stuff": "^1.1.0",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-prettier": "^3.1.1",
    "html-webpack-plugin": "^3.2.0",
    "husky": "^3.1.0",
    "prettier": "3.1.0",
    "pretty-quick": "^2.0.1",
    "serve": "^11.2.0",
    "ts-node": "^8.5.4",
    "tslint": "^5.17.0",
    "typescript": "^3.5.1",
    "uglify-js": "^3.17.4"
  }
```
I have reviewed others questions in StackOverflow but any answer helped me. What am I doing wrong? Can anyone help me?Thank you in advance.

### Versions

* **Cypress version**: 10.11.0
* **Preprocessor version**: 20.1.0
* **Node version**: 18.13.0

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You've added `@badeball/cypress-cucumber-preprocessor` to your package.json, but you're still importing `cypress-cucumber-preprocessor`. Although named similarly, they're different packages and they might as well be named `abc` and `xyz`. Remove `abc` from your project altogether.

Take a look at any of the [many examples](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples), which all work. If something doesn't work, it's always because you're doing something different.

**Comment by AlbaSS18** [comment]
Yes, you're right. I have already solved. Thank you very much and sorry for my error. I was desperate.
