### ISSUE TITLE
Can't find test files after migrate from cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by KarineBrandelli** [badeball/cypress-cucumber-preprocessor#1232]
### Current behavior

I'm migrating from cypress-cucumber-preprocessor, and after adjust the config files, it says that the file doesn't have any tests.

I've created a sandbox `EXACLTY` as my local repo. On the sandbox works perfectly, on my machine don't.

I don't have any errors to go one, maybe some config on my machine is wrong (?)

Sandbox:
![image](https://github.com/user-attachments/assets/4e4a8ede-97ef-4d6a-a557-aecd8c41d802)

My local machine:
![image](https://github.com/user-attachments/assets/fdc92b08-6b55-4e48-8697-f3776cc2a81a)

![image](https://github.com/user-attachments/assets/a87d0822-f156-4ebf-b201-ed2e5206b561)

If I click on the test name, it redirecs correctly to the test file on the IDE.

I've runned out of ideias. Tried literally everything.

### Desired behavior

Find the tests.

### Test code to reproduce

This sandbox WORKS.
On my machine, the SAME configuration, doesn't work.
https://codesandbox.io/p/devbox/3y4jwl

My machine: Ubuntu

### Versions

* **Cypress version**: 13.14.2
* **Preprocessor version**:  20.1.2
* **Node version**: 20.15.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I'm not really sure how I can help with a problem that I can't reproduce nor even experience. You can start by using chrome devtools to see the contents of `check-tree.feature` after it's been compiled into JS and sent to the browser (post it here).

**Comment by KarineBrandelli** [comment]
> I'm not really sure how I can help with a problem that I can't reproduce nor even experience. You can start by using chrome devtools to see the contents of `check-tree.feature` after it's been compiled into JS and sent to the browser (post it here).

You kinda solved it without seeing it lol. The path to my folder test had a special character on it, ex: usr/local/P&D/frontend, and the special character was breaking the path, thus not finding anything. Renamed the folder and worked. Find out looking at the devtools specPath! Thanks 😄
