### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by dnovikau** [badeball/cypress-cucumber-preprocessor#1233]
### Current behavior

After upgrading "aws-amplify" package version from "4.3.7" to "6.6.0" tests started failing with the exception:
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

<img width="790" alt="Screenshot 2024-09-17 at 16 09 17" src="https://github.com/user-attachments/assets/b9eeae4d-64e6-4be7-b8e4-3a7dd05bb5fb">

### Test code to reproduce

https://github.com/dnovikau/browserify-preprocessor/tree/main

Note: provided code works fine with "aws-amplify": "4.3.7" but not with latest version

### Versions

* **Cypress version**: "13.14.2"
* **Preprocessor version**: "20.1.2"
* **Node version**: "20.11.1"

<img width="356" alt="Screenshot 2024-09-17 at 16 15 22" src="https://github.com/user-attachments/assets/fecd4a31-af56-4798-847e-6f1e599d7fa1">

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Not an issue with the preprocessor.

This is related browserify, its default options and the type of libraries you're importing. I can't help you with tweaking this. You can specify options as a 2nd argument to `preprocessor(..)`, but I recommend just using a different bundler altogether.

Furthermore, is it even supposed to run in the browser environment? If not, then `cypress/support/index.js` isn't the right place to import it.
