### ISSUE TITLE
attach does not work in html report if examples are used

### ISSUE THREAD

**Issue by EinmalMitScharf** [badeball/cypress-cucumber-preprocessor#1242]
### Current behavior

If a feature file includes examples (no matter if they are used or not) attach does not work.

### Desired behavior

'attach' working with examples

### Test code to reproduce

I hope to provide only these two "files" is enough for you to reproduce: 

searchengine.feature : 

Feature: Searchengine
  Scenario: visiting a searchengine
    When I visit the Searchengine
    Then I should see the \<SearchbarIdentifer\>
    #Then I should see the "input[type=text]"
Examples:
    | SearchbarIdentifer | 
    | "input[type=text]"  | 

searchengine.js

import { When, Then, attach } from "@badeball/cypress-cucumber-preprocessor";

When("I visit the Searchengine", () => {
  var info = "Test Infos : \n";
  info = info + "  URL : https://google.de";
  attach(info);
  cy.visit('https://google.de');
});

Then("I should see the {string}", (searchbarIdentifier) => {
  cy.get(searchbarIdentifier)
});

This leads to this html report : 
<img width="554" alt="AttachNOTWorking" src="https://github.com/user-attachments/assets/80cd81e7-a193-43f1-a37b-05be6d3e2439">

"attach" will work when _Then I should see the "input[type=text]"_ is used instead of _Then I should see the \<SearchbarIdentifer\>_ AND Example Section is commented

<img width="1105" alt="AttachWorking" src="https://github.com/user-attachments/assets/58e2686b-e39a-46af-bc1b-1f2734e20ba6">

### Versions

* **Cypress version**: 13.11.0
* **Preprocessor version**: 21.0.0
* **Node version**: 20.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
What do you mean by “does not work”? I see no errors here indicating a problem with the method.

**Comment by EinmalMitScharf** [comment]
> What do you mean by “does not work”? I see no errors here indicating a problem with the method.

if examples are used there are no attachments visible in the html report (first screenshot provided) whereas if no examples are used the attachments are visible in the html report (second screenshot provided)

**Comment by badeball** [comment]
This appears to be a bug in one of the core libraries and can be tracked [here](https://github.com/cucumber/react-components/issues/356).

**Comment by EinmalMitScharf** [comment]
> This appears to be a bug in one of the core libraries and can be tracked [here](https://github.com/cucumber/react-components/issues/356).

Thanks a lot!

**Comment by badeball** [comment]
https://github.com/cucumber/react-components/issues/356#issuecomment-2386425289
