### ISSUE TITLE
preprocessor reads same `steps.ts` file for each step defined in it after v21

### ISSUE THREAD

**Issue by mysticdevx** [badeball/cypress-cucumber-preprocessor#1245]
### Current behavior

As of v21.0.0, when I run a single .feature file, test doesn't start. It keeps like compiling the test files, and in console the preprocessor SEEMs in an infinite loop in logging`GET /__cypress/tests?p=cypress/integration/common/path/to/test.feature` 

When I investigate in a minimal repo (see link below), I saw that the number of logs are same as the step definitions. I.e, if the `stepDefinitions: ["cypress/e2e/steps/**/*.ts"]` setting resolves 10 `.steps.ts` files, having 10 step implementations in each, the loop continues for 100 times. Therefore when the framework, and number of tests grow, the loop and wait time seems infinite. (possibly related to the recent this #1243  issue)

I compared the behaviour with v20.1.2 thats not the case. See sample console log.

<img width="1137" alt="Screenshot 2024-10-04 at 14 21 21" src="https://github.com/user-attachments/assets/276a2643-3f13-4fe3-945b-2d5e7ac3e32e">

### Desired behavior

As in the prior v21, the number of steps in step files should not cause the loop.

### Test code to reproduce

You can see a basic repo here: https://github.com/mysticdevx/cucumber-basic/tree/latest-version

### Versions

* **Cypress version**: both in 13.14.0 and 13.15.0
* **Preprocessor version**: both in v21.0.0 and 21.0.1
* **Node version**: 18.20.2
* **Esbuild version**: both 0.20.1 and 0.24.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey @mysticdevx, thanks for the heads up, this has been fixed with v21.0.2.

**Comment by mysticdevx** [comment]
Hi @badeball , I confirm the issue is resolved on my end too. 

Thanks
