### ISSUE TITLE
Question - Does `badeball/ cypress-cucumber-preprocessor` aupport async/await?

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#1246]
### Current behavior

When I tried the [provided example](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/browserify-cjs) with `aync` it throw the error
```
Cucumber preprocessor detected that you returned a native promise from a function handler, this is not supported. Using async / await is generally speaking not supported when using Cypress, period, preprocessor or not.
```

### Desired behavior

I am trying to do something like https://www.youtube.com/watch?v=5faeSbvCJQY because in real world scenarios mostly I will have to write custom functions and ensure the synchronous execution

### Test code to reproduce
1. Clone th example provided in this same repository (link provided above)
2. Replace the contents in the `duckduckgo.js` as below
```javascript
const { When, Then } = require("@badeball/cypress-cucumber-preprocessor");

When("I visit duckduckgo.com", async () => {
  cy.visit("https://duckduckgo.com/");
});

Then("I should see a search bar", async () => {
  cy.get("input[type=text]")
    .should("have.attr", "placeholder")
    .and(
      "match",
      /Search the web without being tracked|Search without being tracked/
    );

  assert.deepEqual({}, {});
});
```

### Versions

* **Cypress version**: latest
* **Preprocessor version**: latest
* **Node version**: v22.2.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Using async / await is generally speaking not supported when using Cypress, period, preprocessor or not.

**Comment by badeball** [comment]
Regarding `cypress-await`: https://github.com/badeball/cypress-cucumber-preprocessor/issues/1219#issuecomment-2277771213
