### ISSUE TITLE
BeforeAll Wrong!

### ISSUE THREAD

**Issue by LeohsPaixao** [badeball/cypress-cucumber-preprocessor#1250]
### Current behavior

![image](https://github.com/user-attachments/assets/b32b7aed-98d8-4089-8517-a846aaf14a3c)
![image](https://github.com/user-attachments/assets/fb5fa9f2-624d-4530-9c4c-a8803b0a8d36)

'**BeforeAll**' of all other specs is running on a specific spec, where it contains only one '**BeforeAll**'.

### Desired behavior

Only the '**BeforeAll**' of the specified spec runs in the tests.

### Test code to reproduce

```typescript
BeforeAll(() => {
  cy.login('######@####.com.br', '######');
  createProject().then((data) => {
    projectIdentifier = data.identificador;
  });
});

Given('[atividade] entrar na rota {string}', (route: string) => {
  cy.visitAndwait(`${route}/${projectIdentifier}`);
  cy.checkDomLoaded();
  atividades.validateVisibleAtividades();
});
```

### Versions

* **Cypress version**: 13.10.0
* **Preprocessor version**: 20.0.5
* **Node version**: 20.14

### Checklist

- [ x ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ x ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This could very well be intended behavior, depending on your configuration and file hierarchy, like if each feature is [paired](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md#pairing-explained) with every file containing hooks & step definitions.

In any case, you need to provide a complete & _runnable_ example illustrating the issue.

**Comment by LeohsPaixao** [comment]
Unfortunately, I can't show you the code anymore as it's from a company project. Regarding the file hierarchy, the specs are separated by modules and each one has its own 'BeforeAll', i.e. there is no dependency between them. But basically, all the BeforeAlls for each spec are the same, doing practically the same thing, as in the code I sent above.

```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "./e2e/specs/**/**/step_definitions/**/*.spec.ts",
    "html": {
      "enabled": true
    }
```

**Comment by LeohsPaixao** [comment]
> This could very well be intended behavior, depending on your configuration and file hierarchy, like if each feature is [paired](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md#pairing-explained) with every file containing hooks & step definitions.
> 
> In any case, you need to provide a complete & _runnable_ example illustrating the issue.

Oooooh, I understood.
