### ISSUE TITLE
@badeball/cypress-cucumber-preprocessor does not read "And" keyword

### ISSUE THREAD

**Issue by KimberlingYarihuaman** [badeball/cypress-cucumber-preprocessor#1258]
### Current behavior

Hi!

I´m trying to run **"And"** keyword using Cypress, Gherkin and @badeball and I´ve got this error:

![Captura de pantalla 2024-11-16 232311](https://github.com/user-attachments/assets/00a69b58-2013-464f-ac44-e05d8bfd1892)

I was reviewing the code of the library and I cannot see the "**And**" keyword neither "**But**".

![Captura de pantalla 2024-11-16 235356](https://github.com/user-attachments/assets/b6664615-b5c1-4553-81d1-3b4b918309b3)

I don´t know if it was the last version. Can you help me with that?

Thanks in advance

### Versions
@badeball/cypress-cucumber-preprocessor: "^21.0.3"
@bahmutov/cypress-esbuild-preprocessor: "^2.2.3"
 cypress: "^13.15.2"

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/821
