### ISSUE TITLE
Updating feature title dynamically based on env

### ISSUE THREAD

**Issue by jrutila** [badeball/cypress-cucumber-preprocessor#1259]
### Current behavior
I have feature files I want to run in multiple modes, let's call the modes `md`, `json` and `xml`.
I tag the feature files that are supposed to be run against the different modes with a tag `@mode`
The idea is that I run three different runs variating the mode, e.g. `cypress run -e \"TAGS=@mode\" -e \"mode=md\"` and after that `cypress run -e \"TAGS=@mode\" -e \"mode=json\"` and so on

The feature file top looks like this
```
@mode
Feature: Load document
  This feature supports different modes
```

Now, the problem is that when my CI runs these and reports all the test suites are named the same: `Load document` and I can't differentiate between the different mode runs.

### Desired behavior

I would like to be able to edit the feature/suite title according to the `mode` env. After this edit the test suite could be named for example `Load document (md)`, `Load document (json)` etc

### Feature request or question?

It might be that this is possible already by hooking into some hook and editing the suite title there. If so, please point me to the correct hook to make this edit.

### Versions

* **Cypress version**: 13.16.0
* **Preprocessor version**: 21.0.3
* **Node version**: 20

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
There's no way of modifying tests results during execution. Furthermore, this seems beyond the scope of gherkin - your features should be standalone descriptions of behavior. You can look into example tables or just considering shipping three different reports.
