### ISSUE TITLE
Selecting a single "feature" file runs all "feature" files

### ISSUE THREAD

**Issue by tyler36** [badeball/cypress-cucumber-preprocessor#1262]
### Current behavior

I have a simple demo project with both specs and feature tests.

![image](https://github.com/user-attachments/assets/5bb2a9cf-2b73-4ede-b5fd-29d18ee953de)

When I select a `spec` file, Cypress runs all tests within the `spec` file.
![image](https://github.com/user-attachments/assets/6dd4ce47-e501-4b0b-98e3-380542fa5168)

When I select a `feature` file, Cypress runs **all tests**, as in every `spec` file and every `feature` file.

![image](https://github.com/user-attachments/assets/88c767e1-fa9d-4d24-aabc-9d352b9c6994)

This also happens via the CLI:

```shell
$ cypress run --spec=cypress/e2e/duckduckgo.feature
...
  │ Cypress:        13.11.0                                                                        │
  │ Browser:        Electron 118 (headless)                                                        │
  │ Node Version:   v20.18.1 (/usr/local/bin/node)                                                 │
  │ Specs:          1 found (duckduckgo.feature)                                                   │
  │ Searched:       cypress/e2e/duckduckgo.feature     
...
  Running:  duckduckgo.feature                                                              (1 of 1)
  simple test
    ✓ can read the site (605ms)
  Osaka test
    ✓ can search for Osaka (4804ms)
  duckduckgo.com
    ✓ visiting the frontpage (1283ms)
```

Happens when using all browsers; Chrome, Firefox, Electron

<details>
<summary> `cypress.config.js` :</summary>

```js
import { defineConfig } from 'cypress'
import createBundler from '@bahmutov/cypress-esbuild-preprocessor'
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor'
import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild'

export default defineConfig({
  e2e: {
    specPattern: 'cypress/e2e/**/*.{cy.js,cy.ts,feature}',
    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions,
    ): Promise<Cypress.PluginConfigOptions> {
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await addCucumberPreprocessorPlugin(on, config)

      on(
        'file:preprocessor',
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        }),
      )

      // Make sure to return the config object as it might have been modified by the plugin.
      return config
    },
  }
})
```

</details>

### Desired behavior

When I select a `feature` file, Cypress runs only the tests within the file.

### Test code to reproduce

1. Create project with cypress
1. Create `spec` tests and confirm they run
1. Install `cypress-cucumber-preprocessor`
1. Create `feature` tests
1. Attempt to run single "feature" file from `cypress open`
1. Attempt to run single "feature" file from `cypress run --spec=....`

### Versions

I originally encountered the error running with [tyler36/ddev-cypress](https://github.com/tyler36/ddev-cypress) (dockerized webserver and addon using `cypress/included` image.
However, I confirmed it also happens when running cypress in the host, hence the mixed Cypress/versions below.

* **Cypress version**: `13.16.0`, `13.11.0`
* **Preprocessor version**: `20.1.1`
* **Node version**: `18.17.1`, `20.18.1`

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hi @tyler36, I can't reproduce the issue using these steps. Did you actually try reproducing the issue using the steps you provided me, or did you just assume they would work? In any case, you need to provide a proper, reproducible example.

**Comment by tyler36** [comment]
Thank you for the quick reply.

You are correct. In a effort to debug and provide exact steps and a repo, I discovered my problem in `.cypress-cucumber-preprocessorrc.json`

```json
{
    "stepDefinitions": [
        "cypress/e2e/**/*.{js,ts}",
        "cypress/support/step_definitions/**/*.{js,ts}",
    ]
}
```

The "problem" line was `"cypress/e2e/**/*.{js,ts}",` which caused all the `spec.js` tests to run when running a single `feature` test.
After removing said line, everything worked as expect.

```diff
{
    "stepDefinitions": [
-        "cypress/e2e/**/*.{js,ts}",
        "cypress/support/step_definitions/**/*.{js,ts}",
    ]
}
```

Sorry to have wasted your time.
