### ISSUE TITLE
Support for French Definitions

### ISSUE THREAD

**Issue by alveshelio** [badeball/cypress-cucumber-preprocessor#131]
Hi,

My manager wants me to describe the tests in French. We have some tests in French that we've done with cucumber and selenium js
```
#language: fr

Fonctionnalité: Filtrer la liste de contenus par type de contenu

  Scénario: L'option du filtre Type de contenu est présent
    Etant donné qu'on est dans la liste de contenus
    Alors le filtre Type de contenu est visible
    Et les valeurs disponibles du filtres Type de contenu sont sélectionnable
```

It works fine in seleniumjs. This is a step_definition that we have
```
this.Given(/^le service de contenus est disponible$/, function () {
        return driver.get(shared.env.baseUrl);
    });
```

However, when I use this `.feature` file and create the definition steps, cypress does not recognize the tests. I get `Error: Step implementation missing for: on est dans la liste de contenus`

If I change the French keywords to English it works fine. Is there something I can do to have the step definitions in French?

 Thanks

**Comment by lgandecki** [comment]
Can you try with French language but without any special characters?

**Comment by alveshelio** [comment]
Hi @lgandecki,

First of all, I want to wish you a happy New Year :)

I'd like to know if there's anything here that we'd need to do? Would we need to translate the keywords in French? If so, I could help with that.

Thank you

**Comment by lgandecki** [comment]
Hello

Thanks, you too.

I won't be able to look at this till the next week.
Maybe @sawasawasawa or @lucetius will be able to help you, or at least diagnoze the problem. 

What would help to start with would be a simple reproduction (yes, it's easy for us to make it, but if you can just push something that you have it will save us some time)

**Comment by dweller23** [comment]
@alveshelio 
My suggestion is creating a step_definition file for each step you are making in your feature file, so for the one you have the issue with I'd do something like:
```given(/^on est dans la liste de contenus$/, () => {
  console.log("test");
});``` (let's call it `on_est_dans_la_liste_de_contenus.js` and place it in your `step_definitions` directory)

After I did it, I stopped getting the error you are getting and started seeing error about `le filtre Type de contenu est visible` step missing (hence we need to have a separate step definition for each of our steps).

**Comment by yeppao** [comment]
That's not a viable solution, we need to simply use this language without cutting our files like this... :disappointed:

**Comment by lgandecki** [comment]
I guess I missed what the problem is, @yeppao could you please create a reproduction and push it to github?

**Comment by mathieutu** [comment]
Actually, our tests are in French too, and everything is working like a charm.
Do you want me to test some syntax from yours on my codebase?

**Comment by Shuunen** [comment]
@mathieutu can you share an example ?

**Comment by mathieutu** [comment]
Sure.
I don't know an example of what, but here is a part of a feature, with the corresponding simplified selectors :

```gherkin
#language: fr
Fonctionnalité: Appel téléphonique

  Lorsqu'un client appel à l'agence, le téléphone ouvre automatiquement une page dans le navigateur avec le numéro de la
  personne qui appelle. Ce numéro doit ensuite servir à identifier si le client existe déjà et afficher le contact.

  Scénario: Client connu

    Lorsque je visite la page "/contacts?telephone=0123456789"
    Alors je dois lire "01 23 45 67 89" dans le "téléphone du contact"
    Et je dois lire "M. Doe John" dans le "nom complet du contact"
    Et je dois lire "john.doe@gmail.com" dans l'"email du contact"

```

```js
When(/^je visite la page "(.*)"$/, pageUrl => {
  cy.visit(pageUrl);
});

Then(/^je dois lire "(.*)" dans (?:le |la |l'|les )"(.*)"$/, (text, name) => {
  cy.get(getSelector(name)).should('contain', text)
});
```

**Comment by Shuunen** [comment]
Great, thanks a lot Mathieu, I'm gonna use this in our vue/cypress/cucumber stack at work.

I'm wondering, do you use other testing tool beside these E2E tests ? like unit tests (Jest, Ava, ...), component catalogue (StoryBook for example) or someting else ?

**Comment by arnogues** [comment]
I am actually looking wfor writing test in french but I have the same error. 
I can't use french words. 

How to use french words?

**Comment by joelgrimberg** [comment]
the #language: <language> in a feature file will break the test when in a cypress/webpack project. Have no clue on how to fix it a.t.m. hoped to find a config file to set the language.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
