### ISSUE TITLE
webpack loader is broken on 1.13

### ISSUE THREAD

**Issue by crysislinux** [badeball/cypress-cucumber-preprocessor#197]
it used to work with 1.11.0, now it's reporting

![image](https://user-images.githubusercontent.com/5404597/62125324-67d61a00-b2ff-11e9-9fca-67a723dc96cd.png)

**Edit (upload text error message):**
```
Oops...we found an error preparing this test file:

  cypress/integration/API.feature

The error was:

./cypress/integration/API.feature
Module build failed (from ./node_modules/cypress-cucumber-preprocessor/loader.js):
TypeError: Cannot read property 'replace' of undefined
 @ multi ./cypress/integration/API.feature main[0]

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

**Comment by lgandecki** [comment]
Yeah, this is probably related to:
https://github.com/Asana/node-asana/issues/114#issuecomment-289156939
and this:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/193#issue-301299837

btw, could you please copy and paste the error text so people googling the issue can land here?

**Comment by crysislinux** [comment]
@lgandecki amazing response speed 😃. Have pasted the text error.

**Comment by lgandecki** [comment]
haha, I was just taking a break and looked at notifications. Please let me know if the trick from @jcundill worked for you.

**Comment by crysislinux** [comment]
@lgandecki the trick doesn't work for me. downgrading to 1.12 works

```js
module.exports = {
  resolve: {
    extensions: ['.ts', '.js'],
  },
  node: { fs: "empty", child_process: "empty", readline: "empty" },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [{
          loader: 'ts-loader',
          options: {
            transpileOnly: true,
          },
        }],
      },
      {
        test: /\.feature$/,
        use: [
          {
            loader: "cypress-cucumber-preprocessor/loader"
          }
        ]
      }
    ],
  },
}
```

**Comment by crysislinux** [comment]
@lgandecki the trick works 🤗

**Comment by jcundill** [comment]
@lgandecki Had a look at options for not having to use the above trick - specifying mocks for cucumber.js in the webpack config.

I've an experimental branch [github:jcundill/cypress-cucumber-preprocessor#jsonAsTask](https://github.com/jcundill/cypress-cucumber-preprocessor/tree/jsonAsTask) which pushes all the cucumber JsonFormatter work node side as a Cypress task, as no longer webpacked into the browser then the issue with unresolved dependencies goes away.

There is a fork of the cypress-cucumber-typescript-webpack-example using this branch at [https://github.com/jcundill/cypress-cucumber-webpack-typescript-example.git](https://github.com/jcundill/cypress-cucumber-webpack-typescript-example.git) 

This gets rid of the workaround and leaves the webpack configs untouched, but as I'm using a task then that needs to be registered in [cypress/plugins/index.js](https://github.com/jcundill/cypress-cucumber-webpack-typescript-example/blob/master/cypress/plugins/index.js#L9)

**Note:** anyone using the cypress-cucumber-preprocessor, whether using webpack or not, will need to add this task - which is a change from the behaviour at the moment.

It would be good to get peoples thoughts about this approach - for those folks using webpack is the empty mock trick acceptable, or would it be a better to change the current behaviour and start doing the cucmber.json generation node side as a Cypress task?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
