### ISSUE TITLE
Feature tags don't affect Hooks with tag expressions

### ISSUE THREAD

**Issue by badeball** [badeball/cypress-cucumber-preprocessor#237]
Hi,

It seems that feature tags aren't being taken into account when determining whether or not a hook should be run, in latest (1.16.0) version.

Given the following hook

```js
Before({ tags: "not @avoid-foo" }, () => {
 // ...
});
```

And the following feature file

```gherkin
@avoid-foo
Feature: Bar
  Scenario: Baz
    # ...
```

I expect the before hook to *not* be invoked. This however does not seem to be the case. If I however move the tag to the scenario, as shown below

```gherkin
Feature: Bar
  @avoid-foo
  Scenario: Baz
    # ...
```

.. then the hook is correctly not invoked.

**Comment by dlabrecque** [comment]
Still happens to us in 1.16.2, but only when using **not**

so:

```
Before({ tags: "not @avoid-foo" }, () => {
 // ...
});
```
works only with scenario tags and:

```
Before({ tags: "@avoid-foo" }, () => {
 // ...
});
```
will work on feature tags.

**Comment by pascalbe-dev** [comment]
@dlabrecque 
I just installed the latest version (1.18.0) and I still experience this problem even without using "not".

**Comment by MarcHajjar0** [comment]
is this solved @badeball ?i want to use tagged before

**Comment by badeball** [comment]
You’re asking in an issue marked as completed, yeah it’s solved.

**Comment by MarcHajjar0** [comment]
@badeball can you tell me how to use it

**Comment by badeball** [comment]
No, read the documentation.
