### ISSUE TITLE
Add on for gherking vs code

### ISSUE THREAD

**Issue by atemor** [badeball/cypress-cucumber-preprocessor#265]
Hello,
Is there a way to manage more easily the gerkin that I am working with ?
For exemple I am working in an ATDD structure, and I will like to know wich gerking sentence is covered by code.

**Comment by lgandecki** [comment]
Hello

Not sure I understand. Is this working differently when you use pure cucumberjs? Is this a request to the cucumber vs code plugin, or for this project?

**Comment by Shelex** [comment]
There is excellent extension to work with Gherkin is VS Code:
https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete

Also, I add some additional commands (find unused step definitions, find step definitions references) for step definitions in my extension:
https://marketplace.visualstudio.com/items?itemName=Shelex.vscode-cy-helper

**Comment by atemor** [comment]
> Hello
> 
> Not sure I understand. Is this working differently when you use pure cucumberjs? Is this a request to the cucumber vs code plugin, or for this project?

Hello Igandecki,
As I am working on big site where I have to do all the acceptance test, it will represent a lot of different scenario wich are not link one to the other. So the idea is that when the PO start wrinting in Gherkin, only the revelet gherkin will be propose to the autocomplete and not all of them.

Thanks Shelex,

**Comment by badeball** [comment]
I am working on a vscode extension specifically for working with Cypress + Cucumber. Not sure exactly when I will have public release ready though.

**Comment by yann-combarnous** [comment]
> There is excellent extension to work with Gherkin is VS Code: [Cucumber (Gherkin) Full Support](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete)
> 
> Also, there are some additional commands (find unused step definitions, find step definitions references) for step definitions in my extension: [Cypress Helper](https://marketplace.visualstudio.com/items?itemName=Shelex.vscode-cy-helper)

Is there anyway to setup your extension to match the paths to lookup steps as in https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md#step-definitions ? Cannot see the filepath replacement variable in your extension. Thx!

**Comment by onthespotqa** [comment]
one thing to add to this. is the current extension (Cucumber Full Support) doesn't support multi-root workspaces. the issue requesting support has been around for about 3 years. It's been a pain point.

**Comment by aslakhellesoy** [comment]
Cucumber has an official VSCode extension now: 

* https://github.com/cucumber/vscode/#readme
* https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official

**Comment by barrymichaeldoyle** [comment]
Unfortunately the official VSCode extension still bugs out with not recognising Step Definitions

**Comment by badeball** [comment]
Closing this as I no longer plan on making an extension myself (a7b3f63).
