### ISSUE TITLE
Scoping and Custom Parameter Type

### ISSUE THREAD

**Issue by fras2560** [badeball/cypress-cucumber-preprocessor#364]
I am using Webpack and TypeScript. I was able to get the defineParameterType to work. However, I was running issues where the parameter would be defined twice for some features and would not be defined for others. It not clear how the scope for the defined parameters work especially when the customer parameter type is used in global steps (in common folder) and local steps. Where should one defineParameterType?

For example:
Say have Type SomeType (st.ts)
some Global Step (g.ts) "Global step with {SomeType}"
some local feature (f1.ts) file with a step "Local step with {SomeType}"
some other feature (f2.ts) that uses the Global Step

If I defineParameterType(SomeType) in g.ts then running f1.ts would say SometType is not defined for "Local step with {SomeType}"

If I defineParameterType(SomeType) in f1.ts then running f2.ts would say SometType is not defined for "Global step with {SomeType}"

If I defineParameterType(SomeType) in both g.ts, f1.ts then running f1.ts would say SometType is not defined twice

I was eventually able to resolve this by defineParameterType in the file that defines the type definition (st.ts).

Is there any recommendation on where to defineParameterType for Custom Parameter Types that could be used in local steps or global steps?

**Comment by timfisher** [comment]
Did you find out how to do this @fras2560 ?

**Comment by fras2560** [comment]
No I never did. However I left the job with the code base that was running into this issue. I dont think I have run into this issue for any personal projects yet. I could create a simple example if need be.

**Comment by timfisher** [comment]
I am just running into an issue of wanting to have all the custom definitions in a single file and not having them in separate step definitions @fras2560 thanks for the fast response, if you know how to do it let me know :)

**Comment by annaet** [comment]
I'm having the same issue. I'd like to use the custom parameter type across multiple files, but defining it inside the `common` folder doesn't allow other steps to use it.

Similarly to above if I redefine the custom parameter type in multiple files the test errors with `There is already a parameter type with name {parameter_name}`.

**Comment by fras2560** [comment]
@lgandecki any insights into this issue? It seems to be affecting other people as well. Let me know if a simple example would help.

**Comment by annaet** [comment]
Actually I think I have a working example here: https://github.com/annaet/cypress-cucumber-typescript-example/tree/custom-parameters

I define two common parameter types inside [common/parameters.ts](https://github.com/annaet/cypress-cucumber-typescript-example/blob/custom-parameters/cypress/integration/common/parameters.ts).

Then I reuse them inside [keyboard.ts](https://github.com/annaet/cypress-cucumber-typescript-example/blob/custom-parameters/cypress/integration/passWithTypescript/Keyboard/keyboard.ts) and [piano.ts](https://github.com/annaet/cypress-cucumber-typescript-example/blob/custom-parameters/cypress/integration/passWithTypescript/Piano/piano.ts).

This appears to work as expected with both Keyboard and Piano tests passing.

I have still not been able to determine why this doesn't work in my production code, but I will update if I figure it out.

**Comment by annaet** [comment]
Ah the key appears to be that the file is importing something from the `common/parameters.ts` file.

In the above example both `keyboard.ts` and `piano.ts` are importing `notes`:

```
import { notes } from '../../common/parameters';
```

If this import is removed, then the error message `Undefined parameter type {ordinal}` returns.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
