### ISSUE TITLE
Is there a workaround to include videos and screenshots for the test cases which are passed as well to the report in cypress????

### ISSUE THREAD

**Issue by pvishnu991** [badeball/cypress-cucumber-preprocessor#382]
Report used: "multiple-cucumber-html-reporter": "^1.16.2".
cucumber-report.js file which contains the current code to attach the screenshots on failures.

what i need is to include the videos generated on execution of features to the html report!!!!!

-----------------Existing Code----------------------------------------------------------------------------------
const report = require('multiple-cucumber-html-reporter')
const fs = require('fs-extra')
const path = require('path')
const chalk = require('chalk')

const cucumberJsonDir = './cypress/cucumber-json'
const cucumberReportFileMap = {}
const cucumberReportMap = {}
const jsonIndentLevel = 2
const ReportDir = './cypress/reports/cucumber-report'
const screenshotsDir = './cypress/screenshots'

getCucumberReportMaps()
addScreenshots()
generateReport()

//Mapping cucumber json files from the cucumber-json directory to the features
function getCucumberReportMaps() {
const files = fs.readdirSync(cucumberJsonDir).filter(file => {
return file.indexOf('.json') > -1
})
files.forEach(file => {
const json = JSON.parse(
fs.readFileSync(path.join(cucumberJsonDir, file))
)
if (!json[0]) { return }
const [feature] = json[0].uri.split('/').reverse()
cucumberReportFileMap[feature] = file
cucumberReportMap[feature] = json
})
}

//Adding screenshots to the respective failed test steps in the feature files
function addScreenshots() {

const prependPathSegment = pathSegment => location => path.join(pathSegment, location)

const readdirPreserveRelativePath = location => fs.readdirSync(location).map(prependPathSegment(location))

const readdirRecursive = location => readdirPreserveRelativePath(location)
.reduce((result, currentValue) => fs.statSync(currentValue).isDirectory()
? result.concat(readdirRecursive(currentValue))
: result.concat(currentValue), [])
const screenshots = readdirRecursive(path.resolve(screenshotsDir)).filter(file => {
return file.indexOf('.png') > -1
})

const featuresList = Array.from(new Set(screenshots.map(x => x.match(/[\w-_.]+.feature/g)[0])))
featuresList.forEach(feature => {
screenshots.forEach(screenshot => {

  const regex = /(?<=--\ ).+?((?=\ \(example\ #\d+\))|(?=\ \(failed\))|(?=\.\w{3}))/g
  const [scenarioName] = screenshot.match(regex)
  console.info(chalk.blue('\n    Adding screenshot to cucumber-json report for'))
  console.info(chalk.blue(`    '${scenarioName}'`))

  const myScenarios = cucumberReportMap[feature][0].elements.filter(
    e => scenarioName.includes(e.name)
  )
  if (!myScenarios) { return }
  let foundFailedStep = false
  myScenarios.forEach(myScenario => {
    if (foundFailedStep) {
      return
    }
    let myStep
    if (screenshot.includes('(failed)')) {
      myStep = myScenario.steps.find(
        step => step.result.status === 'failed'
      )
    } else {
      myStep = myScenario.steps.find(
        step => step.name.includes('screenshot')
      )
    }
    if (!myStep) {
      return
    }
    const data = fs.readFileSync(
      path.resolve(screenshot)
    )
    if (data) {
      const base64Image = Buffer.from(data, 'binary').toString('base64')
      if (!myStep.embeddings) {
        myStep.embeddings = []
        myStep.embeddings.push({ data: base64Image, mime_type: 'image/png' })
        foundFailedStep = true
      }
    }
  })
  //Write JSON with screenshot back to report file.
  fs.writeFileSync(
    path.join(cucumberJsonDir, cucumberReportFileMap[feature]),
    JSON.stringify(cucumberReportMap[feature], null, jsonIndentLevel)
  )
})
})
}

//Report generation with customized meta data included
function generateReport() {
if (!fs.existsSync(cucumberJsonDir)) {
console.warn(chalk.yellow(WARNING: Folder './${cucumberJsonDir}' not found. REPORT CANNOT BE CREATED!))
} else {
report.generate({
jsonDir: cucumberJsonDir,
reportPath: ReportDir,
saveCollectedJSON: true,
displayDuration: true,
reportName: Regression Test Report - ${new Date().toLocaleString()},
metadata: {
browser: {
name: 'chrome'
},
device: 'LM',
platform: {
name: 'Windows'
}
}
})
}
}

**Comment by bitcoder** [comment]
hi @pvishnu991 , thanks for you awesome script.
I've made some minor updates to it, especially on the regex.
Let me share it here. Note that in this version, I'm just populating the 
```javascript
//const report = require('multiple-cucumber-html-reporter')
const fs = require('fs-extra')
const path = require('path')
const chalk = require('chalk')

const cucumberJsonDir = './cypress/cucumber-json'
const cucumberReportFileMap = {}
const cucumberReportMap = {}
const jsonIndentLevel = 2
const ReportDir = './cypress/reports/cucumber-report'
const screenshotsDir = './cypress/screenshots'

getCucumberReportMaps()
addScreenshots()
//generateReport()

//Mapping cucumber json files from the cucumber-json directory to the features
function getCucumberReportMaps() {
    const files = fs.readdirSync(cucumberJsonDir).filter(file => {
        return file.indexOf('.json') > -1
    })
    files.forEach(file => {
        const json = JSON.parse(
            fs.readFileSync(path.join(cucumberJsonDir, file))
        )
        if (!json[0]) { return }
        const [feature] = json[0].uri.split('/').reverse()
        cucumberReportFileMap[feature] = file
        cucumberReportMap[feature] = json
    })
}

//Adding screenshots to the respective failed test steps in the feature files
function addScreenshots() {

    const prependPathSegment = pathSegment => location => path.join(pathSegment, location)

    const readdirPreserveRelativePath = location => fs.readdirSync(location).map(prependPathSegment(location))

    const readdirRecursive = location => readdirPreserveRelativePath(location)
        .reduce((result, currentValue) => fs.statSync(currentValue).isDirectory()
            ? result.concat(readdirRecursive(currentValue))
            : result.concat(currentValue), [])
    const screenshots = readdirRecursive(path.resolve(screenshotsDir)).filter(file => {
        return file.indexOf('.png') > -1
    })

    const featuresList = Array.from(new Set(screenshots.map(x => x.match(/[\w-_.]+\.feature/g)[0])))
    featuresList.forEach(feature => {
        screenshots.forEach(screenshot => {

            const regex = /(?<=\ --\ ).*?((?=\ \(example\ \#\d+\))|(?=\ \(failed\)))/g
            const [scenarioName] = screenshot.match(regex)
            console.info(chalk.blue('\n Adding screenshot to cucumber-json report for'))
            console.info(chalk.blue(scenarioName))

            console.log(featuresList)
            console.log(feature)
            console.log(cucumberReportMap)
            const myScenarios = cucumberReportMap[feature][0].elements.filter(
                e => scenarioName.includes(e.name)
            )
            if (!myScenarios) { return }
            let foundFailedStep = false
            myScenarios.forEach(myScenario => {
                if (foundFailedStep) {
                    return
                }
                let myStep
                if (screenshot.includes('(failed)')) {
                    myStep = myScenario.steps.find(
                        step => step.result.status === 'failed'
                    )
                } else {
                    myStep = myScenario.steps.find(
                        step => step.name.includes('screenshot')
                    )
                }
                if (!myStep) {
                    return
                }
                const data = fs.readFileSync(
                    path.resolve(screenshot)
                )
                if (data) {
                    const base64Image = Buffer.from(data, 'binary').toString('base64')
                    if (!myStep.embeddings) {
                        myStep.embeddings = []
                        myStep.embeddings.push({ data: base64Image, mime_type: 'image/png' })
                        foundFailedStep = true
                    }
                }
            })
            //Write JSON with screenshot back to report file.
            fs.writeFileSync(
                path.join(cucumberJsonDir, cucumberReportFileMap[feature]),
                JSON.stringify(cucumberReportMap[feature], null, jsonIndentLevel)
            )
        })
    })
}

//Report generation with customized meta data included
/*
function generateReport() {
    if (!fs.existsSync(cucumberJsonDir)) {
        console.warn(chalk.yellow(WARNING: Folder './${cucumberJsonDir}' not found.REPORT CANNOT BE CREATED!))
    } else {
        report.generate({
            jsonDir: cucumberJsonDir,
            reportPath: ReportDir,
            saveCollectedJSON: true,
            displayDuration: true,
            reportName: Regression Test Report - ${ new Date().toLocaleString() },
            metadata: {
            browser: {
                name: 'chrome'
            },
            device: 'LM',
            platform: {
                name: 'Windows'
            }
        }
})
}
}
*/

```

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
