### ISSUE TITLE
Error: Cannot find module 'cypress-cucumber-preprocessor' when using Jenkins build for Cypress Tests

### ISSUE THREAD

**Issue by malih2** [badeball/cypress-cucumber-preprocessor#437]
### Current behavior

I am currently running Cypress / cucumber tests as a part of our Jenkins build pipeline. Initially the tests passed when I was using only cypress library but started getting the below error when I added cypress-cucumber-preprocess to my package.json. This only happens on Jenkins, I am able to run the tests locally. 

I tried downgrading the cypress-cucumber-preprocessor version to 1.18 since it was mentioned in many threads that this fixed the issue but it did not in my case. 

Below is the screenshot of the error from build console output.
![image](https://user-images.githubusercontent.com/39099854/91493867-8e0d1700-e87d-11ea-93b4-3c8a85f870c7.png)

package.json
`"dependencies": {},`
  `"devDependencies": {`
   ` "@cypress/code-coverage": "^3.8.1",`
    `"babel-plugin-istanbul": "^6.0.0",`
    `"cypress": "^5.0.0",`
    `"cypress-cucumber-preprocessor": "^2.5.5",`
    `"cypress-file-upload": "^4.0.7",`
    `"cypress-iframe": "^1.0.1",`
    `"eslint": "^7.7.0",`
    `"eslint-plugin-compat": "^3.8.0",`
    `"eslint-plugin-cypress": "^2.11.1",`
    `"eslint-plugin-es5": "^1.5.0",`
    `"eslint-plugin-json-format": "^2.0.1",`
    `"eslint-plugin-mocha": "^7.0.1",`
    `"husky": "^4.2.5",`
    `"lint-staged": "^10.2.11"`
  `},`
 ` "cypress-cucumber-preprocessor": {`
    `"nonGlobalStepDefinitions": true`
  `}`

Cypress/plugins/index.js
`const cucumber = require("../../node_modules/cypress-cucumber-preprocessor").default;`
`  `
`module.exports = function(on){`
   `on("file:preprocessor", cucumber());`
`};`

Below is the project structure
![image](https://user-images.githubusercontent.com/39099854/91494580-ab8eb080-e87e-11ea-83a3-746a0848fb6b.png)

### Desired behavior

Want to be able to run cucumber tests as a part of the pipeline build
### Test code to reproduce

Not relevant

### Versions

* **Cypress version**: 5.0.0
* **Preprocessor version**: 2.5.5
* **Node version**: 10.16.3

**Comment by lgandecki** [comment]
it's hard to say, it seems like the package doesn't get installed in Jenkins. You'd need to do some more debugging, for example listing the node_modules directories to see what's there etc. "cannot find module" is an error that really happens before our package gets a chance to do anything. 

Did you try to do a normal require as well:

const cucumber = require("cypress-cucumber-preprocessor").default;
?

**Comment by malih2** [comment]
yes I tried the normal require. But tried to give the full path anyway to see if this would resolve it. 
Here is the installed cypress-cucumber-preprocessor library in the node_modules dir 
![image](https://user-images.githubusercontent.com/39099854/91565004-200d3200-e907-11ea-80bd-5f6bfbe00f86.png)

**Comment by HartiganHM** [comment]
I'm experiencing a similar issue. Though it doesn't seem to have anything to do with the package not being installed, the environment setup and error seem to match.

We're running our Cypress tests in Jenkins and run into this exact issue consistently. Below are relevant dependencies that we're using as well as our `/plugins/index.js`. All of the failures have a consistent error message along the lines of **`Error: Step implementation missing for: X`**.

Things work fine locally through `cypress open` and `cypress run` commands and even using Docker locally, but once we execute in Docker through Jenkins, it seems to fall apart.

I'm happy to share additional information for our Docker setup, etc. if needed. Thanks!

**Dependencies and config**
```
  "devDependencies": {
    "@testing-library/cypress": "^5.3.0",
    "cypress": "^5.5.0",
    "cypress-cucumber-preprocessor": "^4.0.0",
    "cypress-file-upload": "^4.1.1",
    "cypress-wait-until": "^1.7.1",
    "cucumber": "^6.0.5"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/integration" // This is in an effort to get around the error
  }
```

**`/plugins/index.js`**
```javascript
/// <reference types="cypress" />
// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

const cucumber = require('cypress-cucumber-preprocessor').default;

/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('file:preprocessor', cucumber());
};
```

Also, it's worth noting that the only relevant mention of `cucumber` in the Jenkins console output is the below. Could this have something to do with it?

```
> cucumber-expressions@5.0.18 postinstall /app/node_modules/cypress-cucumber-preprocessor/node_modules/cucumber/node_modules/cucumber-expressions
> node scripts/postinstall.js
```

**Comment by YassineSIDKI** [comment]
I has the same issue and I fix it by setting the `"nonGlobalStepDefinitions"` variable to `false`, and put all my step definitions files in `cypress/support/step_definitions` . The only accepted name for step definitions folder is `step_defintions`, if you choose another one your jobs will fail.

**Comment by daniloc-cit** [comment]
Guys, I'm going through the same problem, using the image `cypress/included:4.12.1`. When I run docker locally everything works fine, but in the **Azure Pipeline** the error happens. I have tried the solution proposals above but nothing has helped. Can anyone help with any tips?

**Comment by lgandecki** [comment]
could you give us more details and preferably a copy paste of the error with as much before/after contexts in terms of logs as possible as well?

**Comment by RitikaGhosh15** [comment]
Hello Am facing the same issue when running on remote, Did someone find any solution to this? 
pls can someone guide me to resolve this? Below is the error that i am facing. Pls note locally its running but getting error while running on pipeline.

Cypress version: 5.6.0

Error: Cannot find module 'cypress-cucumber-preprocessor'
Require stack:
- /builds/feed/tests/e2e/plugins/index.js
- /root/.cache/Cypress/5.6.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
- /root/.cache/Cypress/5.6.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/builds/feed/tests/e2e/plugins/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at runPlugins (/root/.cache/Cypress/5.6.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:213:15)
    at Object.<anonymous> (/root/.cache/Cypress/5.6.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)

**Comment by ashuans** [comment]
I am also facing same kind of issue - 

11:03:18  Your pluginsFile is invalid: /home/jenkins/workspace/project-path/cypress/plugins/index.js
11:03:18  It threw an error when required, check the stack trace below:
11:03:18  Error: Cannot find module 'cypress-cucumber-preprocessor'
11:03:18  Require stack:
11:03:18  - /home/jenkins/workspace/project-path/cypress/plugins/index.js
11:03:18  - /home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
11:03:18  - /home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js
11:03:18      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
11:03:18      at Function.Module._load (internal/modules/cjs/loader.js:746:27)
11:03:18      at Module.require (internal/modules/cjs/loader.js:974:19)
11:03:18      at require (internal/modules/cjs/helpers.js:101:18)
11:03:18      at Object.<anonymous> (/home/jenkins/workspace/project-path/cypress/plugins/index.js:5:18)
11:03:18      at Module._compile (internal/modules/cjs/loader.js:1085:14)
11:03:18      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
11:03:18      at Module.load (internal/modules/cjs/loader.js:950:32)
11:03:18      at Function.Module._load (internal/modules/cjs/loader.js:790:12)
11:03:18      at Module.require (internal/modules/cjs/loader.js:974:19)
11:03:18      at require (internal/modules/cjs/helpers.js:101:18)
11:03:18      at runPlugins (/home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:186:15)
11:03:18      at Object.<anonymous> (/home/jenkins/.cache/Cypress/9.5.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js:8:25)
11:03:18      at Module._compile (internal/modules/cjs/loader.js:1085:14)
11:03:18      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
11:03:18      at Module.load (internal/modules/cjs/loader.js:950:32)
11:03:18  error Command failed with exit code 1.

plugins/index.js

const cucumber = require("cypress-cucumber-preprocessor").default;
module.exports = function(on){
on("file:preprocessor", cucumber());
};

Can someone help me out here,. This is only problem in Jenkins

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
