### ISSUE TITLE
cucumber.json file does not contain failed tests

### ISSUE THREAD

**Issue by ahoad** [badeball/cypress-cucumber-preprocessor#454]
### Current behavior

- When I run my tests and everything passes, then I get a cucumber.json file created which contains the correct results.
- When I run my tests and I have some passing and some failing, then I get a cucumber.json file created which contains only the passing steps.
- When I run my tests and all of them fail, then I get an empty.cucumber.json file with no test details within it at all

### Desired behavior

- I expected to get a cucumber.json file with the all of the test results even when the steps fail

### Test code to reproduce

- Added the following to package.json:
`"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  }`

- Removed any other reporter from cypress.config to see if that was causing issues. It made no difference

### Versions

* **Cypress version**: 5.2.0
* **Preprocessor version**: 2.5.5
* **Node version**: v14.11.0

**Comment by BillCarterNet** [comment]
I've just run into exactly this myself
Really annoying
I cant do any reporting

**Cypress version:** 5.3.0
**Preprocessor version:** 3.0.0
**Node version:** 10.15.0

Needs fix ASAP

**Comment by BillCarterNet** [comment]
Actually to be fair... 
For me this is only occurring when I run a bunch of feature files from the cypress runner
If I run them from the command line the cucumber.json files appear to be generated correctly

**Comment by ahoad** [comment]
That's interesting, I've been running in the commandline and seeing this behaviour. I'll try increasing my versions to match yours and see if that changes anything

**Comment by ahoad** [comment]
I tried upgrading but still had the same results

**Comment by andreidamiean** [comment]
In my case is different.
I use the command line : cypress run -e TAGS='@login and @prio-1 and @existingUser'
No matter the output of this specific test, in the generated json the steps always appear as skipped

"cypress-cucumber-preprocessor": "^4.0.0"
"cypress": "^5.6.0"
node v12

**Comment by cvolant** [comment]
Same here...
I tried most recent versions. Cypress 6.0.1, 6.2.1 hten 6.5.0 and preprocessor 4.0.0 and 4.0.1.
Did you find any solution? It makes the report irrelevant... :slightly_frowning_face:

**Comment by mysticdevx** [comment]
Have the same issue with:
Cypress 5.6.0, node V15. removed cypress-cucumber-preprocessor, cleared yarn cache, and reinstalled. but no use :( I need the generated reports to import to XRay, but unfortunately can not do now. (generated JSONs from other reporters are not supported by XRay import). I badly need this. If any solution, please share :(

**Comment by arnaudruch** [comment]
Hi,

I came across the problem of missing tests reports today, while using bundled feature files.
I solved it by not using bundled feature files.

Here are the details:

I have 2 feature files : the first one with 3 scenarios, the second one with 4 scenarios. Both are using Background.
All 3 scenarios of the first feature file are OK
All 4 scenarios of the second feature files are failing

When bundling the 2 feature files, the report for the first one is correct, but the report for the second one only contains the last (failing) test status. It looks like the 3 previous failing tests status are being overwritten
When not bundling the feature files, both reports are ok.

Hope this will help pinpoint and fix the issue.

**Versions**
cypress version: 6.6.0
cypress-cucumber-preprocessor version: 4.0.1
node version: v14.16.0

**Configuration**
```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/integration/steps",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/reports/cucumber",
      "filePrefix": "",
      "fileSuffix": ""
    }
  }
```

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by hdabas2** [comment]
Hey @badeball. I have mentioned the below configuration but cucumber-json folder is not created & neither the json files. Is there any change in reporting also ?

"cypress-cucumber-preprocessor": {
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }}

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md
