### ISSUE TITLE
Step Definitions are not found

### ISSUE THREAD

**Issue by mikeyhoang** [badeball/cypress-cucumber-preprocessor#553]
Step definitions are not being picked. My current project tree for cypress looks something like this:

```
├── integration
│   ├── features
│   │   ├── backend
│   │   │   └── Testbackend.feature
│   │   └── frontend
│   │       └── Testui.feature
│   ├── pages_objects
│   │   ├── backend.js
│   │   ├── frontend.js
│   └── step_definitions
│       ├── Testui
│       │   └── Testui.js
│       ├── Testbackend
│       │   └── Testbackend.js
│       └── common
│           └── commonSteps.js
```
Essentially I want to define all my features in a single director, all my step defs in a single directory and all my page objects in a single directory for readability
```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "step_definitions": "cypress/integration/step_definitions/"
  }
````

### Current behavior

To my understanding this with the `cypress-cucumber-preprocessor` config. When `nonGlobalStepDefinitions` is true this will get step defs in subfolders, I've also overwritten the `step_definitions` config to locate the location of the `step_definitions` folder.

After running my setup, it fails with 
```
Step implementation missing for: the status should be 201
```
etc. As it seems to not find the step-def
Setting `nonGlobalStepDefinitions` to `false` does work, but it makes all step-defs global. I have a Before/AfterEach step for frontend and backend for test data setups. But doing so will run both Before/AfterEach step for every test (run the Before/AfterEach step twice)

### Desired behavior

I want the step-definitions to locate my desired step-definitions folder. And not share steps (running the before steps from each file)

### Test code to reproduce
Test layout
```
├── integration
│   ├── features
│   │   ├── backend
│   │   │   └── Testbackend.feature
│   │   └── frontend
│   │       └── Testui.feature
│   ├── pages_objects
│   │   ├── backend.js
│   │   ├── frontend.js
│   └── step_definitions
│       ├── Testui
│       │   └── Testui.js
│       ├── Testbackend
│       │   └── Testbackend.js
│       └── common
│           └── commonSteps.js
```
```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "step_definitions": "cypress/integration/step_definitions/"
  }
````

### Versions

* **Cypress version**: "^6.7.1"
* **Preprocessor version**: "^4.1.0"
* **Node version**: v12.18.0

**Comment by simonsankar** [comment]
Yeah same for me. 
Based on the docs I added a file for some steps in the `/integration/common` folder and 2 of the 4 steps I added are picked up but not the rest

**Comment by PatoDeVille** [comment]
i am having the exact same problem. could you solve it some how?

**Comment by ashblox** [comment]
+1

I want to organize my features into subfolders with `nonGlobalStepDefinitions` set to true and it doesn't seem possible with the current implementation. I read through #392 also and tried setting my config like this:

```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "nonGlobalStepBaseDir": "cypress/integration/steps",
    "stepDefinitions": "cypress/integration/features"
  }
```

I also specified the integration folder in my `cypress.json`:

```
    "integrationFolder": "cypress/integration/features",
```

Problem is the feature _subfolders_. Is there a way to glob match on a directory? If I could specify somehow that features live in the subdirectories of the directory above, I feel like I'd be in business. (If I set both `stepDefinitions` and `integrationFolder` to "cypress/integration/features/my-feature" for example, it works.) 

Any help would be appreciated!

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
