### ISSUE TITLE
sync skip; aborting execution in Windows 10

### ISSUE THREAD

**Issue by martinsmall12** [badeball/cypress-cucumber-preprocessor#569]
### Current behavior
This error occurs when running cypress tests with a cocumber.
![image](https://user-images.githubusercontent.com/22866371/119220058-d72a8880-bae8-11eb-865b-1607325f4e93.png)

node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js:71:1

state from row 67 - [state.txt](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/files/6526126/state.txt)

Tests without cocumber work fine.

### Desired behavior
The tests will run on windows as well as my colleagues on linux and macOs.

### Versions

* **Cypress version**:  "^6.3.0"
* **Preprocessor version**: "^4.0.0"
* **Node version**: v14.16.1

Thanks

**Comment by martinsmall12** [comment]
State from row 67.
`{
   "feature":{
      "type":"Feature",
      "tags":[
         
      ],
      "location":{
         "line":1,
         "column":1
      },
      "language":"en",
      "keyword":"Feature",
      "name":"Mutations - settings",
      "children":[
         {
            "type":"Scenario",
            "tags":[
               {
                  "type":"Tag",
                  "location":{
                     "line":3,
                     "column":5
                  },
                  "name":"@wip"
               }
            ],
            "location":{
               "line":4,
               "column":5
            },
            "keyword":"Scenario",
            "name":"I can not see mutations dropdown when I have no mutations",
            "steps":[
               {
                  "type":"Step",
                  "location":{
                     "line":5,
                     "column":9
                  },
                  "keyword":"Given ",
                  "text":"I have an empty bot \"bot\""
               },
               {
                  "type":"Step",
                  "location":{
                     "line":6,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"I open the designer with bot \"bot\""
               },
               {
                  "type":"Step",
                  "location":{
                     "line":7,
                     "column":9
                  },
                  "keyword":"When ",
                  "text":"I can see that designer is ready"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":8,
                     "column":9
                  },
                  "keyword":"Then ",
                  "text":"I can not see the \".e2e-selected-mutation\" section"
               }
            ]
         },
         {
            "type":"Scenario",
            "tags":[
               {
                  "type":"Tag",
                  "location":{
                     "line":10,
                     "column":5
                  },
                  "name":"@wip"
               }
            ],
            "location":{
               "line":11,
               "column":5
            },
            "keyword":"Scenario",
            "name":"I can see mutations dropdown when I have a mutation",
            "steps":[
               {
                  "type":"Step",
                  "location":{
                     "line":12,
                     "column":9
                  },
                  "keyword":"Given ",
                  "text":"I have an empty bot my-bot"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":13,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"The bot has a mutation"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":14,
                     "column":9
                  },
                  "keyword":"When ",
                  "text":"I open the designer with bot my-bot"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":15,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"I can see that designer is ready"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":16,
                     "column":9
                  },
                  "keyword":"Then ",
                  "text":"I can see the \".e2e-selected-mutation\" section"
               }
            ]
         },
         {
            "type":"Scenario",
            "tags":[
               
            ],
            "location":{
               "line":18,
               "column":5
            },
            "keyword":"Scenario",
            "name":"I can see mutations dropdown when I have a mutation",
            "steps":[
               {
                  "type":"Step",
                  "location":{
                     "line":19,
                     "column":9
                  },
                  "keyword":"Given ",
                  "text":"I have an empty bot"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":20,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"The bot has a mutation"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":21,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"The bot has a hello step"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":22,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"I open the designer with bot"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":23,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"I can see that designer is ready"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":24,
                     "column":9
                  },
                  "keyword":"When ",
                  "text":"I select EN mutation"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":25,
                     "column":9
                  },
                  "keyword":"And ",
                  "text":"I set the message to Hello"
               },
               {
                  "type":"Step",
                  "location":{
                     "line":26,
                     "column":9
                  },
                  "keyword":"Then ",
                  "text":"The bot is saved with mutated step"
               }
            ]
         }
      ]
   },
   "scenarioSteps":{
      
   },
   "runScenarios":{
      
   },
   "runTests":{
      
   },
   "stepResults":{
      
   },
   "testError":null,
   "uri":"Mutations.feature",
   "spec":"Feature: Mutations - settings\r\n\r\n    @wip\r\n    Scenario: I can not see mutations dropdown when I have no mutations\r\n        Given I have an empty bot \"bot\"\r\n        And I open the designer with bot \"bot\"\r\n        When I can see that designer is ready\r\n        Then I can not see the \".e2e-selected-mutation\" section\r\n\r\n    @wip\r\n    Scenario: I can see mutations dropdown when I have a mutation\r\n        Given I have an empty bot my-bot\r\n        And The bot has a mutation\r\n        When I open the designer with bot my-bot\r\n        And I can see that designer is ready\r\n        Then I can see the \".e2e-selected-mutation\" section\r\n\r\n    Scenario: I can see mutations dropdown when I have a mutation\r\n        Given I have an empty bot\r\n        And The bot has a mutation\r\n        And The bot has a hello step\r\n        And I open the designer with bot\r\n        And I can see that designer is ready\r\n        When I select EN mutation\r\n        And I set the message to Hello\r\n        Then The bot is saved with mutated step\r\n\r\n# TODO Scenario: I can see highlihted step when it has a matated variant\r\n\r\n\r\n",
   "currentScenario":null,
   "currentStep":0,
   "timer":1621673400493
}`

**Comment by zdrazilmarek** [comment]
I have the same issue on windows 10 and downgrading cypress-cucumber-preprocessor to versions lower then 4.1.0 did not help :( . Cypress tests without preprocessor runs without error. I would be grateful for some solution or advise, thanks. :).

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
