### ISSUE TITLE
Unable to run cypress tests in Ubuntu 20.04 LTS ( Linux ) server machine

### ISSUE THREAD

**Issue by timrajan** [badeball/cypress-cucumber-preprocessor#577]
I have setup the tests to run in a ubuntu server machine. But for some reason, I am not able to run the tests in my ubuntu machine . The same test can be successfully run in a windows machine as well as in a mac machine but not in an Ubuntu Machine.

When I run the tests, what  I see is it is getting identified as a cucumber tests but running from the test runner gives me the following output 

```
**Error: Can't walk dependency graph: Cannot find module 'fsevents' from '/home/timothyrajan/Documents/cypress/smokebdd/node_modules/chokidar/lib'
    required by /home/timothyrajan/Documents/cypress/smokebdd/node_modules/chokidar/lib/fsevents-handler.js
    at /home/timothyrajan/Documents/cypress/smokebdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/timothyrajan/Documents/cypress/smokebdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/timothyrajan/Documents/cypress/smokebdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/timothyrajan/Documents/cypress/smokebdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/timothyrajan/Documents/cypress/smokebdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/timothyrajan/Documents/cypress/smokebdd/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at callback (/home/timothyrajan/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server/node_modules/graceful-fs/polyfills.js:289:20)
    at FSReqCallback.oncomplete (fs.js:183:21)**
```

This seems to be the same issue as the one mentioned in the below link 

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/10

But I tried the solution mentioned in the above page

"With "cypress-cucumber-preprocessor" :- Everything is working fine , if we do not use below line
const { given } = require("cypress-cucumber-preprocessor"); instead of this use global variable given , then etc"

but still facing the issue. 

The same project works well in a mac machine without any code change. Is there any reservations on ubuntu server machines ( 20.04 Server machine LTS ) ?

The following are the versions. 

* **Cypress version**:      "cypress": "^7.4.0",
* **Preprocessor version**:   "cypress-cucumber-preprocessor": "^4.1.2",
* **Node version**:  v10.19.0

Thanks very much for your time on this.

**Comment by MateuszNowosad** [comment]
Hello, 

Could you provide a repository with a minimal reproduction example?

I do all my development on manjaro and didn't encounter this problem. Could you try out a different version of cypress-cucumber-preprocessor?

**Comment by timrajan** [comment]
@MateuszNowosad  - Thanks a lot for your message. Its nothing fancier. Its a simple cypress project but running in ubuntu. The same project runs well in mac. I will create a repo in github and share you the details

**Comment by timrajan** [comment]
@MateuszNowosad  - The git repo is below

https://github.com/timrajan/mybdd.git

Also, I have asked the question in Stackoverflow . Let me know your thoughts. 

https://stackoverflow.com/questions/67920638/unable-to-run-cypress-tests-in-ubuntu-20-04-lts-linux-server-machine

Comment 1 is not working for me and still facing the same issue
Not sure how to implement Comment 2

Thanks a lot  @MateuszNowosad  for your help on this. 

Again to reiterate, the same code works well in a mac machine. Its only Linux where I am facing this issue.

**Comment by timrajan** [comment]
@MateuszNowosad  - Any updates on this ? Would be very helpful for me as I am dependent on my mac for all executions. 
Thanks again for your time.

**Comment by badeball** [comment]
Your project runs fine on Arch Linux with the following changes and I'm not able to reproduce the error you've mentioned in the original post. I'm afraid nobody is going to actively work on an issue that they can't reproduce and you're likely not going to see any more updates until you can provide a reproducible example.

```patch
diff --git a/cypress/integration/tests/step_definitions/test/test.steps.js b/cypress/integration/tests/step_definitions/test/test.steps.js
index a824afe..093b044 100644
--- a/cypress/integration/tests/step_definitions/test/test.steps.js
+++ b/cypress/integration/tests/step_definitions/test/test.steps.js
@@ -1,16 +1,14 @@
-//import {And,Given,When,Then} from 'cypress-cucumber-preprocessor/steps'
+import {And,Given,When,Then} from 'cypress-cucumber-preprocessor/steps'
 
-//const { Given,When,Then,And } = require("@cypress/browserify-preprocessor");
 
-
-given("that the website is loaded and user registration is possible",()=>{
+Given("that the website is loaded and user registration is possible",()=>{
         cy.log('I am in Given1')
 })
 
-when('a user registers by filling out only the mandatory fields',()=>{
+When('a user registers by filling out only the mandatory fields',()=>{
         cy.log('I am in Given2')
 })
 
-then('the newly registered user is able to log back in',()=>{
+Then('the newly registered user is able to log back in',()=>{
         cy.log('I am in Given5')
 })
\ No newline at end of file
diff --git a/cypress/plugins/index.js b/cypress/plugins/index.js
index 84b6e34..e483f14 100644
--- a/cypress/plugins/index.js
+++ b/cypress/plugins/index.js
@@ -21,20 +21,11 @@ const path = require('path');
 const fs = require('fs-extra');
 const cucumber = require('cypress-cucumber-preprocessor').default
 
-const optionalPlugins = [];
-const { IgnorePlugin } = require('webpack');
-
-if (process.platform !== "darwin") { // don't ignore on OSX
-  optionalPlugins.push(new IgnorePlugin({ resourceRegExp: /^fsevents$/ }));
-}
-
-
 
 module.exports = (on, config) => {
   // `on` is used to hook into various events Cypress emits
   // `config` is the resolved Cypress config
   on('file:preprocessor', cucumber())
-  plugins: [ ...optionalPlugins ]
 }
 
 // const browserify = require("@cypress/browserify-preprocessor");
diff --git a/cypress/support/index.js b/cypress/support/index.js
index 9bcf94b..e2df5b6 100644
--- a/cypress/support/index.js
+++ b/cypress/support/index.js
@@ -16,7 +16,6 @@
 
 // Alternatively you can use CommonJS syntax:
 require('./commands')
-require('cypress-cucumber-preprocessor')
 require('cypress-file-upload')
 require('cypress-xpath')
 require('faker')
```

**Comment by timrajan** [comment]
Thanks @badeball . I will give it a try . Thanks once again for your time @badeball . if everything fails, I need to rebuild my ubuntu machine.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
