### ISSUE TITLE
@focus tag does not apply to Scenario Outline

### ISSUE THREAD

**Issue by BurhanH** [badeball/cypress-cucumber-preprocessor#612]
Hi! Looks like the @focus tag cannot be used in Scenario Outline

In the example below with the **@focus** tag, only the first scenario will be executed. Which is expected for **Scenarios**.

```
Feature: Search Engines

  I want to open a search engine
  
  @focus
  Scenario: Opening Google search engine page
    Given I open Google page
    Then I see "Google" in the title
  
  Scenario: Opening DuckDuckGo search engine page
    Given I open DuckDuckGo page
    Then I see "DuckDuckGo" in the title
```

But the **@focus** tag doesn't work for **Scenarios Outline**. See the example below. In that case, all 3 scenarios will be executed.

```
Feature: Google Main Page

  I want to open a search engine and search
  
  Scenario: Opening a search engine page
    Given I open Google page
    Then I see "Google" in the title
  
  @focus
  Scenario Outline: Search in search engine
    Given I open Google page
    When I type <search_text> into search text field
    And I click Google Search button
    Then I get results

   Examples:
   | search_text  |
   | "Cucumber" |
   | "Cypress"     |
```
   

It would be nice to have the **@focus** tag working with **Scenarios Outline**.
Thanks

**Comment by pixelass** [comment]
The same issues happens when you want to only focus on the scenario

```gherkin
Feature: Google Main Page

  I want to open a search engine and search
  
  @focus
  Scenario: Opening a search engine page
    Given I open Google page
    Then I see "Google" in the title
  
  Scenario Outline: Search in search engine
    Given I open Google page
    When I type <search_text> into search text field
    And I click Google Search button
    Then I get results

   Examples:
   | search_text  |
   | "Cucumber" |
   | "Cypress"     |
```

The "Scenario Outline" in the example above should be ignored

**Comment by pixelass** [comment]
Workaround:

I added the following env to my `cypress.json`

```json
{
  "env": {
    "TAGS": "not @ignore and @focus"
  }
}
```

Now only the "Scenario(s)" or "Scenario Outline(s)" that have `@focus` tag run. 
(the `@ignore` is the opposite case).

This is "sort of" documented here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#ignoring-specific-scenarios-using-tags-when-executing-test-runner

* I feel like the documentation could be a little more descriptive (in case this works as designed).
* I still consider it a bug since IMHO  "Scenario" and "Scenario Outline" should be seen as the same and `@focus` does not generally require to be defined in `env.TAGS`. 

Please either adjust this or mention it in the documentation.

**Thank you for your consideration.**

**Comment by pixelass** [comment]
My bad. The workaround does not work. It will only run tests that actually have `@focus`. So if you don't have any `@focus` tags, then no files will run.

The `not @ignore` works. So if you want to ignore tests, the only workaround would be to add `@ignore` on the "Scenario(s)" or "Scenario Outline(s)" that should not run.

**I am more confident that this should be handled as a bug.**

**Comment by badeball** [comment]
> So if you want to ignore tests, the only workaround would be to add @ignore on the "Scenario(s)" or "Scenario Outline(s)" that should not run.

What else do you expect here? How should a test otherwise be ignored?

**Comment by pixelass** [comment]
> What else do you expect here? How should a test otherwise be ignored?

I expect, that only the "Scenario "with `@focus` runs. As the issue clearly describes, the "Scenario Outline" is not ignored.

**Comment by badeball** [comment]
I'm unable to reproduce the original issue with the most recent version of the preprocessor (v4.2.0). The following test

```cucumber
Feature: Google Main Page

  I want to open a search engine and search
  
  Scenario: Opening a search engine page
    Given I open Google page
  
  @focus
  Scenario Outline: Search in search engine
    Given I open Google page

   Examples:
     | search_text  |
     | "Cucumber"   |
     | "Cypress"    |
```

.. when ran yields the following output

```
$ cypress run --spec cypress/integration/foo.feature 

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    6.2.1                                                                              │
  │ Browser:    Electron 87 (headless)                                                             │
  │ Specs:      1 found (foo.feature)                                                              │
  │ Searched:   cypress/integration/foo.feature                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  foo.feature                                                                     (1 of 1)


  Google Main Page
    - Opening a search engine page
    ✓ Search in search engine (example #1)
    ✓ Search in search engine (example #2)


  2 passing (72ms)
  1 pending


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      1                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     foo.feature                                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  foo.feature                               70ms        3        2        -        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                         70ms        3        2        -        1        -  
```

In other words, the non-focused scenario is correctly ignored when using the `@focus` tag.

**Comment by pixelass** [comment]
@badeball Thank you for looking into this. 🙏
In my case the opposite is a problem: **I focus on the "Scenario" but the "Scenario Outline" still runs.**
(As stated here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/612#issuecomment-901621291)

I can open a new issue. I can also try to create a reproduction repo for this issue (but the priority of getting this issue fixed is rather low for us)


## My test case

`npx cypress@8.3.0 run --spec cypress/integration/features/wishlist/ReadWishes.feature`

```gherkin
Feature: Read Wishes
	As a User, I want to see wishes,
	so that I can read what other users wish for.

	Background:
		Given the wishlist has the following wishes:
			| id | subject   | body   | votes |
			|  1 | Subject 1 | Body 1 |     0 |
			|  2 | Subject 2 | Body 2 |     2 |
			|  3 | Subject 3 | Body 3 |    10 |
			|  4 | Subject 4 | Body 4 |    99 |

	@focus
	Scenario: User wants to view all wishes of others

		When the user is on the wishlist page
		Then the user sees all wishes

	Scenario Outline: User wants to read a wish

		When the user is on the wishlist page
		Then the wish with id <id> has "subject" "<subject>"
		And the wish with id <id> has "body" "<body>"
		And the wish with id <id> has "votes" "<votes>"

		Examples:
			| id | subject   | body   | votes |
			|  1 | Subject 1 | Body 1 |     0 |
			|  2 | Subject 2 | Body 2 |     2 |
			|  3 | Subject 3 | Body 3 |    10 |
			|  4 | Subject 4 | Body 4 |    99 |

```

```
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  features/wishlist/ReadWishes.feature                                            (1 of 1)


  Read Wishes
    ✓ User wants to view all wishes of others (11601ms)
    ✓ User wants to read a wish (example #1) (1959ms)
    ✓ User wants to read a wish (example #2) (1603ms)
    ✓ User wants to read a wish (example #3) (1281ms)
    ✓ User wants to read a wish (example #4) (1274ms)


  5 passing (18s)


```

**Comment by robsutherland** [comment]
Yeah I am also having the opposite problem. It is skipping the Scenario ones and running the Scenario Outline ones. 

cypress: 8.3.1
Preprocessor: 4.2.0

**Comment by raghuureddy** [comment]
+1

**Comment by bobmccracken** [comment]
☝️ fyi see my comment at the end of that closed PR. It identifies the issue, though I don't provide a solution. If anyone is feeling like a contributor, this _probably_ isn't too hard to fix.

I can confirm `@focus` is working as expected in the previous version (4.1.4). I'm downgrading because I use focus frequently enough.

**Comment by raghuureddy** [comment]
both '@focus' and inheritance works after commenting the 148th line on createTestFromScenario.js 

``` 
         const scenarioExample = {
            ...section,
            // tags on scenario's should be inherited by examples (https://cucumber.io/docs/cucumber/api/#tags)
            tags: example.tags.concat(section.tags),
            //shouldRun: shouldRunExamples,
            name: uniqueScenarioName,
            example: exampleLocations[index],
          }; 
```

**Comment by redReno** [comment]
I am having the same issue as described here. I use the focus tag on a normal scenario, but all Scenario outlines still run.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
