### ISSUE TITLE
cucumberJson: the report json file only contains the last scenario in feature file

### ISSUE THREAD

**Issue by thienthu1410** [badeball/cypress-cucumber-preprocessor#655]
### Current behavior
**Pre-condition**
Given I have a feature file with 2 scenarios like below image
![image](https://user-images.githubusercontent.com/15967414/145699748-fec015a9-265a-4ac6-878f-ebddbaa8b109.png)
The feature has tag @feature-example
The first scenario has tag @example-1
The last scenario has tag @example-2

And I have configure cucumberJson as below image:
![image](https://user-images.githubusercontent.com/15967414/145699871-1ed0315d-71f9-4057-8839-dc04ae840adc.png)

**Scenario 1**
When I run test with below command:
`npx cypress-tags run -e TAGS='@feature-example and @example-1' --headed -b chrome`

Then I see that only scenario with tag @example-1 is ran, and the console report as below image:
![image](https://user-images.githubusercontent.com/15967414/145700730-55b7366a-0e94-4b37-a97a-22ec2e0f71d7.png)

And I check the json file, I see that only the scenario with tag @example-2 is included in the json file
`[
  {
    "keyword": "Feature",
    "name": "Example check have text",
    "line": 2,
    "id": "example-check-have-text",
    "tags": [
      {
        "name": "@feature-example",
        "line": 1
      }
    ],
    "uri": "check_have_text.feature",
    "elements": [
      {
        "id": "example-check-have-text;",
        "keyword": "Scenario",
        "line": 10,
        "name": "",
        "tags": [
          {
            "name": "@feature-example",
            "line": 1
          },
          {
            "name": "@example-2",
            "line": 9
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 11,
            "name": "I access the github",
            "result": {
              "status": "skipped"
            }
          },
          {
            "arguments": [],
            "keyword": "Then ",
            "line": 12,
            "name": "I check the have text",
            "result": {
              "status": "skipped"
            }
          }
        ]
      }
    ]
  }
]`

Just more details: When I run process to generate html report using multiple-cucumber-html-report, the report file only shows the skipped scenario. I understand that this is not in scope of this issue, as the issue comes from cucumber json
![image](https://user-images.githubusercontent.com/15967414/145700435-f10b4897-109f-43de-9e2c-bc4e4b8c2362.png)

**Scenario 2**
When I run test with below command:
`npx cypress-tags run -e TAGS='@feature-example' --headed -b chrome`

Then I see that all scenarios in feature file are ran, and the console report as below image:
![image](https://user-images.githubusercontent.com/15967414/145700787-b1f9bd67-2d4c-4b11-937f-b2b52b34613c.png)

And I check the json file, I see that only the scenario with tag @example-2 is included in the json file
`[
  {
    "keyword": "Feature",
    "name": "Example check have text",
    "line": 2,
    "id": "example-check-have-text",
    "tags": [
      {
        "name": "@feature-example",
        "line": 1
      }
    ],
    "uri": "check_have_text.feature",
    "elements": [
      {
        "id": "example-check-have-text;",
        "keyword": "Scenario",
        "line": 10,
        "name": "",
        "tags": [
          {
            "name": "@feature-example",
            "line": 1
          },
          {
            "name": "@example-2",
            "line": 9
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 11,
            "name": "I access the github",
            "result": {
              "status": "passed",
              "duration": 1934000000
            }
          },
          {
            "arguments": [],
            "keyword": "Then ",
            "line": 12,
            "name": "I check the have text",
            "result": {
              "status": "passed",
              "duration": 87000000
            }
          }
        ]
      }
    ]
  }
]`

### Desired behavior

**Expected**
All the passed/failed scenarios should be included in the cucumber json file

Only the passed/failed scenario should be included in the cucumber json file, we don't want the skipped scenario here, as the html report will populated the skipped scenario unexpectedly

**Note**
I also have tried run using cytorus, but I got the below issue
![image](https://user-images.githubusercontent.com/15967414/145700078-b1dbd16c-3ce7-4d95-821f-9f3df7e12443.png)

### Versions

* **Cypress version**: 9.1.1
* **Preprocessor version**: 4.3.1
* **Node version**: 16.13.1

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Comment by ernestorocha** [comment]
Hello,

I think this is still an issue for the newest version, `9.0.5`. It least this is happening to my setup the way that was described here.

@thienthu1410, did you have the opportunity to upgrade and check if it was fixed for you?

Thank you!

**Comment by badeball** [comment]
Just chiming in to say that "I think this is still an issue" is not enough and if you need something fixed you have to concrete. I pretty much refrain from getting involved until someone can convince me that it is necessary.
