### ISSUE TITLE
Dependent on a standalone tool "cucumber-json-formatter"

### ISSUE THREAD

**Issue by SylvainStoesel** [badeball/cypress-cucumber-preprocessor#691]
Hi,
First of all, thank you so much for your work on this very useful tool.

We're working on a project with automated e2e tests running in CI mode, and we have some concerns with using the [**cucumber-json-formatter** standalone tool](https://github.com/cucumber/common/tree/main/json-formatter) in order to make the [JSON report](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md) work.

Having to download a standalone tool can be tricky and it's not very CI-friendly (on a Windows environment, it's a *.exe* that can be detected as a malware ; and to make it work on the CI pipeline, we'll have to download the Linux version).
Is there any way to not have to use this standalone tool, and instead using a **npm dependency** that would be able to generate the same JSON report?

Thank you for your help.

**Comment by badeball** [comment]
This tool outputs something called "messages", a NDJSON-format which is library-friendly. All tools in the Cucumber sphere will eventually implement this and then it'll be up to the consumer what to do with them (such as generate a JSON report).

As far as I know, no such NPM package exist.

**Comment by badeball** [comment]
[Here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/cb6f7882870a0be4bffe1de5db580d058f7a15b9/.github/workflows/build.yml#L74-L76) you can see how trivial it is to setup in a CI environment.

**Comment by iomedico-beyer** [comment]
Docker helps :)
https://stackoverflow.com/a/72868618/1948252
