### ISSUE TITLE
Ability to retry a specific scenario

### ISSUE THREAD

**Issue by badeball** [badeball/cypress-cucumber-preprocessor#697]
Cypress offers an interface to [override retry-settings per test](https://docs.cypress.io/guides/guides/test-retries#Custom-Configurations), but this interface is lost of the Gherkin translation.

An alternative solution has been proposed [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/545#issuecomment-1103508500).

Personally I like the `@retries:N` approach. Furthermore, one could perhaps specify `N` for different modes with `@retries(openMode=5)` or similar.

This is a good first issue if anyone would like to take a stab at it. However, for any contribution I expect test coverage and a corresponding update in documentation. The implementation is the easy part and without the other components you would just be committing work to me and thus not really contributing.

**Comment by aljedaxi** [comment]
I've got an ersatz solution for anyone that needs it:
- run cypress with `--reporter json`
- then feed the results into the following function:
```js
const makeSeds = s => {
  return s
    .split (/^\{/m)
    .flatMap (s => s.split (/^\}/m))
    .filter ((_, idx) => isOdd (idx + 1))
    .map (s => JSON.parse (`{${s}}`))
    .flatMap (o => o.failures?.map (f => f.title) ?? [])
    .map (scenario => `gsed -i '/Scenario: ${scenario}/i \\  @focus' cypress/integration/*.feature`
`)
}
```
(`gsed` on mac; just `sed` on linux)

run that code, and it'll put a `@focus` on top of every scenario that failed. Then you can just re-run cypress.

furthermore, you can mark only the feature files that failed using --spec
