### ISSUE TITLE
testrail-integration package and preprocessor

### ISSUE THREAD

**Issue by LoukasKonstantinou** [badeball/cypress-cucumber-preprocessor#699]
I'm trying to determine if there is a way to use the testrail-integration package along with cypress-cucumber-preprocessor.

### Test code to reproduce

```
const runid = 1;
const version = 'Build 1.3.4';
const options = {
  username: 'username@org.com',
  password: 'pwd',
  url: 'https://blahblah.testrail.io/'
};
const testrail = new CucumberRailClient(options);

After(async () => {
  const scenario = cy.state('ctx').currentTest;
  try {
    await testrail.updateTestRailResults(scenario, runid, version);
  } catch (err) {
    cy.log(`Error ${err}`);
  }
});
```
As far as I can tell, the currentTest object contains just the title and nothing else, whereas the updateTestRailResults method would need a Scenario object also containing tags etc. Is there a way to obtain this inside the steps?

Thanks a lot.

### Versions

* **Cypress version**: 8.7.0
* **Preprocessor version**: 4.0.1
* **Node version**: 16.13.0

**Comment by badeball** [comment]
Hey @LoukasKonstantinou. You can try accessing `window.testState.pickle`, it contains a lot of information about the current test.

**Comment by LoukasKonstantinou** [comment]
Not very familiar with this, would I access it like this? `const scenario = cy.window().testState.pickle;`

**Comment by badeball** [comment]
Nope, it's available on the actual window object, so just `window.testState.pickle`.

**Comment by LoukasKonstantinou** [comment]
This is still coming up as undefined, do I need to import anything in particular in order to access the window object?

`import {
  After,
  And,
  Given,
  Then,
  When
} from 'cypress-cucumber-preprocessor/steps';`

**Comment by badeball** [comment]
The package has moved from `cypress-cucumber-preprocessor` to`@badeball/cypress-cucumber-preprocessor`, read more about it [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689). IE. you're not using latest version right now, but you should.

**Comment by LoukasKonstantinou** [comment]
Thank you, I will try that.

**Comment by LoukasKonstantinou** [comment]
Hi again, I have managed to find a way to extract tags from pickle (thanks @badeball). I am now looking to do something similar for the test result - pickle doesn't seem to include such information though. Any thoughts?

**Comment by badeball** [comment]
What are you trying to achieve?

**Comment by LoukasKonstantinou** [comment]
I am trying to do a POST call to the TestRail API which needs to include a `status_id` field to indicate passed or failed, like this (id 1 is passed):
```
const scenario = window.testState.pickle;
  const runId = (await testrail.addRun(3)).id;
  const caseId = Number(scenario.tags[0].name.substring(2));

  try {
    await testrail.addAndUpdateTestCaseResult(scenario, runId, caseId, {
      status_id: 1
    });
  } catch (err) {
    cy.log(`Error ${err}`);
  }
```
I therefore need to get the test result and then decide what `status_id` to send. 

Hope that makes sense?

**Comment by badeball** [comment]
I would perhaps do that kind of stuff in an [`after:spec` handler](https://docs.cypress.io/api/plugins/after-spec-api) or alternatively after running Cypress altogether.

**Comment by LoukasKonstantinou** [comment]
That is a good shout and certainly cleaner code, but how would I get the tag of each scenario in an `after:spec` plugin, so I can associate each test with its result?

Right now I'm using `window.testState.pickle` because I'm inside that test.

**Comment by badeball** [comment]
Right, I would solve this by post-processing the JSON output in a script ran after Cypress.
