### ISSUE TITLE
Requesting Enhancement for "Step_Definitions" location configuration in package.json to support glob patterns

### ISSUE THREAD

**Issue by asmahkojo** [badeball/cypress-cucumber-preprocessor#70]
First of all I want to say that I really love the work you guys have done here. I would, however, like to propose a small tweak to allow the "steps_definitions" location configuration property, configurable in package.json to allow glob patterns. 
A potentially quick fix to make this happen would be to replace (in "index.js" at the root folder)
`if (loaded && loaded.config && loaded.config.step_definitions) {
    return path.resolve(appRoot, loaded.config.step_definitions);
  }`
with
``if (loaded && loaded.config && loaded.config.step_definitions) {
    return `${appRoot}/loaded.config.step_definitions`;
  }``
Getting rid of path.resolve, will allow the user to pass in a glob string without it ultimately resolving to something unintended (doesn't say anywhere that glob patterns aren't supported there yet).  
I need this enhancement because i'm working on a project wherein all the step_definitions aren't defined under one parent folder by design. This enhancement will give users more flexibility to structure their step_definition files as they see fit.
I can currently achieve my ask by using the "fileServerFolder" configuration property configurable in "cypress.json" but the comment in the aforementioned "index.js" file says it is deprecated but left for backwards compatibility. Not sure if it is going to remain there longterm though. However, ideally, it would be awesome to  have that functionality in the "step_definitions" configuration property. 

Thanks! I really appreciate your efforts so far!

**Comment by lgandecki** [comment]
Thanks!

Would you be able to make a fork and try this out? Possibly adding step definitions in a place that would be accessible only through glob and .feature test for it?

**Comment by asmahkojo** [comment]
Hi! Thanks for the quick reply! I would love to but embarrassingly I'm pretty new to Github and currently don't have too much time on my hands for the next couple weeks. I could possibly get on it after a few weeks but I would really appreciate it if a more seasoned contributor were available to get on it. Any takers for now?
Thanks again!

**Comment by lgandecki** [comment]
Sure, we could probably have someone cook this up for you.

But, just to clarify, do you have something like:

cypress/
   step_definitions/
        featureSomtehing/
             somethingDefinition.js
             otherDefinition.js
        otherFeature/
            ...otherDefinition.js
        maybeADefinitionHere.js

or
cypress/
    stepDefinitionsFirstFolder/
    stepDefinitionsSecondFolder/

?

If it's the second case, what's the reason for NOT putting the step definitions under one folder (with nested folders)?
Could you explain a bit more your situation?

**Comment by asmahkojo** [comment]
Awesome thanks!
It is more like the first case. 

To give you more context, let's call the project i'm working on "TestRunnerApp". TestRunnerApp is responsible for running tests for Repository-A and Repository-B. Thus, Repository-A and Repository-B are pulled into TestRunnerApp via npm link.
Both Repository-A and Respository-B will generally have a folder structure like below:

<pre>e2e/
    common/
        step_definitions/
            example1CommonStepDefinitions.js
            example2CommonStepDefinitions.js
    features/
        feature1Folder/
            step_definitions/
                stepDefinitionsSpecificToFeature1.js
            feature1.feature</pre>

So putting it all together, imagine the above folder structure for both Repository-A and Repository-B within the node_modules of TestRunnerApp (because they are pulled in via npm link).
So, I want to be able to do something like below in the package.json for TestRunnerApp:

<pre>
"cypress-cucumber-preprocessor": {
    "step_definitions": "./node_modules/+(Repository-A|Repository-B)/e2e/**/step_definitions/"
}
</pre>

I hope this helps. Thanks again!

**Comment by bhreinb** [comment]
Hi There,

I tried the sample project here @

https://github.com/TheBrainFamily/cypress-cucumber-example

I upgraded the dependencies to

> "cypress": "^3.0.1",
> "cypress-cucumber-preprocessor": "1.2.2"

I notice I'm able to override the default "step_definitions" path when I set this in the package.json

> "cypress-cucumber-preprocessor": {
>     "step_definitions": "./cypress/support/step_definitions/"
>   }

However, I'm unable to do this within "cypress/plugins/index.js"

> const cucumber = require('cypress-cucumber-preprocessor').default
> module.exports = (on, config) => {
>   on('file:preprocessor', cucumber())
> 
>   return Object.assign({}, config, {
>     "integrationFolder": "cypress/integration",
>     "step_definitions": "tests/e2e/support/step_definitions/"
>   })
> 
> }

Naturally, when I set that here I remove the entry within package.json but it doesn't seem to pick up the path I set within "cypress/plugins/index.js". Do I have this right? Any pointers on this would be greatly appreciated.

**Comment by lgandecki** [comment]
the package.json is a different configuration than what you use here as the config. We've decided not to add anything to the cypress configuration as it's owned by the cypress guys and they didn't really want to cooperate on decisions here. :) 

Why can't you use package.json?

**Comment by bhreinb** [comment]
No I can use the package.json (it's just nice to have all test application configuration centralised in the one place is my only thing 👍 )

For example the "integrationFolder" is defined within "cypress/plugins/index.js"

the code behind that driving the test scenario is within "package.json"

```
"cypress-cucumber-preprocessor": {
"step_definitions": "./cypress/support/step_definitions/"
}
```
make sense?

**Comment by Huffman17** [comment]
I am having a similar issue, I am trying to separate features from step_definitions so in my package.json : 
`"cypress-cucumber-preprocessor": {
"step_definitions": "./cypress/integration/project/stepdefinitions/"
}`

and my file path for features is cypress/integration/project/features/file.feature

When I run the feature, it cannot find my step definitions.

**Comment by vio-codes** [comment]
I am basically requesting the same in this issue: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/483
This is the structure that I'm looking for:
```
- integration/
-     common/
-         step_definitions/
-             example1CommonStepDefinitions.js
-             example2CommonStepDefinitions.js
-     features/
-         frontend/
-             step_definitions/
-                 frontendstep1.js
-                 someotherfrontendstep.js
-             frontendfeature1.feature
-        backendend/
-             step_definitions/
-                 backendstep1.js
-                 someotherbackendstep.js
-             backendfeature1.feature
```
Can this be achieved in any other way?

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.
