### ISSUE TITLE
Cannot read properties of null (reading 'seconds')

### ISSUE THREAD

**Issue by thccorni** [badeball/cypress-cucumber-preprocessor#701]
### Current behavior

I get the error _Cannot read properties of null (reading 'seconds')_ since version 9.1.1.

![image](https://user-images.githubusercontent.com/21161192/165895731-b9398454-b4c3-4e3f-a23d-b2496a3facc1.png)

The reason seems to be that `start` is null [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/lib/create-tests.ts#L412)

Might it be, that `start` get's not passed the `then`-chain [before](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/lib/create-tests.ts#L400-L403)? 

### Desired behavior

No error.

### Versions

* **Cypress version**: 9.6.0
* **Preprocessor version**: 9.1.1
* **Node version**: 16.13.2

**Comment by badeball** [comment]
I can’t reproduce this. Can you provide me a minimal example that illustrates the problem?

**Comment by thccorni** [comment]
It seems to be related to the existence of an interceptor in a `Before` step.
https://github.com/thccorni/cypress-cucumber-issue-701 should reproduce the behaviour.

Thanks for your quick reply!

**Comment by badeball** [comment]
Thanks for the example! I've released v9.1.2 which I believe fixes the problem.

**Comment by thccorni** [comment]
Awesome, thanks!
