### ISSUE TITLE
Cannot find module 'cypress-cucumber-preprocessor' only on CI pipeline 

### ISSUE THREAD

**Issue by NikhilNanjappa** [badeball/cypress-cucumber-preprocessor#702]
### Current behavior

When I run the tests using command `npx cypress run -C config/docker.json -b chrome --headless`, it fails in the Gitlab pipeline with the following error

```
e2e_1                  | [203:0430/074638.893596:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
e2e_1                  | Your pluginsFile is invalid: /e2e/cypress/plugins/index.js
e2e_1                  | 
e2e_1                  | It threw an error when required, check the stack trace below:
e2e_1                  | 
e2e_1                  | Error: Cannot find module 'cypress-cucumber-preprocessor'
e2e_1                  | Require stack:
e2e_1                  | - /e2e/cypress/plugins/index.js
e2e_1                  | - /root/.cache/Cypress/9.6.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
e2e_1                  | - /root/.cache/Cypress/9.6.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js
e2e_1                  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
```

I even logged onto the container and checked, the package within node_modules exists.

FYI: The exact same command works fine on my local. Alternatively, tests also works if I remove the `cypress-cucumber-preprocessor` package and have the normal `describe`, `it` way.

My `plugins/index.js` looks like:
```
// referenced node_modules below as it used to reference it to @types/cypress-cucumber-preprocessor for some odd reason

const cucumber = require('../../node_modules/cypress-cucumber-preprocessor').default
/**
 * @type {Cypress.PluginConfig}
 */
module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
};
```

Not mentioned `nonGlobalStepDefinitions` within package.json as its within my `docker.json` config (tried in the package.json anyways without any luck). Which looks like:
```
{
  "waitForAnimations":true,
  "defaultCommandTimeout": 5000,
  "execTimeout":60000,
  "pageLoadTimeout":60000,
  "responseTimeout":15000,
  "requestTimeout":15000,
  "video":false,
  "failOnStatusCode": false,
  "baseUrl": "http://qat-web-service-dev:8001",
  "testFiles": "**/*.feature",
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
}
```
My package.json devDependencies
```
  "devDependencies": {
    "axe-core": "^4.3.5",
    "cypress": "^9.2.1",
    "cypress-axe": "^0.14.0",
    "cypress-cucumber-preprocessor": "^4.3.1",
    "cypress-xpath": "1.6.2",
    "eslint": "8.6.0",
    "eslint-plugin-cypress": "2.12.1",
    "husky": "7.0.4"
  }
```

My docker configurations:
```
// docker-compose.yml
...
e2e:
  image: cypress/browsers:node16.13.2-chrome97-ff96
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    - qat-web-service-dev
  command: npx cypress run -C config/docker.json -b chrome --headless
  working_dir: /e2e
  volumes:
    - ./:/e2e

// Dockerfile
FROM cypress/browsers:node16.13.2-chrome97-ff96
WORKDIR /e2e

COPY package.json .
COPY package-lock.json .

COPY  . .
RUN npm ci
```
Folder structure:
![Screen Shot 2022-04-30 at 10 04 32](https://user-images.githubusercontent.com/94963727/166099236-383899b8-399b-42a8-ad91-d9fcead0c1cf.png)

### Desired behavior

Within the CI pipeline, when I have installed the `cypress-cucumber-preprocessor` package (and confirmed its exists), when running cypress run with all the necessary configurations, it should not throw the `Cannot find module 'cypress-cucumber-preprocessor'` error. It should run the tests as expected.

### Test code to reproduce

The code is within a private domain so unfortunately cant provide the link. All the code is mentioned above. Please let me know if you need anything more.

### Versions

* **Cypress version**: 9.6.0
* **Preprocessor version**: 4.3.1
* **Node version**: 16.13.2

**Comment by badeball** [comment]
I can’t really do anything to help you here. The error is pretty clear and it’s also clearly not an issue with the preprocessor itself.

Additionally, configuration does not go into docker.json and you should be using the most recent version, see https://github.com/badeball/cypress-cucumber-preprocessor/issues/689.

**Comment by NikhilNanjappa** [comment]
@badeball - Im sorry but how is this pretty clear ?

I know what the error says. The issue is that the error is not supposed to appear with all the necessary configurations provided. That part is not clear!

**Comment by badeball** [comment]
You have a problem with node's module resolution on a container environment and that's not due to an issue with the preprocessor. It's always because someone is doing something wrong and it's impossible for me to say exactly what given the provided information.

**Comment by badeball** [comment]
A common mistake people do is that they do build their container with NPM modules, which can be inspected and looks correct. Then they start said container but mount some volume over the working directory thus erasing its original content (exactly like it seems like you're doing with your compose file). Because they're also using `npx`, which auto-downloads the provided package, a lacking `node_modules` is masked and an error only presents itself when attempting to import something non-cypress.

**Comment by NikhilNanjappa** [comment]
Thanks @badeball . That was helpful. Could you please guide me on the right docker configurations ?

**Comment by badeball** [comment]
I recommend just running `npm ci` as part of the build step (and alternatively mount a NPM cache directory), like `command: npm ci && npx cypress run -C config/docker.json -b chrome --headless`.

**Comment by NikhilNanjappa** [comment]
So something in these lines ? (sorry if im off the target)

```
// docker-compose.yml
...
e2e:
  image: cypress/browsers:node16.13.2-chrome97-ff96
  build:
    context: ./
  depends_on:
    - qat-web-service-dev
  command: npm ci && npx cypress run -C config/docker.json -b chrome --headless

// Dockerfile
FROM cypress/browsers:node16.13.2-chrome97-ff96

COPY package.json .
COPY package-lock.json .

RUN npm ci
```

**Comment by badeball** [comment]
You can continue to mount `e2e` if that's necessary, just append `npm ci` to the run-command, but yeah, something like that.

**Comment by NikhilNanjappa** [comment]
Im getting `The npm ci command can only install with an existing package-lock.json` error. Although im copying the package-lock.json

**Comment by NikhilNanjappa** [comment]
Finally fixed the issue. Just had to remove the following from `docker-compose.yml`

```
  working_dir: /e2e
  volumes:
    - ./:/e2e
```
Thanks @badeball
