### ISSUE TITLE
Add documentation for adding screenshots to Cucumber JSON

### ISSUE THREAD

**Issue by GRmeB** [badeball/cypress-cucumber-preprocessor#703]
It would be great if you can add a documentation on how to add/attach screenshots to Cucumber JSON with concrete code examples. And also how to attach screenshots only on failed tests. Currently I was not able to implement such a solution with that new package. So, a more detailed documentation would be very nice and helpful for all people :)

**Comment by badeball** [comment]
Fixed with 3dc38f8a12ff6aca95cf885c93f755c4e4fa839e.
