### ISSUE TITLE
I can't use the --config-file parameter in cypress-tags, always uses the default location

### ISSUE THREAD

**Issue by OSnuszka** [badeball/cypress-cucumber-preprocessor#706]
### Current behavior

I can't use the --config-file parameter in cypress-tags, always uses the default location

```
npx cypress-tags run --config-file cypress/config/dev/devAPI.json
**Failed to read cypress.json, using default configuration**
Spec files:  cypress/integration/**/*.feature
```

Command: 
`npx cypress run --config-file cypress/config/dev/devAPI.json`
normally works

### Desired behavior

Ability to use `--config-file` parameter with cypress-tags

### Test code to reproduce

Just move the default cypress.json file to another location and try to reference it.

### Versions

* **Cypress version**: 9.6.0
* **Preprocessor version**: 4.3.1
* **Node version**: 16.13.0

**Comment by badeball** [comment]
The package has moved to `@badeball/cypress-cucumber-preprocessor`, read more about the transfer [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689), IE. you're not using the most recent version, but you should.

The `cypress-tags` has been removed and made redundant in the latest version. Specs containing no matching scenarios are [automatically filtered](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md#running-a-subset-of-scenarios), provided that `filterSpecs` is set to `true`.
