### ISSUE TITLE
Provide support to add context to the cucumber json from each step in Cypress

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#707]
### Current behavior

In Mocha we have a addContext() function from "mochawesome/addContext" which support to add context to the generated test result json. So that we can publish valid information in report. But in Cypress Cucumber preprocessor, We don't have that support.

### Desired behavior
Please let us know how to add context to the cucumber json from one gherkin step in Cypress. 

For example, I want to export some data like "Page is displayed" from one gherkin step like "Then Check data page is displayed" to cucumber json. How to do that here? Please help!

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md#attachments
