### ISSUE TITLE
Replacement of cucumber-json-formatter? Because of the warning that it is a virus/malware

### ISSUE THREAD

**Issue by OSnuszka** [badeball/cypress-cucumber-preprocessor#708]
### Current behavior

It tries to generate a json file - it needs cucumber-json-formatter to generate it correctly. Unfortunately when I try to download this exe file I get information that it is a type Trojan virus.

![image](https://user-images.githubusercontent.com/78599192/167408053-2d1bab0b-458e-4fb1-9bd0-6cf69989e67e.png)
![image](https://user-images.githubusercontent.com/78599192/167408068-d12567ea-8cbc-4c05-a380-7e7393c94ff1.png)

Without this file I get the following error:

![image](https://user-images.githubusercontent.com/78599192/167408350-a8ad8075-908b-4a51-a7ea-aa3e82e93ecf.png)

I reported the problem on the cucumber-json-fromatter github and got the following response:
https://github.com/cucumber/common/issues/1974

### Desired behavior

Is it possible to use a tool other than? cucumber-json-formatter

Maybe the response from the link on GitHub suggests something:
![image](https://user-images.githubusercontent.com/78599192/167408585-94fc88ee-8578-4978-b1e3-b37dccfb6708.png)

**Comment by badeball** [comment]
> Is it possible to use a tool other than? cucumber-json-formatter

No, there are no other tools. That your antivirus is giving you a false positive is unfortunate, but not really my problem.

> Maybe the response from the link on GitHub suggests something:

I've asked for a clarification in https://github.com/cucumber/common/pull/1916#issuecomment-1121228736.

**Comment by adamzoltan873** [comment]
Hello @OSnuszka,

In plugins/index.js if you call the preprocessor with:   
`await cypressCucumberPreprocessor.addCucumberPreprocessorPlugin(on, config, {omitAfterRunHandler: true});`

and your cypress-cucumber-preprocessor config has something like this

```
{
...
messages: {
    enabled: true,
    output: `cucumber-messages.ndjson`
  }
...
}
```

then you can catch up your ndjson with a gulp task like this

```
gulp.task('cucumber-json', (cb) => {
  exec('npx ndjson-to-json [path-to-ndjson]/cucumber-messages.ndjson -o [path-to-cucumberjson]/cucumber.json', (err, stdout, stderr) => {
    console.log(stdout);
    console.log(stderr);
    cb(err);
  })
})
```

You obviously need to install ndjson-to-json npm package too.

**Comment by xyngfei** [comment]
I think should be a similar issue.

I am trying to enable the JSON reporting, encounter this issue, 

Package.json
"cypress": "^9.7.0",
"@badeball/cypress-cucumber-preprocessor": "^10.0.2",

`
"cypress-cucumber-preprocessor": {
    "json": {
      "enabled": true
    `}`
  }
`


![image](https://user-images.githubusercontent.com/17619539/171600930-f6e1751f-3203-4422-ba97-c7283da16f0a.png)
