### ISSUE TITLE
Before parameters

### ISSUE THREAD

**Issue by fcarvalhido** [badeball/cypress-cucumber-preprocessor#711]
### Current behaviour

cypress-cucumber-preprocessor does no have the testCase and callback available in the before method as cucumber.js has.
```
Before(function() {}
```

cucumber.js
https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/hooks.md#hooks
```
Before(function (testCase, callback) {
  var world = this;
  tmp.dir({unsafeCleanup: true}, function(error, dir) {
    if (error) {
      callback(error);
    } else {
      world.tmpDir = dir;
      callback();
    }
  });
});

```
### Desired behaviour

Be able to get current step, scenario, and feature information

**Comment by badeball** [comment]
Test info can be accessed through `window.testState` (undocumented, so changes may occur). What do you need a callback for?

**Comment by fcarvalhido** [comment]
Thanks that helped, I don't have a need for a callback.
