### ISSUE TITLE
Calling nested Steps seems to require Mocha?

### ISSUE THREAD

**Issue by sgielen** [badeball/cypress-cucumber-preprocessor#712]
I'm trying to use the "calling nested steps" feature as [documented here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/cucumber-basics.md#nested-steps). I use the `() => {...}` syntax instead of `function () {...}` because I like the syntax more and I don't use `this` for context.

I have these steps:

```
When("I visit the app root url", () => {
	cy.visit('/')
});

When("I log in as the new user", () => {
	Step(this, 'I visit the app root url')
	// Fill in the username & password, then click "Log in"
})
```

However, `this` isn't defined, so I get this error:

```
[tsl] ERROR in .../cypress/integration/login.ts(83,7)
      TS2345: Argument of type 'undefined' is not assignable to parameter of type 'Context'.
```

According to the `.d.ts` file the parameter should be a `Mocha.Context`:

```
export declare function Step(world: Mocha.Context, text: string, argument?: DataTable | string): void;
```

This was surprising to me, as I consider Mocha to be an implementation detail here, so it's surprising to me that this type is strictly described. I would expect `world: unknown` here, I think.

It does work when I run `Step(new Mocha.Context(), 'I visit the app root url');` but if an empty Context works, why do I need to pass it at all? If `unknown` is too generic, shouldn't `world: Mocha.Context | undefined` be fine, too?

### Versions

* **Cypress version**: 9.6.0
* **Preprocessor version**: 9.1.3
* **Node version**: 18.0.0

**Comment by badeball** [comment]
> I use the `() => {...}` syntax instead of `function () {...}` because I like the syntax more and I don't use `this` for context.

JS doesn’t care about your preference and arrow functions preserves the outer context.

**Comment by sgielen** [comment]
But you don't think that exposing an unused parameter type of Mocha.Context is also partially at fault here?

**Comment by badeball** [comment]
No, Cypress does the same thing with it(). It’s on this object that you can chose to store values in during the life time of a test and you need to propagate the context in order to satisfy the type requirement of the nested step’s implementation. If you create a new value just to satisfy TS, then you might be surprised later to find that this context in your definitions aren’t the same.

**Comment by sgielen** [comment]
OK, I get that, thanks for explaining. :)

So you recommend to use `function () {...}` syntax even if I don't use `this` myself, so I can pass the context to other steps which may expect to be able to use it, now or in the future. Thanks!
