### ISSUE TITLE
Support of parallel test executions

### ISSUE THREAD

**Issue by GRmeB** [badeball/cypress-cucumber-preprocessor#715]
Currently it is only possible to define one Cucumer report JSON in `package.json`:

```
"cypress-cucumber-preprocessor": {
	"json": {
		"enabled": true,
		"output": "cypress/reports/cucumber/cucumber-json/cucumber-report.json"
	}
}
```

In our case we are executing our tests in different parallel suites via Gitlab CI. So, we have a couple of Cucumber testcases and will execute them for different target applications (in our case different shops with the same functionalities tested by the same feature files). This is realized while using different Cypress config files when starting the tests.

But in the end the Cucumber report JSON file is always overwritten, so that there are only the test results available of the last ended parallel test execution.

So, it would be great if there should be a solution for multiple Cucumber report JSON files that can be merged at the end to a common JSON file with all test results of all parallel test executions in it.

**Comment by SirCmX** [comment]
We also try to execute our tests in parallel, but so far we fail because of our experience. Our tests only run in order.

Could you please give us an insight, without violating the rules of your company?

We didnt try it with sorry-cypress so far and at the moment we try it with cypress-parallel from badeball.

**Comment by badeball** [comment]
It seems like this can be solved by allowing configuration options to be overriden using environment variables, is that correct? Something like `CYPRESS_CUCUMBER_PREPROCESSOR_JSON_OUTPUT=foo.json cypress run ...`.

**Comment by GRmeB** [comment]
@badeball yes that would be a cool solution, because we realize parallel executions in that way that we start several parallel test executions with different config files.

**Comment by GRmeB** [comment]
@SirCmX We simulate parallel execution while starting only parallel jobs over our Gitlab CI. So, we have the chance to part our complete testcases in subgroups/subsuites that we execute. in parallel. So, we reduce the execution time and it is working for us.

**Comment by badeball** [comment]
I've relased v10.0.0 which allows you to override configuration values using environment variables, described [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md#configuration-overrides). Hope this helps.

**Comment by Thairam** [comment]
> I've relased v10.0.0 which allows you to override configuration values using environment variables, described [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md#configuration-overrides). Hope this helps.

Can you please provide me with more information on how it works? 

I have already attempted these configurations:

```
  "cypress-cucumber-preprocessor": {
    "html": {
      "enabled": true,
      "output": "cucumber-report.html"
    }
  }
```

`npx cypress run --env htmlOutput=cucumber-report.html`

But, in the end, the Cucumber report HTML file is always overwritten.

**Comment by badeball** [comment]
> But, in the end, the Cucumber report HTML file is always overwritten.

What do you expect to happen to the report, if not overwritten?

**Comment by Thairam** [comment]
> > But, in the end, the Cucumber report HTML file is always overwritten.
> 
> What do you expect to happen to the report, if not overwritten?

I expected the reports to be "merged".

**Comment by badeball** [comment]
I don't know what gave you that impression, but they're not. The above-mentioned released functionality only allows you to override configuration properties dynamically, not alter the behavior fundamentally.

**Comment by Thairam** [comment]
> I don't know what gave you that impression, but they're not. The above-mentioned released functionality only allows you to override configuration properties dynamically, not alter the behavior fundamentally.

I understand that, but, what I meant is: 

For instance, when multiple jobs run in parallel on different machines, each job will produce a portion of the report. As a result, when the tool overwrites the previous report with the newer one, it only publishes one of the three generated reports. I agree that it would make more sense if the tool could merge the three reports into one, similar to how JUnit does it. This way, the final report would include all the information, and you would not lose any data.

**Comment by badeball** [comment]
> For instance, when multiple jobs run in parallel on different machines, each job will produce a portion of the report. As a result, when the tool overwrites the previous report with the newer one, it only publishes one of the three generated reports.

How are reports overwritten when jobs run on different machines?
