### ISSUE TITLE
Cannot find module 'cypress-cucumber-preprocessor' for Sauce Labs execution

### ISSUE THREAD

**Issue by Bajibabup** [badeball/cypress-cucumber-preprocessor#716]
### Current behavior
I am not able to execute Cypress Specs/Tests in Sauce Labs with Saucectl. This issue is occurring only if I install the Cucumber plugin and configure the Index.js with it.
I have configured the Cucumber-Plugin and executed the Cucumber features, also Mocha Specs successfully in local(through CLI).But, If I try the same through Saucectl then getting an error **"Cannot find module 'cypress-cucumber-preprocessor"**.
Basically its failing@cypress\plugins\index.js.
I am wondering why its failing only through Saucectl command. Saucectl support execution if Cucumber features for Cypress? or any dependences issue? pls help me to investigate this issue.

Command used to execute the test:  C:\CypressSauce> node_modules\.bin\saucectl run 

Here is the error:
Sauce Cypress Runner 8.3.0
Preparing npm environment

Your pluginsFile is invalid: D:\sauce-cypress-runner\8.3.0\bundle\__project__\cypress\plugins\index.js

It threw an error when required, check the stack trace below:

Error: Cannot find module 'cypress-cucumber-preprocessor'
Require stack:
- D:\sauce-cypress-runner\8.3.0\bundle\__project__\cypress\plugins\index.js
- D:\sauce-cypress-runner\8.3.0\bundle\Cache\9.5.3\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js
- D:\sauce-cypress-runner\8.3.0\bundle\Cache\9.5.3\Cypress\resources\app\packages\server\lib\plugins\child\index.js

Index.json:
const cucumber = require('cypress-cucumber-preprocessor').default
// // This function is called when a project is opened or re-opened (e.g. due to
// // the project's config changing)

 module.exports = (on, config) => {
  on('file:preprocessor', cucumber())

//   // `on` is used to hook into various events Cypress emits
//   // `config` is the resolved Cypress config
 }

**Package.json:**
{
  "name": "cypressautomationcore",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node_modules\\.bin\\cypress run",
    "headTest": "npm run test -- --headed",
    "chromeTest": "npm run test -- --browser chrome",
    "recordDashBoardTest": "npm run test -- --record --key fa423514-5a84-42a7-b6a0-b5e7191bba12 --reporter mochawesome",
    "GreenKartTest": "npm run test -- --spec \"cypress/integration/CyPOC/*\""
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^9.6.0",
    "cypress-cucumber-preprocessor": "^4.3.1",
    "mocha": "^10.0.0",
    "mochawesome": "^7.1.3",
    "multiple-cucumber-html-reporter": "^1.20.0"
  },
  "dependencies": {
    "saucectl": "^0.97.0"
  }
}

### Desired behavior
Saucectl should work with Cucumber plugin also.
Note: While installing the Saucectl dependency, I got the message "5 moderate severity vulnerabilities".
I tried npm audit fix --force then got the below error, is it causing the issue?

npm WARN using --force Recommended protections disabled.
npm WARN audit No fix available for saucectl@*

up to date, audited 794 packages in 2s

86 packages are looking for funding
  run `npm fund` for details

# npm audit report

semver-regex  <3.1.3
Severity: moderate
Regular Expression Denial of Service (ReDOS) - https://github.com/advisories/GHSA-44c6-4v22-4mhx 
No fix available
node_modules/semver-regex
  find-versions  <=3.2.0
  Depends on vulnerable versions of semver-regex
  node_modules/find-versions
    bin-version  <=4.0.0
    Depends on vulnerable versions of find-versions
    node_modules/bin-version
      bin-version-check  <=4.0.0
      Depends on vulnerable versions of bin-version
      node_modules/bin-version-check
        bin-wrapper  >=0.4.0
        Depends on vulnerable versions of bin-version-check
        node_modules/bin-wrapper
          saucectl  *
          Depends on vulnerable versions of bin-wrapper
          node_modules/saucectl

6 moderate severity vulnerabilities

Some issues need review, and may require choosing

### Versions

Cypress version:9.6.0
Preprocessor version:4.3.1
Node version:v16.14.2
saucectl": "^0.97.0
Sauce Cypress Runner 8.3.0

**Comment by badeball** [comment]
Have you configured the dependency? https://github.com/saucelabs/saucectl-cypress-example/blob/main/examples/cucumber/.sauce/config.yml#L44

**Comment by Bajibabup** [comment]
Hi Thanks! I missed to add npm dependency. Its working now after adding below  for config.yml.

 “npm:
  packages:
    "cypress-cucumber-preprocessor": "4.0.3"
