### ISSUE TITLE
Before/beforeEach hooks run multiple times when running all tests is invoked from Cypress GUI

### ISSUE THREAD

**Issue by ghost** [badeball/cypress-cucumber-preprocessor#717]
### Current behavior

When running all spec files is invoked from GUI using the "Run ## integrations tests" button, then all `beforeEach` and `before` hooks run as many times as there are spec files before each and before all tests.

![image](https://user-images.githubusercontent.com/80748409/169273217-039c1d0d-d306-41c1-b2ed-aeeaf0507014.png)

This is the hook in question - it resides in a common steps file
![image](https://user-images.githubusercontent.com/80748409/169273482-8eabd8e5-8281-43e1-918b-b88f8a9d9e6e.png)

This is what I see when the test runs - it slows the whole test suite by a lot.
![image](https://user-images.githubusercontent.com/80748409/169273386-2712340c-8074-4074-bf1d-4bb40b65fe8c.png)

The same *does not* happen when tests are invoked in headless mode - then all hooks run correctly.

### Desired behavior

`before` hooks should only run once per the whole test suite (before each spec file would also be acceptable)
`beforeEach` hooks should only run once before each scenario.

### Test code to reproduce

I will provide one when I have more time to work on this

### Versions

* **Cypress version**: 9.3.5
* **Preprocessor version**: 9.2.1
* **Node version**: 16.9.1

**Comment by badeball** [comment]
This is a problem with Cypress, is present with preprocessor or not, and reported EG. [here](https://github.com/cypress-io/cypress/issues/3323).

**Comment by ghost** [comment]
Ah, I see. Would it be difficult to work around the issue by wrapping each feature in a describe block, as pointed out [by this comment](https://github.com/cypress-io/cypress/issues/3323#issuecomment-485629464)? I understand it might be undesirable to "fix" underlying problems by introducing workarounds, but I guess this one might be warranted.

**Comment by badeball** [comment]
The [10-release](https://github.com/cypress-io/cypress/pull/18924) is scheduled for 1st of june and appears to be removing "Run all specs" altogether, [ref](https://github.com/cypress-io/cypress-documentation/blob/757b7479bfdd17e25ccee603c3ab12c91968cd9b/content/_changelogs/10.0.0.md):

> The “Run all specs” and “Run filtered specs” functionality have been removed.

Hence, this is not something I will be focusing on.
