### ISSUE TITLE
How to Register Plugin to use tags option to filter tests

### ISSUE THREAD

**Issue by DeChrish** [badeball/cypress-cucumber-preprocessor#718]
Below are the separate plugin methods from docs, how to register it as use it .
### Plugin file - browserify
`import * as browserify from "@cypress/browserify-preprocessor";
import { preprocessor } from "@badeball/cypress-cucumber-preprocessor/browserify";

export default (
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): void => {
  on(
    "file:preprocessor",
    preprocessor(config, {
      ...browserify.defaultOptions,
      typescript: require.resolve("typescript"),
    })
  );
};`

### Tag - Plugin 
`import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";

export default async (
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> => {
  await addCucumberPreprocessorPlugin(on, config);

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}`

**Comment by badeball** [comment]
I've updated all examples in d102a4b39d7944110ce8e1e2702814f74528fe91, check them out.
