### ISSUE TITLE
An argument with default value from the optional regex capturing group returns `null` instead of a default value

### ISSUE THREAD

**Issue by alesiaviktorchyk** [badeball/cypress-cucumber-preprocessor#720]
### Current behavior

An argument with default value from the optional regex capturing group returns `null` instead of a default value.

Given I have the following step definition:
```js
Given(/^(?:I am|I'm) logged in( as '(.*)')?$/, (userType = 'user') => {
	cy.log(userType);
});
```
When in my feature file I use:
```feature
Feature: Test
    Scenario: Test
        Given I am logged in as 'user'
        Given I am logged in
```
I see the following in cypress test runner:
![screenshot-nimbusweb me-2022 05 22-18_39_59](https://user-images.githubusercontent.com/45420854/169706151-0f957b5b-fb7b-4d16-a4d8-b634c3ba78d1.png)

### Desired behavior

I expect that for both steps cy.log will log `user`.

At least this is how the old `cypress-cucumber-preprocessor` worked.

Here's what I see when I use the old `cypress-cucumber-preprocessor`:
![screenshot-nimbusweb me-2022 05 22-18_38_51](https://user-images.githubusercontent.com/45420854/169706147-8bed5049-a90f-4b3e-8901-60a68ea8e386.png)

### Test code to reproduce

To reproduce:
- clone https://github.com/alesiaviktorchyk/cypress-cucumber-preprocessor-test
- run `npm i`
- run `npm run test`

To compare `@badeball/cypress-cucumber-preprocessor` vs. `cypress-cucumber-preprocessor`:
- switch to the `old-preprocessor` branch and run `npm run test` again.

### Versions

* **Cypress version**: 9.6.1
* **Preprocessor version**: 10.0.0
* **Node version**: 15.8.0

**Comment by alesiaviktorchyk** [comment]
Unrelated to the issue but just wondering why with the new processor there's an empty `wrap` after each cypress command:
![screenshot-nimbusweb me-2022 05 22-18_39_59 (1)](https://user-images.githubusercontent.com/45420854/169707053-64e84e4c-b43e-4ba6-a594-e5196c530f81.png)

**Comment by badeball** [comment]
Regarding optional capturing groups in step definitions and parameter types, it seems that unmatched capturing group in step definition changed from undefined to null in cucumber-expressions-v7.0.1, when typescript was introduced. The previous preprocessor implementation was depending on cucumber-expressions ^6.0.1, while this is now on ^15.0.1, hence the change in behavior you're experiencing.

This is how cucumber-js now behaves and I see no reason for why the preprocessor should behave any differently.

I've relased v10.0.1 which omits logging certain calls to `cy.wrap`. Hope that helps.

**Comment by badeball** [comment]
You can use eg. [patch-package](https://github.com/ds300/patch-package) if you want to change this behavior yourself (you will find the relevant lines in cucumber-expressions in `dist/cjs/src/defineDefaultParameterTypes.js` and `dist/cjs/src/RegularExpression.js`).

**Comment by alesiaviktorchyk** [comment]
@badeball thanks for the explanation and for the quick fix of the `wrap` thing.
