### ISSUE TITLE
Step definitions not found on Windows (OS path separator issue)

### ISSUE THREAD

**Issue by akiver** [badeball/cypress-cucumber-preprocessor#721]
### Current behavior

Hello, I upgraded this project https://github.com/akiver/csgo-map-veto and encountered an issue on **Windows only**.
On Windows, step definitions are never found because of the file separator which is `\` instead of `/`.

This call never detects the step definitions files https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/lib/step-definitions.ts#L24

As a workaround, I'm running this patch on post-install https://github.com/akiver/csgo-map-veto/blob/main/patches/%40badeball%2Bcypress-cucumber-preprocessor%2B10.0.2.patch.
It replaces all `\` chars with `/`, I'm not sure if it's the right place to do it.

### Desired behavior

The step definitions should be found.

### Test code to reproduce

It should be reproducible with one of the examples in this project, otherwise, you can try with this project https://github.com/akiver/csgo-map-veto.

1. Clone https://github.com/akiver/csgo-map-veto
2. Delete the patch file
3. `yarn`
4. `yarn e2e`

### Versions

* **Cypress version**: 9.7.0
* **Preprocessor version**: 10.0.2
* **Node version**: 16

Thank you

**Comment by badeball** [comment]
I believe you're hitting [this](https://github.com/isaacs/node-glob/issues/471) bug in `glob`. Try pinning `glob` to 7.2.0 or 7.2.3 or something.

**Comment by akiver** [comment]
Thx! That was the issue
