### ISSUE TITLE
Loading step definitions from dependency

### ISSUE THREAD

**Issue by ydbondt** [badeball/cypress-cucumber-preprocessor#723]
I am trying to build a gherkin library to use across multiple product implementations for customer projects which are tested from different cypress projects. The idea is to build a set of step definitions that relate to the project behavior, which can be reused to create custom tests that differ depending on the project configuration.

However, I can't seem to be able to load the step definitions from a dependency.

So far I have tried to configure the following in my `package.json` file:

```
"cypress-cucumber-preprocessor": {
    "stepDefinitions": "./node_modules/@mycompany/cucumber-library/cypress/step_definitions/**/*.ts"
}
```
which returns following error:
```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
    at EventEmitter.handler (/home/ydbondt/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:69:27)
    at EventEmitter.emit (node:events:390:28)
    at ChildProcess.<anonymous> (/home/ydbondt/.cache/Cypress/9.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

Then I tried 
```
"cypress-cucumber-preprocessor": {
    "stepDefinitions": "@mycompany/cucumber-library/cypress/step_definitions/**/*.ts"
}
```
which doesn't return errors but no definitions are loaded.

Is there any other way to load step definitions from dependencies ?

### Versions

* **Cypress version**: 9.7.0
* **Preprocessor version**: 10.0.2
* **Node version**: 12.22.0

**Comment by badeball** [comment]
You were right the first time. The error is something you need to handle. You probably have to configure your bundler to transpile that particular path in node_modules, which they typically do not do.
