### ISSUE TITLE
afterRunHandler ndjson to json

### ISSUE THREAD

**Issue by adamzoltan873** [badeball/cypress-cucumber-preprocessor#724]
Hi @badeball,

In 
https://github.com/badeball/cypress-cucumber-preprocessor/blob/be404b90d0905684750e380546ee4fd606bbd997/lib/add-cucumber-preprocessor-plugin.ts#L72

you are referencing the messages.enabled config property, for creating the json output.

I also faced the problem with windows and cucmber-json-formatter (https://github.com/badeball/cypress-cucumber-preprocessor/issues/708) 
With omitting the afterRunHandler, now I have the opportunity to skip the ndjson -> json conversion, but as I can see the referenced line should be the following

` if (!preprocessor.json.enabled) { `

beacuse if I enable messages in config I  will get the ndjson file, but if I disable json in config, the condition will met, and will still get a converted json file.

Thanks, adamzoltan

**Comment by badeball** [comment]
Hey, @adamzoltan873, thanks for reporting the issue. I've fixed this in v11.0.0.
