### ISSUE TITLE
Step definition path still pointing to "cypress\integration" for Cypress version 10.0.0 

### ISSUE THREAD

**Issue by DerKip** [badeball/cypress-cucumber-preprocessor#725]
### Current behavior
Following the major release of [Cypress version 10.0.0](https://docs.cypress.io/guides/references/changelog#10-0-0), breaking changes have been introduced to the cucumber preprocessor.
The integrationFolder and componentFolder options were removed. These options were made obsolete by the new [specPattern option](https://github.com/cypress-io/cypress/pull/19319).

![Screenshot 2022-06-02 025709](https://user-images.githubusercontent.com/28872296/171520402-346327ca-7a4d-455e-993e-77dbe0221175.png)

### Desired behavior
The preprocessor should not error when provided a path not within integrationFolder ("cypress\integration") for cypress version 10.0.0, rather, it should accept the path provided ("cypress/e2e").

### Versions

* **Cypress version**: 10.0.0
* **Preprocessor version**: 4.3.1
* **Node version**: v16.15.0

**Comment by xyngfei** [comment]
@DerKip Do you have any example of cucumber implementation on cypress > 10.0.0?

**Comment by omersomuncu** [comment]
I am also suffering from this problem.

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/722#issuecomment-1144579920

**Comment by damsorian** [comment]
[badeball](https://github.com/badeball) sos un bot? ponele un poco de onda
