### ISSUE TITLE
No Support for Cypress version 10

### ISSUE THREAD

**Issue by bjoshi-codal** [badeball/cypress-cucumber-preprocessor#726]
### Current behavior

Cypress cucumber preprocessor does not support cypress 10 as the folder structure is changed in cypress 10 

### Desired behavior

Should support Cypress 10 version

### Versions

* **Cypress version**: cypress 10
* **Preprocessor version**: 4.3.1
* **Node version**: 16.14.2

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/722#issuecomment-1144579920
