### ISSUE TITLE
Publish GitHub releases for new versions

### ISSUE THREAD

**Issue by wrslatz** [badeball/cypress-cucumber-preprocessor#727]
Splitting this request out from https://github.com/badeball/cypress-cucumber-preprocessor/issues/689#issuecomment-1114883850.

It would be really helpful if new versions were published as GitHub releases. Releases can be separately subscribed to while tags and `CHANGELOG` updates cannot. Subscribing to releases is a great way to notify users as new versions are released. The GitHub release contents can either be a copy of the `CHANGELOG` or a link to the heading in the `CHANGELOG` corresponding to that version.

**Comment by wrslatz** [comment]
From the previous thread, I think there was concern about confusion publishing GitHub releases that included work done during the migration of ownership for this repo. I think not having GitHub releases for the newer versions is equally confusing, since the latest GitHub release version is shown at the top level of the repo. I think new versions since the transfer completed should be published as releases pointing to the corresponding tags.

**Comment by badeball** [comment]
You're right on all counts. I've made a release for v11.0.0 and will continue to do so moving forward.
