### ISSUE TITLE
[Feat] Add compatibility to the ndjson-to-json package

### ISSUE THREAD

**Issue by nicoaugereau** [badeball/cypress-cucumber-preprocessor#728]
_Requirement:_
Convert ndjson messages files to json format regardless of the test environment.

_Current result:_
Use the `json-formatter` converter.

- Problem (constraint) 1 : on a Windows development environment we have to use the file for Windows environment and on a Linux or CI test environment we have to use another file.
- Problem 2 : files provided by `json-formatter` are detected as viruses or trojan horses. (probably false positive, this is not good for corporate security) [Virus total.com](https://www.virustotal.com/gui/file/a1b27a9647c6fffc2b0476ff2a52f147b7466c6f8df51fb995654412c776927a)

_Desired Result:_
Use only 1 file type (script) to convert ndjson to json messages.
The npm package `ndjson-to-json` can be run on all environments, and the `spawn( )` command can be used in the [add-cucumber-preprocessor-plugin.ts](https://github.com/badeball/cypress-cucumber-preprocessor/blob/be404b90d0905684750e380546ee4fd606bbd997/lib/add-cucumber-preprocessor-plugin.ts#L95) file (add `shell: true`)

**Comment by badeball** [comment]
I fail to see any value in this. Anyone can do post-processing themselves, it doesn't have to be built into the preprocessor, and `ndjson-to-json` does next to nothing.

**Comment by badeball** [comment]
Do you realize that `ndjson-to-json` is not a replacement for `cucumber-json-formatter`? The latter does _a lot_ to produce a _correct_ JSON file. It simply not sufficient or even useful to just have _a_ JSON file.

**Comment by nicoaugereau** [comment]
Do you know if it is possible to produce `cucumber-report.json` without `cucumber-json-formatter` ?
Does a solution exists because I can't use `cucumber-json-formatter`? 
And do you know which package for html test reports is available with the new JSON file structure?

**Comment by badeball** [comment]
> Do you know if it is possible to produce `cucumber-report.json` without `cucumber-json-formatter` ?

No such solution exist.

> And do you know which package for html test reports is available with the new JSON file structure?

There is no "new" JSON structure. It has remained the same, but now requires `cucumber-json-formatter` to help with the generation. Any tool you used before should be compatible now as well.

**Comment by iomedico-beyer** [comment]
I solved these problems by creating a Docker image which contains the Linux executable. 
Full documentation including how to use it automatically in @badeball/cypress-cucumber-preprocessor: 

https://stackoverflow.com/questions/72868617/container-to-pipe-to-an-executable-and-out-again/72868618#72868618

You might want to deploy the image on your CI server (docker push) and then reference it in `.cypress-cucumber-preprocessorrc.json` like this (Gitlab example):

    {
        "json": {
            "enabled": true,
            "formatter": "docker",
            "args": ["run", "--rm", "-i", "gitlab.example.com:5050/docker/cucumber-json-formatter"]
        }
    }
