### ISSUE TITLE
`"after each" hook for "test"` error

### ISSUE THREAD

**Issue by bpingris** [badeball/cypress-cucumber-preprocessor#729]
### Current behavior
**Sometimes**, a test will fail with an error saying `"after each" hook for "TEST_NAME"`
*detailed error*:
```
  1 failing
  1) Coupons:
       "after each" hook for "User with coupons":
     Error: Expected to find an error message (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)
Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
      at fail (http://localhost:3000/__cypress/tests?p=cypress/integration/my-account/coupons.feature:2737:11)
      at assert (http://localhost:3000/__cypress/tests?p=cypress/integration/my-account/coupons.feature:2744:5)
      at assertAndReturn (http://localhost:3000/__cypress/tests?p=cypress/integration/my-account/coupons.feature:2748:5)
      at Context.eval (http://localhost:3000/__cypress/tests?p=cypress/integration/my-account/coupons.feature:3386:60)
```

However, in the given error message it marks the test "User with coupon", but it has no "after" hook setup:
```feature
  @mock
  @user-admin
  Scenario: User with coupons
    Given I navigate to the url "/my-account/parrainage"
    Then I should see 2 'Coupon code' elements
    Then I click the 'Share coupon button' element
    Then The clipboard value should be 'xxxxxx'
```
The two tags `mock` and `user-admin` setup HTTP mocking using `Before`

Note that this error does not occur every time I run the tests, it's quite random and I can't find a pattern to reproduce it at 100%.

### Desired behavior
I should not have this error as I do not have any `after` hook setup, might be related directly to the package.

### Versions

* **Cypress version**: 9.5.4
* **Preprocessor version**: 10.0.2
* **Node version**: 14.19.3

**Comment by badeball** [comment]
I understand that you only experience this _sometimes_, but with the provided information you're enabling me to experience it _no times_. You have to put together something if you want any help. Until then I can't / won't consider the problem.

**Comment by bpingris** [comment]
you're right, I should have give you a reproduction repo or something with more information.

I tried to replicate my issue unfortunately I can't do it again with a [trivial project](https://github.com/bpingris/cypress-cucumber-error-repro)
The repository I linked is obviously an ultra trimmed down version of my real world project, but the logic for the tests is the same (i.e. how I call `cy.intercept` in `Before` calls).

So, I guess it's related to my project which might have too much overhead sometimes that might conflict with cypress in some way (still need to be determined, but as I wrote in my original post, it's quite random so it's near impossible to narrow down the issue :/)

**Comment by ekeijl** [comment]
After upgrading cypress-cucumber-preprocessor to this v12, I'm also seeing this error, which seems very related to usage of `cy.intercept()`. Additionally, seeing this error consistently, but only in "run" / headless mode:

``` Error: An error was thrown while processing a network event: onResponse cannot be called twice```
Originating from [here](https://github.com/cypress-io/cypress/blob/ab401ecd359234985b269d8283ff526136eeb4d4/packages/net-stubbing/lib/server/intercepted-request.ts#L62).

I'm using GraphQL, so I'm only using a single interceptor for the `/graphql/**` route and then use some logic in the resolver to send the correct response based on the `operationName`, but still this should send only a single response (and this worked correctly before updating). So my initial thought was that interceptors are not cleaned up correctly after a test and carry over to the second test somehow?

I wasn't able to isolate the issue further yet, debugging in headless mode is hard.
