### ISSUE TITLE
All the step definition are now global

### ISSUE THREAD

**Issue by danbord** [badeball/cypress-cucumber-preprocessor#730]
### Current behavior
New version does not allow to have non-global steps definitions.  

Lets take an example step : "**When I enter username**"

The context of that step may be completely different when used in a different feature file, now it points all to the same global step.

In order to organize things correctly, I think the scope of the steps should be strictly linked to the corresponding feature file and have some global steps that are defined at a specific location where they are intended to be global

### Versions

* **Cypress version**: 9.7.0
* **Preprocessor version**: 10.0.2

**Comment by jbrangwyn** [comment]
How have you configured your stepDefinition filepaths in package.json?

I found that I could mimic the existing behaviour of global **and** non-global steps by including a [filepath] to find the non-global steps, and a common path to find the global steps. For example:

`  "cypress-cucumber-preprocessor": {
    "stepDefinitions": [
      "cypress/step-definitions/[filepath]/*.{js,ts}",
      "cypress/step-definitions/common/**/*.{js,ts}",
      "cypress/step-definitions/common/*.{js,ts}"
    ]
  }`

**Comment by danbord** [comment]
Ok, got I now understand how [filepath] and [filepart] works.  Now It works fine!
