### ISSUE TITLE
Error 'Expected pickle to have a name' when attempting to run scenario with blank title

### ISSUE THREAD

**Issue by jbrangwyn** [badeball/cypress-cucumber-preprocessor#731]
### Current behavior

I had a scenario outline with a blank title that ran successfully prior to the upgrade. Now it fails with a slightly vague error message.
![2022-06-01 08_15_29-kallidus sapling ui](https://user-images.githubusercontent.com/69582899/172173337-0fc38493-3c59-4a8a-8dac-58d82add92e0.png)

### Desired behavior

Suggest validating the scenario has a title.

Mainly logging this as it might help someone else figure out what the issue is.

### Versions

* **Cypress version *9.7.0*:
* **Preprocessor version *10.2*:

**Comment by badeball** [comment]
Hey, @jbrangwyn , thanks for reporting the issue. I've fixed this in v11.0.0.
