### ISSUE TITLE
Required cucumber-json-formatter no longer available for json reports

### ISSUE THREAD

**Issue by jwmickey** [badeball/cypress-cucumber-preprocessor#732]
The [documentation](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md) for generating cucumber reports states that the [cucumber-json-formatter](https://github.com/cucumber/common/tree/main/json-formatter) binary is expected to be installed.

I happen to have already downloaded this for MacOS, but when going back to download it for linux and integrate it into our pipeline, I see it no longer exists.  [This issue](https://github.com/cucumber/common/issues/1915) says it was removed because "We don't need it anymore - Cucumbers are keeping their native JSON formatters."

Is there an alternative solution?  Preferably a nodejs package so we can include this in our package devDependencies rather than installing a binary.

**Comment by badeball** [comment]
> Is there an alternative solution?

There is not.

It's code is kept alive for now, ref https://github.com/cucumber/common/pull/1916#issuecomment-1121458995 and the docs have been updated with the correct URL (37779508e463cdc6e6041476afd17b93447027eb).

**Comment by jwmickey** [comment]
Thanks for the link and updated docs!

**Comment by deepakshrma** [comment]
I have create a wrapper due to same issue. You can give a try. @[jwmickey](https://github.com/jwmickey)


https://www.npmjs.com/package/@deepakvishwakarma/cucumber-json-formatter
