### ISSUE TITLE
Feature Request: create output directories if they do not exist, support absolute paths

### ISSUE THREAD

**Issue by jwmickey** [badeball/cypress-cucumber-preprocessor#736]
### Current behavior

When writing to messages.output, if the target directory does not exist an error will be thrown in the `after:spec` event:

    Error: ENOENT: no such file or directory, open '/code/project/path/to/cucumber-messages.ndjson'

Similarly, when writing to json.output, if the target directory does not exist an error will be thrown in the `after:run` event.

Separately, since the output paths are joined with the project root, you must use relative paths to specify a directory above the project root such as `/tmp/my-report/`.  
    

### Desired behavior

Add a check in the `before:run` event that, when `json.enabled == true`, checks for the existence of the target directories and attempts to create them (recursively) if they do not exist.  

Additionally, if the target path is absolute, it should not be prepended with the project root.

### Versions

* **Cypress version**: 8.7.0
* **Preprocessor version**: 10.0.2
* **Node version**: 16.14.2

**Comment by badeball** [comment]
Hey, @jwmickey , thanks for reporting the issue. I've fixed this in v11.0.0.

**Comment by jwmickey** [comment]
Thanks for the quick turnaround @badeball!  I can confirm both features are working in 11.0.0
