### ISSUE TITLE
Relax nodejs version limitations

### ISSUE THREAD

**Issue by shake82** [badeball/cypress-cucumber-preprocessor#738]
### Current behavior

The npm package is restricted to nodejs 14 and greater
```json
"engines": {
    "node": ">=14.14.0"
  }
```

### Desired behavior

Relax this limitation unless this causes an undesirable affect. I did not see an issue or a pull request that mentioned the reason behind adding this restriction.
I realize that the FAQs mention the nodejs minimum requirement but due to certain limitations, its not possible to do so immediately (legacy code :S).

### Test code to reproduce
With node version 12.x
```bash
> npm install @badeball/cypress-cucumber-preprocessor
```

### Versions

* **Cypress version** 10:
* **Preprocessor version**:
* **Node version** 12.16.x:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I'm not going to subject myself to the limitations of using severely old node versions just because you are, especially when I don't at all buy that you (or anyone) is constricted from upgrading to 14.14.0 (last LTS major FYI).
