### ISSUE TITLE
Step implementation missing for all steps after switch to the badeball package from the original TheBrainFamily

### ISSUE THREAD

**Issue by ameduza** [badeball/cypress-cucumber-preprocessor#739]
### Current behavior

Getting 'Step implementation missing for: ...' all my steps after upgrade from cypress-cucumber-preprocessor 4.3.1 to @badeball/cypress-cucumber-preprocessor 11.0.0
Please see link to code example below.

I'm getting this error when run my tests:
```
Error
Step implementation missing for: I am on Google search page
[node_modules/@badeball/cypress-cucumber-preprocessor/lib/registry.js:71:1](http://localhost:61252/__/#)
  69 |         const matchingStepDefinitions = this.stepDefinitions.filter((stepDefinition) => stepDefinition.expression.match(text));
  70 |         if (matchingStepDefinitions.length === 0) {
> 71 |             throw new Error(`Step implementation missing for: ${text}`);
     | ^
  72 |         }
  73 |         else if (matchingStepDefinitions.length > 1) {
  74 |             throw new Error(`Multiple matching step definitions for: ${text}\n` +
```

Scenario:
```cucumber
    Scenario: Google search
        Given I am on Google search page
        When I search 'Cypress' term
        Then title should contain 'Cypress'
```
Steps definition file:
```typescript
import { Given, When, Then } from "@badeball/cypress-cucumber-preprocessor";

Given("I am on Google search page", () => {
  cy.visit("https://google.com");
  siteContext = siteName.Google;
});
```

cypress/plugins/index.ts
```typescript
import * as browserify from "@cypress/browserify-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import { preprocessor } from "@badeball/cypress-cucumber-preprocessor/browserify";

export default async (
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> => {
  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    preprocessor(config, {
      ...browserify.defaultOptions,
      typescript: require.resolve("typescript"),
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
};
```

### Desired behavior

Be able to run tests

### Test code to reproduce

Minimalistic Git Repo link: https://github.com/ameduza/CypressCucumberFromScratch
The commit with 'attempt to upgrade to @badeball/cypress-cucumber-preprocessor' message contains the issue.
The previous one 'add VSCode settings' with the cypress-cucumber-preprocessor@4.3.1 works just fine.

### Versions

* **Cypress version**: 9.7.0
* **Preprocessor version**: 11.0.0
* **Node version**: 18.3.0

package.json:
```json
  "devDependencies": {
    "@testing-library/cypress": "^8.0.3",
    "@types/cypress-cucumber-preprocessor": "^4.0.1",
    "cypress": "^9.7.0",
    "@badeball/cypress-cucumber-preprocessor": "^11.0.0",
    "typescript": "^4.7.3"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/steps/",
    "commonPath": "cypress/steps/"
  }
```

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Read through the [upgrade guide](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689) and try one more time.

**Comment by ameduza** [comment]
Found my mistake, thanks a lot.
Updated package.json from this
```json
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/steps/",
    "commonPath": "cypress/steps/"
```
to this:
```json
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "cypress/steps/**/*.{js,ts}"
```
Now works just fine. Thanks again :)
