### ISSUE TITLE
Fail function in node_modules/@badeball/cypress-cucumber-preprocessor/lib/assertions.js:7:1 says cannot attribute error to a specific test

### ISSUE THREAD

**Issue by sammyschutz** [badeball/cypress-cucumber-preprocessor#740]
### Current behavior

[file:///Users/sammyschutz/Desktop/Screen%20Shot%202022-06-19%20at%2010.01.33%20PM.png](url)
<img width="432" alt="Screen Shot 2022-06-19 at 10 01 33 PM" src="https://user-images.githubusercontent.com/59894087/174512758-f516093b-1920-4cab-9ad6-65857d4f124f.png">

### Desired behavior

I want to be able to run my tests in cypress.

### Versions

* **Cypress version**: 10.1.0
* **Preprocessor version**: 11.0.0
* **Node version:**: 16.15.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Read through [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) and try one more time.
