### ISSUE TITLE
JSON formatter does not allow arguments

### ISSUE THREAD

**Issue by mrkjdy** [badeball/cypress-cucumber-preprocessor#741]
### Current behavior

Currently, the JSON formatter throws an error when you use arguments:
```
Error: spawn <any formatter with args> ENOENT
  at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
  at onErrorNT (node:internal/child_process:478:16)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
Some examples of a formatter with args include:
* `node some-script.js`
* `some-json-formatter arg1 arg2`
* `node wasm-runner.js some-json-formatter.wasm`

### Desired behavior

I want to be able to pass arguments to the formatter process. This would make the formatter option more flexible. Here's an example of a config that has a formatter with an argument:

```JSONC
"json": {
  // ...
  "formatter": "node cucumber-json-formatter.js"
},
```

In this situation I expect node to be spawned with "cucumber-json-formatter.js" as its first argument

### Versions

* **Cypress version**: `10.1.0`
* **Preprocessor version**: `11.1.0`
* **Node version**: `16.15.1`

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
We can add an option for arguments, but FYI, in case you wasn't aware, you can make JS files into executables and avoid the need for this, by using a "shebang".

```
~$ cat > bin/hello-world
#!/usr/bin/env node
console.log("Hello world!");
^D
~$ chmod +x bin/hello-world 
~$ hello-world 
Hello world!
```

**Comment by mrkjdy** [comment]
I experimented a bit with that but it doesn't work cross-platform (on Windows) right?

**Comment by badeball** [comment]
I don't know use that platform for anything besides gaming, so I wouldn't know.
