### ISSUE TITLE
How do we configure for Javascript instead of typescript BDD configuration

### ISSUE THREAD

**Issue by anilgsk** [badeball/cypress-cucumber-preprocessor#743]
### Current behavior

cypress.config.ts has has script that supports only ts not js. 

### Desired behavior
I am new to JS & Cypress, we are migrating protractor to Cypress. I used BrianFamily cypress cucumber pre-processer, but we have folder structure redundancy there. while integrating badeball cypress cucumber pre-processer, I came across three bundlers Browsify, webpack, Esbuild., what are those? They are in only typescript. How do it integrate with Javascript.?

### Versions

* **Cypress version**:10.
* **Preprocessor version**:latest
* **Node version**:16.15.0

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by DlgSHi** [comment]
@anilgsk thx for raising this, also I'm interested :)

**Comment by hdabas2** [comment]
Same here, looking for the solution.

**Comment by manoj-mukherjee-maersk** [comment]
here I made example - https://github.com/2manoj1/cy-blog-tutorial/blob/main/cypress.config.js

Article
https://www.linkedin.com/pulse/cypress-10-frontend-javascript-engineer-manoj-mukherjee/

**Comment by badeball** [comment]
I've added examples for CJS ("regular" JavaScript) and ESM. I can't however be the one to explain you the intrinsic details and differences between the bundlers. Unless you have particular requirements I recommend using Esbuild.

**Comment by manoj-mukherjee-maersk** [comment]
> Yeah, thanks @manoj-mukherjee-maersk it's working perfect !!
> 
> One more change that i did in **package.json** file -> Mentioning the exact stepDefination file name otherwise all the cypress classes gets picked up.
> 
> "cypress-cucumber-preprocessor": { "stepDefinitions": [ "cypress/e2e/examples/stepDef1.js" ] }

I preferred configuration in separate json file .cypress-cucumber-preprocessorrc.json - https://github.com/2manoj1/cy-blog-tutorial/blob/main/.cypress-cucumber-preprocessorrc.json

**Comment by hdabas2** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/webpack-cjs/cypress.config.js

Thanks @badeball , found it !
