### ISSUE TITLE
External folder with feature files isn't compatible with [filepath] configuration

### ISSUE THREAD

**Issue by TheEnduri** [badeball/cypress-cucumber-preprocessor#744]
### Current behavior
This problem occurs for cypress 10.1.0
Currently when I'm trying to use stepDefinitions configuration based on `[filepath]/**/*.{js,ts}` and common steps with relative path `cypress/steps/common/**/*.{js,ts}`, only common steps are visible.
When I use [filepart] instead [filepath] `cypress/steps/[filepart]/**/*.{js,ts}` this works properly, but I can't use duplicated steps name within parent folder area.
I define in cypress config `specPattern: 'features/**/*.feature'`

My folder structure looks like this:
-e2e
  - cypress
    - steps
      - common
      - feature1
        - feature1A
          - xyz
            - index.ts
       - feature2
       ....
- features
    - feature1
      - feature1A
        - xyz.feature
    - feature 2
    ...

### Desired behavior

Is it possible to have .feature files in external folder, not in cypress folder, like in my example folder structure

### Versions

* **Cypress version**: 10.1.0
* **Preprocessor version**: 11.1.0
* **Node version**: v16.14.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by TheEnduri** [comment]
My previous configuration that allows for duplicated steps name within given feature.
```
    "stepDefinitions": [
      "cypress/stepDefinitions/[filepath]/index.ts",
      "cypress/support/common/**/*.{js,ts}"
    ]
```

**Comment by badeball** [comment]
Please provide me a folder structure / project illustrating this, otherwise I can't be bothered to look into it.

**Comment by TheEnduri** [comment]
https://github.com/TheEnduri/ccmbr-filepath-issue

**Comment by TheEnduri** [comment]
> 

https://github.com/TheEnduri/ccmbr-filepath-issue

**Comment by mike-mccormick** [comment]
I'm seeing the same thing, and my repo structure roughly matches what @TheEnduri has; 

config:
```json
        "stepDefinitions": [
            "cypress/step-definitions/[filepart].{js,ts}",
            "cypress/step-definitions/[filepart]/**.common.{js,ts}",
            "cypress/step-definitions/common/navigation.{js,ts}",
            "cypress/step-definitions/common/mock-authentication.{js,ts}"
        ],
```

dir structure:


```
cypress.config.ts
package.json
cypress
├── step-definitions
│   ├── account-management
 |          └───── account-notes.ts
├── support
└── tests
 |     ├── account-management
 |          └───── account-notes.feature
```

I have two versions of my project repo: 

@badeball/cypress-cucumber-preprocessor@7.0.1
```
  cypress-cucumber-preprocessor looking for step definitions using [
  cypress-cucumber-preprocessor   'cypress/step-definitions/[filepart].{js,ts}',
  cypress-cucumber-preprocessor   'cypress/step-definitions/[filepart]/**.common.{js,ts}',
  cypress-cucumber-preprocessor   'cypress/step-definitions/common/navigation.{js,ts}',
  cypress-cucumber-preprocessor   'cypress/step-definitions/common/mock-authentication.{js,ts}'
  cypress-cucumber-preprocessor ] +1ms
  cypress-cucumber-preprocessor replacing [filepath] with 'account-management/account-notes' +0ms
  cypress-cucumber-preprocessor replacing [filepart] with [ 'account-management/account-notes', 'account-management' ] +0ms
  cypress-cucumber-preprocessor found step definitions [
  cypress-cucumber-preprocessor   '/home/mike/Projects/the-project/integration/cypress/step-definitions/account-management/account-notes.ts',
  cypress-cucumber-preprocessor   '/home/mike/Projects/the-project/integration/cypress/step-definitions/common/navigation.ts',
  cypress-cucumber-preprocessor   '/home/mike/Projects/the-project/integration/cypress/step-definitions/common/mock-authentication.ts'
  cypress-cucumber-preprocessor ] +9ms
```

@badeball/cypress-cucumber-preprocessor@11.1.0:

```
  cypress-cucumber-preprocessor looking for step definitions using [
  cypress-cucumber-preprocessor   'cypress/step-definitions/[filepart].{js,ts}',
  cypress-cucumber-preprocessor   'cypress/step-definitions/[filepart]/**.common.{js,ts}',
  cypress-cucumber-preprocessor   'cypress/step-definitions/common/navigation.{js,ts}',
  cypress-cucumber-preprocessor   'cypress/step-definitions/common/mock-authentication.{js,ts}'
  cypress-cucumber-preprocessor ] +1ms
  cypress-cucumber-preprocessor replacing [filepath] with 'cypress/tests/account-management/account-notes' +0ms
  cypress-cucumber-preprocessor replacing [filepart] with [
  cypress-cucumber-preprocessor   'cypress/tests/account-management/account-notes',
  cypress-cucumber-preprocessor   'cypress/tests/account-management',
  cypress-cucumber-preprocessor   'cypress/tests',
  cypress-cucumber-preprocessor   'cypress'
  cypress-cucumber-preprocessor ] +0ms
  cypress-cucumber-preprocessor found step definitions [
  cypress-cucumber-preprocessor   '/home/mike/Projects/the-project/integration/cypress/step-definitions/common/navigation.ts',
  cypress-cucumber-preprocessor   '/home/mike/Projects/the-project/integration/cypress/step-definitions/common/mock-authentication.ts'
  cypress-cucumber-preprocessor ] +8ms
```

Previously `[filepart]` and `[filepath]` were substituted differently, the current version seems to include, or start from the path of the `.feature` file:

Working:  cypress-cucumber-preprocessor replacing [filepath] with 'account-management/account-notes' +0ms
Failing:  cypress-cucumber-preprocessor replacing [filepath] with 'cypress/tests/account-management/account-notes' +0ms

This is as far as I've gotten between other tasks, is this enough information for you to recreate this Badeball? I can try and throw together another repro repo if needed.

**Comment by badeball** [comment]
> is this enough information for you to recreate this Badeball?

It's not whether it's possible for me to recreate the scenario, it's that I don't want to have to spend time doing that _in addition_ to fixing the actual issue, when you might as well.

**Comment by badeball** [comment]
@TheEnduri, your example works with the following patch (notice the directory rename).

```patch
diff --git a/cypress/steps/feature1/feature1A/xyz/index.ts b/cypress/steps/features/feature1/feature1A/xyz/index.ts
similarity index 100%
rename from cypress/steps/feature1/feature1A/xyz/index.ts
rename to cypress/steps/features/feature1/feature1A/xyz/index.ts
diff --git a/package.json b/package.json
index d6176c2..667143d 100644
--- a/package.json
+++ b/package.json
@@ -17,7 +17,7 @@
   },
   "cypress-cucumber-preprocessor": {
     "stepDefinitions": [
-      "[filepath]/**/*.{js,ts}",
+      "cypress/steps/[filepath]/**/*.{js,ts}",
       "cypress/steps/common/**/*.{js,ts}"
     ]
   }
```

**Comment by princefishthrower** [comment]
@badeball How about the following setup:

Feature file in `features/e2e/contact-form/contact-form.feature`
Test file in `__tests__/e2e/contact-form/contact-form.ts`

I can't get Cypress to run my tests:

```
Cypress could not detect tests in this file.
```

Ideally, I'd like to stay away from putting both my feature and / or test files under the `cypress/` folder. I hope this is possible.

**Comment by mike-mccormick** [comment]
@badeball can I ask a quick question off the back of this? `[filepart]` and `[filepath]` seem to have changed between v7, and the latest version of this package, and I want to know if this was intentional. 

For this test:
`cypress/tests/authentication/user-registration.feature`
We'll store the definitions in: 
`cypress/step-definitions/authentication/user-registration.ts`

On v7 I was able to resolve steps using this `stepDefintions` pattern:
`cypress/step-definitions/[filepart].{js,ts}`

As `[filepart]` no longer returns the file's name (minus extention) and the parent folder, without changing the package I can't see how to achieve a `nonGlobalStepDefinitions` style structure. 

If this was intentional, would you be against me raising an PR to add a third option (ie: `[relpart]`* ) that would function like the old filepart; ` [ 'authentication/user-registration', 'user-registration' ]`. 

   `* I couldn't come up with a better name.

**Comment by princefishthrower** [comment]
@mike-mccormick - I guess you are keeping your files within the `cypress/` folder? Just curious if you had any insight into my question 😄 

Sometimes I wish this library would just have two required config parameters `featureFilePaths` and `testFilePaths`... none of this hardcode or default assumption stuff

**Comment by mike-mccormick** [comment]
@princefishthrower yep! 

![image](https://user-images.githubusercontent.com/2361501/175927755-25e56004-ab04-4493-b5c7-297da3ca8c12.png)

I like keeping all of the test-specific stuff inside the `cypress` folder. 

We have our integration tests subfolder set up like a top-level project, so alongside the `cypress` folder is vscode workspace settings,  eslint rules, prettier config etc, so it's already pretty busy. 


![image](https://user-images.githubusercontent.com/2361501/175929118-4e5d1b45-3494-46a2-bb11-c48f60ae17ca.png)

**Comment by badeball** [comment]
@princefishthrower, no, the preprocessor doesn't understand that you want to simply disregard the `features/` part of paths and instead look in `__tests__`. This is a use-case I am considering.

@mike-mccormick, I don't know which change you're referring to, so you have to put together an example that shows me what used to work and what now doesn't.

@princefishthrower, lmao, you don't know what you're talking about.

**Comment by mike-mccormick** [comment]
@badeball will do, I'll create a new issue when I've something set up to demonstrate, thanks :)

**Comment by princefishthrower** [comment]
lmao, I actually do know what I'm talking about. Weird.

Finally got this working. When using TypeScript, you need to be sure your cypress config has at least the following from the example: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/browserify-ts/cypress.config.ts

Then, instead of taking all feature files in the cypress config, i.e. `specPattern: "**/*.feature"`, specify where your e2e-specific feature files are. (In my case `specPattern: "features/e2e/**/*.features"`):

```typescript
import { defineConfig } from "cypress"
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor"
import browserify from "@badeball/cypress-cucumber-preprocessor/browserify";

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
  await addCucumberPreprocessorPlugin(on, config)

  on(
    "file:preprocessor",
    browserify(config, {
      typescript: require.resolve("typescript"),
    })
  )

  on("before:browser:launch", (browser, launchOptions) => {
    if (browser.name === "chrome") {
      launchOptions.args.push("--lang=en-US")
      return launchOptions
    }
  })

  // Make sure to return the config object as it might have been modified by the plugin.
  return config
}

export default defineConfig({
  projectId: "e846ib",
  e2e: {
    specPattern: "features/e2e/**/*.feature", // CHANGED
    supportFile: false,
    setupNodeEvents,
  },
})
```

Then within `.cypress-cucumber-preprocessorrc.json`, set the location to your corresponding definitions (in my case `__tests__/e2e/**/*.ts`):

```json
{
  "stepDefinitions": "__tests__/e2e/**/*.ts"
}
```

So actually what I was wondering / requesting _does_ work out of the box, I just had some issue understanding the file path definition documention, and also missed the new way to define `cypress.config.ts` - I had the old way still from `TheBrainFamily`

Would be nice to have an example where both the feature and test folders lie both outside and in separate folders than the `cypress/` folder somewhere in the docs 👍 

Hopefully, this helps someone in the future.
