### ISSUE TITLE
Common steps feature is not working

### ISSUE THREAD

**Issue by CharalamposSam** [badeball/cypress-cucumber-preprocessor#745]
### Current behavior
I have downloaded the project of Alapan, from the following link:
https://github.com/alapanme/Cypress-Automation
I executed "login.feature" test scenario and is working fine.

![scenarioWorking](https://user-images.githubusercontent.com/44839448/175320710-f75ca1bb-0c02-4d3b-9420-88456bee8c08.png)

I have added a common folder under the e2e folder and inside that I have add a common.js file.
Inside common.js, I have import cucumber and added the first step from the scenario (meaning that this step does not exist anymore at login.js)

![commonJS](https://user-images.githubusercontent.com/44839448/175321068-d5e4efd8-fa8e-43da-8213-1708fdaedeb6.png)

Executing the scenario again, this is what I get:

![scenarioNotWorking](https://user-images.githubusercontent.com/44839448/175326148-d0e85d13-ea41-4189-a769-617d07b2186f.png)

### Desired behavior

This should be working, as it was working before Cypress 10
### Versions

* **Cypress version**: 10.2.0
* **Preprocessor version**: 11.0.0
* **Node version**: 16.15.1

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Given that you're following @alapanme's examples, I think you should ask them about the issue. Open up a ticket in their tracker.

**Comment by CharalamposSam** [comment]
@badeball the provided code is just an example. If you need from me to upload my own example, no problem.
The question is if the "Common Steps" feature exists in version 11.0.0 for Cypress 10.
If yes, does it have different syntax from version 4.3.1?
If no, will it be implemented?

Thank you in advance.

**Comment by badeball** [comment]
These questions are answered in #689 (Upgrade guide from `TheBrainFamily/cypress-cucumber-preprocessor`). TLDR: Yes, you can still have common steps.

**Comment by uaru** [comment]
I am quite confused, too, and I did not manage to get the common steps to work.

**Comment by badeball** [comment]
I might be able to help if you provide me a reproducible example, IE. a Git repo.

**Comment by tinu-harbr** [comment]
@uaru I have below snippet on my `package.json`. My common step definitions are under` cypress/e2e/common/` folder and feature specific steps are under **sub folder** on `cypress/e2e/features/`. 

```
 "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": [
      "cypress/e2e/common/*.{js,ts}",
      "cypress/e2e/features/**/*.{js,ts}"
    ]
  },
```

**Comment by fras2560** [comment]
I am running into a situation where a global step is missing implementation in one test and another global step (in same file) is used in another test. Any idea on what I could be doing wrong? I added the file quite explicitly to the step definitions.

```
  "stepDefinitions": [
    "[filepath]/**/*.{js,ts}",
    "[filepath].{js,ts}",
    "cypress/features/global/**/*.{js,ts}",
    "cypress/features/global/login.{js,ts}"
  ]
```

EDIT

I was able to figure out the issue. The one test imported from the file with the global steps and other did not import. I am using webpack. Hope this helps if anyone else runs into the issue.

**Comment by badeball** [comment]
@fras2560, you're making it impossible for me to help you. You have to show me an example that I can correct (and don't make it difficult by doing that with screenshots or large bodies of code, give me a cloneable repository that illustrates your folder structure).

**Comment by uaru** [comment]
Thank you, @tinu-harbr. I copied your snippet. I think I had something similar before, but this time it worked. 

I extracted the configuration and example from my project, if anyone is interested.

https://github.com/uaru/cypress-config-example.git
