### ISSUE TITLE
How to generate cucumber HTML reports in new version @badeball ? 

### ISSUE THREAD

**Issue by hdabas2** [badeball/cypress-cucumber-preprocessor#746]
<img width="1566" alt="Screenshot 2022-06-24 at 11 47 42 AM" src="https://user-images.githubusercontent.com/67456583/175474751-3dbbdfee-f22d-430a-abc1-43ceadce0319.png">

I can see multiple videos or examples how to generate this kind of HTML report in Cypress - cucumber for older versions.

 **But in new version of cucumber integration - [badeball]/[cypress-cucumber-preprocessor] how can i integrate the same ? Any leads**

**Comment by badeball** [comment]
This isn't really something I can help you with.

However, if someone knows of any good resources then I might be able create a link collection in the docs.

**Comment by jwmickey** [comment]
This looks like a screenshot from the Jenkins cucumber plugin.  You will need to do a few things:

1. Be sure to call `addCucumberPreprocessorPlugin(on, config)` in your plugins file.
2. You need to have the [cucumber-json-formatter](https://github.com/cucumber/json-formatter) executable downloaded.  In Jenkins I added this as a stage which downloads the file from some known location and places it in the workspace.  The plugin looks for it in the $PATH by default, but you can customize the location when running cypress via `--env.jsonFormatter=path/to/formatter/file`
3. When running cypress you need to enable json reports, one way is via env params: `--env.jsonEnabled=true`.  If the cucumber-json-formatter is not in the $PATH, then you can specify the location the same way:  This is what tells the plugin to convert to cucumber-report.json.
4. Finally, in your pipeline, you can add a stage or post to call the cucumber plugin.  Docs for this are available at https://plugins.jenkins.io/cucumber-reports/#plugin-content-pipeline-usage

**Comment by michaelsc93** [comment]
Hi @hdabas2 , this issue may also help you to configure your reporting
https://github.com/badeball/cypress-cucumber-preprocessor/issues/755

**Comment by dadiaz18** [comment]
Hi! after I used another version and didn't have problems using, for example, mochawesome reports, do you know any way to configure the same type of reports using this badeball version? I can't generate reports using this version.

**Comment by badeball** [comment]
I can't imagine that compatibility with `mochawesome` has changed between the recent versions. Feel however free to show me otherwise.

**Comment by badeball** [comment]
I found that integrating with `@cucumber/html-formatter` was quite easy and plan to add native support for it with v12. Eager users can however install 12.0.0-rc1 (with [changelog](https://github.com/badeball/cypress-cucumber-preprocessor/blob/v12/CHANGELOG.md) and updated [docs](https://github.com/badeball/cypress-cucumber-preprocessor/tree/v12/docs)) and try it out immediately, as shown below.

```
$ npm i @badeball/cypress-cucumber-preprocessor@12.0.0-rc1
```

**Comment by dadiaz18** [comment]
@badeball I installed version 12.0.0-rc1, which is incredible; Regarding `mochawesome` I only tested a little bit it is probably a problem with my configuration because I was able to see the title of the scenarios, but never saw the steps, only the code executed in the background.

**Comment by KyleVassella** [comment]
@hdabas2 This YouTuber has new content regarding Cypress 10 + @badeball/cypress-cucumber-preprocessor HTML Reports: https://www.youtube.com/watch?v=5AGXK9cL2fs

**Comment by badeball** [comment]
HTML reports are now natively supported through `@cucumber/html-formatter`, see [docs/html-report.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/html-report.md).

Users wanting to use [mochawesome](https://www.npmjs.com/package/mochawesome), [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter) or [multiple-cucumber-html-reporter](https://www.npmjs.com/package/multiple-cucumber-html-reporter) can continue to do so as before, but this isn't a support forum for either of those. Feel free to discuss either of them, but don't expect my involvement.
