### ISSUE TITLE
a feature.ts  before() runs as many as there are features 

### ISSUE THREAD

**Issue by aomaryus** [badeball/cypress-cucumber-preprocessor#747]
### Current behavior
This used to work before migrating
I have the following tree:
cypress/e2e/.../

feature_01/
.... feature_01.ts
feature_01.feature

feature_02/
.... feature_02.ts
feature_02.feature

feature_10/
.... feature_10.ts
feature_10.feature

...
...

The each feature_NN.ts contains:
before(() => {
  cy.login();
});

When I run the feature_10.feature, I see cy.login() running in BEFOREALL(1) to  BEFOREALL(10) feature

This the preprocessor config:
module.exports = {
  nonGlobalStepDefinitions: true,
  stepDefinitions: 'cypress/e2e/**/*.ts',
  commonPath: 'cypress/e2e/common/**/*.ts'
};

tried with both true and false for nonGlobalStepDefinitions

### Desired behavior

Only the feature*.ts that contains the login should be the only executed 
### Versions

* **Cypress version**:
* Cypress package version: 10.2.0
* **Preprocessor version**:
* @badeball/cypress-cucumber-preprocessor@11.3.0
* **Node version**:
λ node --version
v16.13.1
### Checklist

- [yes] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [yes] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ yes] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).
![repeated_before()](https://user-images.githubusercontent.com/4463080/175820134-e55f5403-d73d-46cb-ae2b-7e4dac86b910.png)

**Comment by badeball** [comment]
Try something like

```json
{
  "stepDefinitions": "[filepath]/*.{js,ts}"
}
```

**Comment by aomaryus** [comment]
![Screen Shot 2022-06-26 at 10 51 47 PM](https://user-images.githubusercontent.com/4463080/175851162-8e7f1e14-8997-4367-8231-14b8d4700f16.png)
I changed it to:
module.exports = {
  stepDefinitions: '[filepath]/*.{js,ts}'
};

I am able to login() but now I cannot find the definitions for other steps 

It says for example:
Step implementation missing for: user sees cloud inventory
and the definition lives here:
../cypress/e2e/common/public_cloud/dashboard.ts
Appreciate your help.

**Comment by aomaryus** [comment]
I followed the instructions here as well  - same error 
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md

**Comment by badeball** [comment]
Then try something like

```
{
  "stepDefinitions": ["[filepath]/*.{js,ts}", "cypress/e2e/common/**/*.{js,ts}"]
}

**Comment by aomaryus** [comment]
Thank you.
So the change above just worked for that particular feature :)
When I added the rest as below, I am getting the situation where the login() gets executed repeatedly. 

module.exports = {
  nonGlobalStepDefinitions: true,
  json: {
    enabled: true
  },

  stepDefinitions: [
    '[filepath]/*.ts',
    'cypress/e2e/common/**/*.ts',
    'cypress/e2e/shared_features/**/*.ts',
    'cypress/e2e/authenticated_user/**/*.ts',
    'cypress/e2e/public_cloud/**/*.ts',
    'cypress/e2e/private_cloud/**/*.ts',
    'cypress/e2e/network_cloud/**/*.ts',
    'cypress/e2e/role_manager/**/*.ts'
  ]
};

I read issue 9 above and was wondering if I should wait a bit since already spent a lot of time on this particular item.

Thanks.

**Comment by badeball** [comment]
I don't really know what to say here.. You don't seem to grasp search patterns, you're not doing what I told you and the configuration isn't at all of what it should ever be.

I'm not going guess anymore, either show me an example that I can correct or figure it out yourself, because I'm not going to continue this back-and-forth thing.

**Comment by badeball** [comment]
When you outline an example for me, don't make it difficult by doing that with screenshots or large bodies of code, give me a cloneable repository that illustrates your folder structure.

**Comment by aomaryus** [comment]
The specPattern seems to have lost the '**' above for some formatting issues: 
Let me paste again below:
stepDefinitions: [
'[filepath]/*.{js,ts}',
'cypress/e2e/common/**/.ts',
'cypress/e2e/shared_features/**/*.ts',
'cypress/e2e/authenticated_user/**/.ts',
'cypress/e2e/public_cloud/**/.ts',
'cypress/e2e/private_cloud/**/*.ts',
'cypress/e2e/network_cloud/**/.ts',
'cypress/e2e/role_manager/**/.ts'
]
};

Here is my tree structure:
λ tree -L 2 cypress
cypress
|-- README.md
|-- e2e
|   |-- authenticated_user
|   |-- authenticated_user.feature
|   |-- common
|   |-- network_cloud
|   |-- private_cloud
|   |-- public_cloud
|   |-- role_manager
|   `-- shared_features
|-- fixtures
|   |-- monitored_environments
|   `-- props.json
|-- plugin
|   `-- index.ts
|-- support
|   |-- commands.ts
|   |-- e2e.ts
|   |-- helpers.ts
|   `-- pages
|-- tsconfig.json
`-- user-configs

I will try to create a testable repo, but would appreciate it if you take one more look . Thank you.

**Comment by aomaryus** [comment]
`tree 
λ tree -L 2 cypress
cypress
|-- README.md
|-- e2e
|   |-- authenticated_user
|   |-- authenticated_user.feature
|   |-- common
|   |-- network_cloud
|   |-- private_cloud
|   |-- public_cloud
|   |-- role_manager
|   `-- shared_features
|-- fixtures
|   |-- monitored_environments
|   `-- props.json
|-- plugin
|   `-- index.ts
|-- support
|   |-- commands.ts
|   |-- e2e.ts
|   |-- helpers.ts
|   `-- pages
|-- tsconfig.json
`-- user-configs

`

**Comment by aomaryus** [comment]
Please ignore the above. I will create a testable repo. Apparently the text I put gets malformed. I will close this issue and recreate it.
