### ISSUE TITLE
Second retry skip

### ISSUE THREAD

**Issue by Clement398** [badeball/cypress-cucumber-preprocessor#749]
### Current behavior

The second retry is systematically considered OK even when it should be KO.

<img width="634" alt="Capture d’écran 2022-06-28 à 17 41 30" src="https://user-images.githubusercontent.com/90264924/176222506-f3148f9b-6448-4593-b73a-96fe850a171c.png">

### Desired behavior

I expect the second retrie to work the same as the first one.

### Test code to reproduce

https://github.com/Clement398/Bug

### Versions

* **Cypress version**: 10.2.0
* **Preprocessor version**: 11.3.0
* **Node version**: 16.15.1

**Comment by badeball** [comment]
Hey, @Clement398, thanks for reporting the issue. I've fixed it with v11.3.1.
