### ISSUE TITLE
stepDefinitions issue

### ISSUE THREAD

**Issue by aomaryus** [badeball/cypress-cucumber-preprocessor#750]
### Current behavior
I have a before() that has cy.login() 
The login is run for every feature when only one feature is selected

### Desired behavior
before() should only run for the selected feature

### Test code to reproduce
https://github.com/aomaryus/stepDefintionsIssue

### Versions

* **Cypress version**: 10.3
* **Preprocessor version**: 11.3.1
* **Node version**: v12.22.7

### Checklist

- [ yes ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ yes ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ yes ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
What is the purpose of `cypress/e2e/common.feature` in the example?

**Comment by aomaryus** [comment]
I removed it. Was there by mistake. e2e/common should only hold common code step definitions

**Comment by JomyGeo** [comment]
@badeball  I am facing the same issue while executing a specific feature.  All Hooks (Before,beforeEach) are executed as the first step which is nowhere related to the selected feature file.

**Comment by badeball** [comment]
This patch fixes it.

```patch
diff --git a/cypress-cucumber-preprocessor.config.js b/cypress-cucumber-preprocessor.config.js
index 20c548d..c00dd4e 100644
--- a/cypress-cucumber-preprocessor.config.js
+++ b/cypress-cucumber-preprocessor.config.js
@@ -1,3 +1,3 @@
 module.exports = {
-  stepDefinitions: ['[filepath]/*.ts}', 'cypress/e2e/**/*.ts']
+  stepDefinitions: ['[filepart]/!(cypress.config).ts', 'cypress/e2e/common/**/*.ts']
 };
```

**Comment by badeball** [comment]
@JomyGeo, you've misconfigured `stepDefinitions` to include all steps no matter what test is selected, thus including every hook.

**Comment by aomaryus** [comment]
Hi 
I tried the fix above and still see the issue
```
λ cat cypress-cucumber-preprocessor.config.js
module.exports = {
  stepDefinitions: ['[filepart]/!(cypress.config).ts', 'cypress/e2e/common/*.ts']
};
```

Also I think his path:
`cypress/e2e/common/*.ts
`
is not sufficient - as you can see, the are definitions in cypress/e2e/**
I am not sure what to do. I have a heavily nested tree structure and it appears I have to figure out correct step Definitions path. Appreciate any help
<img width="652" alt="Screen Shot 2022-06-30 at 3 21 44 PM" src="https://user-images.githubusercontent.com/4463080/176762874-7a3fe64f-3b3d-410c-88e9-c86fb52c837f.png">

**Comment by badeball** [comment]
Well, in `management.feature` you're referencing a step definition in `public.ts`, so what do you really want here?

**Comment by badeball** [comment]
You're also misunderstanding entirely the purpose `[filepath]` and `[filepart]` in the search pattern. They do _something_, IE. `cypress/e2e/common/*.ts` isn't the only pattern resolving to step definitions.

**Comment by aomaryus** [comment]
> Well, in `management.feature` you're referencing a step definition in `public.ts`, so what do you really want here?

This means that the management.feature needs a step that is already defined in parent. This is not new stuff. It is also possible to have another directory inside management that uses steps from both management and  public.

We cannot have all steps define in common.

**Comment by aomaryus** [comment]
> You're also misunderstanding entirely the purpose `[filepath]` and `[filepart]` in the search pattern. They do _something_, IE. `cypress/e2e/common/*.ts` isn't the only pattern resolving to step definitions.

Help me understand what you mean. What else would the pattern above include from my sample project. 
I doubt if these are included in `cypress/e2e/common/*.ts`
`cypress/e2e/public/**/*.ts
 cypress/e2e/private/**/*.ts
cypress/e2e/network/**/*.ts`

I checked with colleagues and they are having the same issues and unable to upgrade.

What if you tweak my project and test it. I will share your insight with others in my org.

Lastly, I tried DEBUG=cypress:* to see if I can find an expansion for the stepDefinitions but there was none. Is there a way to see it?

Thank you.

**Comment by badeball** [comment]
> Lastly, I tried DEBUG=cypress:* to see if I can find an expansion for the stepDefinitions but there was none. Is there a way to see it?

There's a debug statement mentioned in "Instructions for logging issues", linked in your original post.

**Comment by badeball** [comment]
> This means that the management.feature needs a step that is already defined in parent. This is not new stuff. It is also possible to have another directory inside management that uses steps from both management and public.

That's fine, but if you in `management.feature` want to have available public's steps, then you also get public's before hooks.

**Comment by aomaryus** [comment]
Hi
I needed to recreate the issue. Other folks could not find it.
I have removed the reference to public step but the issue is still there.

Thank you.
