### ISSUE TITLE
Unable to use env variables in test configurations in new cypress cucumber preprocess

### ISSUE THREAD

**Issue by AmiChandra89** [badeball/cypress-cucumber-preprocessor#751]
### Current behavior

I am unable to use the environment variables which are passed in test configuration. For example: I was able to set env variables in Given earlier but now it throws an error
![Screenshot 2022-06-30 at 16 01 47](https://user-images.githubusercontent.com/43046348/176697340-1c2827eb-ea68-4111-827b-8528969f7b6d.png)
![Screenshot 2022-06-30 at 16 03 28](https://user-images.githubusercontent.com/43046348/176697458-bb73f445-05e2-4f32-bed4-e088fdb469e7.png)

### Desired behavior

I should be able to use environment variables passed in each test.

### Versions

* **Cypress version**:10.3.0
* **Preprocessor version**:11.3.1
* **Node version**:14.18.0

### Checklist

- [Yes ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [Yes ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ Yes] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
>  I was able to set env variables in Given earlier but now it throws an error

In what version was this possible?

**Comment by AmiChandra89** [comment]
It was possible in Cypress version 4.3.0. I upgraded my Cypress version to 10.3.0 and cypress-cucumber-preprocessor versions today. If I remove the env variables, it is working fine.

**Comment by badeball** [comment]
A step definition isn’t a test, so specifying test-specific configuration there doesn’t make any sense. I have a hard time believing that this was ever possible.

**Comment by AmiChandra89** [comment]
Well, it was working before. I thought of doing it after reading this article and it worked:
https://docs.cypress.io/guides/guides/environment-variables#Option-5-Test-Configuration
It may not be the same and may not be logical as well.
I do not mind if you close this issue as not an issue. I will find a way around.

**Comment by badeball** [comment]
The method signatures of `it()` and `Given()` aren't the same and they simply can't be. I newly implemented support for test-specific configuration through tags though, illustrated in [docs/test-configuration.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/test-configuration.md). Even though configuring env isn't shown, you can still try EG. `@env(foo='bar')`.
