### ISSUE TITLE
Bring back Bundled.features

### ISSUE THREAD

**Issue by Tastebuder** [badeball/cypress-cucumber-preprocessor#752]
I'm using TypeScript & Webpack and bundled features shaved off 40% from build time because the browser didn't have to keep opening and closing between tests.

**Comment by badeball** [comment]
Thanks for your suggestion, but this isn't something I'd like see solved by a preprocessor.

**Comment by Tastebuder** [comment]
Hey, sorry just one more question, who do you think should solve this problem?

It not only makes the tests run 40% faster it also makes the spec output much cleaner and if any errors occur they are grouped at the bottom for ease of access.

**Comment by badeball** [comment]
Cypress should solve this and not every preprocessor in their own, unique way.

**Comment by Tastebuder** [comment]
But Cypress doesn't support cucumber or feature files which is why this preprocessor exists right?

**Comment by badeball** [comment]
This isn't a discussion. Cypress opens and closes browsers between each spec and this affects output, completely independent of whether you use this preprocessor or not. If you think that's undesirable then you should open up a ticket with them.
