### ISSUE TITLE
hooks() run even when they are not associated with a given feature

### ISSUE THREAD

**Issue by aomaryus** [badeball/cypress-cucumber-preprocessor#753]
### Current behavior
a before() hook run even though it is not associated with the running feature

### Desired behavior
Hooks should only run for the running feature 

### Test code to reproduce
https://github.com/aomaryus/stepDefintionsIssue

### Versions

* **Cypress version**: cypress@10.3.0
* **Preprocessor version**:@badeball/cypress-cucumber-preprocessor@11.3.1
* **Node version**:v12.22.7

### Checklist

- [ Yes ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ Yes ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ Yes ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by aomaryus** [comment]
<img width="645" alt="Screen Shot 2022-07-01 at 8 46 26 AM" src="https://user-images.githubusercontent.com/4463080/176898474-072648f0-12cb-4874-a6d7-b78394ddb2ea.png">

**Comment by badeball** [comment]
```patch
diff --git a/cypress-cucumber-preprocessor.config.js b/cypress-cucumber-preprocessor.config.js
index c00dd4e..890ed99 100644
--- a/cypress-cucumber-preprocessor.config.js
+++ b/cypress-cucumber-preprocessor.config.js
@@ -1,3 +1,3 @@
 module.exports = {
-  stepDefinitions: ['[filepart]/!(cypress.config).ts', 'cypress/e2e/common/**/*.ts']
+  stepDefinitions: ['[filepath]/*.ts', 'cypress/e2e/common/**/*.ts']
 };
```
