### ISSUE TITLE
Add dry run feature

### ISSUE THREAD

**Issue by Narcalen** [badeball/cypress-cucumber-preprocessor#754]
Would be nice to have dry run feature similar to cucumber-js ([doc](https://github.com/cucumber/cucumber-js/blob/main/docs/dry_run.md))

**Comment by badeball** [comment]
Hi, @Narcalen, I like the idea. Which use-cases specifically are you looking to see solved with this?

**Comment by Narcalen** [comment]
Hi @badeball,
I would like to set up PR checks for our automated test framework to make sure that all steps in feature files are implemented, otherwise fail the build. Dry run should be faster than running the tests.

**Comment by badeball** [comment]
I've introduced a diagnostics utility with v13.0.0, read more about it in [docs/diagnostics.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/diagnostics.md). Please try it out and provide feedback.

NB: This is as experimental as it gets.

**Comment by Narcalen** [comment]
The feature is working as expected, thanks! 
its performance is suboptimal though: for a set of 58 feature files, dry run executes for 80 minutes, and if diagnostics utility is applied for each feature file in loop, it takes 3 minutes to complete the dry run.

**Comment by badeball** [comment]
Ouf. I tried it on a relatively medium project of mine own, but apparently didn't encounter such terrible performance. I'm guessing I've implemented something with `O(n^2)` runtime or similar.

**Comment by badeball** [comment]
Eh, it turns out that cli-table3 is actually the culprit, ref. https://github.com/cli-table/cli-table3/issues/68....

**Comment by badeball** [comment]
I've released v13.0.3 which contains some improvements, including replacing cli-table3. Please try it out.

**Comment by Narcalen** [comment]
Ran diagnostics in v13.0.3, performance is good now:
real    0m6.291s
user    0m12.305s
sys     0m1.446s

Thanks!
