### ISSUE TITLE
Configurations for using a custom JSON Formatter

### ISSUE THREAD

**Issue by michaelsc93** [badeball/cypress-cucumber-preprocessor#755]
### Current behavior

JSON Formatter is required to be installed by anyone who wishes to use the reporting functionality. This adds an additional installation step / dependency to any machine running tests. It also seems to tightly couple JSON generation with the preprocessor.

### Desired behavior

A way to add a custom JSON formatter other than the required Standalone executable one. 

This could be a configuration option that would allow the user to only generate the .ndjson file before running their own formatting process once the preprocessor has finished?

After reading the docs I did try to achieve this with json.args: ["custom-formatter.js"] but couldn't find supporting documentation for that option. I also ran into the ENOENT issue from the FAQ (where the Standalone Cucumber JSON Formatter is being searched for, even with the formatter variable set in package.json).

I used many variations of the config "json.enabled" "json.args", "json.formatter", "json.output" options but was unable to get a .ndjson without triggering the search for the standalone formatter executable.
EG:
`    "json": {
      "enabled": true,
      "args": ["cucumber-report-json-formatter.js"],
      "output": "cucumber-report.json"
    }
`

`    "json": {
      "enabled": true,
      "args": ["cucumber-report-json-formatter.js"],
      "formatter": "/formatter/",
      "output": "cucumber-report.json"
    }
`
etc..

### Versions

* **Cypress version**: 10.3.0
* **Preprocessor version**: 11.4.0
* **Node version**: 14.19.3

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
There's a lot of things to address here..

If you only require the NDJSON output, you can simply configure `{ "messages": { "enabled": true } }` and that's it. Then you have a NDJSON file, without the need of external dependencies.

Configuring `{ "json": { "formatter": "/formatter/" } }` is _never_ correct, because you have no executable named `/formatter/` on your system (I checked).

If you want to process the NDJSON using a custom JS-script, you can configure `{ "json": { "enabled": true, "formatter": "node", "args": ["cucumber-report-json-formatter.js"] } }`.

Edit: You can probably also create an executable script with a shebang and configure something like `{ "json": { "enabled": true, "formatter": "./cucumber-report-json-formatter.js" } }`.

**Comment by michaelsc93** [comment]
Thanks @badeball I got it working. 

For anyone in future, I am using the npm package cucumber-json-report-formatter (https://github.com/Vitalizzzer/cucumber-json-report-formatter) to avoid the .exe installation.

With that package, I wrote a short script to operate the formatter (report-formatter.js):
```
const Formatter = require('cucumber-json-report-formatter').Formatter;

const formatter = new Formatter();
const sourceFile = "./cucumber-messages.ndjson"
const outputFile = "./formatted-json/cucumber-report.json"

formatter.parseCucumberJson(sourceFile, outputFile);
```

And then with configuration:
```
  "cypress-cucumber-preprocessor": {
    "stepDefinitions": [
      "cypress/stepDefinitions/*.steps.js"
    ],
    "json": {
      "enabled": true,
      "formatter": "node",
      "args": ["report-formatter.js"],
      "output": "formatted-json/latestFormatProcess.log"
    }
  }
```
Final step is a command to run my html report which is user preference.

Thanks again!

**Comment by Abo-Mamdouh** [comment]
@michaelsc93 
I used npm package cucumber-json-report-formatter 
and i have this package now,
but in which file should i write the short script?

```
const Formatter = require('cucumber-json-report-formatter').Formatter;

const formatter = new Formatter();
const sourceFile = "./cucumber-messages.ndjson"
const outputFile = "./formatted-json/cucumber-report.json"
formatter.parseCucumberJson(sourceFile, outputFile);
```

<img width="317" alt="Screenshot 2022-07-11 at 10 40 11" src="https://user-images.githubusercontent.com/93645203/178223882-047ef2d5-cd2b-4ee4-98be-ad5fd81335ec.png">
?

**Comment by michaelsc93** [comment]
@ahmad-alsermany You can make it as a new .js file. If you put the new file in your root directory then the cucumber-preprocessor config in package.json would be 
```
 "cypress-cucumber-preprocessor": {
    "stepDefinitions": [
      "cypress/stepDefinitions/*.steps.js"
    ],
    "json": {
      "enabled": true,
      "formatter": "node",
      "args": ["fileName.js"],
    }
  }
```
Replace "fileName.js" with whatever you called your file

**Comment by Abo-Mamdouh** [comment]
@michaelsc93 
I did exactly what you said, but in the file `report-formatter.js` is one warning
![Screenshot 2022-07-12 at 10 30 20](https://user-images.githubusercontent.com/93645203/178446396-355c9d5d-97cc-490b-8918-a5587b7bd982.png)
.


my report-formatter.js:
```
const Formatter = require('cucumber-json-report-formatter').Formatter;

const formatter = new Formatter();
const sourceFile = "./cucumber-messages.ndjson"
const outputFile = "./cucumber-report.json"

formatter.parseCucumberJson(sourceFile, outputFile);
```


package.json:
```
"cypress-cucumber-preprocessor": {
    "stepDefinitions": [
      "cypress/e2e/**/*.{js,ts}"
    ],
    "json": {
      "enabled": true,
      "formatter": "node",
      "args": [
        "report-formatter.js"
      ]
    }
  },
```

and I have these 2 files:
![Screenshot 2022-07-12 at 10 33 24](https://user-images.githubusercontent.com/93645203/178447017-1d8dce56-6c9c-4a7b-b850-0ec390d37e59.png)

but the `cucumber-report.json` is still empty.


I tried to use `await ` with `formatter.parseCucumberJson(sourceFile, outputFile);`
but still dosn't work!

What i should do?!

**Comment by oguzhantx** [comment]
I think you should update your outputFile location. When you run test, it creates a cucumber-report.json file that just has general information about process not an actual json file. content of that file should look something like this. 
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/94402055/178821193-0f905b33-7bd4-47a5-b931-0883cbd23d00.png">

then your actual .json report should be in your outputFile location.

**Comment by oguzhantx** [comment]
> Thanks @badeball I got it working.
> 
> For anyone in future, I am using the npm package cucumber-json-report-formatter (https://github.com/Vitalizzzer/cucumber-json-report-formatter) to avoid the .exe installation.
> 
> With that package, I wrote a short script to operate the formatter (report-formatter.js):
> 
> ```
> const Formatter = require('cucumber-json-report-formatter').Formatter;
> 
> const formatter = new Formatter();
> const sourceFile = "./cucumber-messages.ndjson"
> const outputFile = "./formatted-json/cucumber-report.json"
> 
> formatter.parseCucumberJson(sourceFile, outputFile);
> ```
> 
> And then with configuration:
> 
> ```
>   "cypress-cucumber-preprocessor": {
>     "stepDefinitions": [
>       "cypress/stepDefinitions/*.steps.js"
>     ],
>     "json": {
>       "enabled": true,
>       "formatter": "node",
>       "args": ["report-formatter.js"],
>       "output": "formatted-json/latestFormatProcess.log"
>     }
>   }
> ```
> 
> Final step is a command to run my html report which is user preference.
> 
> Thanks again!

were you able to get it working properly for multiple feature files. In my case, formatted json file only includes test details for first test file and ignores the rest.

**Comment by JomyGeo** [comment]
@oguzhantx @badeball   I could not generate the report(CUCUMBER-REPORT.JSON) if I am adding the below code in my index.js. 

In my case, I want to show additional details in the custom data section of the report which i can get from the cypress result JSON file. Please do let me know how to handle it

Note : Report is working fine if I don't use the below code in index.js. CUCUMBER-REPORT.JSON generated properly 


 on('after:run', (results) => {
    if (results) {
      fs.mkdirSync("cypress/.run", { recursive: true });
      fs.writeFile("cypress/.run/results.json", JSON.stringify(results));
    }
  })
