### ISSUE TITLE
Unable to run the Cypress cucumber test's with V10 in circleci  

### ISSUE THREAD

**Issue by kdubakun** [badeball/cypress-cucumber-preprocessor#756]
### Current behavior

Unable to run the cucumber tests with latest cypress version via any CI/CD tool.

Error: We've tried to resolve your step definitions at cypress/integration, but that doesn't seem to exist. As of version 2.0.0 it's required to set step_definitions in your cypress-cucumber-preprocessor configuration. Look for nonGlobalStepDefinitions and add stepDefinitions right next to it. It should match your cypress configuration has set for integrationFolder. We no longer rely on getting information from that file as it was unreliable and problematic across Linux/MacOS/Windows especially since the config file could have been passed as an argument to cypress.

Found a fix manually: https://stackoverflow.com/questions/72582109/configure-cypress-cucumber-preprocessor-with-cypress-10-in-angular

but how to handle it in CI/CD tools like circleCI ? 

### Versions

* **Cypress version**: 10.3.0
* **Preprocessor version**: 4.3.1
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> ### Checklist
> - [ ] I'm not using cypress-cucumber-preprocessor@4.3.1 (package name has changed and it is no longer the most recent version, see https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).
