### ISSUE TITLE
Add 'BeforeAll' hook

### ISSUE THREAD

**Issue by sszemer** [badeball/cypress-cucumber-preprocessor#758]
### Current behavior
**'Before' and 'After' hook names are missleading**
from wiki:
`
"Before() and After() is similar to Cypress' beforeEach() and afterEach()"
`

### Desired behavior

i want some code to run only once for all tests. in cypress i would do something like:
`
  before(() => {
    // runs once before all tests in the block
  })
`
in preprocessor the name is confusing as it suggests running once.

it would be preferable to change 'Before' to 'BeforeEach' and make 'Before' behave in a way that it only runs once per test run

`
Before({ tags: "@foo" }, function () {
  // This hook will be executed once before all scenarios tagged with @foo.
});
`

`
BeforeEach({ tags: "@foo" }, function () {
  // This hook will be executed before each scenario tagged with @foo.
});
`

### Test code to reproduce

`Before({ tags: "@foo" }, function () {
  // This hook will be executed before scenarios tagged with @foo.
});`

### Versions

* **Cypress version**:
* 9.7.0
* **Preprocessor version**:
* 4.0.1
* **Node version**:
*v16.15.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> i want some code to run only once for all tests. in cypress i would do something like:
> `before(() => { // runs once before all tests in the block })`
> in preprocessor the name is confusing as it suggests running once.

You can still do this. `After` and `Before` aren't there to replace Cypress' own hooks, but to replicate behavior seen in `cucumber-js`.

> `Before({ tags: "@foo" }, function () { // This hook will be executed once before all scenarios tagged with @foo. });`

This doesn't exist in `cucumber-js`, thus it will not exist here.

**Comment by jljouannic** [comment]
I think it *does* exist in cucumber-js. There are two hooks `BeforeAll` and `AfterAll` which are not supported in cypress-cucumber-preprocessor but would deserve to be: https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/hooks.md#beforeall--afterall

**Comment by badeball** [comment]
You're right, these aren't implemented but should be. I can't look into it now, contributions are welcome.

**Comment by lotmek** [comment]
Since the feature is about adding some setup before or after the run, would'nt it be better if we allow the users to add some customized callback inside the Cypress `after:run` & `before:run` events ?

https://github.com/badeball/cypress-cucumber-preprocessor/blob/5dc7de975cceb7ac4eacf7a7fa257d85443798f1/lib/add-cucumber-preprocessor-plugin.ts#L89-L95

**Comment by badeball** [comment]
@lotmek, this is already possible through the API that was devised before the existence of `cypress-on-fix` and is described [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md#workaround-2--2).

As for the original proposal, a `BeforeAll(..)` hook as seen in cucumber-js, would not support any tags argument, nor be provided a world context. Additionally it would have no impact on any report generation, as least not as of [yet](https://github.com/cucumber/messages/pull/102). It would probably be a simple wrapper around Cypress' own `before(..)` hook and not allow anything that isn't already possible in user-land. Thus, I suspect that the desire for this stem from a misunderstanding. However, I'm inclined to add it for consistency.

**Comment by VidhiRambhia** [comment]
Hi, 

I'm interested in contributing. Can I pick this up?

**Comment by badeball** [comment]
You may. I recommend starting by looking at it as it exist in `cucumber-js`. Draw inspiration from their tests. Describe the feature using tests before committing to an implementation and propose it.

**Comment by VidhiRambhia** [comment]
Hi @badeball,

I have described the feature and proposed an implementation based on the above comments for going about this - https://github.com/badeball/cypress-cucumber-preprocessor/pull/1114. Please share your thoughts/feedback on this initial draft. Thank you!

**Comment by badeball** [comment]
The above-mentioned PR has been merged and released with v19.1.0.
