### ISSUE TITLE
index.js is throwing error when integrated to CypressV10

### ISSUE THREAD

**Issue by kdubakun** [badeball/cypress-cucumber-preprocessor#760]
### Current behavior

I have added the below dependency in my package.json

  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^11.4.0",
    "cypress": "^10.3.0"
  },

But when running npm run cyopen, getting below issue

Error:
The error was thrown while executing your e2e.setupNodeEvents() function:

   e2e: {
   5 |     setupNodeEvents(on, config) {
>  6 | 	return require('./cypress/plugins/index.js')(on,config)
     | 	                                            ^
   7 |       // implement node event listeners here
   8 |     },
   9 |      "specPattern":"cypress/e2e/**/*.feature" , 

TypeError: require(...) is not a function

This is my index.js 

const cucumber = require("@badeball/cypress-cucumber-preprocessor").default;

module.exports = (on, config) => {

on("file:preprocessor", cucumber());

};

### Versions

* **Cypress version**: 10.3
* **Preprocessor version**: 11.4.0
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Try `require('./cypress/plugins/index.js').default(on,config)`.

**Comment by kdubakun** [comment]
Still the same issue

<img width="859" alt="image" src="https://user-images.githubusercontent.com/97876149/178487876-d206cf23-c33c-44cc-847b-93db1b794efe.png">

**Comment by badeball** [comment]
The code in the above-mentioned screenshot doesn't even remotely make sense... Why are you requiring `cypress/plugins/index.js` *in* `cypress/plugins/index.js` ? I recommend that you take a look at the [examples](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples). Stop trying to use `cypress/plugins/index.js` altogether.

**Comment by kdubakun** [comment]
Thank you, am very new to the Cypress + Cucumber approach and these config are replicated from one of our old repo ...where we use "cypress-cucumber-preprocessor": "^4.3.1"

In the example's folder am not able to find a simple cypress + cucumber + js , similar like this - https://github.com/TheBrainFamily/cypress-cucumber-example/blob/master/cypress/plugins/index.js

can you please help me out with any example repo with cypress10 + cucumber + js  support.

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples

**Comment by kdubakun** [comment]
HI, can you pls help me out with the import statement for the new repo ?

similar to below:

import { Given,When } from "cypress-cucumber-preprocessor/steps"


<img width="782" alt="image" src="https://user-images.githubusercontent.com/97876149/178709939-e6fea272-80f7-415f-b36a-91cfc6858443.png">
<img width="782" alt="image" src="https://user-images.githubusercontent.com/97876149/178709939-e6fea272-80f7-415f-b36a-91cfc6858443.png">

**Comment by badeball** [comment]
No, I can't. I recommend reading through https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md.

**Comment by badeball** [comment]
@kdubakun, I've published v11.5.0 which gives a more thorough error message. Hopefully that'll give you more insight into your step definitions.
