### ISSUE TITLE
Error: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [badeball/cypress-cucumber-preprocessor#761]
### Current behavior

I want to use [module aliases](https://webpack.js.org/configuration/resolve/#resolvealias) to manage imports when it comes to `Page Objects` using Cypress(`v9.7.0`). I currently have this error showing in Cypress's Window:

```
Error: Webpack Compilation Error
Module parse failed: Unexpected token (1:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Feature: Login through UI with valid credentials
|   As a user
|   I want to login to the application
```

<img width="1419" alt="Screen Shot 2022-07-12 at 7 01 32 PM" src="https://user-images.githubusercontent.com/32891808/178539378-e3a2f827-604c-4940-92f5-d71ed76eebc0.png">

This error is coming from cucumber's file with an extension of .feature so I assuming Webpack is throwing an error due to cucumber.

### Desired behavior

Cypress should run normally & accept the alias imports.

### Test code to reproduce

**`cypress/plugins/index.js`**:

```
/* eslint-disable no-undef */
/// <reference types="cypress" />

const cucumber = require("@badeball/cypress-cucumber-preprocessor");
const webpack = require("@cypress/webpack-preprocessor");

// eslint-disable-next-line no-unused-vars
module.exports = (on, config) => {
  on("file:preprocessor", cucumber());
};

module.exports = (on) => {
  const options = {
    webpackOptions: require("../../webpack.config"),
    watchOptions: {},
  };
  on("file:preprocessor", webpack(options));
};
```

**`webpack.config.js`**:

```
// eslint-disable-next-line no-undef
const path = require("path");

// eslint-disable-next-line no-undef
module.exports = {
  resolve: {
    alias: {
      // eslint-disable-next-line no-undef
      "@Pages": path.resolve(__dirname, "cypress/pages"),
    },
  },
};
```

**`cypress/integration/e2e/e2e-login:`**

```
import TabLinksPage from "@Pages/tab-links";
import { Given, When, Then } from "@badeball/cypress-cucumber-preprocessor";

const TabLinks = new TabLinksPage();
Given("the user is on the login page", () => {
  cy.visit(Cypress.config("baseUrl"));
});

When("the user enters valid credentials", () => {
  cy.loginByUI();
});

Then("the user is redirected to the home page", () => {
  cy.getCookies();
  TabLinks.getTabLinkSupplier();
});
```

**`cypress/integration/e2e/e2e-login.feature:`**

```
Feature: Login through UI with valid credentials
  As a user
  I want to login to the application

  Scenario: User logs in the webapp with valid credentials
    Given the user is on the login page
    When the user enters valid credentials
    Then the user is redirected to the home page
```

### Versions

* **Cypress version**: 9.7.0
* **Preprocessor version**: 11.4.0
* **Node version**: v16.16.0

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You can't do double `module.exports` like that. You've just not successfully configured a webpack loader. Follow [this](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/webpack-cjs) example.

**Comment by Manuel-Suarez-Abascal** [comment]
@badeball thanks for the quick reply, but this example is for Cypress 10 which I am not using or planning to upgrade until the next big version. Do you have any examples on Cypress 9.7.0?

**Comment by badeball** [comment]
No, but the webpack configuration is similar. This is the crucial part:

```
            {
              test: /\.feature$/,
              use: [
                {
                  loader: "@badeball/cypress-cucumber-preprocessor/webpack",
                  options: config,
                },
              ],
            }
```

**Comment by Manuel-Suarez-Abascal** [comment]
I will give it a shot. Note that I was also using version `4.3.1` & I was having the same issue. No sure if it's relevant to mention it.

**Comment by badeball** [comment]
v4.3.1 is old, unsupported and should never really be used. There's tons of compatibility issues with the most recent Cypress versions, hence unsupported.

**Comment by Manuel-Suarez-Abascal** [comment]
Do you know/remember by any chance, what was the most stable Cypress version that works with version v4.3.1?

**Comment by badeball** [comment]
No, I wouldn't be able to tell, as I never used it.
