### ISSUE TITLE
Typos in the code 

### ISSUE THREAD

**Issue by josefsmrz** [badeball/cypress-cucumber-preprocessor#764]
### Current behavior

There are typos in the code:

 - in lib/registry.ts and lib/methods.ts in function name "runStepDefininition" -> should be runStepDefinition
 - in lib/registry.ts in function name "resolveStepDefintion" -> should be resolveStepDefinition

**Comment by badeball** [comment]
Closing as not a bug and not important.

**Comment by josefsmrz** [comment]
I was actually figuring out a reason why my step implementations weren't found and saw these function names in the error message. Got me thinking that there might be an issue in the preprocessor, so I thought it might be worth reporting:

Error: Step implementation missing for: I am logged-in
      at Registry.resolveStepDefintion (......)
      at Registry.runStepDefininition (......)
      at Context.eval (......)

**Comment by badeball** [comment]
Thanks, but it's not related. If you upgrade to v11.5.0 you will see an improved error message which might give you more insight into your step definitions.

**Comment by josefsmrz** [comment]
Missed the new version, thx 👍
