### ISSUE TITLE
cypress-tags command is not running after migrated to cypress 10.3.1

### ISSUE THREAD

**Issue by varshanharshank** [badeball/cypress-cucumber-preprocessor#767]
### Current behavior

I am unable to run cypress-tags command via cli after migrating from cypress 9.5 to cypress10.3.1

i run the following command "./node_modules/.bin/cypress-tags run --browser chrome --headless --env TAGS=@test" and getting below error
**./node_modules/.bin/cypress-tags: not found**

### Desired behavior

Expecting to run cypress-tags command in 10.3.1 as same as 9.5

### Versions

* **Cypress version**: 10.3.1
* **Preprocessor version**:11.5.1"
* **Node version**: v16.13.1

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
from https://github.com/badeball/cypress-cucumber-preprocessor/issues/689:

> The `cypress-tags` has been removed and made redundant. Specs containing no matching scenarios are [automatically filtered](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md#running-a-subset-of-scenarios), provided that `filterSpecs `is set to true.

**Comment by townxelliot** [comment]
@badeball would it be possible to provide an example of where to set filterSpecs? I'm also having this issue but it's not obvious where the configuration change should be made. Thanks.

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md
