### ISSUE TITLE
Why do we have to have cucumber/json-formatter installed ? It was not required with the previsous version...

### ISSUE THREAD

**Issue by Pirlouit** [badeball/cypress-cucumber-preprocessor#768]
### Current behavior

I have to install manually cucumber/json-formatter

### Desired behavior

JSON reports are generated like the previous version

### Test code to reproduce

npm install @badeball/cypress-cucumber-preprocessor

### Versions

* **Cypress version**: 9.7
* **Preprocessor version**: 11.5.1
* **Node version**: 14.18.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Because outputting messages is easier than (that) JSON, IE. it's an easier implementation.
