### ISSUE TITLE
Error: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (Using Cypress + Typescript + Cucumber)

### ISSUE THREAD

**Issue by shitalmeghanathi** [badeball/cypress-cucumber-preprocessor#769]
### Current behavior
![image](https://user-images.githubusercontent.com/3427772/180134567-39bedca1-962f-4210-96e9-637764a9dc33.png)

### Desired behavior
Should run cucumber feature file successfully

### Test code to reproduce
Plugins/index.js
![image](https://user-images.githubusercontent.com/3427772/180134718-723d25d9-ef08-4ec9-9f4f-b3d81d340afc.png)

feature file
![image](https://user-images.githubusercontent.com/3427772/180134766-112746f8-16e0-4e1d-805b-e480895aa9c7.png)

Spec.js file
![image](https://user-images.githubusercontent.com/3427772/180134816-0017e9b4-5a72-4e9a-a4b6-aed54670e957.png)

Class file
![image](https://user-images.githubusercontent.com/3427772/180134870-ab4f762a-7069-4d85-8367-e6e20c8628d7.png)

cypress.json
![image](https://user-images.githubusercontent.com/3427772/180134908-5eadd993-b8a8-4224-b9dc-c5fb80deb8ce.png)

package.json
![image](https://user-images.githubusercontent.com/3427772/180134999-c110dbd1-8c8b-4f1a-a3c7-084966286f64.png)

### Versions

* **Cypress package version: 9.7.0**:
* **Bundled Node version:16.13.2**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Dude, the checklist wasn't a suggestion. Last item is of particular interest to you.

> I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

**Comment by shitalmeghanathi** [comment]
@badeball I have already checked in the checklist but still my issue is not resolved so can you please help in the same?

**Comment by badeball** [comment]
You're clearly using `cypress-cucumber-preprocessor` while you should be using `@badeball/cypress-cucumber-preprocessor`.
