### ISSUE TITLE
Cucumber tags are not working after Cypress and cucumber-preprocessor upgrade

### ISSUE THREAD

**Issue by surajwaitz** [badeball/cypress-cucumber-preprocessor#770]
I upgraded Cypress from "9.5.2" to **"10.3.0"** and previously I was using "cypress-cucumber-preprocessor": "4.3.1" now I upgrade it to **"@badeball/cypress-cucumber-preprocessor": "11.4.0"**.

Before the upgrade, I was using cypress-tags for running the test using command npx cypress-tags run --env TAGS="@regression" --browser chrome, but after the upgrade it's throwing me below error.

`npm ERR! could not determine executable to run`

Please find the sample feature below

```
Feature: Login Features

    @regression
    Scenario: Test sample login
        Given I login to the website as "testUser"
```
I checked the cypress-tags packages (https://www.npmjs.com/package/cypress-tags), and it seems they are not updated their code base recently, it might be the problem because cypress-tags are not working with new cypress and cucumber-preprocessor.

Can someone help me to get an alternate option for running tests based on the tags with the latest Cypress and cucumber?

**Comment by badeball** [comment]
The package you're referring to (https://www.npmjs.com/package/cypress-tags) isn't something you should use with the preprocessor, ever. Just don't. The name might sound inviting, but it's not for you.

Here's an explanation for the missing executable: https://github.com/badeball/cypress-cucumber-preprocessor/issues/767
