### ISSUE TITLE
unable to access tags in the code

### ISSUE THREAD

**Issue by iomedico-beyer** [badeball/cypress-cucumber-preprocessor#774]
### Current behavior

I am not able to access tags in the code like indicated in the [docs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md).

### Desired behavior

I want to access tags from in the code

### Test code to reproduce

I have a tag on my scenario, like `@TEST_FOO-42`.

```
cy.log(Cypress.env('tags')); // empty
cy.log(Cypress.env('TAGS')); // empty
cy.log(typeof Cypress.env('tags')); // undefined
cy.log(typeof Cypress.env('TAGS')); // undefined
```

### Versions

* **Cypress version**: 10.3.1
* **Preprocessor version**: 11.5.1
* **Node version**: 14.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You're misunderstanding something here. If I were to run Cypress using `cypress run -e tags='@foo and @bar'`, then `Cypress.env('tags')` would yield `'@foo and @bar'`. You don't access the current scenario's tags with `Cypress.env`. What are you trying to achieve?

**Comment by iomedico-beyer** [comment]
I see. Seems to me the documentation is not clear in this regard.

Use cases:

1. I was thinking about how to structure the test code to have best reusability and maybe also independence from Issue keys. Let's say we a file `1_FOO-42.feature` exported from Xray. For now I ended up with having (almost) no test steps in `1_FOO-42.ts` and everything under a common steps folder. Almost, because it seems I need different cleanup code (in “Before”) for different tests. So I still need `1_FOO-42.ts` because of “Before”. Now I was thinking to add some hints about what to cleanup in tags. 
2. I also was thinking about creating individual datasets for each test in the test itself. I would name such a dataset like the name of the test. Currently all my datasets are called `CYPRESS`. This does not work in a parallel testing environment, as one test might already have created the dataset shortly before another test tries to do so ...

**Comment by badeball** [comment]
I can't help you with that, but you might find some inspiration in

https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/features/mixing_types.feature and
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/features/tags/tagged_hooks.feature
