### ISSUE TITLE
Not generating json report or messages.ndjson

### ISSUE THREAD

**Issue by surajwaitz** [badeball/cypress-cucumber-preprocessor#775]
### Current behavior

I would like to get json report for generating cucumber HTML report, it's not generating while running cypress.

### Test code to reproduce

Please find the below cypress.config.js file

`const { defineConfig } = require("cypress");
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");

async function setupNodeEvents(on, config) {
  await preprocessor.addCucumberPreprocessorPlugin(on, config);
  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
    })
  );
  return config;
}

module.exports = defineConfig({
  e2e: {
    specPattern: "cypress/e2e/features/*.feature",
    baseUrl: "https://www.saucedemo.com",
    screenshotsFolder : "reports/chrome_report/screenshots",
    setupNodeEvents,
    experimentalSessionAndOrigin: true,
    chromeWebSecurity: false,
    supportFile : "cypress/support/e2e.{js,jsx,ts,tsx}",
  },
});
`

Also please find the below preprocessor file

`
module.exports={
    "nonGlobalStepDefinitions": true,
    "json": {
      "enabled": true,
      "output": "reports/chrome_report/jsonlogs/log.json",
      "formater": "cucumber-json-formatter.exe"
    },
    "messages": {
      "enabled": true,
      "output": "reports/chrome_report/jsonlogs/messages.ndjson",
    },
    "stepDefinitions": [
      "[filepath]/**/*.{js,ts}",
      "[filepath].{js,ts}"
    ]
}`

### Versions

* **Cypress version**: 10.3.1
* **Cucumber Preprocessor version**: 11.3.1
* **esBuild Preprocessor version**: 2.1.3

Can someone please help me to fix this issue?

**Comment by badeball** [comment]
I can't reproduce the issue given the provided information.

**Comment by surajwaitz** [comment]
I pushed my entire suite to this repo
https://github.com/surajwaitz/cypress-cucumber/tree/main

**Comment by badeball** [comment]
Remove the configuration from `package.json`, you can't have both.

**Comment by surajwaitz** [comment]
Removed below configuration from package.json, but still json report is not generating. I committed the latest code to the [repo](https://github.com/surajwaitz/cypress-cucumber/tree/main)

`"json": {
    "enabled": true
  }`

**Comment by surajwaitz** [comment]
After removing below config from package.json

`"cypress-cucumber-preprocessor": {
    "filterSpecs": true,
    "omitFiltered": true
  },`
  
it's generating json and messages report but scripts are failing with below error 

```
Error: 
Step implementation missing for "I navigate to the website".
We tried searching for files containing step definitions using the following search pattern templates:
```

@badeball could you please help me to know where we can move filterspecs and omitFiltered from package.json for successful execution?

**Comment by badeball** [comment]
I think you're being awfully helpless here.

You've been told that you can't have configuration in multiple locations. So you should move what you had in `package.json` over to `cypress-cucumber-preprocessor.config.js` or vice versa.

As for your other error regarding missing step implementation, I think the error message is well informative enough. You need to be able to configure it to suite your requirements yourself.

**Comment by surajwaitz** [comment]
Ok 
As you suggested, I moved my entire config from `cypress-cucumber-preprocessor.config.js` to`package.json` but still the report is not generating. Now I have my configurations only in `package.json`. Please find the latest code in the [repo](https://github.com/surajwaitz/cypress-cucumber/tree/main)

**Comment by badeball** [comment]
Configuration, when placed in `package.json` has to go inside the `"cypress-cucumber-preprocessor": { .. }` block.

**Comment by surajwaitz** [comment]
Thanks @badeball, It worked...
You made my day.. :)
