### ISSUE TITLE
Cucumber & messages json not generating when running from Cypress UI

### ISSUE THREAD

**Issue by kiran-epic** [badeball/cypress-cucumber-preprocessor#776]
### Current behavior

Even after setting the required configuration as per the [Docs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md), not able to get the json & messages generated when cypress is launched using `npx cypress open` & an feature is executed

### Desired behavior

Cucumber json should be generated the same way they get generated when using the `npx cypress run` command

### Test code to reproduce

https://github.com/kiran-epic/CypressCucumber_NoJSON

### Versions

* **Cypress version**: 10.3
* **Preprocessor version**:11.5.1
* **Node version**:16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I can't reproduce your issue, they reports are generated as expected.

**Comment by kiran-epic** [comment]
@badeball That's super strange, where are the logs getting generated for you? Also are you running from console or using the cypress runner (`npx cypress open` & then selecting a feature) ?

**Comment by kiran-epic** [comment]
@badeball I just ran using the `npx cypress run` command & was able to see the logs. So the issue is only when you run using the cypress UI runner (`npx cypress open`)

**Comment by badeball** [comment]
JSON reports aren't typically generated in open-mode. They rely on some events that aren't available in open-mode, at least not without `experimentalInteractiveRunEvents: true`. However, it seems like even this experimental flag broke some time ago, ref. https://github.com/cypress-io/cypress/issues/18955.
