### ISSUE TITLE
Common steps doesn't working

### ISSUE THREAD

**Issue by amber-yuan** [badeball/cypress-cucumber-preprocessor#779]
### Current behavior
I created my project according to the recommended structure. I have set up the common steps in the common directory `/cypress/features/common`. 

If I set ` "stepDefinitions"：" **/*.step.ts"`  in the package.json., the common steps work fine, but Before hooks become global, and when I run `home.features`, the Before log in srp steps is printed.
![image](https://user-images.githubusercontent.com/15075236/181519803-0eae1336-2882-489c-af50-a4a262c1fda9.png)

If I remove ` "stepDefinitions"：" **/*.step.ts"`  from the package.json., Before hooks can work for specific feature, but common steps don't work.
![image](https://user-images.githubusercontent.com/15075236/181521420-986cd57c-bd70-45be-a482-ccafe2198b7f.png)

### Test code to reproduce
https://github.com/amber-yuan/cypress-cucumber-demo

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Working as intended, try this.

```patch
diff --git a/package.json b/package.json
index 70afa8a..6ed9da4 100644
--- a/package.json
+++ b/package.json
@@ -16,6 +16,9 @@
   },
   "cypress-cucumber-preprocessor": {
     "nonGlobalStepDefinitions": true,
-    "stepDefinitions": "**/*.steps.ts"
+    "stepDefinitions": [
+      "[filepath]/*.steps.ts",
+      "cypress/features/common/*.steps.ts"
+    ]
   }
 }
```

**Comment by amber-yuan** [comment]
@badeball Hi~ I tried this approach and it worked very well, thank you very much.


 I try to change the structure and failed.
![image](https://user-images.githubusercontent.com/15075236/181557011-e8a4ad80-1b33-462c-bb37-7fabfc340a7d.png)

![image](https://user-images.githubusercontent.com/15075236/181557941-4b97ee29-d217-4fd0-8966-6a0e9f333cb7.png)

It can't find the step that defines in `properties.steps.ts`
![image](https://user-images.githubusercontent.com/15075236/181559328-73935e0b-d164-4df5-8170-7e196ad86c54.png)

**Comment by badeball** [comment]
You have to figure out this stuff yourself. I recommend updating to the latest version for somewhat improved error messages.

**Comment by amber-yuan** [comment]
I push a new version to https://github.com/amber-yuan/cypress-cucumber-demo
I configured the stepDefinition in `package.json` and the common steps can be recognized. But the same issue occurred "**Before hooks become global, and when I run home.features, the Before log in srp steps is printed.**"

![image](https://user-images.githubusercontent.com/15075236/181585997-0eb5ac86-a8dd-44c4-b193-4a8d668918f9.png)

And I try to set like below
```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "nonGlobalStepBaseDir": "cypress/step_definitions"
  }
```

The Before hooks is also global. 

Any help would be appreciated!  @badeball

**Comment by badeball** [comment]
You've essentially reverted my changes, so why would it work?

In any case, you appear to be about to stumble upon another, unresolved [issue](https://github.com/badeball/cypress-cucumber-preprocessor/issues/748).
