### ISSUE TITLE
Add integration with `@cucumber/html-formatter`

### ISSUE THREAD

**Issue by badeball** [badeball/cypress-cucumber-preprocessor#780]
Subjects says almost everything. The mentioned package can take messages and generate a report, albeit it's interface is somewhat unpractical which I think explains why it has never been mentioned here.

**Comment by badeball** [comment]
This has been released as v12.0.0.

**Comment by giraffeingreen** [comment]
Hi @badeball any usage example?

**Comment by badeball** [comment]
It's simple, you pretty much just enable it, as illustrated here: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/html-report.md.
