### ISSUE TITLE
Tables not being printed in steps/logs

### ISSUE THREAD

**Issue by cos-p** [badeball/cypress-cucumber-preprocessor#782]
### Current behavior

When using a table, the contents do not get printed in the steps output. 

![image](https://user-images.githubusercontent.com/67924030/181878142-258facc3-f084-409a-883a-688b25ba879d.png)

### Desired behavior

The steps log should include the table/contents.

### Test code to reproduce

Feature file (tried with and without table headers and it makes no difference)
Rule: Correctly placed letters appear in green
    Background:
      Given the target word is:
        | B | L | A | N | D |

    Scenario: Correctly placed letters
      When the player enters the following letters:
        | first | second | third | fourth | fifth |
        | P | R | I | N | T |
      Then the squares should be colored as follows:
        | - | - | - | * | - |

Step code: 
When("the player enters the following letters:", (table) => {
    table.hashes().forEach((row) => {
        cy.log('aaaaaaaaaaaaaaaaaaaaaaaaa', row.first, row.second, row.third, row.fourth, row.fifth)

    })
});

### Versions

* **Cypress version**:10.3.0
* **Preprocessor version**:11.4.0
* **Node version**:v14.16.0

**Comment by badeball** [comment]
This goes for doc strings as well.

**Comment by nilgaar** [comment]
I can take care of this one @badeball , will submit the PR this week.

**Comment by nilgaar** [comment]
Hi @badeball .
atm, fixing this issue requires this to be solved: https://github.com/cypress-io/cypress/issues/24964. I'll keep an eye on it and, if the fix takes more than one month, I'll try to fix it myself.

**Comment by badeball** [comment]
This has been fixed in v7.1.0.
