### ISSUE TITLE
Does not work with Yarn PnP

### ISSUE THREAD

**Issue by AaronBuxbaum** [badeball/cypress-cucumber-preprocessor#783]
### Current behavior

When using Yarn berry, the pnp linker will not allow a TS configuration -- see failing case here: https://github.com/AaronBuxbaum/cypress-cucumber-preprocessor/tree/master/examples/yarn-pnp-ts-fails

Furthermore, even when you're using JS, it will throw during the preprocessing step. Note that I'm currently using the esbuild plugin, which may or may not matter. See failing case here: https://github.com/AaronBuxbaum/cypress-cucumber-preprocessor/tree/master/examples/yarn-pnp-cucumber

```
cypress/e2e/navigation/healthcheck.feature:3:37: ERROR: Could not resolve "/home/abuxbaum/Nuro/frontend/.yarn/__virtual__/@badeball-cypress-cucumber-preprocessor-virtual-151461ef74/0/cache/@badeball-cypress-cucumber-preprocessor-npm-12.0.0-8d30ea0002-53ffdf9717.zip/node_modules/@badeball/cypress-cucumber-preprocessor/lib/registry"
cypress/e2e/navigation/healthcheck.ts:1:34: ERROR: Could not resolve "@badeball/cypress-cucumber-preprocessor"
    at failureErrorWithLog (/home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:1621:15)
    at /home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:1263:28
    at runOnEndCallbacks (/home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:1043:63)
    at buildResponseToResult (/home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:1261:7)
    at /home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:1374:14
    at /home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:675:9
    at handleIncomingPacket (/home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:772:9)
    at Socket.readFromStdout (/home/abuxbaum/Nuro/frontend/.yarn/unplugged/esbuild-npm-0.14.51-a22b50b89c/node_modules/esbuild/lib/main.js:641:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Desired behavior

It should work exactly the same as with a `node-modules` linker.

### Test code to reproduce

https://github.com/AaronBuxbaum/cypress-cucumber-preprocessor/tree/master/examples/yarn-pnp-ts-fails
https://github.com/AaronBuxbaum/cypress-cucumber-preprocessor/tree/master/examples/yarn-pnp-cucumber

### Versions

* **Cypress version**: 10.3.1
* **Preprocessor version**: 12.0.0
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> When using Yarn berry

What does this entail? What do I have to do to reproduce the error?

**Comment by AaronBuxbaum** [comment]
> > When using Yarn berry
> 
> What does this entail? What do I have to do to reproduce the error?

The Yarn berry binary is actually checked into Git. So just cd into the example folders provided and run `yarn`. Then you can `yarn cypress` to run the tests!

If you don’t already have it, you’ll have to install Yarn 1 (`brew install yarn`). The design has Y1 calling into the checked-in Yarn and bootstrapping it

**Comment by badeball** [comment]
Does using berry work with Cypress minus the preprocessor, IE. just regular Cypress?

**Comment by AaronBuxbaum** [comment]
> Does using berry work with Cypress minus the preprocessor, IE. just regular Cypress?

Yes — the TS config file does not work, but it works with a JS config file. So Problem 1 is Cypress's fault, but Problem 2 is the preprocessor's fault

Edit: I've added two examples just for sake of proof:
https://github.com/AaronBuxbaum/cypress-cucumber-preprocessor/tree/master/examples/cypress-pnp-ts
https://github.com/AaronBuxbaum/cypress-cucumber-preprocessor/tree/master/examples/cypress-pnp-js

The usual reason that libraries fail when applying PnP is that they have imports into other dependencies, and with PnP, those need to be resolved differently. See https://yarnpkg.com/advanced/pnpapi for some documentation; there's some helper functions in there that I think will resolve this

**Comment by badeball** [comment]
You need to tell esbuild how to handle packages now that they're not found at the usual location. See the following patch.

```patch
diff --git a/examples/yarn-pnp-cucumber/cypress.config.js b/examples/yarn-pnp-cucumber/cypress.config.js
index faa71fb..97c8d72 100644
--- a/examples/yarn-pnp-cucumber/cypress.config.js
+++ b/examples/yarn-pnp-cucumber/cypress.config.js
@@ -2,6 +2,7 @@ const { defineConfig } = require("cypress");
 const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
 const { addCucumberPreprocessorPlugin } = require("@badeball/cypress-cucumber-preprocessor");
 const { createEsbuildPlugin } = require("@badeball/cypress-cucumber-preprocessor/esbuild");
+const {pnpPlugin} = require("@yarnpkg/esbuild-plugin-pnp");
 
 async function setupNodeEvents(
   on,
@@ -12,7 +13,7 @@ async function setupNodeEvents(
   on(
     "file:preprocessor",
     createBundler({
-      plugins: [createEsbuildPlugin(config)],
+      plugins: [createEsbuildPlugin(config), pnpPlugin()],
     })
   );
 
diff --git a/examples/yarn-pnp-cucumber/cypress/e2e/duckduckgo.ts b/examples/yarn-pnp-cucumber/cypress/e2e/duckduckgo.ts
index 3caf3d9..51a410d 100644
--- a/examples/yarn-pnp-cucumber/cypress/e2e/duckduckgo.ts
+++ b/examples/yarn-pnp-cucumber/cypress/e2e/duckduckgo.ts
@@ -1,4 +1,4 @@
-import { When, Then } from "@badeball/cypress-cucumber-preprocessor";
+import { When, Then } from "@badeball/cypress-cucumber-preprocessor/methods";
 
 When("I visit duckduckgo.com", () => {
   cy.visit("https://duckduckgo.com/");
diff --git a/examples/yarn-pnp-cucumber/package.json b/examples/yarn-pnp-cucumber/package.json
index 1aa13f5..73cf7c6 100644
--- a/examples/yarn-pnp-cucumber/package.json
+++ b/examples/yarn-pnp-cucumber/package.json
@@ -2,6 +2,7 @@
   "dependencies": {
     "@badeball/cypress-cucumber-preprocessor": "latest",
     "@bahmutov/cypress-esbuild-preprocessor": "latest",
+    "@yarnpkg/esbuild-plugin-pnp": "^3.0.0-rc.14",
     "cypress": "latest",
     "typescript": "latest"
   },
```

**Comment by badeball** [comment]
The reason that `When` and `Then` is now imported from `@badeball/cypress-cucumber-preprocessor/methods` is https://github.com/yarnpkg/berry/issues/2987.

**Comment by AaronBuxbaum** [comment]
Aha! This works for me. And actually this has made .config.ts work too :D

**Comment by iomedico-beyer** [comment]
> Aha! This works for me. And actually this has made .config.ts work too :D

You mean `cypress.config.ts`, right? 

Good to know! I am currently using Browserify, because I couldn’t make it work with Esbuild at all. And we would like to switch to Yarn berry, too. Does someone know if any of the bundlers works with Yarn berry together with Cypress and this preprocessor out of the box?

**Comment by AaronBuxbaum** [comment]
> > Aha! This works for me. And actually this has made .config.ts work too :D
> 
> You mean `cypress.config.ts`, right?
> 
> Good to know! I am currently using Browserify, because I couldn’t make it work with Esbuild at all. And we would like to switch to Yarn berry, too. Does someone know if any of the bundlers works with Yarn berry together with Cypress and this preprocessor out of the box?

Feel free to pull down my repo and change the bundler to whatever you need to test it! That said, generally speaking if you can get esbuild working, you can get anything working 😆

**Comment by phlex89** [comment]
After some hours struggling with this issues, I found out the problem was `esbuild` version. I had to use `"esbuild": "^0.14.51"`, to make it works (I had a recent one before).
