### ISSUE TITLE
Step definitions fail to reload when they contained a faulty import

### ISSUE THREAD

**Issue by Bertg** [badeball/cypress-cucumber-preprocessor#786]
### Current behavior

```
Given I have a step definition file that contains an invalid (relative) import
When I start cypress and try to run that feature
Then I get the following error
  > Error: Build failed with 1 error:
  > cypress/e2e/test.js:1:42: ERROR: Could not resolve "../support/helpers"
When I then fix the broken import
Then I still get the error
```

This is using the esbuild solution.

### Desired behavior

When the broken import is fixed, the feature should start running.

### Test code to reproduce

https://github.com/younited/cypress_cucumber_import_bug

Instructions on how to replicate the issue are in the readme. 

### Versions

* **Cypress version**: 10.4.0
* **Preprocessor version**: 12.0.0 (also happens on 11)
* **Node version**: 16.14.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This appears to happen even if you don't use the preprocessor, but simply `@bahmutov/cypress-esbuild-preprocessor`, which means the problem probably lies there. I think you should open up an issue at https://github.com/bahmutov/cypress-esbuild-preprocessor.

**Comment by Bertg** [comment]
@badeball I've opened an issue there.

Depending on how fast that gets resolved, the recommended bundler should change? https://github.com/badeball/cypress-cucumber-preprocessor/blob/0bcdbfa906478dbc0205f98b686d4a5a86544e10/docs/quick-start.md?plain=1#L21

**Comment by badeball** [comment]
https://github.com/bahmutov/cypress-esbuild-preprocessor/issues/380 was recently fixed and closed. Can you try using the latest @bahmutov/cypress-esbuild-preprocessor (v2.2.7) and see if the behavior is changed?
