### ISSUE TITLE
multiple-cucumber-html-reporter not generating json files

### ISSUE THREAD

**Issue by frnc07** [badeball/cypress-cucumber-preprocessor#789]
### Current behavior

I was using multiple-cucumber-html-reporter earlier with the following dependency versions and it was working fine based on the configuration mentioned in this article: https://blog.knoldus.com/generating-cucumber-html-report-cypress/

"devDependencies": {
    "[cypress](https://npmjs.com/package/cypress)": "[^8.4.0](https://npmjs.com/package/cypress)",
    "[cypress-cucumber-preprocessor](https://npmjs.com/package/cypress-cucumber-preprocessor)": "[^4.1.4](https://npmjs.com/package/cypress-cucumber-preprocessor)",
    "[multiple-cucumber-html-reporter](https://npmjs.com/package/multiple-cucumber-html-reporter)": "[^1.18.0](https://npmjs.com/package/multiple-cucumber-html-reporter)",
    "[standard](https://npmjs.com/package/standard)": "[^16.0.4](https://npmjs.com/package/standard)"
  },

### Desired behavior
Current configuration:
"devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^12.0.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.3",
    "cypress": "^10.4.0",
    "esbuild": "^0.14.53",
    "multiple-cucumber-html-reporter": "^1.21.6",
    "standard": "^16.0.4"
  }
According to the configuration below in packag.json, it should create a json file in output folder cypress/cucumber but it is not creating any json files
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "nonGlobalStepBaseDir": "cypress/e2e/**/*.{js,ts}",
    "stepDefinitions": "cypress/e2e/**/*.{js,ts}",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber",
      "filePrefix": "cucumber-",
      "fileSuffix": ""
    }
  }

### Versions

* **Cypress version**: 10.4.0
* **Preprocessor version**: 12.0.0
* **Node version**: 14.15.3

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Article is outdated, here are the correct docs describing JSON reporting: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md.

**Comment by frnc07** [comment]
Okay I used that configuration and its creating a cucumber-report.json. How do I convert it to HTML report?

I am trying to use multiple-cucumber-html-reporter. It says once you have the json file, you can run the following code to generate html report but the html report which gets generated is blank:

const report = require('multiple-cucumber-html-reporter')

report.generate({
  jsonDir: 'cypress/cucumber/',
  reportPath: 'cypress/reports',
  metadata: {
    browser: {
      name: 'chrome',
      version: '90'
    },
    device: 'Local test machine',
    platform: {
      name: 'ubuntu',
      version: '16.04'
    }
  },
  customData: {
    title: 'Run info',
    data: [
      { label: 'Project', value: '' }
    ]
  },
  displayReportTime: true,
  hideMetadata: true,
  saveCollectedJSON: true,
  pageTitle: '',
  reportName: '',
  displayDuration: true
})

**Comment by badeball** [comment]
This isn't the right place to ask for help with `multiple-cucumber-html-reporter`.
