### ISSUE TITLE
Cypress configuration error

### ISSUE THREAD

**Issue by noelklein** [badeball/cypress-cucumber-preprocessor#790]
### Current behavior

I'm trying to get this cypress preprocessor working in my `esbuild-ts` project and I'm getting a `Cypress configuration error` when starting cypress. I checked out your [example project](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-ts) and it fails with the same problem as soon as I add the standard `tsconfig.json` as mentioned in the [Cypress docs](https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfig-json):
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "node"]
  },
  "include": ["**/*.ts"]
}
```

```
TypeError
Your configFile threw an error from: /Users/noelklein/Documents/GitHub/cypress-cucumber-preprocessor/examples/esbuild-ts/cypress.config.ts

The error was thrown while executing your e2e.setupNodeEvents() function:

[Stack trace](http://localhost:50236/__launchpad/index.html#)
TypeError: (0 , cypress_esbuild_preprocessor_1.default) is not a function
    at /Users/noelklein/Documents/GitHub/cypress-cucumber-preprocessor/examples/esbuild-ts/cypress.config.ts:14:18
    at step (/Users/noelklein/Documents/GitHub/cypress-cucumber-preprocessor/examples/esbuild-ts/cypress.config.ts:33:23)
    at Object.next (/Users/noelklein/Documents/GitHub/cypress-cucumber-preprocessor/examples/esbuild-ts/cypress.config.ts:14:53)
    at fulfilled (/Users/noelklein/Documents/GitHub/cypress-cucumber-preprocessor/examples/esbuild-ts/cypress.config.ts:5:58)
```
### Test code to reproduce

https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-ts

Just add the standard `tsconfig.json`, as seen above, to your example.

### Versions

* **Cypress version**: 10.4.0
* **Preprocessor version**: 12.0.0
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This isn't really related to the preprocessor, but add `esModuleInterop: true` in `compilerOptions`.

**Comment by noelklein** [comment]
That works, thank you!
