### ISSUE TITLE
Providing output configuration path for json display illegal operation on directory error. 

### ISSUE THREAD

**Issue by mrsenzy** [badeball/cypress-cucumber-preprocessor#791]
### Current behavior

providing output path for json in (.cypress-cucumber-preprocessorrc.json) as mentioned in (/docs/json-report.md) and run a cypress tag scenario display error like following - 
Error: EISDIR: illegal operation on a directory, open 'C:\Users\sen\Desktop\fw\cypress-fw\cypress\cucumber-json'

{
  "stepDefinitions": [
    "cypress/e2e/stepdefinition/**/*.{js,ts}"
  ],
  "json": {
    "enabled": true,
    "output": "cypress/cucumber-json"
  }
}

### Desired behavior

Copy the generated json file to desired folder -- cypress/cucumber-json

### Test code to reproduce

copy below in .cypress-cucumber-preprocessorrc.json and run a tag scenario 

{
  "stepDefinitions": [
    "cypress/e2e/stepdefinition/**/*.{js,ts}"
  ],
  "json": {
    "enabled": true,
    "output": "cypress/cucumber-json"
  }
}

### Versions

* **Cypress version**: 10.0.3
* **Preprocessor version**: 12.0.0
* **Node version**: 14.17.5

### Checklist

- [Yes] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [Yes] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [Yes] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
`json.output` should point to a _file_, not a directory.

**Comment by mrsenzy** [comment]
Got it. Thank you.
