### ISSUE TITLE
Cannot destructure property 'testCaseStartedId' of 'properties' as it is undefined.

### ISSUE THREAD

**Issue by FDIM** [badeball/cypress-cucumber-preprocessor#792]
### Current behavior

An error is thrown when `@env(something=1)` is used in a feature file.

![image](https://user-images.githubusercontent.com/1985429/183414698-519ba6ca-59c7-44a7-b64b-4a84947131c1.png)

### Desired behavior

It should work. It actually does work, but only on a subsequent run. Aka I can run the test, then update feature file by adding `@env` decorator. When change is detected and test runs again, error is not thrown.

### Test code to reproduce

````
@env(foo=2000)
Feature: duckduckgo.com
  Scenario: visting the frontpage
    When I visit duckduckgo.com
    Then I should see a search bar

````

### Versions

* **Cypress version**: 8.5.0
* **Preprocessor version**: 12.0.0
* **Node version**: 16.2.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, @FDIM. Thanks for reporting the issue. This has been fixed in v12.0.1.

**Comment by NachoVazquez** [comment]
I'm getting this error on the following versions

Cypress version: 10.7.0
Preprocessor version: 14.0.0
Node version: 14.18

```gherkin
Feature: Platform

  Scenario: The user opens dashboard and see latest statements/publications
    Given the user opens the dashboard page
    And the "SearchNarratives" request completes
    And the "LatestReferences" request completes
    And the "LatestStatements" request completes
    Then the username "John McClane" is displayed in the top-right corner
```

**Comment by badeball** [comment]
If you're asking for help, then you need to provide a full example that reproduces the issue.

**Comment by NachoVazquez** [comment]
I'll try to create a reproduction for this.
