### ISSUE TITLE
How to pass the stepDefinitions in runtime?

### ISSUE THREAD

**Issue by vigneshwaran-erd233** [badeball/cypress-cucumber-preprocessor#794]
### Current behavior

Please find my .cypress-cucumber-preprocessorrc.json below, 

{
  "json":  {
    "enabled": true,
    "formatter": "node",
    "args": ["report-formatter.js"],
    "output": "formatted-json/latestFormatProcess.log"
  },
  "messages": {
    "enabled": true,
    "output": "./cucumber-messages.ndjson"
  },
  "stepDefinitions": [
    "cypress/e2e/StepDefinitions/*.{js,ts}",
    "cypress/e2e/StepDefinitions/TEST1/**/*.js",
    "cypress/e2e/StepDefinitions/TEST2/**/*.js"

  ]
}

### Desired behavior

TEST1 Folder contains features of our module 1. (Inside TEST1 Folder, I have a common.js file containing before() and aftereach() which is applicable only for our module 1.  
TEST2 Folder contains features of our module 2. (Inside TEST2 Folder, I have a common.js file containing before() and aftereach() which is applicable only for our module 2.  

Expected Scenario:

I want to pass the StepDefinition in run time as mentioned below so that only the features under TEST1 folder should get executed and should consider only the before() & aftereach() methods present in common.js file which is inside the TEST1 folder. In this case, it should not consider the features in TEST2 and also the common.js file present in TEST2. 
 
npx cypress run -e stepDefinitions= "cypress/e2e/StepDefinitions/TEST1/**/*.js"  --browser='electron'

Issue Description: 
It is not considering the step definitions if I pass it in run time. 

P.S : I tried passing the above command in runtime by giving empty stepDefinitions[] in .cypress-cucumber-preprocessorrc.json and also passing only
 stepDefinitions[
"cypress/e2e/StepDefinitions/*.{js,ts}",
] 

### Versions

* **Cypress version**: "^10.3.1"
* "@badeball/cypress-cucumber-preprocessor": "^11.4.0",
 * "@bahmutov/cypress-esbuild-preprocessor": "^2.1.3",

### Checklist

- Yes, I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- Yes,  I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- Yes, I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Config override is explained in the docs and I can't tell you anymore than what's already there, https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md#configuration-overrides.

This might be of interest: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#--env--tags-isnt-picked-up.

**Comment by vigneshwaran-erd233** [comment]
@badeball My problem is that it is not at all considering the StepDefinitions if pass it in the command line. 

npx cypress run -e stepDefinitions= "cypress/e2e/StepDefinitions/TEST1/**/*.js" --browser='electron'

Please correct me if there is any mistake in the above command.

**Comment by badeball** [comment]
It looks correct to me.

**Comment by vigneshwaran-erd233** [comment]
But it is not getting overriding. Please help.

**Comment by badeball** [comment]
From https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md#caveats--debugging:

> If you're unsure of what configuration values is actually being applied, then you can run Cypress with the following to enable debug output which will tell you.
>
> ```
> $ DEBUG=cypress:electron,cypress-configuration,cypress-cucumber-preprocessor cypress run
> ```

Do that and see what values are actually being applied (and paste it here).

**Comment by badeball** [comment]
IE. run with the mentioned `DEBUG` variable _and_ your configuration override.

**Comment by badeball** [comment]
> @badeball My problem is that it is not at all considering the StepDefinitions if pass it in the command line.
> 
> npx cypress run -e stepDefinitions= "cypress/e2e/StepDefinitions/TEST1/**/*.js" --browser='electron'
> 
> Please correct me if there is any mistake in the above command.

Do you realize that there's an erroneous space in your command? After the equal sign.
