### ISSUE TITLE
Tests names are not translated to json file properly from examples table. 

### ISSUE THREAD

**Issue by oguzhantx** [badeball/cypress-cucumber-preprocessor#795]
### Current behavior
when tests with scenario outline runs and name of the scenario comes from examples table, json report does not show the name properly. 

Sample feature file: 
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/94402055/183743564-48940cee-5235-4872-a6ab-d61a0b1ef81e.png">

json report. 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/94402055/183742434-a2792985-0a85-482d-889b-f69ea09cd793.png">

Test name is passed as string not as parameter from table. 

### Desired behavior

json should have correct name from examples table. 

### Versions

 "cypress": "^10.3.0",
* **Preprocessor version**: "@badeball/cypress-cucumber-preprocessor": "^12.0.1",
* **Node version**: 16.13.1

### Checklist

- [x ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey @oguzhantx. Thanks for letting me know. This is however an issue with https://github.com/cucumber/json-formatter and I've reported it [here](https://github.com/cucumber/json-formatter/issues/25).
