### ISSUE TITLE
Add cucumber code snippet

### ISSUE THREAD

**Issue by iso13** [badeball/cypress-cucumber-preprocessor#799]
### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Elaborate.

**Comment by iso13** [comment]
Reference: https://github.com/cucumber/cucumber-js/blob/main/docs/snippets.md

Being lazy and efficient.
As well as an opportunity for people new to cucumber to get on boarded quickly.

In most standard cucumber frameworks you can run cucumber steps, which are missing step definitions, execute the scenario via terminal and it will provide a cucumber snippet.

 ? Given I do something
       Undefined. Implement with the following snippet:
       
         Given('I do something', async function () {
           // Write code here that turns the phrase above into concrete actions
           return 'pending';
         });

**Comment by badeball** [comment]
Closely related to https://github.com/badeball/cypress-cucumber-preprocessor/issues/754, where I actually have implemented snippet suggestions. I don't have time to continue on it right now though.

**Comment by badeball** [comment]
This has been introduced with v13.0.0.

**Comment by uo9qsuf** [comment]
@badeball Thank you,

but if I wirte When or Then I get always a Given as suggestion. And the placeholder for string etc. aren't inside the suggestion. Can you extend the feature?

**Comment by badeball** [comment]
> And the placeholder for string etc. aren't inside the suggestion.

What do you mean by this?

**Comment by uo9qsuf** [comment]
@badeball here an example

```gherkin
Scenario: test
   Given here a text with content "hallo world"
```

the suggestion should be link this

```javascript
Given(here a text with content {string}', (value) => {
       // Write code here that turns the phrase above into concrete actions
       console.log('value', value)
       return 'pending';
     });
```

**Comment by badeball** [comment]
I've opened a separate issue with this [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/974). Feel free to take a stab at this yourself.
