### ISSUE TITLE
Missing current step in window.testState

### ISSUE THREAD

**Issue by elangbayu** [badeball/cypress-cucumber-preprocessor#800]
### Current behavior

In preprocessor `v4.3.1`, window.testState object contains currentStep index that can be used to identify which step is currently running at the time. In `v12.0.0` I couldn't find this information anywhere.

### Desired behavior

testState object should contains current step information to make it easy to debug at each step level.

### Test code to reproduce

https://github.com/elangbayu/teststate-comparison

### Versions

* **Cypress version**: **10.4.0**
* **Preprocessor version**: **12.0.0**
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, @elangbayu. I've added this in v12.1.0.

**Comment by elangbayu** [comment]
Oh wow, thank you so much @badeball ! Now I can continue migrating my project to the latest version of cypress and cypress-cucumber-preprocessor 😃

**Comment by marcrecor** [comment]
Having the same problem with:

- **Cypress version: 12.3.0**
- **Preprocessor version: 17.1.0**
- Node version: 18.15.0
