### ISSUE TITLE
Multiple matching step definitions errors firing when steps do not match

### ISSUE THREAD

**Issue by maryeHoltz** [badeball/cypress-cucumber-preprocessor#802]
### Current behavior

We recently upgraded our cypress-cucumber-preprocessor and now we have quite a few tests failing that were previously working. We are getting many different versions of this error:
![image](https://user-images.githubusercontent.com/91213593/184960112-f94c6dca-c158-4b5a-8da7-cd51ae20a5ed.png)

Some other examples of "matching" step definitions are:
I enter {string} in {POMstring}
I enter {string} in the {POMstring} element and click out

I see {string} selected in the {POMstring} iFrame dropdown
I see {string} selected in the {POMstring} dropdown

Some additional information: we are using global step definition files located in cypress\support\step_definitions and have the nonGlobalStepDefinitions configuration set to 'false'.

### Desired behavior

The preprocessor should only throw the 'Multiple matching step definition' error if the step string is different.

### Versions

* **Cypress version**: 10.4.0
* **Preprocessor version**: 11.4.0
* **Node version**: 17.3.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
How’s POMString defined?

**Comment by maryeHoltz** [comment]
We treat the POMString as an array. The first element of the array refers to the file name of the json file, and the second element refers to the json key needed to retrieve the value:

`When("I enter {string} in the {POMstring} element and click out", (inputText, pageObjectArr) => {`
`cy.fixture("pages/" + pageObjectArr[0]).then((json) => {`
`const pageObjectElement = json[pageObjectArr[1]];`
`cy.get(pageObjectElement).type(inputText).blur();`
`});`
`});`

**Comment by badeball** [comment]
Okey, I’m not sure yet that it’s unintended behaviour you’re experiencing, so I need to see a minimal example that illustrates it (preferably a cloneable repository).

**Comment by nids2307** [comment]
Is there a documentation to see how the preprocessor 11.4 identifies the matching steps (just based on partial text matching)?

**Comment by maryeHoltz** [comment]
I can't link to a repository, but here is a simplified breakdown:
### Test File
Scenario: Testing an input field
      **When** I enter "some text" in the "myPage.myInputField" element and click out
      **Then** The "myPage.myInputField" should contain text

### Json page that houses the elements
Located in cypress/fixtures/pages/myPage:
`{ 
"myInputField": "#inputField",
}`

### Step Definition File
Located in cypress\support\step_definitions\when_defs:

- The below line defines the step definition
`When("I enter {string} in the {POMstring} element and click out", (inputText, pageObjectArr) => {`
- This line grabs the first part of the POMstring array (myPage) then locates that file and utilizes its JSON in the then block
`cy.fixture("pages/" + pageObjectArr[0]).then((json) => {` 
- This line uses the second part of the POMstring array (myInputField) and finds the value that corresponds to that key, which is '#inputField'. It then sets that value as pageObjectElement
`const pageObjectElement = json[pageObjectArr[1]];`
-This line uses the retrieved value (#inputField) in the cy.get command to enter the string that was passed in the scenario
`cy.get(pageObjectElement).type(inputText).blur();`
`});`
`});`

I agree with nids2307, any documentation around how 11.4 identifies matching steps would be greatly appreciated. If the preprocessor is looking for just a partial match and that's why it's coming up with multiple step definitions it could use, what is the best way to make sure similarly named step definitions remain unique to the preprocessor?

**Comment by badeball** [comment]
Your breakdown is unfortunately useless because it doesn’t contain the relevant parts.

Furthermore, when I ask for a minimal example, I’m not actually looking for access to your company repo, because that’s probably not even the least minimal. What I want is for you to put together an example specifically for the purpose of illustrating the behaviour that you think is wrong. The reason I ask for this is that I highly suspect that I will be able to point out something you’re doing wrong. Hence I think you’re getting ahead of yourself when asking for workarounds here.

**Comment by maryeHoltz** [comment]
I apologize for not being clear. Here is as basic as I could possibly lay it out:

### Test file:
Scenario: Testing an input field
**When** I enter "some text" in the "myPage.myInputField" element and click out

### Step Definition File
When("I enter {string} in the {POMstring} element and click out", (inputText, pageObjectArr) => {
doSomeCode()
});

When("I enter {string} in {POMstring}", (inputText, pageObjectArr) => {
doSomeOtherCode()
});

### Expected Behavior
The preprocessor does not throw the 'Multiple matching step definitions error' because thier expressions do not match.

**Comment by badeball** [comment]
I need a runnable example, IE. something that's so complete (but minimal) that I can run it and see the originally mentioned error.

**Comment by maryeHoltz** [comment]
@badeball Here is the repository:
https://github.com/maryeHoltz/mismatchError

Please let me know if this doesn't run for you, I had to work through a bunch of certificate errors and I hope it has everything you need. When you run the only test in the repo, the first will pass, then the second should fail with this error:
![image](https://user-images.githubusercontent.com/91213593/185692165-678bf943-9561-4da7-ac33-5138a521a809.png)

The expected behavior for this test is that they should both pass and the preprocessor should recognize the step definitions are unique.

**Comment by badeball** [comment]
This is expected behavior given how you defined `{POMString}`. It's matching everything, including `"SearchPage.SearchField" element and click out`. Try using the expression `/"([^"]+)"/` instead.
