### ISSUE TITLE
Unable to resolve the fs promise (node events)

### ISSUE THREAD

**Issue by nids2307** [badeball/cypress-cucumber-preprocessor#803]
### Current behavior

I have upgraded Cypress to version 10.4 and cucumber-cypress-preprocessor to version 11.4.0. As this needed a bundler, I installed the ESbuild dependencies based on the examples given in the project.

Since then, I am receiving error when trying to run any test in the suite.
I tried using fs-extra dependency with no luck
I also tried replacing fs.readFileSync(file) with fs.promised.readfile using async and wait with no success.

I found a potential fix but not sure how to add it to my project: https://esbuild.github.io/getting-started/#bundling-for-node

Error: Build failed with 1 error:
cypress/support/commands/readXlsx.js:2:23: ERROR: Could not resolve "fs"
    at failureErrorWithLog (/Users/abc/Test Automation Projects/functional-prj/node_modules/esbuild/lib/main.js:1624:15)

### Desired behavior

I want the fs promise to work as before. though I had to add a bundler(Esbuild) for preprocessor 11.4 to work, I am still using node as the package manager.

### Test code to reproduce

Cypress.Commands.add("readXlsx", (file, sheet) => {
    const fs = require("fs");
    const XLSX = require("xlsx");

    const read = ({ file, sheet }) => {
        const buf = fs.readFileSync(file);
        const workbook = XLSX.read(buf, { type: "buffer" });
        const rows = XLSX.utils.sheet_to_json(workbook.Sheets[sheet]);

        return rows;
    };

    module.exports = {
        read,
    };
});

### Versions

* **Cypress version**: 10.4.0
* **Preprocessor version**:11.4.0
* **Node version**:16.14.2

### Checklist

- [ x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You can’t use node modules in the Cypress runtime like that, you need to use a task which runs in a node process.

**Comment by nids2307** [comment]
Can you please elaborate a little bit as the code was working fine with preprocessor version 4.0.

In CLI, it is suggesting to do add platform:node. Please see below:
✘ [ERROR] Could not resolve "fs"

    cypress/support/commands/readXlsx.js:2:23:
      2 │     const fs = require("fs");
        ╵                        ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

**Comment by badeball** [comment]
I can’t really see how this ever worked, in any version.

**Comment by Jsijbel** [comment]
I can confirm this did work in the older versions. We were using node:path (https://nodejs.org/api/path.html) which we had to remove for now after upgrading to cypress 10 and the new cucumber plugin version.

We were also using the cypress-fail-on-console-error package(https://www.npmjs.com/package/cypress-fail-on-console-error) which I can't seem to get working using the esbuild bundler. It is using node:os (https://nodejs.org/api/os.html) which also is not working now.

Both worked with the older version.

Esbuild seems to give the following feedback:

> The package "os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

The cypress-esbuild-preprocessor(https://github.com/bahmutov/cypress-esbuild-preprocessor) seems to have an option to give a platform config:

> If you want to pass your own [ESBuild options](https://esbuild.github.io/api/)

```
// cypress/plugins/index.js
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor')
module.exports = (on, config) => {
  const bundler = createBundler({
    // any ESBuild options here
    // https://esbuild.github.io/api/
  })
  on('file:preprocessor', bundler)
}
```
And from the linked esbuild documentation:

> By default, esbuild's bundler is configured to generate code intended for the browser. If your bundled code is intended to run in node instead, you should set the platform to node:

I have tried passing the platform configuration in cypress.config.js, 
```
async function setupNodeEvents(on, config) {
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on(
    'file:preprocessor',
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
      platform: 'node',
    }),
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}
```
but then I run into other errors.
```
The following error originated from your test code, not from Cypress.

> require is not defined
```


I'm really hoping it is just a matter of configuration and we can get this working so we can upgrade to your new plugin without compromises. Any assistance would be greatly appreciated.

**Comment by Jsijbel** [comment]
> Can you please elaborate a little bit as the code was working fine with preprocessor version 4.0.
> 
> In CLI, it is suggesting to do add platform:node. Please see below: ✘ [ERROR] Could not resolve "fs"
> 
> ```
> cypress/support/commands/readXlsx.js:2:23:
>   2 │     const fs = require("fs");
>     ╵                        ~~~~
> ```
> 
> The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

You could possibly add it to cypress.config.js setup node events as a task.
```
const fs = require('fs');
const xlsx = require('node-xlsx').default;

async function setupNodeEvents(on, config) {

  on('task', {
    parseXlsx({ filePath }) {
      return new Promise((resolve, reject) => {
        try {
          const jsonData = xlsx.parse(fs.readFileSync(filePath));
          resolve(jsonData);
        } catch (e) {
          reject(e);
        }
      });
    },
  });

}
```

and run with cy.task (we added is as a command)
```
Cypress.Commands.add('parseXlsx', (inputFile) => {
  return cy.task('parseXlsx', { filePath: inputFile });
});
```

This works for us in this situation with the new cucumber plugin version.

**Comment by badeball** [comment]
> You could possibly add it to cypress.config.js setup node events as a task.

I can chime in and say that this is the _only_ way. At no point has anyone been able to do anything else. You simply can't run a node module in the browser. You might have been able to make a node module compile with earlier versions of browserify / webpack, but it just wouldn't behave as you'd expect.
