### ISSUE TITLE
on("after:run" ... ) not work with cucumber preprocessor

### ISSUE THREAD

**Issue by charlesaraujo** [badeball/cypress-cucumber-preprocessor#805]
### Current behavior

when i try to put a on("after:run" ... ) or other lifecycle  that cucumber preprocessor uses that not work,

### Test code to reproduce

when i try to use on("after:run" ... ) after await addCucumberPreprocessorPlugin(on, config) i have no output of my report, i use html report, but when i put my  on("after:run" ... )  before they dont work.

.cypress-cucumber-preprocessorrc.json
{
  "stepDefinitions": [
    "**/cypress/e2e/**/*.{js,ts}",
    "**/cypress/e2e/.{js,ts}",
    "**/cypress/support/**/*.{js,ts}"
  ],
  "messages": {
    "enabled": false
  },
  "html": {
    "enabled": true,
    "output": "cypress/report/index.html"
  }
}

-- This not output my html report
setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
  await addCucumberPreprocessorPlugin(on, config);

  on("file:preprocessor", WebpackSettings(config)); // this work property for ts files

  on("after:run", (results) => {
    console.log("test");
  });
  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

--  And this not output my console.log
setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {

  on("after:run", (results) => {
    console.log("test");
  });

  await addCucumberPreprocessorPlugin(on, config);

  on("file:preprocessor", WebpackSettings(config));  this work property for ts files

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

my deps:
  "dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^12.0.1",
    "@cypress/webpack-preprocessor": "^5.12.2",
    "cypress": "10.5.0",
    "ts-loader": "^9.3.1",
    "typescript": "^4.7.4"
  }

### Versions

* **Cypress version**:10.5.0
* **Preprocessor version**: 5.12.2
* **Node version**: 14.19.1

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by charlesaraujo** [comment]
i solve my problem. with this code.

import {  addCucumberPreprocessorPlugin,  afterRunHandler } from "@badeball/cypress-cucumber-preprocessor";
----
  await addCucumberPreprocessorPlugin(on, config, {
    omitAfterRunHandler: true,
  });

  on("file:preprocessor", WebpackSettings(config)); //this work property for ts files

  on("after:run", (results) => {
    console.log("test");

    afterRunHandler(config);
  });

**Comment by JomyGeo** [comment]
@charlesaraujo I am facing the same problem for generating the report.  How/Where do I configure the above code in the cypress 10(Javascript) project.

**Comment by Innohh** [comment]
> i solve my problem. with this code.
> 
> ## import { addCucumberPreprocessorPlugin, afterRunHandler } from "@badeball/cypress-cucumber-preprocessor";
> await addCucumberPreprocessorPlugin(on, config, { omitAfterRunHandler: true, });
> 
> on("file:preprocessor", WebpackSettings(config)); //this work property for ts files
> 
> on("after:run", (results) => { console.log("test");
> 
> ```
> afterRunHandler(config);
> ```
> 
> });

You sir, just fixed an issue for me which I wasn't able to fix for over a few months. Thanks!
