### ISSUE TITLE
Jenkins build job not working while doing npm install process 

### ISSUE THREAD

**Issue by mrsenzy** [badeball/cypress-cucumber-preprocessor#808]
### Current behavior

We have upgrade our cypress and cucumber-preprocessor version from (9.5.0 to 10) and (4.0.0 to badeball cucumber v12.0.0). Our local install and testing worked fine with this version upgrade - able to run desired test and generate reports fine,. but while running the build job via jenkins it stucks at below line during npm install.

11:21:51  Skipping 'fsevents' build as platform linux is not supported
11:21:52  
11:21:52  > core-js@3.6.4 postinstall /home/jenkins/agent/workspace/EQA/TCOE/Cypress/CI_INT/Cypress_Ref_Project_Build/App/dist/node_modules/@angular-devkit/build-angular/node_modules/core-js
11:21:52  > node -e "try{require('./postinstall')}catch(e){}"
11:21:52  
11:21:52  
11:21:52  > esbuild@0.11.23 postinstall /home/jenkins/agent/workspace/EQA/TCOE/Cypress/CI_INT/Cypress_Ref_Project_Build/App/dist/node_modules/@badeball/cypress-configuration/node_modules/esbuild
11:21:52  > node install.js
11:21:52  

we tried to debug by upgrade only cypress version and remove cucumber upgarde then build runs fine - after upgrading cucumber version to 12.0.0 the above issue occur.  

Request if anyone else faced this issue and how it was resolved. 

### Desired behavior

Jenkins build run successfully similar like previous versions. 

### Test code to reproduce

    "dependencies": {
        "@angular/animations": "~10.0.14",
        "@angular/common": "~10.0.6",
        "@angular/compiler": "~10.0.6",
        "@angular/core": "~10.0.6",
        "@angular/forms": "~10.0.6",
        "@angular/platform-browser": "~10.0.6",
        "@angular/platform-browser-dynamic": "~10.0.6",
        "@angular/router": "~10.0.6",
        "@badeball/cypress-cucumber-preprocessor": "^12.0.0",
        "@cypress/webpack-preprocessor": "^5.12.0",
        "archiver": "^3.1.1",
        "axios": "^0.21.1",
        "bootstrap-sass": "^3.3.7",
        "bootstrap-select": "^1.13.18",
        "cheerio": "^1.0.0-rc.3",
        "cors": "^2.8.5",
        "cypress": "^10.0.3",
        "esbuild": "^0.14.54",
        "file-saver": "^2.0.5",
        "font-awesome": "^4.7.0",
        "fs": "^0.0.1-security",
        "hig-cypress": "^4.2.1-SNAPSHOT",
        "hig-ui-kit": "^3.3.44",
        "imap": "0.8.19",
        "mailparser": "^2.7.1",
        "minimist": "^1.2.5",
        "ng2-file-upload": "^1.3.0",
        "ng2-pdf-viewer": "^6.4.1",
        "nodemailer": "^6.4.2",
        "npm-run-all": "^4.1.5",
        "rally": "^2.1.3",
        "resolve": "1.15.1",
        "rxjs": "~6.5.5",
        "shelljs": "^0.8.4",
        "ts-loader": "^9.3.1",
        "tslib": "^2.0.0",
        "username": "^5.1.0",
        "util.promisify": "^1.1.1",
        "webpack": "^5.74.0",
        "zip-a-folder": "^0.0.12",
        "zone.js": "~0.10.3"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.1000.5",
        "@angular/cli": "~10.0.5",
        "@angular/compiler-cli": "~10.0.6",
        "@types/fs-extra": "^9.0.6",
        "@types/graceful-fs": "^4.1.5",
        "@types/jasmine": "~3.5.0",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "^12.11.1",
        "archiver": "^3.1.1",
        "axios": "^0.21.0",
        "browserstack-cypress-cli": "1.8.1",
        "cheerio": "^1.0.0-rc.3",
        "codelyzer": "^6.0.0",
        "crypto": "^1.0.1",
        "cucumber-html-reporter": "^5.3.0",
        "cypress-localstorage-commands": "^1.4.0",
        "cypress-log-to-output": "^1.1.2",
        "imap": "0.8.19",
        "mailparser": "^2.7.1",
        "nodemailer": "^6.4.2",
        "npm-run-all": "^4.1.5",
        "protractor": "~7.0.0",
        "rally": "^2.1.3",
        "simple-encryptor": "^4.0.0",
        "ts-node": "~8.3.0",
        "tslint": "~6.1.0",
        "typescript": "~3.9.5",
        "username": "^5.1.0",
        "zip-a-folder": "^0.0.12"
    }

javascript that runs the jenkins package build job is 

var shell = require('shelljs');
var fs = require('fs');
var archiver = require('archiver');

console.log('Building Cypress Test Suite in', process.cwd());
shell.exec('mkdir -p dist/cypress');
shell.exec('mkdir -p dist/binary');
shell.exec('cp e2e-automation.sh dist/');
shell.exec('cp cypressFlow.js dist/');
shell.exec('cp browsers.js dist/');
shell.exec('cp package.json dist/');
shell.exec('cp browserstack.json dist/');
shell.exec('cp .npmrc dist/');
shell.exec('cp cypress.config.ts dist/');
shell.exec('cp -R cypress/* dist/cypress');
// shell.exec('cp cypress/fixtures/test.json dist/cypress/fixtures/');
const version = shell.exec('node -v')
console.log('Running on Node', version.toString());

shell.exec('npm install npm@7')
const npm_version = shell.exec('npm -v')
console.log('Running on NPM', npm_version.toString());

console.log('npm install command');
console.log('Downloading Cypress binary via maven');
shell.exec('npm install --force --prefix dist --userconfig=.npmrc');
shell.exec('mvn -q org.apache.maven.plugins:maven-dependency-plugin:2.8:copy -Dartifact=cdn.cypress.io:Cypress:10.0.3-linux-x64:zip -DoutputDirectory=./ -Dmdep.useBaseVersion=true -Dmdep.stripVersion=true')
shell.exec('mvn -q org.apache.maven.plugins:maven-dependency-plugin:2.8:copy -Dartifact=cucumber.json-formatter.io:cucumber-json-formatter-linux-amd64:19.0.0:zip -DoutputDirectory=./ -Dmdep.useBaseVersion=true -Dmdep.stripVersion=true')

jenkins build get hang at line (shell.exec('npm install --force --prefix dist --userconfig=.npmrc');) 

### Versions

* **Cypress version**: 10.0.3
* **Preprocessor version**: 12.0.0
* **Node version**: 14.20.0

### Checklist

- [ Yes] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ Yes] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [Yes ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
That's esbuild's postinstall script that is hanging, possibly at downloading your platform-specific artifact. I recommend reading through its issue tracker.
