### ISSUE TITLE
ESbuild TypeScript cypress.config.ts example may need updating, does not work in Angular

### ISSUE THREAD

**Issue by KyleVassella** [badeball/cypress-cucumber-preprocessor#809]
### Current behavior

In an Angular project, the current example **cypress.config.ts** file for an esbuild TS setup is not working. Previously, my project was successfully using Cypress 10+ with Cypress-Cucumber-Preprocessor v 12.1.0 using Browserify. When trying to switch to ESbuild preprocessor using TypeScript example for esbuild (https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-ts), I get the following error on npm run:cypress open and clicking the E2E Testing button:

![Screen Shot 2022-08-21 at 4 17 31 AM](https://user-images.githubusercontent.com/19896179/185784909-8f4bc567-ebe3-46b4-beb5-d16144bee6d9.png)

### Desired behavior

I want the Cypress test runner to open successfully. 

### Test code to reproduce

Unfortunately, it's hard to replicate an Angular project with Cypress on StackBlitz, jsFiddle, etc.

The only way for you to reproduce would be, on your local machine, set up an angular project like so:

`npm install -g @angular/cli`
`ng new my-app`
`ng e2e`

This will prompt you to install an e2e test framework. Select 'Cypress' - this will install the cypress-schematic version 2. Cypress-schematic is just Angular's way of installing Cypress. NOTE: if you are not prompted to install an e2e framework, just run ng add @cypress/schematic

Okay, now Cypress v10 is set up. Now we run npm install @badeball/cypress-cucumber-preprocessor (or even better, npm install --save-dev @badeball/cypress-cucumber-preprocessor, since we don't need this for production builds, only for development).

Then we add our configurations in package.json like so:

```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/e2e",
    "filterSpecs": true
  },
```
  
Then we install a preprocessor. Let's use ESbuild:

`npm i -D cypress @bahmutov/cypress-esbuild-preprocessor esbuild`

Then, in **cypress.config.ts**, copy in the code from the current ESbuild TypeScript example from this repo: https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-ts

### Versions

* **Cypress version**: 10.6.0
* **Preprocessor version**: 12.1.0
* **Node version**: 16.14.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/790
