### ISSUE TITLE
[Request] Add pretty formatter plugin

### ISSUE THREAD

**Issue by burakkaygusuz** [badeball/cypress-cucumber-preprocessor#810]
Do you have any plans to add the pretty plugin to this processor according to the below package? It would be nice to monitor the scenario steps via the CLI.

https://github.com/cucumber/cucumber-js-pretty-formatter

**Comment by badeball** [comment]
No such plans exist, albeit it'd be nice to have. I however don't have time to work on this. Furhermore, I reckon it'd be pretty major work, as one can't simply just integrate cucumber-js reporters into cypress, it'd more likely require a complete re-implementation.

**Comment by badeball** [comment]
I'm happy to announce that this is implemented in v18.0.0. Read the [docs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/pretty-output.md) for information on how to enable it. This is still fairly experimental and feedback is welcome.

**Comment by mpconsultsai** [comment]
Is it possible to use this if running on version below Node 18? - that is could this be a package you could install in isolation - or is it only supported on versions > Node 18 - we are currently tied to Node 16 but would like to use this if possible. If not I suppose we need to upgrade to Node 18 which might facilitate this move

**Comment by badeball** [comment]
> Is it possible to use this if running on version below Node 18?

The v18-requirement comes from use of `findLastIndex(..)`, which is only invoked in certain conditions, namely if you omit configuring `baseUrl`. Omitting this configuration is not recommended. Thus, you can probably use this library with v16 as long as you do configure said property.
