### ISSUE TITLE
How to handle cucumber/json-formatter for different OS versions?

### ISSUE THREAD

**Issue by deepakksusarla** [badeball/cypress-cucumber-preprocessor#811]
### Current behavior

Automation code development will be done on Windows machine. CI Jenkins will run on linux machine. 
"json": {
      "enabled": true,
      "output": "jsonlogs/log.json",
      "formatter": "cucumber-json-formatter.exe"
    },

### Desired behavior

json-formatter should be picked dynamically irrespective of OS.
"json": {
      "enabled": true,
      "output": "jsonlogs/log.json",
      "formatter": "cucumber-json-formatter"
    },

### Test code to reproduce

npm install @badeball/cypress-cucumber-preprocessor

### Versions

* **Cypress version**: 10.6.0
* **Preprocessor version**:12.1.0
* **Node version**:14.8.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Afaik, you shouldn't have to specify `json.formatter` in either case. I run tests on both windows and linux (as part of this project's CI) and I don't.

**Comment by deepakksusarla** [comment]
Thanks for the reply. Do I need to download json-format's binary files(windows, linux) or not required?

**Comment by badeball** [comment]
_That_ is required.

**Comment by deepakksusarla** [comment]
Thanks. Got the answer. Closing the ticket
