### ISSUE TITLE
Overwriting of stepDefinitions is not working

### ISSUE THREAD

**Issue by simon-ittmann** [badeball/cypress-cucumber-preprocessor#812]
### Current behavior

We want to overwrite the **stepDefinitions** like this:
```
{
  "stepDefinitions": [
    "src/[filepath]/**/*.ts",
    "src/[filepath].ts",
    "src/@common-steps/**/*.ts"
  ]
}
```

In the package.json it has no effect. If we add a **.cypress-cucumber-preprocessorrc.json** file this error will be thrown:

![error](https://user-images.githubusercontent.com/12498062/186451039-aa4a6edb-c02b-4bee-bffa-2da93865e18c.PNG)

In the json-parser an empty space is appended as first sign to the json string, what causes the error.

### Desired behavior

No error should be thrown

### Test code to reproduce

https://github.com/simon-ittmann/cypress-cucumber-global-steps

### Versions

See github repo below

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Your file contains a byte order mark.

**Comment by simon-ittmann** [comment]
Solves the problem, thank you :)
