### ISSUE TITLE
HTML Report only shows the time execution of the first .feature

### ISSUE THREAD

**Issue by ghost** [badeball/cypress-cucumber-preprocessor#813]
### Current behaviour

HTML Report only shows the time execution of the first *.feature

<img width="729" alt="image" src="https://user-images.githubusercontent.com/110224377/186877866-5d3096ca-5092-42e2-ae9a-d9803e7b3ce9.png">

 
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/110224377/186878294-80824bae-1e50-4b9e-be71-553bb0b398c1.png">

### Desired behaviour

The report should show the total time of execution 

**_45 seconds_** 

### Test code to reproduce

Create two *.feature files and execute them together

### Versions

* **Cypress version*10.3.1*:
* **Preprocessor version*12.1.0*:
* **Node version*16.16.0*:

### Checklist

- [ ok] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ok] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ok] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Looks like I was a little bit quick in https://github.com/badeball/cypress-cucumber-preprocessor/issues/798. I understand why it happens, but I'm unable to fix it right away. It shouldn't be too hard and anyone is welcome to take a stab at it if they want.

**Comment by badeball** [comment]
This has been fixed in v12.2.0.
