### ISSUE TITLE
[Question] Is it possible to run steps on different viewports?

### ISSUE THREAD

**Issue by conrad-azzopardi** [badeball/cypress-cucumber-preprocessor#814]
Is there a quick and easier way to run steps on multiple viewports?

At the moment I am able to do a forEach javascript in every step, but would prefer if there was a way of doing something globally, rather than having the same forEach repeated across all steps.

Thanks,

**Comment by badeball** [comment]
Being explicit about it in each steps sounds like the easy and preferred way tbh. What else did you have in mind?

**Comment by conrad-azzopardi** [comment]
To have it at least every scenario, or every feature file. In cypress (without cucumber) you can have the javascript forEach every it. which occurs less often then every step.

I'm trying to reduce repeated code as much as possible

**Comment by badeball** [comment]
So you're not actually trying to repeat a single step, but rather a whole scenario? I'd look into scenario outlines. Aside from that, there's nothing that Cucumber can help you with.

**Comment by jordan-bite** [comment]
@conrad-azzopardi Did you happen upon a solution for this? I'm attempting to do the same, repeat all features for multiple viewports.

**Comment by jbjhjm** [comment]
Same here @jordan-bite ... but I'm not optimistic. Been investigating for a while and nothing besides Scenario Outlines or running the whole test suite multiple times with different environment data came up.

**Comment by conrad-azzopardi** [comment]
The only 'solution' I have found is to have the scenarios doubled, and add a variable that says "on 'Desktop' " and "on 'Mobile' "

Not what I wanted, but gets the job done.
