### ISSUE TITLE
Cannot run my .feature file if there is a hooks in support/e2e.js

### ISSUE THREAD

**Issue by sonwilwil** [badeball/cypress-cucumber-preprocessor#815]
### Current behavior

<img width="469" alt="image" src="https://user-images.githubusercontent.com/105593675/187234690-6b9fbf4a-94b3-4804-8cff-e35673378409.png">

### Desired behavior

should it be fine ? i'm still learning to implement cucumber on cypress 10

### Test code to reproduce

<img width="662" alt="image" src="https://user-images.githubusercontent.com/105593675/187235002-58648a56-fbec-463c-867d-52779320d051.png">

### Versions

* **Cypress version**: "^10.6.0"
* **Preprocessor version**: "^12.1.0"
* **Node version**: "v16.14.2"

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I don’t understand what you’re asking here.
