### ISSUE TITLE
Is there any way to find whether test is passed or failed in After hook?

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#816]
### Current behavior

1. Is there any way to find whether running scenario is passed or failed in after hook class? (In previous Cypresss-Cucumber-Preprocessor, we can get the status from this command **testState.runTests[testState.currentScenario.name][testState.currentStep]** likewise do we have any way to achieve this here?)
2. Also do we have any possibility to get tag name of running scenario inside before hook class? (This is not possible in previous version asking whether its possible now?)

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I can't be the one to provide general support for every user, so you need to find somewhere else to ask these types of questions.
