### ISSUE TITLE
Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by maobat** [badeball/cypress-cucumber-preprocessor#818]
### Current behavior

![error_cypress](https://user-images.githubusercontent.com/102359319/187658025-20300325-f0b8-45a3-b685-ff717ed115d5.PNG)

### Desired behavior

exec the test

### Test code to reproduce
via terminal Visual Studio Code
.\node_modules\.bin\cypress open 

### Versions

* **Cypress version**: 10.6.0
* **Preprocessor version**: "@badeball/cypress-cucumber-preprocessor": 12.1.0
* **Node version**: v16.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by maobat** [comment]
I'm trying to run the feature file to exec the integrated Cypress-Cucumber test

**Comment by badeball** [comment]
You need to read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
