### ISSUE TITLE
Cypress tags does not run the tagged scenario if I run it along with --env environment variables in it

### ISSUE THREAD

**Issue by dominicd1986** [badeball/cypress-cucumber-preprocessor#819]
### Current behavior

I have a feature say test.feature, I have 2 scenarios in the feature as mentioned below,

@test
Scenario: Invalid test
Given =======
===

@devlopment
Scenario: Invalid test part 2
Given =======
=====

When I use the command from terminal "npx cypress-tags run -e TAGS=@test --headed --no-exit" , it runs the first scenario successfully it works well no issue with that,
 but when I use the command with the environment variables like "npx cypress-tags run -e TAGS=@test --env envValue=dev", it runs the entire feature that is both the screnarios in test.feature. I need a way to run only one screnario tagged as @test .

### Desired behavior

I need a way to run only one screnario tagged as @test when the command has environment details added to it

### Test code to reproduce

npx cypress-tags run -e TAGS=@test --env envValue=dev

### Versions

* **Cypress version* 9.7.0*:
* **Preprocessor version*4.3.0*:
* **Node version*14.15.4*:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#--env--tags-isnt-picked-up
