### ISSUE TITLE
Error from argument must be of type string

### ISSUE THREAD

**Issue by tuddilue** [badeball/cypress-cucumber-preprocessor#822]
### Current behavior
I'm trying to upgrade from thebrainfamily version.
When I run a feature file I get this error:

Error: Webpack Compilation Error

Module build failed (from ./node_modules/@badeball/cypress-cucumber-preprocessor/webpack.js):
TypeError: The "from" argument must be of type string. Received undefined
    at Watching.handle [as handler] (\node_modules\@cypress\webpack-preprocessor\dist\index.js:176:23)

I'm using a webpack file and I think that the problem is there somewhere but I do not understand why.
It looks like this:

const webpack = require("@cypress/webpack-preprocessor");
const fkcyaxe = require("fk-cypress-axe/plugins");

const options = {
    webpackOptions: {
        resolve: {
            extensions: [".ts", ".js"],
        },
        node: {
            fs: "empty",
            // eslint-disable-next-line camelcase
            child_process: "empty",
            readline: "empty",
        },
        module: {
            rules: [
                {
                    test: /\.feature$/,
                    use: [
                        {
                            loader: require.resolve(
                                "@badeball/cypress-cucumber-preprocessor/webpack",
                            ),
                        },
                    ],
                },
                fkcyaxe.webpackLoadingRule,
            ],
        },
    },
};

function install(on, config) {
    on("file:preprocessor", webpack(options));
    return config;
}

module.exports = { install, options };

My package.json file looks like this:
    "cypress-cucumber-preprocessor": {
        "json": {
            "enabled": true
        }
    }
So I wonder if womeone has the same problem?
Or if you have a fix for this?

### Versions

* **Cypress version**: 9.5.3
* **@cypress/webpack-preprocessor**: "^5.11.1",
* **@badeball/cypress-cucumber-preprocessor**: "12.1.0",
* **Node version**: 16.15.0

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You’re not passing configuration options to the loader. Take a closer look at the webpack examples in the (this) repo.

**Comment by tuddilue** [comment]
Aha thanks I will test that and come back to you.

**Comment by tuddilue** [comment]
@badeball I have tested it now. I had to rewrite the webpack file so I could access the config. Then it worked like a charm! So thank you for fast answer!

**Comment by xiaoqing-zoe** [comment]
@tuddilue can you tell me which configuration you added to resolve this issue? I face the same issue as well
