### ISSUE TITLE
commonPath property doesn't work

### ISSUE THREAD

**Issue by tuddilue** [badeball/cypress-cucumber-preprocessor#823]
I'm using common parts for my cucumber tests.
With the TheBrainFamily/cypress-cucumber-preprocessor I used the commonPath property in the package.json file.

Looks like this in package.json:
```
    "cypress-cucumber-preprocessor": {
        "commonPath": "tests/e2e/specs/cucumber/common"
    }
```

But when running the testcase the searching part doesn't find the common stepdefinition. It looks like this:
```
We tried searching for files containing step definitions using the following search pattern templates:

  - tests\e2e\specs/[filepath]/*/.{js,mjs,ts,tsx}
  - tests\e2e\specs/[filepath].{js,mjs,ts,tsx}
  - cypress/support/step_definitions/*/.{js,mjs,ts,tsx}

These templates resolved to the following search patterns:

  - tests\e2e\specs\cucumber\0.Forsteg\*.{js,mjs,ts,tsx}
  - tests\e2e\specs\cucumber\0.Forsteg.{js,mjs,ts,tsx}
  - cypress\support\step_definitions\*.{js,mjs,ts,tsx}

These patterns matched the following files:

  - tests\e2e\specs\cucumber\0.Forsteg\Forsteg.StepDefinition.js
  - 
  ```
So in Forsteg.StepDefinition.js my other steps that is not common is placed.

So I'm wondering how do you specify common steps?
Is it another way than the TheBrainFamily did do it?

### Versions
* **Cypress version**: 9.5.3
* **Preprocessor version**: 12.1.0
* **Node version**: 16.15.0

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md
