### ISSUE TITLE
Need to update documentation in npm

### ISSUE THREAD

**Issue by satya319** [badeball/cypress-cucumber-preprocessor#828]
### Current behavior

- cypress is now 10.XX 
- It is confusing where to add which line of code
### Desired behavior

- Need to update readme file according the latest cypress version

### Versions

* **Cypress version**: 10.6.0
* **Preprocessor version**:4.3.1
* **Node version**:14.16.X

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> I'm not using cypress-cucumber-preprocessor@4.3.1 (package name has changed and it is no longer the most recent version, see https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).
