### ISSUE TITLE
Not able to Execute test case using Cucumber in Cypress v10.3

### ISSUE THREAD

**Issue by gurinder-singh** [badeball/cypress-cucumber-preprocessor#829]
Got the Below error on Chrome browser while running 
Error
The following error originated from your test code, not from Cypress.

> Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
[C:/Users/DELL/Cypress_Automation/node_modules/@badeball/cypress-cucumber-preprocessor/lib/assertions.js:7:1](http://localhost:52892/__/#)
   5 | const package_json_1 = require("../package.json");
   6 | function fail(message) {
>  7 |     throw new Error(`${message} (this might be a bug, please report at ${package_json_1.homepage})`);
     | ^
   8 | }
   9 | exports.fail = fail;
  10 | function assert(value, message) {

the test file code:
import { Given, When, Then } from "@badeball/cypress-cucumber-preprocessor";
Given('I Opened Login page',()=>{
    cy.visit('http://zero.webappsecurity.com/login.html')

    })
    when ('I submit Login',()=>{
        cy.get('#user_login').type('username')
        cy.get('#user_password').type('password')
        cy.get('input[name="submit"]').click()      
        })
    Then('I Should see home page',()=>{

        cy.get('#account_summary_tab').should('be.visible')
    })

the Feature File :
Feature: login to application

As a Valid user 
I want to log into the application 

Scenario: Valid Login
Given I Opened Login page
When I submit Login
Then I Should see home page

e2e file
// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')
//For Cucumber Integration
const createEsbuildPlugin =
  require('@badeball/cypress-cucumber-preprocessor/esbuild').createEsbuildPlugin
const createBundler = require('@bahmutov/cypress-esbuild-preprocessor')
const nodePolyfills =
  require('@esbuild-plugins/node-modules-polyfill').NodeModulesPolyfillPlugin
const addCucumberPreprocessorPlugin =
  require('@badeball/cypress-cucumber-preprocessor').addCucumberPreprocessorPlugin
module.exports = async (on, config) => {
  await addCucumberPreprocessorPlugin(on, config) // to allow json to be produced
  // To use esBuild for the bundler when preprocessing
  on(
    'file:preprocessor',
    createBundler({
      plugins: [nodePolyfills(), createEsbuildPlugin(config)],
    })
  )
  return config
}

**Comment by badeball** [comment]
You're not providing enough information for me to reproduce the issue here. You need to provide me with a runnable example that illustrates it.

**Comment by gurinder-singh** [comment]
cypress.config.js 
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      "experimentalSessionAndOrigin";"true"
      
      "testFiles"; "**/*.{feature,features}"
      
      
    },
  },
});

package.json file
{
  "name": "newtocypress",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^12.2.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.3",
    "@esbuild-plugins/node-modules-polyfill": "^0.1.4",
    "cypress": "^10.3.1",
    "cypress-file-upload": "^5.0.8"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/e2e/cucumber-test/**/*.{js,ts}"
  }
}
 Do let me know if any other file specification is required from my end

**Comment by badeball** [comment]
You need to provide me with a runnable example that illustrates the issue, IE. a repository that I can clone.

**Comment by gurinder-singh** [comment]
https://github.com/gurinder-singh/Cucumber-Cypress-   pls check this repo.

**Comment by badeball** [comment]
Your `cypress/support/e2e.js` is wrong, the code doesn't go there. I recommend checking out any of the many [examples](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples).

**Comment by badeball** [comment]
Closing as answered.
