### ISSUE TITLE
[cypress-cucumber-preprocessor in nx]0 passing but successful run

### ISSUE THREAD

**Issue by dereklin** [badeball/cypress-cucumber-preprocessor#830]
### Current behavior

I am trying to add cypress-cucumber-preprocessor in nrwl/nx

![Screen Shot 2022-09-19 at 4 55 40 PM](https://user-images.githubusercontent.com/2231799/191140321-8c3a5326-ec2b-4a9d-bf28-233b6437da15.png)

The feature was found, but it won't fail

### Desired behavior

It should fail when the test is not passing

### Test code to reproduce

Please follow the readme in my repo: https://github.com/dereklin/nx-cucumber-preprocessor

### Versions

* **Cypress version**: ^10.7.0
* **Preprocessor version**: ^13.0.0
* **Node version**: v14.17.0

### Checklist

- [ x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
`apps/hello-e2e/src/e2e/landing.feature` is empty, so why are you expecting failure?

**Comment by dereklin** [comment]
@badeball Thanks for catching that.  I was troubleshooting and didn't realize the file was empty.  I have created another issue that was exactly where I was stuck: https://github.com/badeball/cypress-cucumber-preprocessor/issues/832
