### ISSUE TITLE
The generated Cucumber HTML Report is not processing properly when parameters are used in the .feature files.

### ISSUE THREAD

**Issue by youvegotnigel** [badeball/cypress-cucumber-preprocessor#831]
### Current behavior

Given when a scenario is written as below:
    Scenario Outline: <scenario_name>
        When A user provides incorrect credentials
            | username          | password |
            | <user_name>   | <pass_word>      |
        And A user clicks on the login button
        Then The error message "Epic sadface: Username and password do not match any user in this service" is displayed

        Examples:
            | user_name  | pass_word | scenario_name                    |
            | testName | secret_sauce   |  Incorrect Username Login  |
            | standard_user | testPassword  |  Incorrect Password Login    |

In this case the actual cucumber HTML report is displayed like this
![image](https://user-images.githubusercontent.com/48122863/191163342-a09b6edd-27af-4b1e-a821-2b6c56528614.png)

The same can be viewed when try to generate the cucumber report in Jenkins using the cucumber-report.json.json file.
![image](https://user-images.githubusercontent.com/48122863/191164924-4832d671-873a-4a01-9880-8bcc60e32347.png)

This is my .cypress-cucumber-preprocessorrc.json
```
{
  "json": {
    "enabled": true,
    "output": "reports/cucumber-report.json",
    "formatter": "cucumber-json-formatter.exe"
  },
  "messages": {
    "enabled": true,
    "output": "reports/cucumber-messages.ndjson"
  },
  "html": {
    "enabled": true,
    "output": "reports/cucumber-report.html"
  },
  "stepDefinitions": [
      "[filepath]/**/*.{js,ts}",
      "[filepath].{js,ts}",
      "cypress/e2e/step_definitions/*.{js,ts}"
  ]
}
```

### Desired behavior
![image](https://user-images.githubusercontent.com/48122863/191163444-0853d089-84e5-47e9-b1ec-abef27dc90eb.png)

In the expected behavior the parameters used in the feature file should be replaced by the values given in the examples section as above.

### Test code to reproduce

https://github.com/youvegotnigel/cypress-cucumber-allure-demo/blob/master/cypress/e2e/features/login.feature

Execute this via `npm run cy:run`
The cucumber report will be generated in the "reports" folder.

### Versions

```
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^12.1.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.3",
    "cypress": "^10.7.0",
    "esbuild": "^0.14.48",
    "multiple-cucumber-html-reporter": "^2.0.0",
    "@shelex/cypress-allure-plugin": "^2.31.0",
}
```
* **Node version**: v16.15.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is something you should ask the authors of `multiple-cucumber-html-reporter` of.

https://github.com/wswebcreation/multiple-cucumber-html-reporter

**Comment by youvegotnigel** [comment]
Hi @badeball 
Thank you for your reply,
Actually here I'm talking about the HTML report generated from the " .cypress-cucumber-preprocessorrc.json"

I have enabled the HTML report in the preprocessorrc as below:
```
{
  "json": {
    "enabled": true,
    "output": "reports/cucumber-report.json",
    "formatter": "cucumber-json-formatter.exe"
  },
  "messages": {
    "enabled": true,
    "output": "reports/cucumber-messages.ndjson"
  },
  "html": {
    "enabled": true,
    "output": "reports/cucumber-report.html"
  },
  "stepDefinitions": [
      "[filepath]/**/*.{js,ts}",
      "[filepath].{js,ts}",
      "cypress/e2e/step_definitions/*.{js,ts}"
  ]
}
```
I'm not 100% sure but I think since the HTML report is generated from the "**cucumber-report.json**", This needs to be fix from that point.
Please correct me if I'm wrong.

**Comment by badeball** [comment]
_That_ HTML report is generated by https://github.com/cucumber/html-formatter and https://github.com/cucumber/react-components, so any suggestions should posted in either of those.
