### ISSUE TITLE
[cypress-cucumber-preprocessor in nx] definitions not found

### ISSUE THREAD

**Issue by dereklin** [badeball/cypress-cucumber-preprocessor#832]
I am trying to add cypress-cucumber-preprocessor in nrwl/nx

<img width="991" alt="image" src="https://user-images.githubusercontent.com/2231799/191275496-26bd082a-fbed-4ab0-b430-04f605694c65.png">

### Desired behavior

The step definition should be found in apps/hello-e2e/src/e2e/landing/landing.ts

### Test code to reproduce

Please follow the readme in my repo: https://github.com/dereklin/nx-cucumber-preprocessor

### Versions

* **Cypress version**: ^10.7.0
* **Preprocessor version**: ^13.0.0
* **Node version**: v14.17.0

### Checklist

- [ x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Looks like there's a bug in handling absolute paths in `stepDefintiions`. You should use relative paths for now.

**Comment by badeball** [comment]
I've fixed this with v13.0.1.

**Comment by dereklin** [comment]
Wow @badeball, you are super fast!  Awesome!  Thanks!
