### ISSUE TITLE
How can I set custom configurations for individual scenarios?

### ISSUE THREAD

**Issue by gusbmurphy** [badeball/cypress-cucumber-preprocessor#833]
I'm wondering how I can go about using custom configurations for individual scenarios, as is [described here in the Cypress documentation](https://docs.cypress.io/guides/guides/test-retries#Custom-Configurations). Specifically I'm looking to set a different amount of test retries for a particular scenario.

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/test-configuration.md

**Comment by badeball** [comment]
Examples shows a tagged feature, but scenarios can be tagged similarly.

**Comment by gusbmurphy** [comment]
Thanks for the quick response and my apologies for not finding this in the documentation!
