### ISSUE TITLE
Json report not generated while testing from Cypress UI runner

### ISSUE THREAD

**Issue by mrsenzy** [badeball/cypress-cucumber-preprocessor#834]
### Current behavior

cucumber Json report not generated while testing from Cypress UI runner

### Desired behavior

Json report get generated while testing from Cypress UI runner as earlier versions

### Test code to reproduce

1) Add @badeball/cypress-cucumber-preprocessor@12.0.0
2) Cypress 10.3.0
3) Cypress open 
4) Run any feature spec 

### Versions

* **Cypress version**: 10.3.0
* **Preprocessor version**: 12.0.0
* **Node version**: 14.17.5

### Checklist

- [X ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/776#issuecomment-1194662310
