### ISSUE TITLE
Issue while generating json report in Linux

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#835]
### Current behavior

Feature files are executing but Issue occurred while generating the JSON report in linux.

**"An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

Error: spawn cucumber-json-formatter ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)"**

I did download and placed cucumber-json-formatter inside my folder but its not picking I suppose. Instead of downloading cucumber-json-formatter, renaming and placing it in my execution folder manually, Can we use **cucumber** dependency to import json formatter from cucumber dependency and get the required work done?

Like,
const JsonFormatter = require('cucumber').JsonFormatter;
const { defineSupportCode } = require('cucumber');

const outputDir = './';

'use strict';

defineSupportCode(({ After, registerListener }) => {

  const jsonFormatter = JsonFormatter;

  jsonFormatter.log = function (string) {

   console.log(string);

  };

  registerListener(jsonFormatter);
});

### Desired behavior

JSON has to be created

### Test code to reproduce
**.cypresscucumberrc.json**
{
    "json": {
        "enabled": true,
        "output": "cypress/reports/SANITY/json/log.json"
    },
    "messages": {
        "enabled": true,
        "output": "cypress/reports/SANITY/json/messages.ndjson"
    },
    "html": {
        "enabled": true,
        "output": "cypress/reports/SANITY/html/AutomationReport.html"
    },
    "stepDefinitions": [
        "cypress/e2e/stepDefinitions/*.{js,ts}"
    ],
    "filterSpecs": true,
    "omitFiltered": true
}
**Config**
import { defineConfig } from "cypress";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import browserify from "@badeball/cypress-cucumber-preprocessor/browserify";
async function setupNodeEvents(
    on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
    await addCucumberPreprocessorPlugin(on, config);
    on(
        "file:preprocessor",
        browserify(config, {
            typescript: require.resolve("typescript"),
        })
    );
    return config;
};
export default defineConfig({
    e2e: {
        baseUrl: "XXXX",
        chromeWebSecurity: false,
        excludeSpecPattern: "*.ts",
        specPattern: "**/*.feature",
        setupNodeEvents,
    },
});

### Versions

* **Cypress version**: 10.6.0
* **Preprocessor version**:12.1.0
* **Node version**: 16.9.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> I did download and placed cucumber-json-formatter inside my folder but its not picking I suppose. Instead of downloading cucumber-json-formatter, renaming and placing it in my execution folder manually

This isn't how you install it, ref https://github.com/cucumber/json-formatter#linux

> Can we use cucumber dependency to import json formatter from cucumber dependency and get the required work done?

No.
