### ISSUE TITLE
[Request] Customisable report names or add date stamp

### ISSUE THREAD

**Issue by MassimoLobrutto** [badeball/cypress-cucumber-preprocessor#837]
Currently the default cucumber reports can only have a static file name
It would be good if there was a way to customise the report name or even just add a date stamp at the end of the filename
This would help identify which report was for which run when the tests have been run multiple times
Also the same filename means if a subsequent run is made then it overwrites the previous report html

**Comment by badeball** [comment]
[Cosmiconfig](https://github.com/davidtheclark/cosmiconfig) (used for reading configuration) allows for JS as configuration files, where you can create whatever file names you want. I think this is a sufficient solution.
