### ISSUE TITLE
[Request] Add JSON formatter to be used on Azure DevOps Pipeline

### ISSUE THREAD

**Issue by conventim** [badeball/cypress-cucumber-preprocessor#838]
Do you have any plans to add a JSON formatter to be used on DevOps Pipeline? I can't use cucumber-json-formatter as mentioned in your documentation?

I tried to use it on Azure Pipeline but it's not working.
This is the error on the pipeline
<img width="1176" alt="Schermata 2022-09-22 alle 15 11 20" src="https://user-images.githubusercontent.com/45484365/191756495-7e7c1400-f0d9-4dd1-b8c4-e9d977c83b3b.png">

I tried to check if the file is missing but it seems to be in the right path
<img width="1179" alt="Schermata 2022-09-22 alle 15 11 47" src="https://user-images.githubusercontent.com/45484365/191756749-24d452a1-5dae-4828-b875-3e79a52b1e66.png">

I tried also to give right permission with command `chmod +x cucumber-json-formatter` with no success.
On my Mac it works fine.

I saw also this issue/request but i don't know if is connected
https://github.com/badeball/cypress-cucumber-preprocessor/issues/810

**Comment by badeball** [comment]
There's nothing with `cucumber-json-formatter` that make it not work in a pipeline. Putting it in the root directory is just not how it's installed, ref https://github.com/cucumber/json-formatter#linux (it must be in your `PATH`).

**Comment by conventim** [comment]
Hi @badeball, i tried to add cucumber-json-formatter folder to Azure DevOps agent `PATH` and to make it executable with `chmod +x cucumber-json-formatter` but when I try to run `cucumber-json-formatter --help` i get this error
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/45484365/192224816-b5889508-21a2-468f-a1bd-9be475a1a584.png">
Could you help me please?
Thanks a lot
