### ISSUE TITLE
Cannot import "And" Cucumber keyword, getting erro (0 , import_cypress_cucumber_preprocessor.And) is not a function

### ISSUE THREAD

**Issue by FatmaHameed** [badeball/cypress-cucumber-preprocessor#839]
### Current behavior

When imported "And" using import { Given, When, And, Then } from '@badeball/cypress-cucumber-preprocessor', the Cypress test stopped with TypeError: import_cypress_cucumber_preprocessor.And) is not a function.

### Desired behavior

I want to be able to import and use "And" keyword. 

I have solved this issue currently by uninstalling the latest version of @badeball/cypress-cucumber-preprocessor, and then installing a previous version (11.4.0) as this version worked fine with "And" keyword

### Test code to reproduce

```
import { Given, When, And, Then } from '@badeball/cypress-cucumber-preprocessor'

Given('I visit {string}', (url) => {
  cy.visit(url);
});

When('I click on register link', () => {
  home.clickRegisterLink();
});

And('I type', (datatable) => {
  datatable.hashes().forEach((data) => {
    register.typeFirstName(data.firstname);
    register.typeLastName(data.lastname);
    register.typeUsername(data.username);
    register.typePassword(data.password);
  });
});
```

### Versions

* **Cypress version*10.8.0*:
* **Preprocessor version*13.0.1*:
* **Node.js version*14.4.0*:
* **Node-semver version*1.0.0*:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
These has been deprecated and removed in v13.0.0, ref. https://github.com/badeball/cypress-cucumber-preprocessor/issues/821. TLDR: use `Given`, `When` or `Then`.

**Comment by nursulnbc** [comment]
> These has been deprecated and removed in v13.0.0, ref. #821. TLDR: use `Given`, `When` or `Then`.

Why deprecated? Let's bring it back

**Comment by shieldsi** [comment]
Are the any plans to bring the And keyword back?

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#function-members-and-and-but-are-missing

**Comment by Arslanmalik47** [comment]
Use When instead of And
