### ISSUE TITLE
Add support for Cypress-cucumber-preprocessor in nx projects

### ISSUE THREAD

**Issue by alexmonteirocastro** [badeball/cypress-cucumber-preprocessor#840]
### Current behavior

Hello, I would like to add cypress-cucumber preprocessor to an nx project of mine but, unfortunately there seems to be no support to it or, even if there is, I can't find any documentation. 
Could someone please help? 
 
### Desired behavior

There should be out-of-the-box support for nx projects or at least some proper documentation on how to configure it. 

### Versions

"cypress": "^10.7.0",
"@badeball/cypress-cucumber-preprocessor": "^13.0.1",
"@nrwl/cypress": "^14.7.6"

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
The preprocessor is added to a _cypress project_ and it's not really relevant whether that is contained within NX or anything else. Any of the examples should still suffice. I can't help you any further with this.
