### ISSUE TITLE
TypeError: cypress_esbuild_preprocessor_1.createBundler is not a function

### ISSUE THREAD

**Issue by alexmonteirocastro** [badeball/cypress-cucumber-preprocessor#842]
### Current behavior

When I follow the setup according to the [quick-start guide](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md)

I see this

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/35965983/191848031-237e6ae6-9da5-40da-bb3e-9de55d4fb126.png">

When I change the import from 

```ts
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
```

to 

```ts
import { createBundler } from "@bahmutov/cypress-esbuild-preprocessor";
```

Then the warning disappears. 

But when I try to run the cucumber tests I get this error:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/35965983/191848905-7e83c4d8-1b57-4e46-8d8b-f289466f6b8d.png">

Also the `@bahmutov/cypress-esbuild-preprocessor` didn't came install so I had to install it separately, but there was nothing mentioned in the documentation. 

### Desired behavior

Documentation should describe the need to download `@bahmutov/cypress-esbuild-preprocessor` and we should be able to import the createBundler without error. 

### Test code to reproduce

See snippet above

### Versions

"cypress": "^10.7.0"
"@badeball/cypress-cucumber-preprocessor": "^13.0.2",
"@bahmutov/cypress-esbuild-preprocessor": "^2.1.4",

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I’m guessing your hitting the same thing described here: https://github.com/badeball/cypress-cucumber-preprocessor/pull/826#issuecomment-1242007788

**Comment by alexmonteirocastro** [comment]
> I’m guessing your hitting the same thing described here: [#826 (comment)](https://github.com/badeball/cypress-cucumber-preprocessor/pull/826#issuecomment-1242007788)

Thank you. 
Would it be possible to update the documentation? Thank you

**Comment by alexmonteirocastro** [comment]
@badeball the fix mentioned on [this comment](https://github.com/badeball/cypress-cucumber-preprocessor/issues/790#issuecomment-1205886614) solved it but maybe it could be good to update documentation as I suspect i won't be the only user asking this question. 
Shall I open a new issue or could I contribute with a PR for update documentation?

**Comment by badeball** [comment]
a2702f5ce247c96269a0432358ed919b596a4dbb
