### ISSUE TITLE
Test step "And" is not accessible

### ISSUE THREAD

**Issue by raj-iwt** [badeball/cypress-cucumber-preprocessor#843]
"When, Then, and Before" are accessible. But "And, But" are not accessible to use. The error says there is no exported member.

![image](https://user-images.githubusercontent.com/82278707/192125916-4b55ab65-239c-4120-9a95-10d0b61dc71f.png)

**Comment by tuan-yojee** [comment]
Hi @raj-iwt, 
`And` and `But` have been removed. You can check the version [v13.0.0](https://github.com/badeball/cypress-cucumber-preprocessor/releases/tag/v13.0.0) to get more information.
