### ISSUE TITLE
Upgrading to Cypress 10

### ISSUE THREAD

**Issue by mathpunk** [badeball/cypress-cucumber-preprocessor#844]
I'm upgrading to Cypress 10. I've been knocking out errors after running the upgrade wizard, and this one has me stumped:

```
Error: Webpack Compilation Error
Module build failed (from ./node_modules/@badeball/cypress-cucumber-preprocessor/webpack.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at handle (/Users/tomhenderson/lg/logicgate/platform/cypress/src/e2e/node_modules/@cypress/webpack-preprocessor/dist/index.js:180:23)
   ...
```

Here's what I think is the relevant portion of my webpack config:

```
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: "ts-loader"
          }
        ]
      },
      {
        test: /\.feature$/,
        use: [
          {
            loader: "@badeball/cypress-cucumber-preprocessor/webpack" // This used to be "cypress-cucumber-preprocessor/loader"; the error before the one I posted was, this loader couldn't be found at all
          }
        ]
      }
    ]
  },
```

### Versions

- node 14.20.0
- "cypress": "^10.8.0",
- "@cypress/webpack-preprocessor": "^5.12.2",
- "@badeball/cypress-cucumber-preprocessor": "^13.0.2",
- "@types/cypress-cucumber-preprocessor": "^4.0.1",

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/822
