### ISSUE TITLE
Missing preprocessor event handlers (this usally means you've not invoked addCucumberPreprocessorPlugin() or not returned the config object in setupNodeEvents()

### ISSUE THREAD

**Issue by kadhaner** [badeball/cypress-cucumber-preprocessor#845]
### Current behavior

When I run my test and click on feature file in test runner, I am getting this error

_Missing preprocessor event handlers (this usally means you've not invoked addCucumberPreprocessorPlugin() or not returned the config object in setupNodeEvents()_

### Desired behavior
It should navigate to the selected feature and run the scenarios in feature file

### Versions

  "cypress": "^10.8.0",
 "@badeball/cypress-cucumber-preprocessor": "^13.0.2",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.5",
    "@cypress/code-coverage": "^3.10.0",
    "@esbuild-plugins/node-modules-polyfill": "^0.1.4",

Node Version v14.17.0
### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md#example-setup

**Comment by kadhaner** [comment]
The issue is not resolved . Can you please provide javascript code for cypress.config.js.

**Comment by badeball** [comment]
It's in the above-mentioned link.
