### ISSUE TITLE
[Request] BeforeStep and AfterStep Hooks

### ISSUE THREAD

**Issue by ghost** [badeball/cypress-cucumber-preprocessor#847]
Would it be possible to implement BeforeStep and AfterStep hooks?

Example usage would be to take screenshots after each successful step.

**Comment by alexmonteirocastro** [comment]
Already implemented [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/cucumber-basics.md#hooks). 
If you want `beforeAll()` and `afterAll()` hooks simply add `before()` and `after()` hooks in the step definition file. 

As per example below:

```ts
// FeatureName.ts

before(() => {
    cy.log('this is before ALL')
})

Before(() => {
    cy.log('this is BEFORE each')
 });
```

**Comment by ghost** [comment]
> Already implemented [here](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/cucumber-basics.md#hooks). If you want `beforeAll()` and `afterAll()` hooks simply add `before()` and `after()` hooks in the step definition file.
> 
> As per example below:
> 
> ```ts
> // FeatureName.ts
> 
> before(() => {
>     cy.log('this is before ALL')
> })
> 
> Before(() => {
>     cy.log('this is BEFORE each')
>  });
> ```

Maybe I didn't word this correctly or you misunderstood. 
I am aware of these hooks. They only run before and after the whole script or scenario.

What I was asking for was if it was possible to implement hooks that run before and after each individual step definition

**Comment by badeball** [comment]
Given that this exist in cucumber-js, this is a reasonable addition. I have some questions that needs to be answered about their implementation:

- Are AfterStep hooks executed despite step failure? This wouldn't be possible in Cypress
- Are these type of hooks reflected in messages output?

I'm open to contributions here. It's likely not a complicated addition, but I don't strictly require this myself and I don't have a lot of spare time lately to prioritize development.

**Comment by kogratte** [comment]
If it is possible to get information about the current scenario, it will be great. I'm facing a case where I would like to add custom tags to indicate which python fixture file I should use, and use this information to run the python task. Looks like the perfect solution!

**Comment by badeball** [comment]
Check out the somewhat undocumented `doesFeatureMatch(..)`.

https://github.com/badeball/cypress-cucumber-preprocessor/blob/cb6f7882870a0be4bffe1de5db580d058f7a15b9/features/mixing_types.feature#L20-L24

It might something for you. You can eg. ask if the current scenario is tagged with both foo and bar a `doesFeatureMatch("@foo and @bar")`.

**Comment by kogratte** [comment]
@badeball I'll take a look at the implementation, but for the record, is this method able to tackle dynamic tags?
eg:
```
@fixture('myFile')
```

Then extract `myFile` and run the task using it.

**Comment by badeball** [comment]
No, tags are just strings and your string happens to contain parentheses and something that looks like an argument, but that's not part of tag expressions, ref. https://cucumber.io/docs/cucumber/api/?lang=javascript#tag-expressions and https://www.npmjs.com/package/@cucumber/tag-expressions.

**Comment by badeball** [comment]
I have implemented intelligent parsing of such tags (seen in https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/lib/tag-parser.test.ts), but that's not exposed. What is it that you're trying to achieve here?

**Comment by kogratte** [comment]
It looks like, yes.  I would like to access the current scenario infos, including tags, whether inherited from feature or not. Even after inspecting the Cypress object, nothing seems to be usable.

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/search?q=testState&type=issues

**Comment by kogratte** [comment]
I've got something which looks promising, but I'm not sure it worth to be
part of preprocessor.

I'll anonymize my codebase and share it with you ASAP, but thanks pointing
me in the direction!

Le mar. 11 oct. 2022 à 16:38, Jonas Amundsen ***@***.***> a
écrit :

**Comment by manv6** [comment]
@kogratte any update on sharing your solution?

**Comment by kogratte** [comment]
I've been fired since then and don't have access to the solution anymore, I
need to rebuilt it from the ground -_-

Le lun. 7 nov. 2022 à 11:09, Manolis Vlastos ***@***.***> a
écrit :

**Comment by youvegotnigel** [comment]
Is there any workaround for this? My goal is to take a screenshot of the web page after the execution of each step definition and attach it to the cucumber report.

**Comment by marcrecor** [comment]
It would be great to have BeforeStep and AfterStep Hooks. I'd like to be able to take a screenshot after each step.

Also I think it would be interesting to have BeforeFeature and AfterFeature Hooks


@badeball

**Comment by badeball** [comment]
This has been fixed with v17.2.0. Check it out and comment.

**Comment by marcrecor** [comment]
@badeball Check on v17.2.0 BeforeStep and AfterStep Hooks are included. Many thanks 😊 

But one comment:

`window.testState`  gives an error. With version 15.1.2, this doesn't append.

I use this to get the current step name from the actual scenario.

**Comment by badeball** [comment]
You need to be way more specific.

**Comment by youvegotnigel** [comment]
Thank you @badeball for this feature. It is working as expected in my project :)

**Comment by marcrecor** [comment]
Hi @badeball ,

With version 17.2.0, the implemetation that we have with `window.testState` shows and error because it doesn't recognized. It doesn't happen in version 15.1.2.

You can see more details in the image below.

![Captura de Pantalla 2023-06-09 a las 12 31 36](https://github.com/badeball/cypress-cucumber-preprocessor/assets/84714326/e50a1ddd-c628-4e7c-93f3-c7a881579b73)

**Comment by badeball** [comment]
The package doesn't offer any type information regarding this anymore, although the data is there.

**Comment by marcrecor** [comment]
Ok, so is there any option to access:

- current step name (in afterStep/beforeStep hooks)
- all steps in the current scenario (in after/before hooks)

With the latest version I access this data with `window.testState`.

**Comment by badeball** [comment]
You can still use `window.testState`, the data is there.

**Comment by RodrigoBarretosTR** [comment]
@marcrecor Ignore VS Code Intellisense telling you it doesn't exist. If you run the code with `window.testState` it will still work like before.

**Comment by marcrecor** [comment]
It has worked, many thanks 🥳🤠😁
