### ISSUE TITLE
Wanted to have the json logs without json-formatter.exe so that cucumber report can be generated

### ISSUE THREAD

**Issue by Keyur90** [badeball/cypress-cucumber-preprocessor#850]
### Current behavior

Unable to get the logs without using json-formatter.exe

### Desired behavior

I wanted to get the logs in JSON file of my last test run so that I can generate a cucumber report running on the agent through the CI pipeline. I can not check in json-formatter.exe so wanted eliminate the json-formatter.exe file usage.

### Versions

* **Cypress version**: 10.3.0
* **Preprocessor version**: 11.5.1
* **Node version**: 14.18.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by WTK** [comment]
That's probably not going to happen as this preprocessor relies on cucumber-json-formatter completely for json output (parsing cucumber messages to json format). That said, I'd love to hear from @badeball if there are ANY alternatives given that cucumber-json-formatter has several bugs (reported by him as well) that are stale since May.

**Comment by sagar-maheshwari** [comment]
I've been using https://github.com/Vitalizzzer/cucumber-json-report-formatter

It consumes the messages file and generates the JSON without the need for a formatter. However, they have an open issue where the step duration shows incorrectly, however, if it doesn't bother you, you can try this out.

**Comment by WTK** [comment]
Awesome, thanks for the tip, I'll try it out!

**Comment by Keyur90** [comment]
> I've been using https://github.com/Vitalizzzer/cucumber-json-report-formatter
> 
> It consumes the messages file and generates the JSON without the need for a formatter. However, they have an open issue where the step duration shows incorrectly, however, if it doesn't bother you, you can try this out.

Is this really a NPM package, provided by MIT Licence?

**Comment by Keyur90** [comment]
> I've been using https://github.com/Vitalizzzer/cucumber-json-report-formatter
> 
> It consumes the messages file and generates the JSON without the need for a formatter. However, they have an open issue where the step duration shows incorrectly, however, if it doesn't bother you, you can try this out.

Hey Sagar, thanks for referring to this. Do you mind if you can show me how have you used this? 
What I did is I created a file formatter.js and provided the below code within the same. (don't bother about the location)

import {Formatter} from 'cucumber-json-report-formatter';

const formatter = new Formatter()
const sourceFile = "./cucumber-messages.ndjson"
const outputFile = "./reports/cucumber-report.json"
await formatter.parseCucumberJson(sourceFile, outputFile)

**Comment by sagar-maheshwari** [comment]
You can run the js file using node after your test execution is finished, but the easiest way is to amend the configuration in `.cypress-cucumber-preprocessorrc.json` or `package.json` as below:

![image](https://user-images.githubusercontent.com/58690196/194033601-498e84d1-770e-4198-8342-da9adad20310.png)

**Comment by Keyur90** [comment]
> You can run the js file using node after your test execution is finished, but the easiest way is to amend the configuration in `.cypress-cucumber-preprocessorrc.json` or `package.json` as below:
> 
> ![image](https://user-images.githubusercontent.com/58690196/194033601-498e84d1-770e-4198-8342-da9adad20310.png)

I tried this but it is expecting to run cucumber-json-formatter and looking for that exe in the after:run tag event 
![image](https://user-images.githubusercontent.com/41822766/194433699-1f01f23f-8c13-47df-8737-4e2afdb2e146.png)

**Comment by jaxfellow** [comment]
@Keyur90 I guess we have the same problem, as described here #851

**Comment by sagar-maheshwari** [comment]
> > You can run the js file using node after your test execution is finished, but the easiest way is to amend the configuration in `.cypress-cucumber-preprocessorrc.json` or `package.json` as below:
> > ![image](https://user-images.githubusercontent.com/58690196/194033601-498e84d1-770e-4198-8342-da9adad20310.png)
> 
> I tried this but it is expecting to run cucumber-json-formatter and looking for that exe in the after:run tag event ![image](https://user-images.githubusercontent.com/41822766/194433699-1f01f23f-8c13-47df-8737-4e2afdb2e146.png)


Do you have a after:run event in your config? If yes, you'd need to amend it. example here: https://github.com/badeball/cypress-cucumber-preprocessor/issues/805#issuecomment-1218399297

**Comment by badeball** [comment]
> I can not check in json-formatter.exe so wanted eliminate the json-formatter.exe file usage.

I don't expect anyone to check this into VCS anymore than I expect you to check Node into it and that's fairly unheard of. I'm using it Gitlab actions myself, without any issues: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/.github/workflows/build.yml

Despite this, I do intend to replace it in time: https://github.com/badeball/cypress-cucumber-preprocessor/issues/870
