### ISSUE TITLE
ENV variables not being set either in config file or using --env flag in cli

### ISSUE THREAD

**Issue by mazza1892** [badeball/cypress-cucumber-preprocessor#852]
Hi there,

I'm having trouble with environment variables, seems like adding them in cypress.config.js or using --env cli does not register them in cypress. When I inspect the settings in the UI or print the env vars during tests I see the following.

<img width="531" alt="Screenshot 2022-10-07 at 09 41 53" src="https://user-images.githubusercontent.com/29543633/194511721-91f07b57-8480-4003-b682-111167e001e7.png">

If I use `cypress.env.json`, it registers my variables but it also shows the same error.

<img width="518" alt="Screenshot 2022-10-07 at 09 47 45" src="https://user-images.githubusercontent.com/29543633/194512946-3001f14b-ee7e-4c15-b58a-cadfcdafa1dc.png">

### Versions

* **Cypress version**: 10.9.0
* **Preprocessor version**: 13.0.2
* **Node version**: 18.9.1

my `cypress.config.js` file looks like this:

```
const { defineConfig } = require("cypress");
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const addCucumberPreprocessorPlugin =
  require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const createEsbuildPlugin =
  require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;

require('dotenv').config({path: './.env'});

module.exports = defineConfig({
 
  e2e: {
    async setupNodeEvents(on, config) {
      const bundler = createBundler({
        plugins: [createEsbuildPlugin(config)],
      });

      on("file:preprocessor", bundler);
      await addCucumberPreprocessorPlugin(on, config);

      return config;
    },

    specPattern: "cypress/e2e/features/*.feature",
    chromeWebSecurity: false,
  },

});
```

my `package.json` contains the following:
```
  "cypress-cucumber-preprocessor": {
    "stepDefinitions": "./cypress/e2e/step_definitions/*.cy.js"
  }
```

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
How are you invoking Cypress with —env? Show me the exact command.

**Comment by mazza1892** [comment]
Thanks for getting back to me, sure here is it..

`npm run cypress:open --env VARIABLE=value`

**Comment by badeball** [comment]
Try running `npm run cypress:open -- --env VARIABLE=value`.

**Comment by mazza1892** [comment]
Great! so that works, but still seeing the error message too. Any idea what that is?

<img width="520" alt="Screenshot 2022-10-09 at 10 30 57" src="https://user-images.githubusercontent.com/29543633/194749208-3a62cf1c-9b78-4bf6-99e1-ba5dc82ed9e8.png">

**Comment by badeball** [comment]
It’s not an error, but something set by the plugin and not something you need to be concerned about.
