### ISSUE TITLE
How i solve this Build ERROR?

### ISSUE THREAD

**Issue by luizh-silva-oliveira** [badeball/cypress-cucumber-preprocessor#853]
### Current behavior
Error opening spec
![image](https://user-images.githubusercontent.com/41453112/194638570-80afc7e8-7f91-4b08-b4f0-048d878f29a9.png)
My config file
![image](https://user-images.githubusercontent.com/41453112/194638788-eef91051-d96a-4467-915c-45f2c70fd8ee.png)
my .cypress-cucumber-preprocessorrc file
![image](https://user-images.githubusercontent.com/41453112/194639395-1e7365c7-ead1-4dd1-8a41-1883683029db.png)

### Desired behavior

I want to open my feature file without errors

### Versions

* **Cypress version**: 10.9.0
* **Preprocessor version**: 13.0.2
* **Node version**: 14.18.3

**Comment by badeball** [comment]
Read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) and try again.
