### ISSUE TITLE
Use cucumber preprocessor only for UI tests ?

### ISSUE THREAD

**Issue by kiran-epic** [badeball/cypress-cucumber-preprocessor#857]
I've setup cypress UI tests using the cucumber pre-processor & it's working well. Now I am planning to add API tests in the e2e folder which will have `{ts,tsx}` extension, but these tests don't show up in the cypress runner. 

I have my project configured using ESBuild as per this [doc](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/examples/esbuild-ts/cypress.config.ts)

I changed the specpattern now to 
`specPattern: 'cypress/e2e/**/*.{feature,tsx}',`

but the tests in the API folder don't show up in the cypress runner. 

The folder structure looks something like this :

- e2e
  -  UI
      - uitest.feature
  - API
    - apitest.tsx

Any help is greatly appreciated!

### Versions

* **Cypress version**: 10.10.0
* **Preprocessor version**: 13.0.2
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I know for a fact that this works, as it’s tested in CI: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/features/mixing_types.feature

I can’t tell what you’re doing wrong though.

**Comment by kiran-epic** [comment]
I noticed that if I don't include the `await addCucumberPreprocessorPlugin(on, config);  ` line in the setupNodeEvents then both the tests show up as expected as per the spec pattern  `specPattern: 'cypress/e2e/**/*.{tsx,feature}',`

```
async function setupNodeEvents(
    on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {

    on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
    );

    // Make sure to return the config object as it might have been modified by the plugin.
    return config;
}
```

However the tests won't run as expected :)
<img width="403" alt="image" src="https://user-images.githubusercontent.com/98785077/195410387-6e4f40af-4f4f-4f1d-a09b-ab0706346c23.png">

**Comment by badeball** [comment]
I still can’t tell what you’re doing wrong and that always means you have to provide a complete example.

**Comment by kiran-epic** [comment]
Found the issue. It has to do with **TAGS** in the env variable & when the **filterSpecs** & **OmitFiltered** is set to true

Sample Project -> https://github.com/kiran-epic/CypressCucumber_Processor

**Comment by badeball** [comment]
In other words, everything is working as intended.

**Comment by kiran-epic** [comment]
Nopes. 'not @ignore' means that it should load all tests which don't have that tag. I haven't tagged the non cucumber tests, so they should load just as the other features load ?

**Comment by badeball** [comment]
No and I don't care to explain any further. Use `@skip` instead, ref. https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md#smart-tagging.
