### ISSUE TITLE
Would like a [filename] variable to stepDefinitions

### ISSUE THREAD

**Issue by pwpatton** [badeball/cypress-cucumber-preprocessor#862]
### Current behavior

Cucumber currently allows me to have a stepDefinitions like this
```
  "stepDefinitions": [
    "cypress/e2e/[filepart]/step_definitions/**/*.{js,ts}",
    "cypress/e2e/[filepart]/**/*.{js,ts}",
  ]
```  
This allows me to have stepDefinitions  scoped to the .feature file.

```
cypress/e2e/MyFeature.feature
cypress/e2e/MyFeature/step_definitions/some-steps.ts
```

This is great but clutters directories where I have my .feature files.

### Desired behavior

Would like a [filename] variable that can be used in the step definitions so that I can define the directory structure (like below) that would still allow stepDefinitions  to be scoped to the .feature file.

```
  "stepDefinitions": [
    "cypress/e2e/[filepath]/step_definitions/[filename].{js,ts}",
    "cypress/support/step_definitions/[filename].{js,ts}"
  ]
```  
This would allow me to have stepDefinitions scoped to the .feature w/o the clutter.
```
cypress/e2e/Feature1.feature
cypress/e2e/Feature2.feature
cypress/e2e/Feature3.feature
cypress/e2e/step_definitions/
    Feature1.ts
    Feature2.ts
    Feature3.ts
```
```
cypress/e2e/Feature1.feature
cypress/e2e/Feature2.feature
cypress/e2e/Feature3.feature
cypress/support/step_definitions/
    Feature1.ts
    Feature2.ts
    Feature3.ts
```

### Versions

* **Cypress version**: 10.9.0
* **Preprocessor version**: 13.0.2
* **Node version**: v14.17.3

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I believe that this is already supported. Try something like

```json
[
  "cypress/support/step_definitions/[filepath].{js,ts}"
]
```

**Comment by pwpatton** [comment]
Trying that now. I think I got this right:
```
  "stepDefinitions": [
    "cypress/support/step_definitions/[filepart]/**/*.{js,ts}"
  ]
```
I tried that and it's complaining about multiple step defs of the same text.

![image](https://user-images.githubusercontent.com/4737815/197273627-86f3af6c-07b8-40c4-bd6a-0f30cfc494a5.png)

Here's my dir structure
![image](https://user-images.githubusercontent.com/4737815/197273843-4f39801c-da3b-4862-8b0e-013b3edf87bd.png)


I'll make a sample repo and submit this as an issue

**Comment by badeball** [comment]
With the pattern you're using, that's expected.. Don't use `[filepart]` for now, just stick with `[filepath]` and see if you can get that  to work.

**Comment by pwpatton** [comment]
Ok, changed that but I'm still seeing the same issue
```
 "stepDefinitions": [
    "cypress/support/step_definitions/[filepath]/**/*.{js,ts}"
  ]
  ```

**Comment by badeball** [comment]
Run Cypress with the following debug variable

```
$ DEBUG=cypress:electron,cypress-configuration,cypress-cucumber-preprocessor cypress ...
```

.. this will give you some hints into what patterns are actually created here.

**Comment by pwpatton** [comment]
I'm on windows using an npm script. Have I got this right? What should I expect to see?

```
"cy:open": "set DEBUG=cypress:electron,cypress-configuration,cypress-cucumber-preprocessor && npx cypress open --e2e --config-file=cypress.config.ts",
```

**Comment by badeball** [comment]
When done right, you should see a lot more output in your terminal. I can't speak for windows, but I'd assume it'd just be `"cy:open": "DEBUG=foobar npx cypress .."`, IE. without `set`.

**Comment by pwpatton** [comment]
Ok I ran this form the command prompt and now see the output

```
  cypress-cucumber-preprocessor compiling C:\Landmark\sandbox2\webtest\cypress\e2e\paging\ListGridPaging.feature +2m
  cypress-cucumber-preprocessor resolved no configuration +87ms
  cypress-cucumber-preprocessor replacing [filepath] with 'paging\\ListGridPaging' +1ms
  cypress-cucumber-preprocessor replacing [filepart] with [ 'paging\\ListGridPaging', 'paging' ] +1ms
  cypress-cucumber-preprocessor looking for step definitions using [
  cypress-cucumber-preprocessor   'cypress\\e2e/[filepath]/**/*.{js,mjs,ts,tsx}',
  cypress-cucumber-preprocessor   'cypress\\e2e/[filepath].{js,mjs,ts,tsx}',
  cypress-cucumber-preprocessor   'cypress/support/step_definitions/**/*.{js,mjs,ts,tsx}'
  cypress-cucumber-preprocessor ] +0ms
  cypress-cucumber-preprocessor found step definitions [
  cypress-cucumber-preprocessor   'C:/Landmark/sandbox2/webtest/cypress/support/step_definitions/paging/ListGridPaging/ListGridPaging.ts',
  cypress-cucumber-preprocessor   'C:/Landmark/sandbox2/webtest/cypress/support/step_definitions/paging/TemplateGridPaging/TemplateGridPaging.ts'
  cypress-cucumber-preprocessor ] +6ms
  cypress-cucumber-preprocessor compiled C:\Landmark\sandbox2\webtest\cypress\e2e\paging\ListGridPaging.feature +0ms

```
`cypress-cucumber-preprocessor   'cypress/support/step_definitions/**/*.{js,mjs,ts,tsx}'`

Looks like it's lopping off the filepath

**Comment by badeball** [comment]
That should give you enough information to understand the configuration options and get the value correctly.

**Comment by pwpatton** [comment]
I'm not sure but when I played with this some time ago I remember something about the filepath not working when it's after step_definitions.

**Comment by pwpatton** [comment]
Thanks @badeball, the debug output really helps make it clear what is happening. 

This is working for me as I now understand the patterns produced by the `stepDefinitions`.
Using this:
```
{
  "stepDefinitions": [
    "cypress/support/src/[filepart]/step_definitions/**/*.{js,ts}"
  ]
}
```
yielded these patterns.
```
  cypress-cucumber-preprocessor for 'cypress\\e2e\\element-ids\\TestPageIdsIPhoneRes.feature' yielded patterns [
  cypress-cucumber-preprocessor   'cypress\\support\\src\\element-ids\\TestPageIdsIPhoneRes\\step_definitions\\**\\*.{js,ts}',
  cypress-cucumber-preprocessor   'cypress\\support\\src\\element-ids\\step_definitions\\**\\*.{js,ts}',
  cypress-cucumber-preprocessor   'cypress\\support\\src\\step_definitions\\**\\*.{js,ts}'
```

which means that it won't find other steps in other `[filepart]` directories as the steps are only found in `step_definition` for each directory going up the chain.
