### ISSUE TITLE
Not able to use Cypress-XPath dependency

### ISSUE THREAD

**Issue by Dave0814** [badeball/cypress-cucumber-preprocessor#863]
### Current behavior

The cypress-XPath dependency does not work together with the cucumber-preprocessor dependency, at the time of running the test it does not identify it as a function.

### Desired behavior

The cypress-XPath dependency should work when running a test with.

### Test details

<img width="873" alt="Screen Shot 2022-10-24 at 17 29 35" src="https://user-images.githubusercontent.com/61260768/197641887-ab90dbaf-f219-497c-88cc-8bac8d5d2d47.png">

<img width="424" alt="image" src="https://user-images.githubusercontent.com/61260768/197643808-ef7bdb1a-c939-43bd-9be1-985649f3313c.png">

<img width="422" alt="Screen Shot 2022-10-24 at 17 47 17" src="https://user-images.githubusercontent.com/61260768/197644183-f103e2bb-37fd-4bd9-91dd-d3562ef24747.png">

### Versions

* **Cypress version**: ^10.1.0
* **Preprocessor version**: ^12.1.0
* **Node version**: 16.14.2
*  **cypress-xpath version**: ^1.6.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You need to provide a minimal and runnable example that illustrates the issue, as I can’t reproduce it.

**Comment by Dave0814** [comment]
Sure, I created a simple test and changed some dependencies, because the cypress-XPath has been deprecated, let me know if you need something else.

```
const { When, Then } = require("@badeball/cypress-cucumber-preprocessor");

When("I visit duckduckgo.com", () => {
  cy.visit("https://duckduckgo.com/");
});

Then("I should see a search bar", () => {
  cy.xpath("//input[@id='search_form_input_homepage']")
  .click()

});
```

Here's the modification I made for the dependencies

```
"dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^13.0.3",
    "@cypress/webpack-preprocessor": "^5.15.0",
    "@cypress/xpath": "^2.0.2",
    "webpack": "^5.74.0"
  }
```

**Comment by badeball** [comment]
There's nothing runnable about what you're providing me now. You're now only providing me with whatever you think is relevant, but that's rarely where the issue reside (otherwise you wouldn't be posting here).

In your case, I'm guessing you've configured `supportFile: false`, in which case your `import ".."` is not actually being executed

**Comment by Dave0814** [comment]
Thanks! we're able to solve the issue.
