### ISSUE TITLE
arguments are typed as 'unknown' and display as errors by ts linter

### ISSUE THREAD

**Issue by orizens** [badeball/cypress-cucumber-preprocessor#865]
### Current behavior

In my project, there are some cucumber expressions that include arguments in the form of:

```typescript
Then('I see text {string} is visible', text => {
  cy.findByText(text).should('exist');
});
```
even though my `tsconfig` is configured with `strict: false`, the `text` parameter is marked with a red bottom curly border displaying a lint error with the `text: unknown` hint:

<img width="662" alt="Screen Shot 2022-10-26 at 3 50 53 PM" src="https://user-images.githubusercontent.com/878660/198122985-12d57053-3e12-424d-bcfd-7ece31de1e29.png">

### Desired behavior

I should not see any typescript strict related errors.

### Test code to reproduce
N/A

### Versions

* **Cypress version**: 10.10
* **Preprocessor version**: cra 5 (webpack 5)
* **Node version**: 16.16

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You need to type it explicitly, as it can’t be inferred statically.

**Comment by orizens** [comment]
Thank you - i figured it is not typed.
My question goes further to why is strict typing is enforced even though the tsconfig set it to false?

**Comment by badeball** [comment]
I can't answer that.
