### ISSUE TITLE
afterEach hook that runs like in native cypress

### ISSUE THREAD

**Issue by aj-sdet** [badeball/cypress-cucumber-preprocessor#866]
How can this be achieved? I am assuming this is not implemented yet, right?

// sample.feature
Feature: Some feature name

Scenario: Sample test 1
        Given step 1
        When step 2  <-- imagine this step failed for whatever reason
        Then step 3 with some validation

//sample.ts step defintions for above

`Given("step 1", function () {
    cy.log('step 1 Successful');
});

When("step 2", function () {
    cy.log('step 2 FAILED for whatever reason');
});

Then("step 3", function () {
   cy.log('step 3 SKIPPED, which expected');
});

After(function () {
cy.log('I want this hook to still run like CYPRESS afterEach() HOOK');
});`

**Comment by badeball** [comment]
No. If you want the behaviour of Cypress hooks, then use Cypress hooks.

**Comment by aj-sdet** [comment]
afterEach is running after each feature file instead of only the step definition file that contains it, how can that be achieved though?

**Comment by badeball** [comment]
I've extended the documentation regarding pairing and explained a common trap that people fall victim to: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md

It's probably relevant for you.

**Comment by aj-sdet** [comment]
thank you, based on those examples I was able to achieve what I intended, one more question though, why does this configuration  
```
 "cypress-cucumber-preprocessor": {
    "stepDefinitions": [
      "cypress/e2e/stepDefinitions/[filepath].ts"
    ]
  }
```
resolves in cypress/e2e/stepDefinitions/features/[filepath].ts.

In other words given the directory below with config above:

/home/john.doe/my-project
└── cypress
    └── e2e
        ├── features
        │   ├── a.feature
        │   └── b.feature
        ├── stepDefinitions
        │   ├── a.ts
        │   └── b.ts
        
this will throw step definition is not implemented unless I add additional directory "features" under "stepDefinitions" as below
and then it will pickup the step definitions with config above
├── stepDefinitions
        ├── features
        │   ├── a.ts
        │   └── b.ts

**Comment by badeball** [comment]
It's difficult to follow your example and it looks like the indenting might be off. Can you provide an example in form of a repository?
