### ISSUE TITLE
 createEsbuildPlugin is not a function

### ISSUE THREAD

**Issue by marvinhosea** [badeball/cypress-cucumber-preprocessor#868]
### Current behavior

When I try to run test after following the recommended TS guidelines(I literally copied the conf)

### Desired behavior

Compile and run test

### Test code to reproduce

``` 
import {defineConfig} from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";
import pkg from '@badeball/cypress-cucumber-preprocessor';

const {addCucumberPreprocessorPlugin} = pkg;

async function setupNodeEvents(
    on: Cypress.PluginEvents,
    config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {
    // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
    addCucumberPreprocessorPlugin(on, config);

    on(
        "file:preprocessor",
        createBundler({
            plugins: [createEsbuildPlugin(config)],
        })
    );

    // Make sure to return the config object as it might have been modified by the plugin.
    return config;
}

export default defineConfig({
    e2e: {
        specPattern: "**/*.feature",
        supportFile: false,
        setupNodeEvents,
    },
});
```

### Versions

* **Cypress version**: 10.11.0
* **Preprocessor version**: 13.0.3
* **Node version**: 16.15.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I guessing this applies to you as well: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#i-get-cypress_esbuild_preprocessor_1createbundler-is-not-a-function

**Comment by marvinhosea** [comment]
Fixed it thank you.
