### ISSUE TITLE
Unnecessary Deprecation of And and But Steps 

### ISSUE THREAD

**Issue by marvinhosea** [badeball/cypress-cucumber-preprocessor#869]
### Current behavior

Cucumber and Gherkin's standards and guidelines include the keywords And and But.
I'm not sure how they got deprecated because a "PR" was submitted on this #821 without any supporting documents or links, etc.

These steps are critical, and while I understand that we can use When and Then, they are not declarative and do not conform to BDD flow and standards, even when compared to other BDD libraries and frameworks.

This is a significant breaking change for bulk bdd files and testers/operations teams who write BDD tests for developers to implement.

Bonus improve code readability and improve collaboration.

### Desired behavior

Support for And and But

### Test code to reproduce

n/a

### Versions

* **Cypress version**: n/a
* **Preprocessor version**: n/a
* **Node version**: n/a

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I suspect you’re misunderstanding the implications of this change, so before I respond any further I ask you to read the following comment: https://github.com/badeball/cypress-cucumber-preprocessor/issues/821#issuecomment-1267073941
