### ISSUE TITLE
Native JSON formatter

### ISSUE THREAD

**Issue by badeball** [badeball/cypress-cucumber-preprocessor#870]
The [cucumber-json-formatter](https://github.com/cucumber/json-formatter) has some open issues, many residing from here, and the community (including readers here) have not shown any willingness / ability to do anything about it.

Because I'm not familiar with Go myself, I am considering replacing it with a TypeScript implementation.

Furthermore, a vocal minority perceive using a standalone tool as incredibly difficult, despite EG. using it in CI-environment is extremely trivial. While they don't have my sympathy, it'll be nice to avoid the noise.

I don't have a lot of free time on my hands lately, but I will get on it in time. Meanwhile, contributions are welcome.

**Comment by sriramvenkataram** [comment]
There is one good package that seems to do the job for me. [cucumber-json-report-formatter](https://www.npmjs.com/package/cucumber-json-report-formatter)

Have a little write up [here](https://medium.com/@sriram.venkataram/cypress-cucumber-test-framework-with-html-reporting-be19592b1361) which could help configuring the report to be auto-generated after test run

**Comment by badeball** [comment]
`cucumber-json-formatter` has been replaced with native components in v16.0.0.
