### ISSUE TITLE
[CRA - React 18] error message due tsconfig 

### ISSUE THREAD

**Issue by c0ncentus** [badeball/cypress-cucumber-preprocessor#871]
### Current behavior

![image](https://user-images.githubusercontent.com/25374826/198900512-67f616e5-7a15-4c9c-a01d-f5400abdfada.png)

 
try to make the basic exemple https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md
exactly but with "todo" name file

### Desired behavior

**no webpack weird behaviour.**
Executing test in cypress with cucumber syntax !

### Test code to reproduce
put this tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
}
```

### Versions

* **Cypress version**:^10.11.0
* **Preprocessor version**:
*     "@badeball/cypress-cucumber-preprocessor": "^13.0.3",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.5",
* **Node version**: 18.5

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

I'm leaving this tool because no success to make the basic one on "get started" and dont absulitly want manage webpack issues.
It's just too dirty.

**Comment by badeball** [comment]
Not an issue with the preprocessor and the error message speaks for itself. Target es6 (or higher) or write es5. There’s very little reason to do the latter when using Cypress, unless you're actually targeting legacy browsers.
