### ISSUE TITLE
JSON output file name

### ISSUE THREAD

**Issue by mysticdevx** [badeball/cypress-cucumber-preprocessor#873]
### Current behavior

when running cucumber with default settings, i.e. without defining the output filenames, the .ndjson (and translated .json)  filenames have static names, namely: `cucumber-messages.ndjson` (and `cucumber-report.json` after the translation with cucumber-json formatted). Additionally, there's no option to set the outputFolder.  

### Desired behavior

As in the previous implementation. It would be better if the created message file has the name of the feature as the file name. 
Assitionally, I would be great i we can set the outputFolder directory without defining a static file name.

### my cucumber settings

```Javascript
module.exports = {
  "stepDefinitions": [
    "cypress/integration/**/*.ts"
  ],
  "filterSpecs": true,
  "messages": {
    "enabled": true,
    "output": `cypress/cucumber-json/output.ndjson`
  },
  "json": {
    "enabled": true,
    "output": `cypress/cucumber-json/output.cucumber.json`,
    "formatter": "node",
    "args": [
      "../../node_modules/@deepakvishwakarma/cucumber-json-formatter/lib/main.js"
    ]
  }
}
```

### Versions

* **Cypress version**: 10.9.0
* **Preprocessor version**:13.0.2
* **Node version**:14.17.3

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> As in the previous implementation. It would be better if the created message file has the name of the feature as the file name.

The report contains information about all specs run (as it should), so how would this work?
