### ISSUE TITLE
Missing preprocessor event handlers when running with custom config file 

### ISSUE THREAD

**Issue by vjmaiky** [badeball/cypress-cucumber-preprocessor#874]
### Current behavior

Missing preprocessor event handlers (this usally means you've not invoked addCucumberPreprocessorPlugin() or not returned the config object in setupNodeEvents()) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

### Desired behavior

Setup should start

In project settings i can see that config envs are loaded. If i remove the cucumber part and run directly, works as expected.

### Test code to reproduce

`import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import preprocessor from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild.js";

import allureWriter from "@shelex/cypress-allure-plugin/writer.js";

import { readFileSync } from "fs";

export async function setupNodeEvents(on, config) {

  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);
  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
    })
  );

  /**
   * allure reporting for better reports
   */
  allureWriter(on, config);

  /**
   * Reading the env values from jSON
   */
  // const envName = config.env.name
  // const text = readFileSync(`./${envName}.json`)

  const text = readFileSync('./dev.json')
  const values = JSON.parse(text)
  config.env = {
    ...values
  }

  // Make sure to return the config object as it might have been modified by the plugin.
  return config
}

export default defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    setupNodeEvents,
    supportFile: false,
  },
  defaultCommandTimeout: 10000,
  watchForFileChanges: false,
  chromeWebSecurity: false,
  waitForAnimations: true,
  pageLoadTimeout: 50000,
  requestTimeout: 10000,
  responseTimeout: 30000,
  viewportWidth: 1600,
  viewportHeight: 1200,
  screenshotOnRunFailure: true,
  trashAssetsBeforeRuns: true,
  videoUploadOnPasses: false,
  video: false,
  videoCompression: false,
  fixturesFolder: 'cypress/fixtures',
  downloadsFolder: 'cypress/downloads',
  screenshotsFolder: 'cypress/screenshots',
  retries: {
    'runMode': 1,
    'openMode': 1
  },

});`

### Versions

* **Cypress version**: Version 10.9.0
* **Preprocessor version**:     "@badeball/cypress-cucumber-preprocessor": "latest",
* **Node version**: v18.0.0

**Comment by badeball** [comment]
Format your code properly, ffs.

**Comment by vjmaiky** [comment]
For other people which might run in the same situation, the trick is to add data related to env's or any other data that you need for test data before preprocesor/cucumber logic.

```
export async function setupNodeEvents(on, config) {

  /**
   * allure reporting for better reports
   */
  allureWriter(on, config);

  /**
   * Reading the env values from jSON
   */
  const envName = config.env.name
  const text = readFileSync('./qa.json')
  // const text = readFileSync(`./${envName}.json`)
  const values = JSON.parse(text)
  config.env = {
    ...values
  }

  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}
```
And for the owner of the repo, you know that sometimes you need to have a nicer attitude to the community :). Maybe you should invest that bad energy to create better error handling. Have a nice day.

**Comment by badeball** [comment]
You're wasting my time having me read through ill-formatted code. If you want my help, why can't you do this one simple thing for me?

**Comment by vjmaiky** [comment]
Better?

```javascript
export async function setupNodeEvents(on, config) {

  /**
   * allure reporting for better reports
   */
  allureWriter(on, config);

  /**
   * Reading the env values from jSON
   */
  const envName = config.env.name
  const text = readFileSync('./qa.json')
  // const text = readFileSync(`./${envName}.json`)
  const values = JSON.parse(text)
  config.env = {
    ...values
  }

  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}
```
