### ISSUE TITLE
e2e.setupNodeEvents() throws type error while executing cypress tests

### ISSUE THREAD

**Issue by prasadsolanki** [badeball/cypress-cucumber-preprocessor#875]
### Current behavior

I am migrating to Cypress 10 and following the steps here to set up cucumber - https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-ts 
But when I run the cypress tests I get below error

![tempsnip](https://user-images.githubusercontent.com/21264793/200257134-3afc5f09-b6a4-4c03-883f-3d0ed8eba759.png)

Here is my cypress.config.ts

![image](https://user-images.githubusercontent.com/21264793/200257612-87e8f8cc-b892-45ef-a36d-488bf1ac0a1b.png)

And also got required dependencies in package.json

![image](https://user-images.githubusercontent.com/21264793/200257908-c5e49de2-61ca-49df-9b0e-000f56bbd3a7.png)

### Desired behavior

Tests should run and cucumber json reports should be generated

### Versions

* **Cypress version**:10.8.0
* **Preprocessor version**:13.0.3
* **Node version**:16.13.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> Don't ever post screenshots of code or errors unless they're also accompanied by text. We're not going to perform OCR on your ticket just to be able to help you. Screenshots unaccompanied by text makes it impossible for anyone to find your issue through search.

Additionally, you'll find the answer in the FAQ.
