### ISSUE TITLE
New step definition path not captured from package.json

### ISSUE THREAD

**Issue by Krish0369** [badeball/cypress-cucumber-preprocessor#881]
### Current behavior
I saved step definitions path in package.json and cypress-cucumber-preprocessorrc.json. But it search step definitions file always under following default paths. Not the path I specified,
- cypress\e2e\features/[filepath]/*/.{js,mjs,ts,tsx}
- cypress\e2e\features/[filepath].{js,mjs,ts,tsx}
- cypress/support/step_definitions/*/.{js,mjs,ts,tsx}
![image](https://user-images.githubusercontent.com/118180890/201696227-13273c72-a47e-41b3-85e9-ca0e2657c3d8.png)

### Desired behavior

![image](https://user-images.githubusercontent.com/118180890/201695613-8b8f84a9-5e59-4b99-8144-828f2a197005.png)
Above is the folder structure. 

![image](https://user-images.githubusercontent.com/118180890/201699794-7912d3e6-1d0e-4991-8355-c0dd4a7c8e31.png)
package.json

Please let me know why couldn't I use different path for step definitions even after declared the new path.

### Versions

* **Cypress version**:11.0.1
* **Preprocessor version**:14.0.0
* **Esbuild version**:2.1.5
* **Node version**:16.13.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by sagar-maheshwari** [comment]
I think you've declared it incorrectly on `package.json`

You need to do it as per this guide - https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md

eg:
`"cypress-cucumber-preprocessor": {
    "stepDefinitions": "cypress/support/step_definitions/*.js"
}`

**Comment by Krish0369** [comment]
@sagar-maheshwari 
Thank you. Great help. It works.
Earlier I used the following way
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md

**Comment by Krish0369** [comment]
closed
