### ISSUE TITLE
 afterEach() and After({tags: "@sometag"}) is executing in wrong order

### ISSUE THREAD

**Issue by mi4i0** [badeball/cypress-cucumber-preprocessor#884]
### Current behavior
We have migrated our project from Cypress 8.4... to 10.11 +
Moved from "cypress-cucumber-preprocessor": "4.2.0" to "@badeball/cypress-cucumber-preprocessor": "14.0.0"

**Before migration:**
Hooks for afterEach(() => {some code}) are executing before After({ tags: '@something' } () => {}) hook
<img width="597" alt="image" src="https://user-images.githubusercontent.com/18115147/203095039-7125cb8e-6a55-45de-b02e-e26553139a9c.png">

On screenshot  From Cypress 8.4.1 AFTER EACH(1) is hook from afterEach(() => {some code}) part of code
AFTER EACH(2) (and so on)  is hook from  After({ tags: '@something' } () => {}) from different stages

**After migration:**
Hooks for After({ tags: '@something' } () => {}) are executing before afterEach hook
<img width="742" alt="image" src="https://user-images.githubusercontent.com/18115147/203097058-55c0cfec-0173-40c8-9a73-ff9ef6ed4a3f.png">

As you can see steps 281 and 286 were done before AFTER EACH at the end in the latest version
### Desired behavior
Is it possible to run afterEach(() => {some code}) as it was done before or any workaround?

### Versions

* **Cypress version:** 10.11
* **Preprocessor version:** 14.0.0
* **Node version:** 18.12.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
As a workaround can replace `After(..)` hooks with `afterEach(..)` and use the (pt now) undocumented method `doesFeatureMatch(..)` (ref https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/features/mixing_types.feature#L31) to conditionally run based on tags.

**Comment by mi4i0** [comment]
Hi, @badeball will it be fixed in the future or any improvements on it?

**Comment by badeball** [comment]
No, you're actually encountering intended behavior.
