### ISSUE TITLE
stepDefinitions are not recognized on a CI pipeline run

### ISSUE THREAD

**Issue by cristina-boop** [badeball/cypress-cucumber-preprocessor#886]
### Current behavior
I want to run e2e tests on an Azure Pipeline, but step definitions are not recognized on it.
Everything looks fine when I run my tests locally.
![image](https://user-images.githubusercontent.com/78798938/203491589-9c36289c-edba-4c55-bc51-a769e9ba78ca.png)

### Desired behavior
I have a .cypress-cucumber-preprocessorrc.json where stepDenitions are defined. 
{
  "json": {
    "enabled": false,
    "output": "jsonlogs/log.json",
    "formatter": "cucumber-json-formatter.exe"
  },
  "messages": {
    "enabled": false,
    "output": "jsonlogs/messages.ndjson"
  },
  "html": {
    "enabled": false
  },
  "stepDefinitions": [
    "[filepath]/**/*.{js,ts}",
    "[filepath].{js,ts}",
    "cypress/e2e/step_definitions/*.{js,ts}",
    "[filepath]\\***.{js,ts}",
    "[filepath].{js,ts}",
    "cypress\\e2e\\step_definitions\\**\\*.{js,ts}"
  ]
}
![image](https://user-images.githubusercontent.com/78798938/203492299-e82ac891-4b5a-4a8f-a6d7-3c7d4cb855cd.png)

### Versions

* **Cypress version 10.10.0**:
* **Preprocessor version 13.0.3**:
* **Node version 16.0**:

**Comment by badeball** [comment]
Try using forward-slash as path separators in `stepDefinitions`.

**Comment by badeball** [comment]
Closed due to inactivity.
