### ISSUE TITLE
Throws error in step_definitions.ts if specPattern is outside the project root

### ISSUE THREAD

**Issue by jordan-bite** [badeball/cypress-cucumber-preprocessor#887]
### Current behavior

My project references features from outside the project root.

Eg. `specPattern: '../../../../features/**/*.feature'`

This causes the library to throw an error from [this check](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/lib/step-definitions.ts#L82)

### Desired behavior

Allow the spec files to exist outside the project root.
This check seems purely arbitrary and doesn't actually prevent any problems.

### Test code to reproduce

define a path outside the project root in  `specPattern`

### Versions

* **Cypress version**: 11.0.1
* **Preprocessor version**:  14.0.0
* **Node version**: 16.15.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> [..] and doesn't actually prevent any problems.

You may be completely right, but I'm wary with these changes nonetheless. Have you tried removing it? Using eg. patch-package is pretty easy to make lasting changes circumventing upstream.

**Comment by jordan-bite** [comment]
@badeball Yes indeed commenting out this check does eliminate the error and allows the tests to run as expected.

**Comment by badeball** [comment]
Removing this creates the issue of calculating common ancestor paths when there are multiple spec roots, including one outside of the project root. This isn't a problem I'd like to visit now, so I've decided to let the assertion remain.
