### ISSUE TITLE
Error: No elements found for include in frame Context

### ISSUE THREAD

**Issue by tuddilue** [badeball/cypress-cucumber-preprocessor#888]
### Current behavior

When I try to update from:
"@badeball/cypress-cucumber-preprocessor": "12.2.0",
to
"@badeball/cypress-cucumber-preprocessor": "13.0.0",

I get the error:
No elements found for include in frame Context

The error comes from axe-core, I found this code:
https://npmdoc.github.io/node-npmdoc-axe-core/build/apidoc.html#apidoc.element.axe-core.utils.respondable.isInFrame

So I do not know why this error occures? And if there is something you can do about it?

### Desired behavior

That the error not occure

### Versions

* **Cypress version**: 10.11.0
* **Preprocessor version**: 13.0.0
* **Node version**: v16.15.0
* **axe-core**: 4.5.2

**Comment by badeball** [comment]
I can’t reproduce the error. You need to provide a complete example.

**Comment by tuddilue** [comment]
Ok I will try to do so.

I have in my package.json file:
"@badeball/cypress-cucumber-preprocessor": "13.0.0",
"axe-core": "4.5.2",

and the cupress console log writes:
[1] GET /__cypress/iframes/cypress%5Ce2e%5C10.Kvittens1Solo.feature 200 2.841 ms - 960
[1] GET /__cypress/tests?p=cypress%5Csupport%5Ce2e.ts 200 11421.732 ms - -
[1] GET /__cypress/tests?p=cypress%5Ce2e%5C10.Kvittens1Solo.feature 200 12020.642 ms - -
[1] ---------------Accessibility Summary----------------

and in cypress it looks like this:
![image](https://user-images.githubusercontent.com/98521351/203752415-7b8655b3-8e12-4c1c-a6a2-baaf45908f7f.png)

I hope it should be easy to reproduce?

**Comment by badeball** [comment]
You need to provide me with a complete example that I can run and that illustrates the error. Ideally in the form of a repository that I can clone.

**Comment by tuddilue** [comment]
I disussed with our developers and they had a idea what this can be.
Otherwise I will create a repository for you so you can have a look.

**Comment by tuddilue** [comment]
We found the error, it was in a component that made this error. Thanks for your support!
