### ISSUE TITLE
ERROR: Could not resolve "@badeball/cypress-cucumber-preprocessor"

### ISSUE THREAD

**Issue by Jexsie** [badeball/cypress-cucumber-preprocessor#890]
### Current behavior

I am trying to run tests with cypress and cucumber, but, after installing and configuring. I always get this.
![Screenshot from 2022-11-29 07-59-20](https://user-images.githubusercontent.com/104269786/204442864-462b2cde-89c6-43c1-b3b4-0d67c2a70341.png)

I can't really tell whats happening, I have also tried to update my node to the latest stable version, but still failing. 

### Test code to reproduce
The github repo is below
https://github.com/Jexsie/cypressCucumber

### Versions

* **Cypress version**:  11.0.1
* **Preprocessor version**: 14.0.0
* **Node version**: 18.12.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Can't reproduce. Have you actually installed the modules though?

**Comment by Jexsie** [comment]
Yes @badeball, I have installed them.  Below is my package.json
```{
  "name": "cypress-cucumber-boilerplate",
  "version": "2.2.0",
  "description": "This project is meant to be a kind of template to start working with Cucumber and Cypress just cloning the project.",
  "main": "index.js",
  "scripts": {
    "cypress:runner": "cypress open",
    "cypress:execution": "cypress run",
    "cypress:execution-tags": "cypress run --env tags=@mobile",
    "cypress:execution-allure": "cypress run --env allure=true",
    "allure:clear": "rm -r allure-results/ allure-report cypress/screenshots || true",
    "allure:report": "allure generate allure-results --clean -o allure-report",
    "allure:history": "mv -f allure-report/history allure-results/history && rm -r allure-report || true"
  },
  "keywords": [
    "cypress"
  ],
  "author": "cucumber",
  "license": "ISC",
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^14.0.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.5",
    "@shelex/cypress-allure-plugin": "^2.34.0",
    "cypress": "^11.0.1",
    "esbuild": "^0.15.13",
    "multiple-cucumber-html-reporter": "^3.0.1"
  }
}
```
I have tried deleting the node modules and the package.json, then reinstalling, still getting the same error. Test without cucumber, only cypress pass.
Node v18.12.1

**Comment by Jexsie** [comment]
```
Error: Build failed with 7 errors:
node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:6:50: ERROR: Could not resolve "@cucumber/tag-expressions"
node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:7:39: ERROR: Could not resolve "@cucumber/cucumber-expressions"
node_modules/@badeball/cypress-cucumber-preprocessor/lib/create-tests.js:8:23: ERROR: Could not resolve "uuid"
node_modules/@badeball/cypress-cucumber-preprocessor/lib/registry.js:7:39: ERROR: Could not resolve "@cucumber/cucumber-expressions"
node_modules/@badeball/cypress-cucumber-preprocessor/lib/registry.js:8:50: ERROR: Could not resolve "@cucumber/tag-expressions"
```

It seems @badeball/cypress-cucumber-preprocessor needs some configurations, coz, I have seen **"could not resolve @cucumber/tag-expressions"** The package if finely installed, and I need in configuring it, maybe. Thanks a lot @badeball for your time and support

**Comment by Jexsie** [comment]
The above error message changed when I tried to use **"filterSpecs": true** in my package.json

**Comment by nilgaar** [comment]
I can take care of this one @badeball.
I'm also unable to reproduce, please @Jexsie :
- submit your `package-lock.json`.
- The command you use to run Cypress

**Comment by Jexsie** [comment]
Thanks, @nilgaar for the concern, I couldn't stand waiting, so I erased everything on my machine and upgraded to ubuntu 22.04. And thanks to God, am no longer getting that error.

**Comment by nilgaar** [comment]
I see @Jexsie , kinda fixed then. I think we can resolve the Issue then @badeball .
