### ISSUE TITLE
Detected integration directory changes depending on which features are included in a run

### ISSUE THREAD

**Issue by appius-phil** [badeball/cypress-cucumber-preprocessor#891]
### Current behavior

Using a project structure similar to the one outlined in Example 2 from the docs:

```
/home/john.doe/my-project
└── cypress
    └── e2e
        ├── foo
        │   ├── common
        │   │   └── 3.js
        │   ├── a.feature
        │   └── a.js
        ├── bar
        │   ├── b.feature
        │   └── b.js
        └── common
            ├── 1.js
            └── 2.js
```

And step definitions like this:

```json
{
  "stepDefinitions": [
    "cypress/e2e/[filepath].js",
    "cypress/e2e/[filepart]/common/*.js"
  ]
}
```

When running a single feature (e.g. a.feature) then the integration folder is incorrectly detected as the direct parent (i.e. '/home/john.doe/my-project/cypress/e2e/foo') so my steps from a.js are no longer available (because the search pattern evaluates to '/home/john.doe/my-project/cypress/e2e/a.js', missing the 'foo' folder).

This was not an issue prior to upgrading to Cypress v10, when the integration directory was set explicitly through config.

### Desired behavior

The detected integration directory should not change from one test run to another based on which features are included.

Preferably, some alternative config option would be made available to override the new auto-detect functionality (which I appreciate is still very useful).

### Versions

* **Cypress version**: 11.2.0
* **Preprocessor version**: 14.0.0
* **Node version**: 16.13.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I thought this was properly fixed in https://github.com/badeball/cypress-cucumber-preprocessor/issues/785, but that could be wrong. I'm however unable to reproduce the issue you're describing. Exactly how are you running Cypress?

EDIT: Are you returning the config object in setupNodeEvents?

**Comment by appius-phil** [comment]
I'm setting an environment variable (CYPRESS_FEATURE) which I then use to set the specPattern in cypress.config.js.

Here's a simplified version of what I'm running:

```
async function setupNodeEvents (on, config) {
    config.specPattern = (config.env['FEATURE']) ?
      [
        `cypress/integration/foo/**/${config.env['FEATURE']}.feature`
      ] : [
        `cypress/integration/foo/**/*.feature`
      ]

    await preprocessor.addCucumberPreprocessorPlugin(on, config)
    on('file:preprocessor', createBundler({
      plugins: [createEsbuildPlugin.default(config)]
    }))
  
    return config
  }
```

I think the CAP is calculating correctly according to your logic, but of course the CAP for a single feature file is not actually the correct integration folder for this scenario (which needs to be higher up the tree so that the common steps are able to be found).

**Comment by badeball** [comment]
I don't understand why you wouldn't just volunteer this information in the original post, it's highly relevant and would have saved me some time.

The preprocessor can't do anything differently in this case. You need to find another way of filtering, EG. using tags, https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/tags.md#running-a-subset-of-scenarios.

**Comment by appius-phil** [comment]
Apologies, I didn't realise the relevance and it wasn't my intention to waste your time. I really appreciate everything you're doing for this project.

I believed it was a valid use case and a relevant suggestion based on how this used to work with previous versions, so it's unfortunate that you say it can't be supported. I understand the CAP logic has to work this way if the filtered feature files aren't passed to the processor, but I was hoping there might still be the possibility to reintroduce an explicit configuration option to bypass this new logic and give us back that control.

I will try to find an alternative based on tags, as you suggest, or possibly by adding an empty feature file higher up the hierarchy.
