### ISSUE TITLE
Can't define And and But from the Gherkin syntax

### ISSUE THREAD

**Issue by tuddilue** [badeball/cypress-cucumber-preprocessor#892]
### Current behavior

I can't find And and But from the Gherkin syntax.
When I look in the code I think they should be here:
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/lib/index.ts#L66

Here is an example that I'm using in the .feature file:

Ansokan.feature
-----------------------------------------------------------------------------------
#language: sv

  Scenario: MessageBox
    Givet kunden är på Ansökan
    När kunden är på Ansökan
    Så ska MessageBox visas
    Och ska MessageBox visa text nycklar
-----------------------------------------------------------------------------------
Ansokan.StepDefinition.js

import {
    Given as Givet,
    When as När,
    Then as Så,
    And as Och, //this doesn't work
} from "@badeball/cypress-cucumber-preprocessor";

Givet("kunden är på Ansökan", () => {
    # some code...
});

När("kunden är på Ansökan", () => {
    # some code...
});

Så("ska MessageBox visas", () => {
    # some code...
});

//this doesn't work
Och("ska MessageBox visa text nycklar", () => {
    # some code...
});

### Desired behavior

I want to define And and But.

### Test code to reproduce

See example above

### Versions

* **Cypress version**: 10.11.0
* **Preprocessor version**: 13.0.0
* **Node version**: 16.15.0

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This has been answered many times already, use the search.
