### ISSUE TITLE
Cucumber HTML reporter is showing scenario as failure even though the scenario passed after rerun using retries

### ISSUE THREAD

**Issue by vlokesh09** [badeball/cypress-cucumber-preprocessor#893]

**Comment by faltfe** [comment]
How did you solve the problem? I have the same issue after migrating from Cypress 9 to 11.

**Comment by patriciaSR** [comment]
How did you solve the problem? I have the same issue after migrating from Cypress 9 to 12. Is any way to ignore failed scenarios on retries??

@vlokesh09

**Comment by vlokesh09** [comment]
I have not solved this yet.. I remember creating another issue ...may be some leads over there ..
https://github.com/WasiqB/multiple-cucumber-html-reporter/issues/221

**Comment by g-iliadis** [comment]
hello all i manage to solve by just reformatting the generated json

`import fs from "fs";
let cucumberLogs = fs.readFileSync('cucumber-json/log.json');
let array = JSON.parse(cucumberLogs.toString())
array.forEach(obj=> {
    obj.elements = obj.elements.filter((item, index, self) => {
        let duplicate = self.findIndex((t) => t.id === item.id) === index;
        let failed = item.steps.some(s => s.result.status === "failed");
        return !(duplicate && failed);
    });

})

fs.writeFileSync('cucumber-json/log.json', JSON.stringify(array));
`

you just create a file cucumberFormaterForRetries.mjs
and then on your post test you just run the node script
