### ISSUE TITLE
Want step result(status) added to Test State

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#896]
### Current behavior

Currently we don't have test step result(status) stored in test state. We need it to be stored in test state to update the test results json based on the current test case passed or failed. By virtue of it, We are blocked from upgrading our cypress cucumber framework to latest version. We have this option in older cypress cucumber version =>
(window as any).testState.runTests[testState.currentScenario.name[testState.currentStep].status

Currently we have picklestep, pickle & pickles in test state. Do you think can we add step result(status whether current step passed or failed) or spec result to the test state?

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> We need it to be stored in test state to update the test results json based on the current test case passed or failed.

I don't understand this use case. Can you elaborate on it?

**Comment by sadhishsk** [comment]
@badeball When I retrieve the test state in afterEach hook, we store pickleStep like below object
```
"pickleStep": {
        "id": "9b88ee7e-8a2f-4f1e-88c3-aaab71c8062c",
        "text": "Customer should not see Country and Language model",
        "type": "Outcome",
        "astNodeIds": [
            "72439ca9-3056-4f42-94fe-8341d7155fca"
        ]
    }
```

Can we add result(status) node to it? Like the below output
```
"pickleStep": {
        "id": "9b88ee7e-8a2f-4f1e-88c3-aaab71c8062c",
        "text": "Customer should not see Country and Language model",
        **"status": "passed"** => Based on the step passed or failed during execution
        "type": "Outcome",
        "astNodeIds": [
            "72439ca9-3056-4f42-94fe-8341d7155fca"
        ]
    }
```

**Comment by badeball** [comment]
You're not showing me any code here. For what do you need the result?

**Comment by sadhishsk** [comment]
@badeball We are maintaining a separate json in our framework which contains execution details to use in our dashboard. For example, if we ran a sanity suite, we have a separate sanityExecutionDetails.json =>

```
{
	"SANITY_TC001": {
		"test_id": "SANITY_TC001",
		"scenario": "",
		"status": "",
		"video": "",
		"executed_on": "",
		"trip_type": "",
		"pax_count": "",
		"confirmation_number": "",
		"skymiles_number": "",
		"medallion": "",
		"first_name": "",
		"last_name": "",
		"origin": "",
		"destination": "",
		"cabin": ""
	},
	"SANITY_TC002": {
		"test_id": "SANITY_TC002",
		"scenario": "",
		"status": "",
		"video": "",
		"executed_on": "",
		"trip_type": "",
		"pax_count": "",
		"confirmation_number": "",
		"skymiles_number": "",
		"medallion": "",
		"first_name": "",
		"last_name": "",
		"origin": "",
		"destination": "",
		"cabin": ""
	}
}
```
All the above child node values will be updated at the run time using tag. In place of **status** we want to update whether the executed test case is passed or failed. I don't want to find the test results from plugin events as we can't use cy commands there. Please help!

**Comment by sadhishsk** [comment]
@badeball Any updates?

**Comment by sadhishsk** [comment]
Sorry to bother you with this issue. I have got the work around.

**Comment by vojtech-cerveny** [comment]
Can you at least provide some information how did you resolve it? You know, be part of community, add some to community. 😉

**Comment by sadhishsk** [comment]
@vojtech-cerveny I have got the test status in afterEach hook class via **this.currentTest?.state**. This gave me the spec status whether its Passed or Failed. :)
