### ISSUE TITLE
Do we have an option to generate individual ndjson for each feature file or scenario?

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#897]
### Current behavior
Do we have an option to generate individual ndjson for each feature file or scenario? Previously we used to have individual json for each feature file but now we are creating ndjson | json for complete run. 

Previously when we run a individual tag, We used to delete that particular cucumber json instead of all stored cucumber json so that we can publish report with both stored jsons & newly published json. 

For example, if we have 37 feature files and we ran by group tag, after execution we see 4 feature files failed because of environment stability means we will run only those test cases again. By doing so we don't want the previously generated cucumber jsons to be deleted so we will be deleting only those individual jsons based on the name.

Can we have an option to generate individual json for each feature file? i.e Individual jsons to be generated with the corresponding feature file name

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
No, this is something you have to solve post-run yourself. And to be frank, we're only talking about post-processing a JSON file and splitting an array here, so you don't need catering from the library for it.

**Comment by sadhishsk** [comment]
Thanks @badeball
