### ISSUE TITLE
Generated Cucumber message ndjson don't have any information when we declare after spec in setupNodeEvents

### ISSUE THREAD

**Issue by sadhishsk** [badeball/cypress-cucumber-preprocessor#898]
### Current behavior

If we have **after spec in setupNodeEvents in cypress.config.ts**, my ndjson just shows testRunStarted and testRunFinished, Just like this issue in stackoverflow https://stackoverflow.com/questions/73902649/cypress-cucumber-preprocessor-not-logging-to-messages-json

If I comment **after spec in setupNodeEvents in cypress.config.ts**, ndjson is generated as expected.

### Desired behavior

ndjson should be created with expected contents.

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> Addiitonally, properly formatted [blocks of code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) is an absolute requirement.

**Comment by sadhishsk** [comment]
@badeball Updated the description. Please check!

**Comment by sadhishsk** [comment]
@badeball Any updates?

**Comment by sadhishsk** [comment]
I have fixed the issue with afterSpecHandler. Closing this as completed!
