### ISSUE TITLE
Error in the first step

### ISSUE THREAD

**Issue by josefsmrz** [badeball/cypress-cucumber-preprocessor#900]
### Current behavior

After an upgrade from 11.x, I'm getting this error for every **first** executed step of the feature file:

```
"before all" hook failed: Missing preprocessor event handlers
(this usally means you've not invoked addCucumberPreprocessorPlugin() or
not returned the config object in setupNodeEvents()) (this might be a bug,
please report at https://github.com/badeball/cypress-cucumber-preprocessor)

> "before all" hook
undefined
```

The steps that follow run fine.

### Desired behavior

No error and functioning first step

### Versions

* **Cypress version**: 10.11.0
* **Preprocessor version**: 14.0.0
* **Node version**: 16.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> It's impossible to fix an issue that we can't reproduce ourselves and issues lacking enough information to reproduce the behavior will be closed.

From [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).

**Comment by josefsmrz** [comment]
I found out that it was dependent on my setup. If there are more async functions called from `setupNodeEvents`, then  `addCucumberPreprocessorPlugin(on, config)` needs to be called at the very end of the function, otherwise the first test can throw the error I have posted in the issue.
