### ISSUE TITLE
ERROR: Transforming const to the configured target environment ("es5") is not supported yet

### ISSUE THREAD

**Issue by ZampaglioneGaston** [badeball/cypress-cucumber-preprocessor#901]
### Current behavior

ERROR: Transforming const to the configured target environment ("es5") is not supported yet
![cy error](https://user-images.githubusercontent.com/83976674/206226699-9661eda0-5a0e-4181-a178-0eb941a3a112.JPG)

### Desired behavior

I would like to get support for cypress >11 while using this dependency

### Test code to reproduce

//

### Versions

* **Cypress version**: "cypress": "^12.0.1",
* **Preprocessor version**: "@badeball/cypress-cucumber-preprocessor": "^14.0.0",
* **Node version**: "version": "19.2.0",

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> It's impossible to fix an issue that we can't reproduce ourselves and issues lacking enough information to reproduce the behavior will be closed.

From [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).

**Comment by danieka** [comment]
@ZampaglioneGaston Changing the target in my tsconfig (`e2e/cypress/tsconfig.json`) fixed this error for me. From `"target": "es5",` to `"target": "es6",`.

**Comment by badeball** [comment]
Closed due to inactivity.
