### ISSUE TITLE
'And' not supported

### ISSUE THREAD

**Issue by ptletski** [badeball/cypress-cucumber-preprocessor#906]
### Current behavior

The following feature definition fails due to compilation error.

**create-todo.feature**
```
Feature: Create ToDo

Scenario: User creates new ToDo
  Given I am on the home page
   When I enter ToDo text as TEST
    And I click Add ToDo button
   Then a ToDo entry with ID of 1
    And TEST should display
```

**create-todo.ts**
```
import { Given, When, Then, **ERROR->**And } from '@badeball/cypress-cucumber-preprocessor';

Given('I am on the home page', () => {
  cy.visit("/");
  cy.get("h1").should('have.text', "QA BOX LET'S TEST");
  cy.get("h3").should('have.text', 'Angular ToDo');
})

When('I enter ToDo text as TEST', () => {
  cy.get('#todo-input').type('TEST');
})

**ERROR->**And('I click Add ToDo button', () => {
  cy.get('#submit-button').click();
})

Then('a ToDo entry with ID of 1', () => {
  cy.get('#todo-id-0').should('have.text', '1');
})

**ERROR->**And('text as TEST should display', () => {
  cy.get('#todo-text-0').should('have.text', 'TEST');
})
```

### Desired behavior

'And' should be permitted. 'And' was supported by the original cypress-cucumber-preprocessor. This breaks roughly 100 feature tests for me. Might want to consider supporting 'Or' as well.

### Test code to reproduce

See above.

### Versions

* **Cypress version**:10.9.0
* **Preprocessor version**:15.0.0
* **Node version**:16.13.0

### Checklist

- [**X**] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [**X**] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [**X**] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md#function-members-and-and-but-are-missing

**Comment by ptletski** [comment]
The purpose of a gherkin/cucumber preprocessor is to allow recognized gherkin syntax. As noted here: https://cucumber.io/docs/gherkin/reference/, And and as well as other step definitions, are valid. The concern highlighted by the link you provide is a developer issue that a preprocessor should find other means of solving, not ignoring as the link shows. Precluding use of And is the antithesis of the goal of your preprocessor. I have moved to another product. Thanks.
