### ISSUE TITLE
Repeated step name error

### ISSUE THREAD

**Issue by ptletski** [badeball/cypress-cucumber-preprocessor#907]
### Current behavior

I have a feature file that contains multiple scenarios.

```
Scenario: First Scenario
  Given: Do something 1
  When: I click button
  Then: Observe result 1

Scenario: Second Scenario
  Given: Do something 2
  When: I click button
  Then: Observe result 2

Scenario: Third Scenario
  Given: Do something 3
  When: I click button
  Then: Observe result 3

Scenario: Fourth Scenario
  Given: Do something 4
  When: I click button
  Then: Observe result 4
```

where each Given creates a unique context which is to be examined for the feature.

Preprocess flags 'When: I click button' as a redundant name.
=> Multiple matching step definitions for: I click button

### Desired behavior

Should not cause an error. Legacy version permitted this.

### Test code to reproduce

See above

### Versions

* **Cypress version**: 10.9.0
* **Preprocessor version**: 15.0.0
* **Node version**: 16.13.0

### Checklist

- [X] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [X] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is intended behavior and in line with how cucumber-js works.
