### ISSUE TITLE
Using esbuild@latest in host project causes type error with @bahmutov/cypress-esbuild-preprocessor

### ISSUE THREAD

**Issue by th1nkgr33n** [badeball/cypress-cucumber-preprocessor#909]
### Current behavior

We use this preprocessor in combination with the @bahmutov/cypress-esbuild-preprocessor to bundle it as a file:preprocessor.  

Unfortunately the cypress-esbuild-preprocessor has esbuild as peer dependency and if another dependency on host project comes with a newer version like esbuild@0.15.18 or esbuild@0.16.10 there are type errors.
Currently we have to pin the esbuild to 0.14.54 although not entirely necessary.  

***esbuild Changelog:***
./node_modules/esbuild/lib/main.d.ts
0.15.18 Changes on BuildOption -> Property "Write"  changed typing
0.16.10 Changes on type Loader (new entry empty) -> leads to mismatch

### Desired behavior

Updating the esbuild dependecy in this project to @latest or at least (0.16.10)

### Test code to reproduce

```cypress.config.ts
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {

  await addCucumberPreprocessorPlugin(on, config);

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );

  return config;
}

...

```

### Versions

* **Cypress version**: 11.2.0
* **Preprocessor version**: 15.0.0
* **Node version**: 18.12.1

### Checklist

- [ x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

Additional marks:
I'm rather new in the peer dependency topic so forgive me if the default solution for this would be to pin the version in host project rather than to ask you to update your dependency which brings additional workload to you.

**Comment by badeball** [comment]
There’s not really anything I can do about this. You can track this here: https://github.com/bahmutov/cypress-esbuild-preprocessor/issues/229

**Comment by th1nkgr33n** [comment]
Thank you @badeball for linking the corresponding issue in the cypress-esbuild. Couldn't find it by myself.
