### ISSUE TITLE
Examples: doesn't apply to all scenario in the feature file

### ISSUE THREAD

**Issue by QAFreak** [badeball/cypress-cucumber-preprocessor#910]
### Current behavior

Scenario: A
I login with "<username>"

Scenario: B
I login with "<username>"

Scenario: C
I login with "<username>"

Scenario: D
I login with "<username>"

Examples:
|username|
|john|
|peter|

The username values gets applied only to scenario C and D. For scenario A its picked directly as <username> instead of that being considered as a parameter

### Desired behavior

The parametrization should work across all the scenario.

**Comment by badeball** [comment]
This intended behaviour and how all cucumber implantations work.
