### ISSUE TITLE
Conflicts between two features with same commands

### ISSUE THREAD

**Issue by pedro-arruda09** [badeball/cypress-cucumber-preprocessor#911]
When I use the same description for two different features, he gets the first one in the folders of VS Code.

![image](https://user-images.githubusercontent.com/105317826/209559221-72a69f74-5eaf-4527-84f8-8b4605ae5a06.png)

![image](https://user-images.githubusercontent.com/105317826/209562522-cb647f6f-caae-4f71-ae82-5a4a7a621f44.png)

So, I want to know how to fix that. Always when we have a repeated command into the features of different files/folders, he gets the first one and executes it, even when I say that the functionality is different.

**Comment by badeball** [comment]
I don't understand the issue here. You need to use the issue template and provide me with a minimal and runnable example that illustrates what you think is wrong.

**Comment by pedro-arruda09** [comment]
I run multiple automatized tests and in between those tests, there are repeated commands inside differents features. My concern is, once this is all into develop, a feature will run the command of another one, given that they have the same command. (I'm sorry, english is not my first language.)

**Comment by badeball** [comment]
A step matching multiple step definitions will yield an ambiguity error (provided that you're using the most recent version, see the pinned issue). How to associate certain step definitions with certain feature files is explained in the docs, specifically [Pairing explained](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md).
