### ISSUE TITLE
[Request] Global Before Hooks

### ISSUE THREAD

**Issue by CMadden8** [badeball/cypress-cucumber-preprocessor#912]
First off, great work with this plugin. I'll also have a look at the codebase too at some point and see if I can create a PR for what I'm suggesting...

Currently the common step definitions have removed tons of repetition from the tests we've created. And the Before hooks and tags are also working great. But there's repetition cropping up with the hooks that's a result of the Befores apparently not being available for global use.

Eg, we have many scenarios that require changing the intercepted data for a particular endpoint. So you'd have the below in the feature.ts:

`Before({ tags: "@EndpointDataA" }, function () {
  // some logic
});`

But it gets repeated multiple times for other feature files that use this EndpointDataA to switch the data.

A global Before that works like the global/common Steps would result in even less code. 

That's my first suggestion, but I was also curious about the potential for tags before Steps. This one I'll admit is probably cucumber sacrilege, so I can understand if it's not doable. But occasionally you have to change the data for the same endpoint that was fired in beginning of the test (as it gets called again after some interaction but requires different data) - the workaround for this at the moment results in somewhat gratuitous steps that are really just cheats/workarounds to have something in place to allow us to change the data at some point.

This is also true for example of cy.wait('@endpointDataA') situations.  

Hopefully that all makes sense. Again, really good work on this - even without the above, we've made huge efficiency gains with this plugin, so I'm just throwing this out there in the event that the above is doable without reinventing the wheel. If not, no worries.

**Comment by badeball** [comment]
> But there's repetition cropping up with the hooks that's a result of the Befores apparently not being available for global use.

In don't understand what you're describing here and what this issue is about. Can you elaborate?

**Comment by badeball** [comment]
> That's my first suggestion, but I was also curious about the potential for tags before Steps.

Furthermore, what do you mean by this?

**Comment by CMadden8** [comment]
> In don't understand what you're describing here and what this issue is about. Can you elaborate?

Currently if you create test.feature file that has a tag `@EndpointDataA` over `Scenario A`, you have to create a test.ts to add the below hook:

`Before({ tags: "@EndpointDataA" }, function () { // some logic });`

So that `Before` fires only for test.feature.

But I currently have a situation where I have the exact same `Before` hook being used for multiple feature files. 

A step only needs to be added once to step definitions or a common steps directory - and from then on, it's 'globally' available for use in all feature files. But I can't do the same with a `Before` - it only works if added to a ts file with the same name as the feature file.

> Furthermore, what do you mean by this?

This one's probably not possible, but here's an example:

```
Scenario: The user wants to search car models
Given The user navigates to the car models page
When The user selects a brand from the brands filter
@WaitForModels
Then The car models are loaded
```

The idea being that I could target the `@WaitForModels` with a hook in the same way scenarios can be targeted, and I can write `cy.wait('@getModelsMock')` into the hook without the need of writing it into the step logic.

Why not add it to the step logic? 

Because it's not always needed. The phrases we use have keywords, datatables, doc strings that allow one phrase to be used in multiple scenarios - we write no code as a result. We just change the variables in the phrase and the language is still natural to read. 

The only thing that's not viable is changing the intercepted data of a mock or waiting for a mock to finish, as we haven't been able to think of variables for the phrase that don't look unnatural when read aloud.

I can provide more detailed examples if that still doesn't make sense.

**Comment by badeball** [comment]
[Here](https://github.com/badeball/cypress-cucumber-preprocessor/commit/2b7a65a48ec36cd4472bfe99a64486b6b2af026e) you can see a passing example of a global Before hook. IE. what you're asking of seem to already work like intended.

As for tagged steps, that's a no. You need to find a different solution. Furthermore, the gherkin language isn't actually developed here, this preprocessor is first and foremost a consumer of it.

**Comment by CMadden8** [comment]
Interesting about the global Before hook - that example is definitely something I've tried. I'll give it another shot - it could have been conflicting with another similarly named hook. Good enough for me to know it's a feature anyway.

And yeah, I figured tagged steps might not be possible...
