### ISSUE TITLE
After hook does not run when the scenario fails

### ISSUE THREAD

**Issue by mysticdevx** [badeball/cypress-cucumber-preprocessor#916]
### Current behavior

`After` hook does not run when a scenario fails

### Desired behavior

`After` hook should run even if the scenario fails.

### Test code to reproduce
``` javascrippt
// my hooks
Before({ tags: '@my-tag' }, () => {
  cy.log('this is my before hook with a tag')
});

After({ tags: '@my-tag' }, () => {
  cy.log('this is my after hook with a tag')
});

```
```gherkin
// here is my scenario
  @my-tag
  Scenario: my passing scenario
    Given visit google.com pass
  
  @my-tag
  Scenario: my failing scenario
    Given visit google.com fail

```

My result:

<img width="575" alt="hooks" src="https://user-images.githubusercontent.com/49609497/210646368-48884da7-eab9-4935-8a9d-26b1ce9d51df.png">

### Versions

* **Cypress version**: 12.1.0
* **Preprocessor version**: 15.0.0
* **Node version**: 14.20.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/issues/824#issuecomment-1241794134
