### ISSUE TITLE
How to save global variables in my project

### ISSUE THREAD

**Issue by MarcHajjar0** [badeball/cypress-cucumber-preprocessor#917]
Hello folks,

I will describe my problem briefly i hope you can help me solve it !!!!!!

I've been using this preprocessor for about 2 month. I have a long flow where i'm e2e testing it. I split each part into a scenario in the same feature file.

Every scenario contains data that is coming from the previous scenario.

In each scenario I'm saving the data i want to use in the second scenario using stateStore ( inside helpers.js export const stateStore ={};)

ISSUE:

stateStore variables can be accessed in the different scenario if we are in the same feature. When a new feature start running and try to access a data inside stateStore (stateStore.username ) i get undefined.

WHAT IS THE SOLUTION TO PASS DATA BETWEEN FEATURES??

WAITING FOR YOUR FEEDBACK

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#3-do-you-have-a-question

**Comment by badeball** [comment]
FYI, your question probably isn't dependent upon using this library. Furthermore, what you're asking for is  bad practice.
