### ISSUE TITLE
Unable to generate allure report

### ISSUE THREAD

**Issue by saikumarbt** [badeball/cypress-cucumber-preprocessor#919]
I am unable to generate allure report. Kinda stuck here. Did a simple google search using POM+BDD & Typescript. I am able to run the feature file succeessfully however unable to generate / see the execution status in the generated allure report. Without cucumber If I run, able to see the report. Not sure what I am missing here. 

This is how my cypress.config.ts file looks like

import { defineConfig } from "cypress";
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const addCucumberPreprocessorPlugin = require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
const createEsBuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;
import allureWriter from '@shelex/cypress-allure-plugin/writer';

export default defineConfig({
  env: {
    "allureAddVideoOnPass": true
  },
  e2e: {
    excludeSpecPattern: ["*.ts", "*.js", "*.md"],
    specPattern: "**/*.feature",
    supportFile: false,
    async setupNodeEvents(on, config) {
      // implement node event listeners here
      const bundler = createBundler({
        plugins: [createEsBuildPlugin(config)],
      });
      on('file:preprocessor', bundler);
      await addCucumberPreprocessorPlugin(on, config);
      allureWriter(on, config);
      return config;
    },
  },

});

Package.json:

{
  "name": "pasautomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "cy:run": "cypress run --spec \"cypress/e2e/features/**/\" --env allure=true",
    "allure:report": "allure generate allure-results --clean -o allure-report && allure open allure-report",
    "allure:clear": "if exist allure-report rmdir /q /s allure-report && if exist cypress\\screenshots rmdir /q /s cypress\\screenshots && if exist cypress\\videos rmdir /q /s cypress\\videos",
    "allure:history": "mv -f allure-report/history allure-results/history || true",
    "pretest": "npm run allure:clear",
    "posttest": "npm run allure:report || npm run allure:history",
    "test": "npm run cy:run || npm run posttest"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": [
      "cypress/step_definitions/**/*.ts"
    ]
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cypress": "^12.3.0",
    "typescript": "^4.9.4"
  },
  "devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^15.1.0",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.5",
    "@shelex/cypress-allure-plugin": "^2.34.0",
    "allure-commandline": "^2.20.1",
    "mocha-allure-reporter": "^1.4.0"
  }
}

**Comment by badeball** [comment]
This has come up before, search among the issues for “allure”.
