### ISSUE TITLE
Socket closes in afterall step 

### ISSUE THREAD

**Issue by DevKhaira** [badeball/cypress-cucumber-preprocessor#920]
### Current behavior
In afterall step I get an error 

CypressError: A callback was provided to intercept the upstream response, but a network error occurred while making the request:
Error: Socket closed before finished writing response

There is an issue on cypress which is fixed
https://github.com/cypress-io/cypress/issues/7180

### Desired behavior
This doesn't occur, or at least retries the test (but thatll probably be for the main cypress part) 

### Test code to reproduce

If you mock a test and put the html reporter in it, thats where it could happen

### Versions

* **Cypress version**: 12.3.0
* **Preprocessor version**: 15.0.0
* **Node version**: 16.7.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Does this have anything to do with the preprocessor?

> If you mock a test and put the html reporter in it, thats where it could happen

Also, this isn't enough for me to reproduce the issue.

**Comment by DevKhaira** [comment]
Hi Badebell, this seems to be an cypress issue, sorry about the lack of information. 
It happens when you have a lot of tests in one run (greater than 7). I believe it might be a cypress issue, just the cucumber preproccesor makes it worse. 

Should I post it on cypress?

**Comment by badeball** [comment]
If this can be reproduced without using the preprocessor, then it's definitely not a preprocessor issue and you should report it elsewhere, yes.

**Comment by DevKhaira** [comment]
Hey @badeball just looking, it seems to come from the cypress code
as shown on this screenshot. This happens when the cpu is slow
![Screenshot 2023-01-20 at 16 04 39](https://user-images.githubusercontent.com/5183639/213747967-5933da62-802d-44b0-937a-cf2931eeb07f.png)
