### ISSUE TITLE
Unable to integrate with `dev-tools.ai` configuration

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#924]
Unable to integrate with `dev-tools.ai` configuration. The line `await registerSmartDriverTasks(on, config);` is not picking up as expected.

```javascript
import { defineConfig } from "cypress";
import { registerSmartDriverTasks } from "@devtools-ai/cypress-sdk/dist/plugins.js";
import preprocessor from "@badeball/cypress-cucumber-preprocessor";
import browserify from "@badeball/cypress-cucumber-preprocessor/browserify.js";

export async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);
  on("file:preprocessor", browserify.default(config));
  await registerSmartDriverTasks(on, config);
  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

export default defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    supportFile: false,
    setupNodeEvents,
    baseUrl: "https://my-app-url.com",
    browser: "Chrome"
  },
});
```

Please check the issue here:
https://github.com/dev-tools-ai/devtoolsai_demo_cypress/issues/1

**Comment by badeball** [comment]
> The line `await registerSmartDriverTasks(on, config);` is not picking up as expected.

What do you mean by this?

**Comment by rakeshnambiar** [comment]
@badeball apologies for providing much details in the description. As you could see here https://github.com/dev-tools-ai/devtoolsai_demo_cypress the `dev-tools.ai` provides the ML based element locator strategy by providing the method like `cy.findByAI`. However, when I am trying to merge this suite with Cucumber preprocessor config, it says `TypeError: cy.findByAI is not a function`

**Comment by badeball** [comment]
This isn't an issue with the preprocessor. I recommend that you read through their install instruction thoroughly: https://github.com/dev-tools-ai/js-cypress-sdk#installation.

**Comment by rakeshnambiar** [comment]
@badeball Thanks for your reply. Can you see any visible errors in the `JMX config file` after I added the`dev-tools.ai` settings? Appreciate if you could verify it and that probably solve the issue.

The `dev-tools.ai` sole settings as follows:

```javascript
import { defineConfig } from 'cypress';
import { registerSmartDriverTasks } from '@devtools-ai/cypress-sdk/dist/plugins';
export default defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      registerSmartDriverTasks(on, config);
      // implement node event listeners here
      return config;
    },
  },
  chromeWebSecurity: false,
});
```
