### ISSUE TITLE
Gherkin French Definitions

### ISSUE THREAD

**Issue by gmtmaxime** [badeball/cypress-cucumber-preprocessor#925]
### Current behavior

When I write the test cases in French in the .feature files, it is impossible to execute the test. However, when writing in English (Given, when, then), the test runs correctly.

<img width="818" alt="Capture d’écran 2023-01-17 à 09 58 57" src="https://user-images.githubusercontent.com/47059512/212855653-04280aa5-2a67-4eb5-b7a9-1abc325eb703.png">
<img width="876" alt="Capture d’écran 2023-01-17 à 09 59 26" src="https://user-images.githubusercontent.com/47059512/212855686-d26df647-fe4d-4746-ac93-49aad4286ea2.png">

### Desired behavior

I would like to be able to write the test cases in French in the .feature files and have the tests run as when they are in English.

### Versions

* **Cypress version**: 12.3.0
* **Preprocessor version**: 15.1.0
* **Node version**: 14.21.2

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/localisation.md
