### ISSUE TITLE
cy custom command is not a function

### ISSUE THREAD

**Issue by valentinogagliardi** [badeball/cypress-cucumber-preprocessor#926]
### Current behavior

Cypress custom command not loaded in test run. 

Custom commands invoked in a test, for example as `cy.getByPlaceholderText("Search the web without being tracked") ` raise a `TypeError`: `TypeError: cy.getByPlaceholderText is not a function`.

### Desired behavior

Custom commands defined in `cypress/support/commands.js` should be picked up by the test runner.

### Test code to reproduce

Building from the example in [esbuild-cjs](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-cjs), I configured a custom command in `examples/esbuild-cjs/cypress/support/commands.js`:

```js
Cypress.Commands.add('getByPlaceholderText', (placeholder) => {
  cy.get("input").should(
    "have.attr",
    "placeholder",
    placeholder
  );
})
```

Content of `examples/esbuild-cjs/cypress/support/e2e.js`:

```js
import './commands'
```

Test code in `examples/esbuild-cjs/cypress/e2e/duckduckgo.js`:

```js
const { When, Then } = require("@badeball/cypress-cucumber-preprocessor");

When("I visit duckduckgo.com", () => {
  cy.visit("https://duckduckgo.com/");
});

Then("I should see a search bar", () => {
  cy.getByPlaceholderText("Search the web without being tracked")

  assert.deepEqual({}, {});
});
```

### Extended debug output

```text
  cypress-cucumber-preprocessor resolved no configuration +1s
  cypress-cucumber-preprocessor resolving step definitions using template(s) [
  cypress-cucumber-preprocessor   'cypress/e2e/[filepath]/**/*.{js,mjs,ts,tsx}',
  cypress-cucumber-preprocessor   'cypress/e2e/[filepath].{js,mjs,ts,tsx}',
  cypress-cucumber-preprocessor   'cypress/support/step_definitions/**/*.{js,mjs,ts,tsx}'
  cypress-cucumber-preprocessor ] +1ms
  cypress-cucumber-preprocessor replacing [filepath] with 'duckduckgo' +0ms
  cypress-cucumber-preprocessor replacing [filepart] with [ 'duckduckgo' ] +0ms
  cypress-cucumber-preprocessor for 'cypress/e2e/duckduckgo.feature' yielded patterns [
  cypress-cucumber-preprocessor   'cypress/e2e/duckduckgo/**/*.{js,mjs,ts,tsx}',
  cypress-cucumber-preprocessor   'cypress/e2e/duckduckgo.{js,mjs,ts,tsx}',
  cypress-cucumber-preprocessor   'cypress/support/step_definitions/**/*.{js,mjs,ts,tsx}'
  cypress-cucumber-preprocessor ] +1ms
  cypress-cucumber-preprocessor found step definitions [ 'cypress/e2e/duckduckgo.js' ] +2ms


  duckduckgo.com
[40846:0117/150124.326784:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", source:  (0)
[40846:0117/150124.735284:INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", source:  (0)
    1) visiting the frontpage


  0 passing (3s)
  1 failing

  1) duckduckgo.com
       visiting the frontpage:
     TypeError: cy.getByPlaceholderText is not a function
      at Context.eval (https://duckduckgo.com/__cypress/tests?p=cypress/e2e/duckduckgo.feature:10649:12)
      at Registry.runStepDefininition (https://duckduckgo.com/__cypress/tests?p=cypress/e2e/duckduckgo.feature:9238:48)
      at Object.fn (https://duckduckgo.com/__cypress/tests?p=cypress/e2e/duckduckgo.feature:10119:41)
      at runStepWithLogGroup (https://duckduckgo.com/__cypress/tests?p=cypress/e2e/duckduckgo.feature:9843:36)
      at Context.eval (https://duckduckgo.com/__cypress/tests?p=cypress/e2e/duckduckgo.feature:10116:60)
```

### Versions

* **Cypress version**: latest
* **Preprocessor version**: latest
* **Node version**: v18.9.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I'm guessing you've configured `supportFile: false`, in which case your import ".." is not actually being executed.

**Comment by valentinogagliardi** [comment]
Seems to be indeed the case. Any particular reason why `supportFile` is set to `false` in the example? Thanks.

**Comment by badeball** [comment]
Only that there's nothing useful to put in a support file (for an example) and Cypress doesn't like a non-existing support file. But I'm going to add a bunch of empty files because you're not the first one to fall into this.
