### ISSUE TITLE
Error with multiple tags

### ISSUE THREAD

**Issue by edurendon** [badeball/cypress-cucumber-preprocessor#927]
### Current behavior

When you try to execute two or more test with different tags like this:

npx cypress run --env TAGS="@testone or @testthree"

show this error:

_Couldn't determine Mocha version
Can't run because no spec files were found.

We searched for specs inside of this folder:_

### Desired behavior

When you run: 

npx cypress run --env TAGS="@testone or @testthree"

The test with tags @testone and @testthree runs.

### Test code to reproduce

Feature: Test

  @testone
  Scenario Outline: Access
    Given ......
    Then ....

  @testtwo
  Scenario Outline: Search
    Given ..........
    When ........
    Then ..........

  @testthree
  Scenario Outline: Search
    Given ..........
    When ........
    Then ..........

### Versions
Cypress version: 12.3.0
Preprocessor version: 15.1.1
Node version: 16.16.0

**Comment by badeball** [comment]
It appears that you're misunderstand the boolean logic here. There are no scenarios that are tagged with both A and B. If you're looking to run test tagged with either A or B, you would use `tags="@A or @B"`.
