### ISSUE TITLE
Invalid option in build() call: "watch"

### ISSUE THREAD

**Issue by Darksymphony75** [badeball/cypress-cucumber-preprocessor#929]
package.json:
```
  "@badeball/cypress-cucumber-preprocessor": "^15.1.2",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.5",
    "cypress": "^12.3.0",
```
using cypress.config.js (not .ts):
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({

  e2e: {
    baseUrl: 'http://localhost:4200',
    specPattern: "**/*.feature",

  async setupNodeEvents(on, config) {
  const createEsbuildPlugin = require('@badeball/cypress-cucumber-preprocessor/esbuild').createEsbuildPlugin
  const createBundler = require('@bahmutov/cypress-esbuild-preprocessor')

  await require('@badeball/cypress-cucumber-preprocessor').addCucumberPreprocessorPlugin(on, config)

  on('file:preprocessor',   createBundler({
    plugins: [createEsbuildPlugin(config)],
  }));

  return config;
}

  },
});
```
Now when I run cypress test runner, all tests are there. But when I click on ANY test, I have immediately this error:

```
Error: Build failed with 1 error:
C:\Users\JS\Desktop\test\node_modules\esbuild\lib\main.js:255:12: ERROR: Invalid option in build() call: "watch"
    at failureErrorWithLog (C:\Users\JS\Desktop\test\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Users\JS\Desktop\test\node_modules\esbuild\lib\main.js:953:16
    at responseCallbacks.<computed> (C:\Users\JS\Desktop\test\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (C:\Users\JS\Desktop\test\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (C:\Users\JS\Desktop\test\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
I can't run any test with the latest cucumber preprocessor and latest cypress. Before (with version 11.5 cucumber and v.10 cypress i had no isssues at all).

Also I can't find any normal documentation how to configure the latest cucumber preprocessor with the latest cypress in config. JS file.

**Comment by badeball** [comment]
I can’t reproduce the issue with the information you’re providing. Also there are plenty of working examples here: https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples.

**Comment by Darksymphony75** [comment]
strange, maybe then some issue with esbuild on my side. I now tried to replace it with browserify and works well.

**Comment by l0gicgate** [comment]
I have the exact same issue. Running same config as @Darksymphony75 and same version of the plugins.

What fixed it for me was locking `esbuild` version to `0.16.5`.

```
"devDependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^15.1.2",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.1.5",
    "esbuild": "0.16.5",
    // ...
}
```

**Comment by norbertorok92** [comment]
I had the same issue. @l0gicgate great catch! seems like locking `esbuild` to version `0.16.5` solves the issue.

**Comment by dlabrecque-uzinakod** [comment]
esbuild seems to have introduced backwards incompatible changes with version 0.17.0.
See changelog: [https://github.com/evanw/esbuild/releases/tag/v0.17.0](https://github.com/evanw/esbuild/releases/tag/v0.17.0)
For now, locking your version to any version below 0.17.0 seems to fix the issue.

**Comment by badeball** [comment]
This can be tracked at https://github.com/bahmutov/cypress-esbuild-preprocessor/issues/229 and @l0gicgate's workaround (https://github.com/badeball/cypress-cucumber-preprocessor/issues/929#issuecomment-1399654455) can be used for now.

**Comment by badeball** [comment]
`@bahmutov/cypress-esbuild-preprocessor` appears to have been updated and pinning esbuild should no longer be necessary-
