### ISSUE TITLE
When I am trying to execute bdd testcases, found this issues 'And is not defined', is it expected behavior for this plugin?

### ISSUE THREAD

**Issue by prithabazani** [badeball/cypress-cucumber-preprocessor#930]
### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by prithabazani** [comment]
The following error originated from your test code, not from Cypress.

> And is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

**Comment by badeball** [comment]
Sigh… I’m going to let you figure this one out yourself.
