### ISSUE TITLE
adding retries to config disables screenshots being added to html report

### ISSUE THREAD

**Issue by MassimoLobrutto** [badeball/cypress-cucumber-preprocessor#931]
When a test is run in normal mode screenshot has (failed).png suffix attached and is picked up correctly bu the html report

Add 

retries: {
    runMode: 1
  },

to cypress config and rerun test

Expected - Screenshot to be picked up by html report
Actual - Screenshot is not picked up by report. This is probably due to any screen shot that is retried has the suffix (failed) (attempt 2).png attached and thus due to the addition of (attempt x) is not being picked up by the report

This repo will reproduce the issue

https://github.com/MassimoLobrutto/ErrorReproduction

After reproducing the issue, remove the retries entry from cypress config and the screenshot will return

**Comment by badeball** [comment]
Hey @MassimoLobrutto, thanks for reporting this issue. I've fixed it in v15.1.3.
