### ISSUE TITLE
Not able to add "AND" sentence with TS on step definitions ,

### ISSUE THREAD

**Issue by ugogarziasoftserve** [badeball/cypress-cucumber-preprocessor#934]
### Current behavior

When I tried to add cucumber expresion AND on steps defintions using Typescript file (extension ts), the import it is not working as expected 

import { And } from "@badeball/cypress-cucumber-preprocessor";

"Module '"@badeball/cypress-cucumber-preprocessor"' has no exported member 'AND'.ts(2305)"

It only works when I change the file extension to JS

### Desired behavior

I should be able to work with TS extension files 

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).
<img width="903" alt="Capture2" src="https://user-images.githubusercontent.com/110488889/214889629-dfaf9767-4866-4983-bdd7-a8ad5cf9f57a.PNG">

**Comment by badeball** [comment]
You need to go through the checklist, they’re not suggestions.

**Comment by ugogarziasoftserve** [comment]
there is not any suggestion, looks like AND sentence it is missing for TS files,  I have navigate trought "indexd.ts" and there its only given, when and then 

export { defineStep as Given, defineStep as When, defineStep as Then};

**Comment by ugogarziasoftserve** [comment]
> You need to go through the checklist, they’re not suggestions.
there is not any suggestion, looks like AND sentence it is missing for TS files,  I have navigate trought "index.d.ts" and there its only given, when and then 

export { defineStep as Given, defineStep as When, defineStep as Then};

**Comment by badeball** [comment]
Dude, this is explained in the FAQ.
