### ISSUE TITLE
Webpack compilation errors involving TypeScript import aliases

### ISSUE THREAD

**Issue by michaelmaat** [badeball/cypress-cucumber-preprocessor#938]
First of all thanks for maintaining this package. The ability to use `.feature`files helps a lot for the acceptance of e2e testing in our organization.

### Current behavior

Using TypeScript import aliases in e2e related `.ts` files results in Webpack compilation errors when running the e2e tests. But not all imports that use a TypeScript aliases result in an error.

Running `npm run nx -- e2e admin-e2e` results in the following error in the terminal:

> Oops...we found an error preparing this test file:
> src/e2e/user-scenarios.feature
> The error was:
> Error: Webpack Compilation Error
> Module not found: Error: Can't resolve '@mycompany/shared/cypress/helpers/util-wait' in '/Users/michael/sites/mycompany-apps/apps/admin-e2e/src/e2e'
>    at handle (/Users/michael/sites/mycompany-apps/node_modules/@cypress/webpack-preprocessor/dist/index.js:231:23)
>    at finalCallback (/Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:441:32)
>    at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:505:17
>    at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/HookWebpackError.js:68:3
>    at Hook.eval [as callAsync] (eval at create (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/Hook.js:18:14)
>    at Cache.storeBuildDependencies (/Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Cache.js:122:37)
>   at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:501:19
>    at Hook.eval [as callAsync] (eval at create (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/Hook.js:18:14)
>    at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:498:23
>    at Compiler.emitRecords (/Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:919:5)
>    at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:490:11
>    at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:885:14
>    at Hook.eval [as callAsync] (eval at create (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/Hook.js:18:14)
>    at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:882:27
>    at /Users/michael/sites/mycompany-apps/node_modules/neo-async/async.js:2818:7
>    at done (/Users/michael/sites/mycompany-apps/node_modules/neo-async/async.js:3522:9)
>    at Hook.eval [as callAsync] (eval at create (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/michael/sites/mycompany-apps/node_modules/tapable/lib/Hook.js:18:14)
>    at /Users/michael/sites/mycompany-apps/node_modules/webpack/lib/Compiler.js:736:33
>    at /Users/michael/sites/mycompany-apps/node_modules/graceful-fs/graceful-fs.js:143:16
>    at /Users/michael/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
>    at /Users/michael/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
>    at /Users/michael/Library/Caches/Cypress/10.8.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
>    at FSReqCallback.oncomplete (node:fs:192:23)
>
> This occurred while Cypress was compiling and bundling your test code. This is usually caused by:
> 
> - A missing file or dependency
> - A syntax error in the file or one of its dependencies
> 
> Fix the error in your code and re-run your tests.

The used alias (`@mycompany/shared/cypress/helpers/util-wait`) is present in `tsconfig.base.json` and ESLint and VS Code correctly recognize the alias and its corresponding path.

When replacing the aliases that result in an error with relative paths the tests do run. In our full repository this causes issues when moving and creating libraries because the relative imports have to be adjusted every time.

### Desired behavior

The ability to use TypeScript paths for imports in all e2e related .ts files.

### Test code to reproduce

Minimal Git repository that I've created: https://github.com/michaelmaat/mycompany-cucumber. It has a **main** and **webpack-error** branch to illustrate the problem.

Please note that we have a [Nx monorepo](https://nx.dev/) setup. In this minimal example I've removed all Angular apps and all but one of the e2e apps.

#### main branch
- Uses relative paths for (some) imports in `mycompany-apps/apps/admin-e2e/src/e2e/user-scenarios.ts` and `mycompany-apps/apps/admin-e2e/src/support/e2e.ts`
- Running `npm run nx -- e2e admin-e2e` works as expected. One scenario succeeds and one scenario fails on purpose
- Note that the import in `mycompany-apps/apps/admin-e2e/src/fixtures/surgeons.ts` does use a TypeScript path/alias for the import without problems.

#### webpack-error branch
- Uses TypeScript paths/aliases for the imports in `mycompany-apps/apps/admin-e2e/src/e2e/user-scenarios.ts`
- Running `npm run nx -- e2e admin-e2e` gives a Webpack Compilation error as described above.

### Versions

* **Cypress version**: 10.8.0
* **Preprocessor version**: 15.1.2
* **Node version**: 16.18.1
* **Nx version**: 14.7.8

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I _really_ wish you'd remove everything about Nx from the example, as well as every unrelated file. Otherwise, I basically have to do it, in order to verify exactly where the problem reside.

**Comment by michaelmaat** [comment]
Since the errors seem to be path related I was hesitant to make a lot of changes in the structure, but I get your point that it's not very clear when seeing the repository for the first time.

Using `DEBUG=cypress-cucumber-preprocessor` and looking into the preprocessor code, I think the issue is related to the fact that the `libs` folder is outside of the Cypress root folder. There seem to be some checks in place to see if a `filePath` is located inside the `projectRoot`. But I think this only takes step definition files into account, since the message is not displayed when you import a library which is outside the `projectRoot`.

I have created a new very minimalistic repository to demonstrate this: https://github.com/michaelmaat/minimal-cucumber-project. In [cypress/e2e/duckduckgo.ts](https://github.com/michaelmaat/minimal-cucumber-project/blob/main/cypress/e2e/duckduckgo.ts) only using a relative import for the WaitHelper works, importing using a TypeScript alias gives the error we have been experiencing in our project as well:

>  Module not found: Error: Can't resolve '@mycompany/helpers/waithelper' in '/Users/michael/sites/minimal-cucumber-project/cypress/e2e'

Would it somehow be possible to load libraries from outside the `projectRoot`?

**Comment by badeball** [comment]
`ts-loader` doesn't seem to take `compilerOptions.paths` into account by default, but requires a plugin, ref.: https://github.com/TypeStrong/ts-loader#baseurl--paths-module-resolution.

**Comment by michaelmaat** [comment]
Thank you! After adding the plugin the typescript paths work.
