### ISSUE TITLE
Ignoring the settings in the `support` folder

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#939]
As described here https://on.cypress.io/uncaught-exception-from-application I have added the `e2e.js` inside the `support` folder. But the test is ignoring it completely. Please see the screenshot below.

![Screenshot 2023-02-01 at 21 36 50](https://user-images.githubusercontent.com/20258636/216169327-7be13fdb-e244-4ca7-af31-32183e80137e.png)

**Comment by badeball** [comment]
Not related to preprocessing.

**Comment by rakeshnambiar** [comment]
@badeball I checked this without `cucumber-preprocess` on the latest cypress version `12.4.0` and it is working as expected. I am almost certain this is related to preprocessing. Could you please check by adding it?

**Comment by badeball** [comment]
This works fine, as far as I know.

**Comment by rakeshnambiar** [comment]
Can you pls include it in the sample?

**Comment by rakeshnambiar** [comment]
forgot to mention that I am keen on `browserify-esm` exmaple

**Comment by rakeshnambiar** [comment]
I tried adding it to the `broserify-esm` example and it is working. When it cannot locate an element, I can see it is printing ` AssertionError: Timed out retrying after 4000ms: Expected to find element: `#sample`, but never found it.` However, when I have the similar situation in my application (due to any cosole error / API error in the console) it is failing. However, with the normal cypress I am able to execute the similar steps.

**Comment by badeball** [comment]
There is nothing I can do for you unless you can provide me with a clear example that illustrates the issue. Vague descriptions such as the last scenario you're description isn't going to make me investigate.
