### ISSUE TITLE
Overriding TAG option in command not work when run more features

### ISSUE THREAD

**Issue by miroslav750** [badeball/cypress-cucumber-preprocessor#940]
### Current behavior

Currently if I have project with more feature files and I want to run all feature files and once but ONLY test cases that have specific tag, it just ignore it.
I am using scripts command to run:
` "cy:pipeline": "branch=${CI_COMMIT_REF_SLUG:-$(git rev-parse --abbrev-ref HEAD)}; cypress run --project ./apps/my-app --browser=electron --e2e --config-file cypress/configs/deployed.config.js --env branchPath=$branch",
`
This script is called from pipeline  or manually(command from makefile):
`npm run cy:pipeline -- --config '{"specPattern":"**/API/user-ms.feature"}' --env '{"TAGS":"@manually", "branchPath":"$$CI_COMMIT_REF_SLUG"}'
`

Result is that all tests are run. 

### Desired behavior

Desired behavior is to run only test cases that have tag `@manually`

### Versions

* **Cypress version**: 11.2
* **Preprocessor version**: 15.0.0
* **Node version**: 16.17.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [X] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You need to provide a way of reproducing the issue.

**Comment by badeball** [comment]
Closing due to lack of reproducible example. Feel free to open up another issue if anything changes in this regard.
