### ISSUE TITLE
Can't run the cucumber feature on Gitlab pipeline which works in local environment

### ISSUE THREAD

**Issue by chaitali-diwanji** [badeball/cypress-cucumber-preprocessor#941]
**Current behavior**

Getting the below error while running the feature on gitlab pipeline
Error:
**An error was thrown in your plugins file while executing the handler for the before:run event.
The error we received was:
TypeError: fs_1.promises.rm is not a function
    at beforeRunHandler (/xxxxx/cypress-cucumber-test/node_modules/@badeball/cypress-cucumber-preprocessor/lib/add-cucumber-preprocessor-plugin.js:66:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)**

**Desired behavior**

As the set up is same on local environment, feature should execute in the same way on pipeline

**Versions**

* **Cypress version**: 12.4.0
* **Preprocessor version**: 15.1.2
* **Node version**: v12.18.3
* **Browser**: Electron 106 (headless) 

I'm passing the run command as below in .gitlab.yml file :
npm run runFeatures

where package.json has scripts added with this configuration:
    "runFeatures" : "./node_modules/.bin/cypress run --headless --spec cypress/e2e/features/**/*.feature"

**Comment by badeball** [comment]
Answered in FAQ.

**Comment by sscaff1** [comment]
Where in the FAQ?
