### ISSUE TITLE
stepDefinitions [filepath] doesn't escape special characters

### ISSUE THREAD

**Issue by awinograd** [badeball/cypress-cucumber-preprocessor#946]
### Current behavior

I have the following directory structure in a NextJS app:

```
pages/organizations/[id].ts
features/organizations/[id]/steps.ts
cypress/support/step_definitions/steps.ts
```

My configuration uses the default for stepDefinitions which includes `"features/[filepath]/**/*.{js,ts}"`

However, because the filepath (`organizations/[id]` ) includes special characters `[]` the call to `glob` to find matching files does not find the matching `steps.ts` and I get the following error when running tests:

```
We tried searching for files containing step definitions using the following search pattern templates:

- features/[filepath]/*/.{js,ts}
- features/[filepath].{js,ts}
- cypress/support/step_definitions/*/.{js,ts}

These templates resolved to the following search patterns:

- features/organizations/[id]/*/.{js,ts}
- features/organizations/[id].{js,ts}
- cypress/support/step_definitions/*/.{js,ts}

These patterns matched the following files:

- cypress/support/step_definitions/steps.ts
```

### Desired behavior

Desired Behavior is for `[filepath]` to escape any special characters such that they properly match paths on the filesystem. In this case the resulting substitution should be `organizations/\\[id\\]`

Or if you choose not to implement this, perhaps adding a Caveat https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md#caveats

### Test code to reproduce

 Working on this.

### Versions

* **Cypress version**: 12.x
* **Preprocessor version**: 14.0.0
* **Node version**: 16.x

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Does escaping as described here work for you? https://github.com/isaacs/node-glob/issues/153

**Comment by awinograd** [comment]
yes the escaping does work as expected

**Comment by awinograd** [comment]
For the time being, I've resorted to a yarn patch to achieve the proper escaping. It's not possible to do so in user-land as the `[filepath]` substitution is performed in the library

```diff
diff --git a/lib/step-definitions.js b/lib/step-definitions.js
index f36ac987e755593e39f5633f57969afcb0e5b81c..0bbbc389b38c22c9dd4ecdedb3ff883aaab271f9 100644
--- a/lib/step-definitions.js
+++ b/lib/step-definitions.js
@@ -42,7 +42,7 @@ function getStepDefinitionPatternsPost10(configuration, filepath) {
     if (!(0, is_path_inside_1.default)(filepath, projectRoot)) {
         throw new Error(`${filepath} is not inside ${projectRoot}`);
     }
-    const filepathReplacement = trimFeatureExtension(path_1.default.relative(configuration.preprocessor.implicitIntegrationFolder, filepath));
+    const filepathReplacement = trimFeatureExtension(path_1.default.relative(configuration.preprocessor.implicitIntegrationFolder, filepath)).replaceAll('[', '\\[').replaceAll(']', '\\]');
     (0, debug_1.default)(`replacing [filepath] with ${util_1.default.inspect(filepathReplacement)}`);
     const parts = pathParts(filepathReplacement);
     (0, debug_1.default)(`replacing [filepart] with ${util_1.default.inspect(parts)}`);
```

**Comment by badeball** [comment]
Why do you not escape your configuration values as described in the above-mentioned issue?

**Comment by awinograd** [comment]
My configuration value is `"features/[filepath]/**/*.{js,ts}"`. The issue isn't the brackets surrounding `[filepath]`. Rather, the issue is the string that is expanded from `[filepath]`, namely, `organizations/[id]`. Unfortunately I cannot escape `[id]` as `\\[id\\]` in my configuration as it's dynamically inserted via the substitution

**Comment by badeball** [comment]
Aha, now I understand. I'll see if I can get around to this soon.

**Comment by badeball** [comment]
I'm releasing v15.1.5 now, hits npm in a couple of minutes.

**Comment by awinograd** [comment]
Thanks @badeball ! Confirming 15.1.5 fixes my issue
