### ISSUE TITLE
Flags for on/off  log groups

### ISSUE THREAD

**Issue by varshanharshank** [badeball/cypress-cucumber-preprocessor#947]
### Current behavior

Until the version 15.0.0, Test logs are not grouped. After migrating 15.1.0 (https://github.com/badeball/cypress-cucumber-preprocessor/issues/796), logs are grouped. 

Do we have any flags to enable old way to display logs in the new version? ( My perspective easy to view logs for expanding each step compare with grouping test logs)

This will help out to enable or disable when ever it is required.

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> Do we have any flags to enable old way to display logs in the new version?

No.

> This will help out to enable or disable when ever it is required.

I don't understand the use case here. When would you prefer the old behavior?

**Comment by varshanharshank** [comment]
@badeball  

In version **15.0.0**, I could see the report below (Each step **Given, When,Then**)  is able to expand and narrow down )

<img width="793" alt="image" src="https://user-images.githubusercontent.com/81335781/221312228-256d4210-4111-47f2-a12b-7d2f8dc7b935.png">

But, In  the latest version **15.1.4**, there is no expansion and narrow-down options for **Given When,Then**,

<img width="878" alt="image" src="https://user-images.githubusercontent.com/81335781/221317575-0c1dee7f-3795-46e7-8ea7-5ac83c1a007d.png">

Is there any way I can see the old way of reporting in 15.1.4?

**Comment by badeball** [comment]
What kind of report is it you're referring to here?

**Comment by varshanharshank** [comment]
@badeball  I am using an allure report. The below dependencies are used for my project

<img width="446" alt="image" src="https://user-images.githubusercontent.com/81335781/221465720-c406c4e8-ca7e-4001-ad02-ac41bea11936.png">

If I use this version "**@badeball/cypress-cucumber-preprocessor": "15.0.0"**,  the following cucumber steps Given, When, Then are able to expand and narrow down. I am expecting the same kind of style in "**@badeball/cypress-cucumber-preprocessor": "15.1.4"**

**Comment by badeball** [comment]
I don't believe the solution lies within this repository and I see that it's already been reported at https://github.com/Shelex/cypress-allure-plugin/issues/186.
