### ISSUE TITLE
Unable to use preprocessor in conjunction with deleting videos if successful cypress code

### ISSUE THREAD

**Issue by AdrianPaters0n** [badeball/cypress-cucumber-preprocessor#949]
### Current behavior
I am attempting to implement the Cypress code to delete videos of the test if successful however this code conflicts with the preprocessor. I believe the issue is that both are dependent on being triggered against the 'after:spec' node event.

The Cypress example for video deletion is here: [https://docs.cypress.io/api/plugins/after-spec-api#Delete-the-recorded-video-if-the-spec-passed](https://docs.cypress.io/api/plugins/after-spec-api#Delete-the-recorded-video-if-the-spec-passed)

Depending on the order of registering the Node events, you either generate a cucumber.json output with an empty object [] and the videos are successfully deleted, or a populated cucumber.json output but the videos are not deleted.

### Desired behavior

You should be able to successfully generate the cucumber.json output alongside deleting the videos of any successful tests.

### Test code to reproduce

```
async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {

  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await addCucumberPreprocessorPlugin(on, config);

  on('after:spec', (spec, results) => {
    if (results && results.stats.failures === 0 && results.video) {
      // `del()` returns a promise, so it's important to return it to ensure
      // deleting the video is finished before moving on
      return del(results.video)
    }
  })

  return config;
}

export default defineConfig({
  e2e: {
    setupNodeEvents,
  },
});

```

### Versions

* **Cypress version**: 12.5.1
* **Preprocessor version**: 15.1.3
* **Node version**: 18.13.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I've been meaning to document this, but haven't gotten that far yet. Meanwhile you can check [this](https://github.com/badeball/cypress-cucumber-preprocessor/issues/705#issuecomment-1126357407) and see if you can solve it yourself.

**Comment by badeball** [comment]
I've documented this here: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md
