### ISSUE TITLE
Configure timeouts for tasks

### ISSUE THREAD

**Issue by MassimoLobrutto** [badeball/cypress-cucumber-preprocessor#954]
I have a block of code that checks a certian amount of rows, all works fine if i run 50, or even 100 rows for it to check

but if i let this number increase i get 

![image](https://user-images.githubusercontent.com/81157392/220626750-11775304-f911-4d55-954b-59af430dcbdf.png)

there doesnt seem to be a way to configure this time out, while 60s is plenty in practice a lot of actions take longer than 60s so this timeout should be configurable by the user

would this be possible?

**Comment by badeball** [comment]
The code that Cypress appears to claim times out, is this: https://github.com/badeball/cypress-cucumber-preprocessor/blob/v15.1.4/lib/add-cucumber-preprocessor-plugin.ts#L370-L376.

IE. it's merely a variable assignment and if it takes longer than 60 seconds, then something else is up. I can't tell you what based on the current information, but I can say that it wont be solved by making the timeouts longer.
