### ISSUE TITLE
omitFiltered property does not function for tags

### ISSUE THREAD

**Issue by rustam0533** [badeball/cypress-cucumber-preprocessor#955]
### Current behavior

Based on your doc  once "omitFiltered" is being set true tests without the tag should be ignored. That's not the case, they have been pended which takes some extra time

### Desired behavior

only test with defined tag runs and all other tests are ignored at all without being pended.
![r1](https://user-images.githubusercontent.com/31739529/220920012-c10931f2-ca65-4a2f-a362-363196238d62.png)
![r2](https://user-images.githubusercontent.com/31739529/220920018-946e0a4d-c10a-4664-97d4-bb1ef12f4577.png)
![r3](https://user-images.githubusercontent.com/31739529/220920021-91ba385d-bd6f-4015-a3e7-9f0305ed3611.png)
![r5](https://user-images.githubusercontent.com/31739529/220920023-7081c57c-66de-46f6-bf51-933dde2eb5f5.png)

### Versions
**Language - Typescript
* **Cypress version- 12.4.0
* **Preprocessor version-15.1.0
* **Node version-18.12.1

**Comment by tuan-yojee** [comment]
can you try to use this command: `npx cypress run --e2e --env tags=@smoke`. Let me know if it works or not

**Comment by rustam0533** [comment]
hey @tuan-yojee , I have tried it, but it didn't make difference
![ru1](https://user-images.githubusercontent.com/31739529/221008119-a1c0346a-d762-44f4-ad19-44e7a60f3545.png)

**Comment by badeball** [comment]
`omitFiltered` and `filterSpecs` aren't configuration options that goes into the `json` block, they should be outside.
