### ISSUE TITLE
Readme instruction doesn't work for running feature files

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [badeball/cypress-cucumber-preprocessor#956]
### Current behavior

I was following your [readme](https://www.npmjs.com/package/cypress-cucumber-preprocessor) instructions to setup tests using gherkin syntax and ts files. But it didn't work. When running command `npx cypress open` and then choosing google chrome it simply ignores all the `.feature` files and displayls only regular cypress tests in `.cy.ts` files.
When I cloned your repository at main branch it behaves the same way. Also your main branch is missing those files that readme references. I've found out that commit c88a5039ec3bbdc3c0ecb72b813a2aaab213401e contains those files that readme references. When I switched to that commit, ran `yarn install` and then `npx cypress open` - it displays different window then browser (no browser choice) which looks unusual but at least it shows a list of .feature files. Gives error on execution though (it doesn't see steps definitions) but at least it lists `.feature` files.
Also I tried to use tips from your readme in this repository from main branch - but it didn't help neither.

### Desired behavior

Please update your readme instruction so that I could follow it and be able to use gherkin syntax for cypress tests. Best to provide some minimal working example as well. Just minimum required to execute tests from `.feature` files via google chrome. So that any developer could build up on top of it anything that's necessary. Thanks.

### Test code to reproduce

// \cypress.config.ts
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});

```

// \package.json
```
{
  "name": "etaplus-test-gherkin",
  "version": "1.0.0",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "cosmiconfig": "^8.0.0",
    "cypress": "^12.6.0",
    "typescript": "^4.9.5"
  },
  "scripts": {
    "build": "tsc"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  },
  "dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^15.1.4"
  }
}

```

// \yarn.lock
// didn't provide, because it's too long and it's autogenerated anyway.

// \cypress\tsconfig.json
```
{
  "compileOnSave": true,
  "exclude": ["node_modules", "tmp"],
  "include": ["**/*.ts", "**/*.feature"],
  "compilerOptions": {
    "sourceMap": false,
    "types": ["cypress", "node"]
  },
  "testFiles": "**/*.{feature,features}",
  "noEmit": true
}

```

// \cypress\e2e\sample.feature
```
Feature: sample
  Scenario: visiting the frontpage
    When I visit duckduckgo
    Then I should see a search bar

```

// \cypress\e2e\sample.ts
```
import { When, Then } from "@badeball/cypress-cucumber-preprocessor";

When("I visit duckduckgo", () => {
  cy.visit("https://www.duckduckgo.com");
});

Then("I should see a search bar", () => {
  cy.get("input").should(
    "have.attr",
    "placeholder",
    "Search the web without being tracked"
  );
});

```

// \cypress\fixtures\example.json
```
{
  "name": "Using fixtures to represent data",
  "email": "hello@cypress.io",
  "body": "Fixtures are a great way to mock data for responses to routes"
}

```

// \cypress\plugins\index.ts
```
// const cucumber = require("cypress-cucumber-preprocessor").default; // eslint-disable-line

// module.exports = on => {
//   on("file:preprocessor", cucumber());
// };

```

// \cypress\support\commands.ts
```
// ***********************************************
// This example commands.js shows you how to
// create various custom commands and overwrite
// existing commands.
//
// For more comprehensive examples of custom
// commands please read more here:
// https://on.cypress.io/custom-commands
// ***********************************************
//
//
// -- This is a parent command --
// Cypress.Commands.add('login', (email, password) => { ... })
//
//
// -- This is a child command --
// Cypress.Commands.add('drag', { prevSubject: 'element'}, (subject, options) => { ... })
//
//
// -- This is a dual command --
// Cypress.Commands.add('dismiss', { prevSubject: 'optional'}, (subject, options) => { ... })
//
//
// -- This will overwrite an existing command --
// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })
```

// \cypress\support\e2e.ts
```
// ***********************************************************
// This example support/e2e.js is processed and
// loaded automatically before your test files.
//
// This is a great place to put global configuration and
// behavior that modifies Cypress.
//
// You can change the location of this file or turn off
// automatically serving support files with the
// 'supportFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/configuration
// ***********************************************************

// Import commands.js using ES2015 syntax:
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')
```

### Versions

* **Cypress version**: 12.6.0
* **Preprocessor version**: 15.1.4
* **Node version**: 16.4.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues). - it's not a logging issue, so I didn't check this one.
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor
