### ISSUE TITLE
Feature files running in Random order (Folders) instead of Sequential order using  multiple TAGS

### ISSUE THREAD

**Issue by JomyGeo** [badeball/cypress-cucumber-preprocessor#960]
### Current behaviour

I have multiple folders and it contains more no of feature files in it. When I run the feature files using the **TAGS** the order of execution is happening in random order instead of the **sequential order of the folder.**. 

Each and every folder is dependent on the previous folder in my project. So it should run in the sequential order 

Eg: When I run the below script then It should start running from FormFIlling,  OrangeHRM and SauceDemofolder. But sometimes it picks the random folder in random order for the execution. It is not happening all the time. 

npx cypress run --env TAGS="@Formor @HRMor @SDemo"

  ---e2e
       -----FeatureFiles
          ---FormFIlling
                       cucumberTag  : @Form
               ----- 01_FillForm_AdamDetails.feature
               ----- 02_FillForm_jacobDetails.feature  
               ----- 03_FillForm_johnDetails.feature  

         ---OrangeHRM
                       cucumberTag: @HRM
             ----- 01_OrangeHRM_Invalidlogin.feature
             ----- 02_OrangeHRM_validlogin.feature  

        ---SauceDemo
                 cucumberTag: @SDemo
            ----- 01_SourceDemo_Invalidlogin.feature 
            ----- 02_SourceDemo_lockedUser.feature  
            ----- 03_SourceDemo_validlogin.feature   

### Versions

* **cypress": "^12.4.0**:
* **@badeball/cypress-cucumber-preprocessor": "^15.1.2**:
* **Node version : v16.17.0**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hye @JomyGeo, you need to provide me with a runnable example that illustrates this behavior.

**Comment by JomyGeo** [comment]
@badeball  please find the repo URL - https://github.com/JomyGeo/DemoAutomationProject.git

Execution command :  npx cypress run --headed  --spec "cypress/e2e/FeatureFiles/DSD_FeatureFiles/**/**/*.feature" -e stepDefinitions="cypress/e2e/StepDefinitions/DSD_StepDefinitions/**/**/*.js",TAGS="@Form or @HRM or @SDemo"

Folder structure:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/89033776/229423367-9c6e5a5a-2185-4c9f-852d-4cf3eeab285d.png">

Execution Order :
<img width="648" alt="image" src="https://user-images.githubusercontent.com/89033776/229423400-ac660f4b-9794-4173-a776-eeeefb5f3cf0.png">

Current behavior :  It is currently running in the below order
 --- @Form
--- @Sdemo
---@HRM

Expected behavior : I should run in the below mentioned order based on the folder structure in framework

 --- @Form
---@HRM
--- @Sdemo

**Comment by badeball** [comment]
Can't reproduce, I'm getting the expected execution order.

```
$ npx cypress run --headed  --spec "cypress/e2e/FeatureFiles/DSD_FeatureFiles/**/**/*.feature" -e stepDefinitions="cypress/e2e/StepDefinitions/DSD_StepDefinitions/**/**/*.js",TAGS="@Form or @HRM or @SDemo"

...

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  Form Filling/01_FillForm_AdamDetail      00:08        1        1        -        -        - │
  │    s.feature                                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  Form Filling/02_FillForm_jacobDetai      00:05        1        1        -        -        - │
  │    ls.feature                                                                                  │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  Form Filling/03_FillForm_johnDetail      00:05        1        1        -        -        - │
  │    s.feature                                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  OrangeHRM/01_OrangeHRM_Invalidlogin      00:08        1        1        -        -        - │
  │    .feature                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  OrangeHRM/02_OrangeHRM_validlogin.f      00:06        1        1        -        -        - │
  │    eature                                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  SauceDemoLogin/01_SourceDemo_Invali      00:02        1        1        -        -        - │
  │    dlogin.feature                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  SauceDemoLogin/02_SourceDemo_locked      00:02        1        1        -        -        - │
  │    User.feature                                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  SauceDemoLogin/03_SourceDemo_validl      00:02        1        1        -        -        - │
  │    ogin.feature                                                                                │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:41        8        8        -        -        -

**Comment by JomyGeo** [comment]
@badeball  Can you please execute the same multiple times. So that you can reproduce it

P.S: It is  getting reproduced randomly. Beacuse of this problem, Daily build jobs getting failed in jenkins

**Comment by badeball** [comment]
I ran it ten times, still observing expected behavior.

**Comment by JomyGeo** [comment]
@badeball  It usually occurs when we have more feature files and more scenarios on a feature. Can you please run the same in multiple terminal at same time. Then you can reproduce the issue in the second Terminal

**Comment by badeball** [comment]
I understand that you're seeing this in CI, but have you yourself tried to use the example to reproduce the behavior locally? IE. does your example work at all?

**Comment by JomyGeo** [comment]
@badeball Yes, It is reproducing in the local machine and CI. The screenshot that I attached above is reproduced on a local machine.

**Comment by badeball** [comment]
Still can't reproduce despite running it in parallel.

**Comment by JomyGeo** [comment]
@badeball  Somewhere it is breaking the execution. I'm able to reproduce the issue 2 out of 5 times. I suspect, More load on a machine makes the issue. **(Running high volume scripts parallel )** Please run this example along with any other projects/scripts that you have on your local machine.  Meanwhile, i will attach the screen record of the issue during the execution.

**Comment by badeball** [comment]
I _highly_ doubt that this is load dependent. Furthermore, I doubt that it has anything to do with the preprocessor at all. In any case, I'm not going to investigate any further until you can provide a (more) consistent way of reproducing the issue.

**Comment by JomyGeo** [comment]
@badeball  Consistently reproducing the issue in Windows machine. 
 [Click to view the screenrecord](https://www.loom.com/share/c712cd1d952b4808a4262406c3e5d939)

**Comment by badeball** [comment]
I can see from the video that Cypress has resolved specs out-of-order from the initial output, before the preprocessor is ever invoked. I'm guessing this is due to the fact that fast-node, which globby is based on, which cypress use, does not return in a defined order:

> This package provides methods for traversing the file system and returning pathnames that matched a defined set of a specified pattern according to the rules used by the Unix Bash shell with some simplifications, meanwhile results are returned in **arbitrary order**.

(from https://github.com/mrmlnc/fast-glob)

Closing as this has got nothing to do with the preprocessor.

**Comment by badeball** [comment]
I was actually able to reproduce this on Windows and I confirmed that `glob` isn't the culprit here. The preprocessor returns the same `specPattern` property, yet Cypress somehow still runs them out-of-order. I can't look more into why.
