### ISSUE TITLE
Step Definitions are not recognized when using a custom path

### ISSUE THREAD

**Issue by HikariSenshi** [badeball/cypress-cucumber-preprocessor#962]
I have a configuration with typescript+browserify and cucumber preprocessor and next structure.

> -- root

    -- api
    -- any other type of testing
    -- lib (directory with POM and other utilities that we need for testing)
    -- ui (directory with a cypress tests)
        -- features (directory with feature file)
            --suite1
            --suite2 
    -- steps  (step def dir which I want to have)
    -- plugins (usual cypress dir)
cypress.config.ts    
package.json

My package.json:

`  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "step_definitions": "ui/**/*.ts"
  }
`

My cypress config:

`
import {defineConfig} from 'cypress'
import {addCucumberPreprocessorPlugin} from "@badeball/cypress-cucumber-preprocessor";
import browserify from "@badeball/cypress-cucumber-preprocessor/browserify";
export default defineConfig({
    fixturesFolder: 'lib/env/fixtures',
    screenshotsFolder: 'reports/ui/screenshots',
    videosFolder: 'reports/ui/videos',
    watchForFileChanges: false,
    viewportWidth: 1300,
    viewportHeight: 800,
    chromeWebSecurity: false,
    defaultCommandTimeout: 60000,
    reporter: 'mochawesome',
    reporterOptions: {
        reportDir: 'reports/ui', 
        overwrite: false,
        html: false,
        json: true,
    },
    e2e: {
        // We've imported your old cypress plugins here.
        // You may want to clean this up later by importing these.
        async setupNodeEvents(
            on: Cypress.PluginEvents,
            config: Cypress.PluginConfigOptions
        ): Promise<Cypress.PluginConfigOptions> {
            // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
            await addCucumberPreprocessorPlugin(on, config);

            on(
                "file:preprocessor",
                browserify(config, {
                    typescript: require.resolve("typescript"),
                })
            );

            // Make sure to return the config object as it might have been modified by the plugin.
            return config;

        },
        specPattern: 'ui/**/*.{feature,features}',
        supportFile: 'ui/support/index.js',

    },
    env: {
        "MAILDEV_PROTOCOL": "https",
        "MAILDEV_HOST": "staging-maildev.salucro-staging.net",
        "EMAIL_PORT": 25,
        "doCaptureLitleRequest": "/xadmin/master/DoCaptureLitle.php?tx_id=",
        "runRecurringJobRequest": "/xadmin/master/recurring/run-recurring-job.php",

    }
})

`
    
### Current behavior

Currently i get missing error step. Steps working only if i am place them in root of the feature files. 
![image](https://user-images.githubusercontent.com/42742113/224219620-a9a413f7-60a0-4bcd-8595-b541fc00d2ac.png)

### Desired behavior

I want to be able to place step definitions anywhere where I want and configure this paths.

### Test code to reproduce

https://github.com/HikariSenshi/cypress-cucumber-custom-step-defs

### Versions

* **Cypress version**: 12.7.0
* **Preprocessor version**: 15.1.4
* **Node version**: 18.3.0

### Checklist

1. I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
2. I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
3. I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md
