### ISSUE TITLE
Messages don't log correct execution duration for steps with status: "failed"

### ISSUE THREAD

**Issue by golinskiSt** [badeball/cypress-cucumber-preprocessor#963]
### Current behavior

Using messages system as a source of data for reports. Messages don't correctly log how much time scenarion is being executed if first step fails. In messages this time is saves as 0.
![image](https://user-images.githubusercontent.com/30158798/224254662-5c81376b-ae55-47aa-a723-831af072d30c.png)

### Desired behavior

Messages correctly log time of execution for steps ans scenarios with status "FAILED"

### Test code to reproduce

https://stackblitz.com/edit/angular-orraiy?file=cypress.config.ts
### Versions

* **Cypress version**: ^12.3.0"
* **Preprocessor version**: ^15.1.2
* **Node version**: v16.17.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This has been fixed with v17.2.0.
