### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by AJ-309** [badeball/cypress-cucumber-preprocessor#965]
I am seeing this error

Missing preprocessor event handlers (this usally means you've not invoked addCucumberPreprocessorPlugin() or not returned the config object in setupNodeEvents()) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

Because this error occurred during a before all hook we are skipping all of the remaining tests.

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues
