### ISSUE TITLE
Scenario outline is not recognised in report

### ISSUE THREAD

**Issue by RankaPalak** [badeball/cypress-cucumber-preprocessor#966]
### Current behavior

When we use examples in scenario outline itself, the report generated is not able to decode the examples in scenario outline.
<img width="643" alt="Screen Shot 2023-03-13 at 10 22 39 AM" src="https://user-images.githubusercontent.com/69755090/224623426-10428f42-9d9f-4234-8577-3f9be0eb9256.png">

Report Output:
<img width="654" alt="Screen Shot 2023-03-13 at 10 29 07 AM" src="https://user-images.githubusercontent.com/69755090/224624291-6bd2e8e5-b369-4e36-92c2-d281fb5cbfff.png">

cuucmber-report.json:
<img width="1011" alt="Screen Shot 2023-03-13 at 10 34 00 AM" src="https://user-images.githubusercontent.com/69755090/224625329-fcf16104-a761-4f09-8a2d-c06be6fe5083.png">

### Desired behavior

The report should have the example value itself in the scenario outline section.

### Test code to reproduce

https://github.com/WasiqB/multiple-cucumber-html-reporter/issues/69

### Versions

* "cypress": "^10.0.0",
* "@badeball/cypress-cucumber-preprocessor": "^15.1.0",
* "@bahmutov/cypress-esbuild-preprocessor": "^2.1.4",
* **Node version**: v18.14.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This is an issue with the json-formatter and has been reported here: https://github.com/cucumber/json-formatter/issues/25
