### ISSUE TITLE
Retried test cases are reported multiple times in report

### ISSUE THREAD

**Issue by RankaPalak** [badeball/cypress-cucumber-preprocessor#967]
### Current behavior

When we use retry feature in cypress, the report displays all the retried attempts.

Test cases run, the retried attempt is 2 for this case:

<img width="763" alt="Screen Shot 2023-03-13 at 2 17 52 PM" src="https://user-images.githubusercontent.com/69755090/224673252-08af225d-07e5-4cf9-a0d2-ff1dfc185f8e.png">

The report generated displays both the attempts:

<img width="947" alt="Screen Shot 2023-03-13 at 2 18 33 PM" src="https://user-images.githubusercontent.com/69755090/224673420-eb7c0ef8-0e9b-4f1c-ad3c-6ea1d08a6b4b.png">

### Desired behavior

Only the latest attempt should be displayed in the report.

### Test code to reproduce

Add the below code for retries in cypress.config file:
    retries: {
        runMode: 1,
        openMode: 1,
    }

### Versions

"cypress": "^10.0.0",
"@badeball/cypress-cucumber-preprocessor": "^15.1.0",
"@bahmutov/cypress-esbuild-preprocessor": "^2.1.4",
Node version: v18.14.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/cucumber/json-formatter/issues/4
