### ISSUE TITLE
scenarios testrial integration ? 

### ISSUE THREAD

**Issue by MrNeo28** [badeball/cypress-cucumber-preprocessor#968]
I am trying to intergate testrail but so far unsucessful in doing so. Tried this cypress-testrail-reporter, cypress-testrail-simple.

**Comment by badeball** [comment]
I’m not personally familiar with any of those tools, but I’ll leave this open in case anyone else has more insight.

**Comment by deepakksusarla** [comment]
@MrNeo28 We have implemented in our project. We used test rail API to update test results in test rail. 
test rail url :https://***.testrail.com/index.php?/api/v2/
to get sections we used below rest API
https://***.testrail.com/index.php?/api/v2/get_sections/<projectId>

Iterated through results.json file and then created json according to need of test rail API

**Comment by badeball** [comment]
This is clearly not the right place, these kinds of questions don''t get the publicity required.
