### ISSUE TITLE
Throwing Unexpected token � in JSON at position 0 while trying to read cucumber results.json file

### ISSUE THREAD

**Issue by deepakksusarla** [badeball/cypress-cucumber-preprocessor#969]
### Current behavior
Executing cypress in windows machine.

Using ".cypress-cucumber-preprocessorrc.json" to generate cucumber json reports file. But it is not automatically generating the json file.
So explicitly generating results.json file using below command and able to generate json file successfully.

execSync("type TestReports/messages.ndjson | ./JsonFormatter/cucumber-json-formatter > TestReports/Cucumber_Json_Results.json", {'shell':'powershell.exe'});

But when trying to read the results.json file throwing "Unexpected token � in JSON at position 0"
### Desired behavior

Should be able to read results.json file with out any issues

### Test code to reproduce

Here is the preprocessor config.ts

{
  "json": {
    "enabled": true,
    "output": "TestReports/Cucumber_Json_Results.json",
    "formatter": "./JsonFormatter/cucumber-json-formatter"
  },
  "messages": {
    "enabled": true,
    "output": "TestReports/messages.ndjson"
  },
  "html": {
    "enabled": true
  },
  "nonGlobalStepDefinitions": false,
  "stepDefinitions": [
      "cypress/tests/*.ts"
  ]
}
 cypress.config.ts file
import { defineConfig } from "cypress";
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

import * as fs from "fs-extra";
import * as path from "path";
const { execSync } = require('node:child_process');
const os: any = require("os");

const mkdir = require('mkdirp')

async function setupNodeEvents(
  on: Cypress.PluginEvents,
  config: Cypress.PluginConfigOptions
): Promise<Cypress.PluginConfigOptions> {

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin(config)],
    })
  );
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on("before:run", async () => {
   
  })

  

  on('after:run', async () => {
    if (os.type() === "Windows_NT") {
      execSync("type TestReports/messages.ndjson | ./JsonFormatter/cucumber-json-formatter > TestReports/Cucumber_Json_Results.json", {'shell':'powershell.exe'});
      }
       const filePath = path.resolve("TestReports/Cucumber_Json_Results.json");
      const data = require(filePath);
  });

  // Make sure to return the config object as it might have been modified by the plugin.
  return config 
}

export default defineConfig({
  pageLoadTimeout: 120000,
  requestTimeout: 60000,
  responseTimeout: 120000,
  defaultCommandTimeout: 15000,
  screenshotOnRunFailure: true,
  screenshotsFolder: "TestReports/screenshots",
  scrollBehavior: 'center',
  video: false,
  experimentalInteractiveRunEvents: true,
  watchForFileChanges: false,
  e2e: {
    specPattern: "**/*.feature",
    supportFile: "cypress/support/index.ts",
    excludeSpecPattern: [
      "*.js",
      "*.ts",
      "*.md",
      "*.json"
    ],
    chromeWebSecurity: false,
    setupNodeEvents,
  },
});

package.json
"dependencies": {
    "cypress": "12.6.0",
    "@badeball/cypress-cucumber-preprocessor": "15.1.4",
    "@bahmutov/cypress-esbuild-preprocessor": "2.2.0",
    "@types/cypress": "1.1.3",
    "typescript": "4.9.5",
    "@types/cucumber": "7.0.0",
    "cucumber": "6.0.7",
    "esbuild": "0.17.11"
  }

### Versions

* **Cypress version**: 12.6.0
* **Preprocessor version**: 15.1.4
* **Node version**:v18.14.2

### Checklist

- [&check;] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [&check;] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [&check;] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md

**Comment by deepakksusarla** [comment]
Hi @badeball , Thanks for providing the link. Can you please provide some context on this. As I am not able to understand what to do with event handlers for the issue that I am facing.  "**Throwing Unexpected token � in JSON at position 0 while trying to read cucumber results.json file**"

I tried adding the code that provided in the link https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md. But still I am getting the error.

Cucumber results.json file is getting generated but not able to read that file. I copied the json content and viewed in "https://jsonviewer.stack.hu/" to see whether there is any error in json. But no json error displayed. and content properly displayed.

**Comment by badeball** [comment]
I'm guessing your shell prepends a byte order mark, but it's difficult to say. You don't even provide the file that you're unable to read.

**Comment by deepakksusarla** [comment]
Hi. Thanks for providing info "shell prepends a byte order mark". I encoded the json file with ASCII and issue resolved.
