### ISSUE TITLE
Unable to generate cucumber-report.json

### ISSUE THREAD

**Issue by rakeshnambiar** [badeball/cypress-cucumber-preprocessor#970]
### Current behavior

When I move the feature files to cyprss/e2e/features and add the below code block in the package.json to detect the stpe defenition it is not generating the json report. 
```
  "cypress-cucumber-preprocessor": {
    "stepDefinitions": "cypress/e2e/**/*.{js,ts}",
    "cucumberJson": {
      "generate": true
    }
  }
```

### Desired behavior

It should benegrate `cucumber-report.json` in the `cypress/generate-reports` folder

### Test code to reproduce

https://github.com/rakeshnambiar/browsify-report-issue

### Versions

* **Cypress version**: 12.0.7
* **Preprocessor version**: latest
* **Node version**:  v19.4.0

### Checklist

- [ x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x ] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [ x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by rakeshnambiar** [comment]
@badeball appreciate if you could help me

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md

**Comment by rakeshnambiar** [comment]
Thanks. It worked. In fact, I tried it earlier and it was generating in the root folder. Now I am removing the `.cypress-cucumber-preprocessorrc.json` and use the below config in the `package.json`

```json
  "cypress-cucumber-preprocessor": {
    "stepDefinitions": "cypress/e2e/**/*.{js,ts}",
    "json": {
      "enabled": true,
      "output": "cypress/generate-reports/cucumber-report.json"
    }
  }
  ```
