### ISSUE TITLE
unable to run any scripts after initial setup

### ISSUE THREAD

**Issue by sonesnema** [badeball/cypress-cucumber-preprocessor#972]
I want to do initial setup for this repository I have cloned this repo then run npm build then npm watch but when i try to run any script like npm run test it throwing error,let me know what prerequisite i am missing  No files matching the pattern were found: "'**/*.ts'
when running npm run test:unit
     Error: Expected [
  '/cypress/e2e/foo/bar/baz/step_definitions/*.ts',
  '/cypress/e2e/foo/bar/step_definitions/*.ts',
  '/cypress/e2e/foo/step_definitions/*.ts',
  '/cypress/e2e/step_definitions/*.ts'
], but got [
  '/cypress/e2e/foo\\bar\\baz/step_definitions/*.ts',
  '/cypress/e2e/foo\\bar/step_definitions/*.ts',
  '/cypress/e2e/foo/step_definitions/*.ts',
  '\\cypress\\e2e\\step_definitions\\*.ts'
]

**Node version 18.12
Npm Version**8.5.5
Cypress version cypress-cucumber-preprocessor": "^15.1.5",

can you explain what are the all steps nees to taken after cloning the repo

**Comment by badeball** [comment]
There are no other steps as far as I know and I can’t explain the results you’re getting given the provided information.
