### ISSUE TITLE
How to integrate screenShot of testCase Success in the JSON report

### ISSUE THREAD

**Issue by jasp402** [badeball/cypress-cucumber-preprocessor#975]
### Current behavior

Currently, when a Case test fails. it automatically creates a ScreenShot. This is recorded in the JSON report.
This works correctly thanks to function: `screenshotOnRunFailure()`. 
@screenshotOnRunFailure(true)
@screenshotOnRunFailure(false)
But I need you to also record the evidence of successful cases.

I was reading about controllers, however I don't think I know how to use it or if this could be useful.
```
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import {
  addCucumberPreprocessorPlugin,
  beforeRunHandler,
  afterRunHandler,
  beforeSpecHandler,
  afterSpecHandler,
  afterScreenshotHandler,
} from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";

export default defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    async setupNodeEvents(on, config) {
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await addCucumberPreprocessorPlugin(on, config, {
        omitBeforeRunHandler: true,
        omitAfterRunHandler: true,
        omitBeforeSpecHandler: true,
        omitAfterSpecHandler: true,
        omitAfterScreenshotHandler: true,
      });
//. . . 
on("after:screenshot", async (details) => {
        await afterScreenshotHandler(config, details);

        // Your own `after:screenshot` code goes here.
      });
```

### Desired behavior

As I said before, it is possible that I am not doing things correctly. But it could help a lot to complement the documentation.

### Versions

* **Cypress version**:  "cypress": "^12.2.0"
* **Preprocessor version**: "@badeball/cypress-cucumber-preprocessor": "^13.0.2",
* **Node version**: 16.16.0 (LTS)

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by jasp402** [comment]
I found someone with the same query as me.
https://stackoverflow.com/questions/73273947/attach-screenshots-to-cucumber-html-report-for-passed-as-well-as-for-failed-scen

**Comment by badeball** [comment]
Screenshots are automatically added to JSON reports, as per [docs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/json-report.md#screenshots), so you can just take a screenshot.
