### ISSUE TITLE
[BUG] Step definition pattern match regression in 16.0.0

### ISSUE THREAD

**Issue by remarkablemark** [badeball/cypress-cucumber-preprocessor#976]
### Current behavior

When upgrading `cypress-cucumber-preprocessor` to [16.0.0](https://github.com/badeball/cypress-cucumber-preprocessor/releases/tag/v16.0.0), I am getting the errors:

```
Step implementation missing for "I do not fail on uncaught exception".

We tried searching for files containing step definitions using the following search pattern templates:

  - /[filepath]/**/*.{js,mjs,ts,tsx}
  - /[filepath].{js,mjs,ts,tsx}
  - cypress/support/step_definitions/**/*.{js,mjs,ts,tsx}

These templates resolved to the following search patterns:

  - ../../../../../cypress/e2e/w3c/w3c/**/*.{js,mjs,ts,tsx}
  - ../../../../../cypress/e2e/w3c/w3c.{js,mjs,ts,tsx}
  - cypress/support/step_definitions/**/*.{js,mjs,ts,tsx}

These patterns matched the following files:

  - cypress/support/step_definitions/index.ts

However, none of these files contained a step definition matching "I do not fail on uncaught exception".

You can implement it using the suggestion(s) below.

  Given("I do not fail on uncaught exception", function () {
    return "pending";
  });
```

### Desired behavior

A step definition file relative to the feature file should continue to work

### Test code to reproduce

1. https://github.com/remarkablemark/cypress-cucumber-steps/pull/261
2. https://github.com/lilboards/lilboards/pull/1115

### Versions

* **Cypress version**: 12.8.1
* **Preprocessor version**: 16.0.0
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
If you previously had configured `specPattern` to equal `**/*.feature` (or similar), then you should change it to `cypress/e2e/**/*.feature` in order to not accidentally include feature files located in `node_modules`. This will otherwise interfere with the calculation of the *common ancestor path* and thus step definition resolution.

**Comment by badeball** [comment]
For future reference and those who are curious: the background for this is that an update in the dependencies, specifically moving `@cucumber/cucumber` from devDeps to mer deps, caused a feature-file to be installed in node_modules upon installation. The `@badeball/cypress-configuration` package, which is a re-implementation of some Cypress internal mechanisms, would resolve this feature file, while Cypress would not. IE. there's a discrepancy between the implementation and the re-implementation. This newly added feature file in people's node_modules would be picked up by `@badeball/cypress-configuration` and this would affect the common ancestor path which is calculated for Cypress projects post v10. Additionally, there's a bug with projects where the common ancestor path is determined to be equal to the project root path.

**Comment by remarkablemark** [comment]
Thanks @badeball for the quick response! Changing `specPattern` from `**/*.feature` to `cypress/e2e/**/*.feature` fixed it for me.

**Comment by badeball** [comment]
The need for the above-mentioned changes is gone as of v16.0.3. In other words, upgrading from v15 to v16 now _doesn't_ require any changes, assuming one doesn't specifically target any of the earlier 16-versions.
