### ISSUE TITLE
Scenarios are not visible in report when present with Scenario Outline in same feature file

### ISSUE THREAD

**Issue by RankaPalak** [badeball/cypress-cucumber-preprocessor#978]
### Current behavior

When we add Scenario and Scenario outline together in a feature file, the report only shows the scenario outline execution and not the scenario present in the same file with feature file.

### Desired behavior

The report should have execution detail for both Scenario and Scenario outline.

### Test code to reproduce

Feature File:

Feature: Test File

    Scenario: Test Example
      Given the target word is
        | word |
        | A    |
        | B    |

    Scenario Outline: Test Scenario Outline
      Given The target word is "<word>"
      Examples:
        | word |
        | A    |
        | B    |

Step Definition File:

```
import { Given} from "@badeball/cypress-cucumber-preprocessor";
import { assert } from '../components/assertions.js';

Given("the target word is", (table) => {
 let data = table.hashes();
        data.forEach((element) => {
           cy.log(element.word);
        });

});

Given("The target word is {string}", (word) => {

cy.log('Words:',word )

});
```

Execution Report:
 The json and html report shows the execution steps for only Scenario outline and nothing for Scenario.

### Versions

* **Cypress version**:     "cypress": "^10.0.0",
* **Preprocessor version**: "@badeball/cypress-cucumber-preprocessor": "^16.0.0",
* **Node version**: v18.14.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
You need to provide a runnable example that illustrates the issue.

**Comment by sagar-maheshwari** [comment]
@RankaPalak We use scenario & scenario outline in a single feature file and have no issues with the JSON or html.

**Comment by RankaPalak** [comment]
@badeball - the example I created is not reproducing this issue. But I can still see the issue persisting in my ongoing project. I'll try to find the cause and the difference between these and will update.
