### ISSUE TITLE
Webpack compilation Error

### ISSUE THREAD

**Issue by marijana-rukavina** [badeball/cypress-cucumber-preprocessor#981]
### Current behavior

When I try to run the test I get the error:
```
Error: Webpack Compilation Error
./cypress/e2e/Account/Login.feature 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @login @app
| Feature: Login to webshop
|
```

### Desired behavior

It should run the test without any errors

### Test code to reproduce

Followed the steps to upgrade to Cypress 12 from this blog https://testersdock.com/cypress-cucumber-bdd/

### Versions

* **Cypress version**: 12.9.0
* **Preprocessor version**: 16.0.1
* **Node version**:  16.18.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
> It should run the test without any errors

You seem to imply that following a blog should not result in any errors, but that's not the case. I can't control what other people write about this library. I can see from glancing at it, that it's severely outdated. I recommend that you take a look at any of the official [exampes](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples) instead.

**Comment by marijana-rukavina** [comment]
Hey, thanks for the feedback. 
I tried to use the example: https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/esbuild-cjs

But somehow I get now the error: 

```
Step implementation missing for "User enters the webshop page".



We tried searching for files containing step definitions using the following search pattern templates:



  - cypress/stepDefinitions/*.js



These templates resolved to the following search patterns:



  - cypress\stepDefinitions\*.js



These patterns matched no files containing step definitions. This almost certainly means that you have misconfigured stepDefinitions.
```

Not sure where is this coming from ... 
Do you have any idea what could be wrong?

**Comment by badeball** [comment]
The error is fairly informative IMO. Should it find any step definitions at the mentioned location?

**Comment by marijana-rukavina** [comment]
I got it resolved once I removed the node_modules folder and did npm ci again, I guess something was left from the previous attempts. The example you provided works as a  charm. Thanks so much for the feedback and the help :)
