### ISSUE TITLE
Question: Does the naming of feature files and steps matter?

### ISSUE THREAD

**Issue by marijana-rukavina** [badeball/cypress-cucumber-preprocessor#984]
This is more of a question to the relevant people - authors of the plugin. 
Is there any convention we need to follow when writing the feature files and steps?
Any special naming conventions to link steps to the corresponding feature file?
Any special folder structure to follow as it was before with the previous plugin?
Is any configuration to be done in addition to this?
Hope I will get an accurate answer here :) 
Thanks!

### Versions

* **Cypress version**: 12
* **Preprocessor version**: 15.1.5
* **Node version**: 16.18.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [Instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
I don't offer any opinion to these questions and your question probably won't get any publicity here. Instead I recommend searching and when you search, leave "cypress" as a keyword out of it. Cucumber and BDD came well before Cypress. My experience so far is that adding "cypress" as a keyword to general questions that transcends Cypress, only serves to reduce the quality of the search results.

**Comment by badeball** [comment]
In case you don't know, Cypress has its own discord server where you might get more response than here.
