### ISSUE TITLE
Adding too many test cases for Scenario Outline crashes Google Chrome.

### ISSUE THREAD

**Issue by kostia-Etaplus** [badeball/cypress-cucumber-preprocessor#987]
### Current behavior

When I added 5 test cases for Scenario Outline it crashes every other time. With 17 test cases it was crushing every time.
It causes Google Chrome error "Aw, Snap!" and gives link to [this page](https://support.google.com/chrome/answer/95669?visit_id=638165768407580751-3052045286&p=e_awsnap&rd=1).
All the test cases work properly separately (some fail, some succeed, but they work without crushing Google Chrome).

### Desired behavior

It should work stabelly without crushing browser.

### Test code to reproduce

I'm dealing with NDA so I can't provide full source code as is. I'll ask permission about what I can post here.
Basically Scenario Outline is login, go to page, fill the form, create record, validate that everything was saved, delete the record.
Nothing supernatural. And I've been experiencing it with 2 scenarios already.
Probably you could try first to reproduce it with any Scenario Outline that you have and just try to add many many test cases.

### Versions

* **Cypress version**: "@nrwl/cypress": "15.5.2"
* **Preprocessor version**: "@badeball/cypress-cucumber-preprocessor": "^15.1.5"
* **Node version**: v16.14.2

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Hey, and thanks for reporting this issue. You need to provide a [minimal, reproducible example issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by kostia-Etaplus** [comment]
I've spent whole day trying to reproduce it outside of our website and didn't succeed so far. But I've noticed that the error is "out of memory". Looks like this:
![image](https://user-images.githubusercontent.com/121185810/231197521-b9d02857-9af5-4ab5-81ee-62ca9b8e7ecd.png)

Also I've tried to run same code in a separate 17 scenarios with hardcoded parameters values instead of Scenario Outline with 17 examples and it was still out of memory error.

I've tried to run everything (17 Scenarios and Scenario Outline with 17 examples) via console (without `--watch` parameter) and it executed all 34 without any problem. So seems like the root cause has to do with a test execution in a visible for a user way.

I've checked my RAM and hard drive and they are not an issue. RAM stayed within 45-55% during tests execution and hard drive also has planty of memory.

I suspect that probably cypress tries to remember website state during work of tests as a complete state in RAM and as test goes it builds such a big amount of info that it exceeds OS limit per process. And since Google Chrome breaks its work into processes for each tab, only tab with tests crashes. Or it also might be Chrome's limit of memory.

Oh, and I checked that exect same scenario and website via plain cypress - it results in the same out of memory error.

So seems like there's nothing to do here within the preprocessor. It's either cypress memory managment probably could be optimized somehow or chrome memory limit could be edited (probably, I'm not sure) or we just have to execute tests in a `--watch` mode in limited chunks.

What do you think about it?

**Comment by badeball** [comment]
> What do you think about it?

I think you've stumbled upon a known limitation of Cypress, unfortunately, as explained [here](https://github.com/cypress-io/cypress/issues/431#issuecomment-320082677).
