### ISSUE TITLE
How i can add the And keyword??

### ISSUE THREAD

**Issue by DinoFra** [badeball/cypress-cucumber-preprocessor#988]
Feature: Add TODO item
As a user
I want to add a new todo item
So that I can easily access to it in the list

Scenario: Add a new TODO item
Given I open the application
And access to the landing page <--------- Do this in file.ts

And i have in file.ts:

import {Given, When, Then } from '@badeball/cypress-cucumber-preprocessor';

Given('I open the application', () => {
    cy.visit('https://example.cypress.io/todo');
    cy.contains('.header h1', 'todos');
});

**Comment by badeball** [comment]
From https://stackoverflow.com/questions/24747464/how-to-use-and-in-a-gherkin-using-cucumber-js:

> `And` is only used in scenarios, not as step definition methods. Semantically it means "same keyword as in previous step"; technically it is just another step. In fact, you can use `Given()`, `When()` and `Then()` interchangeably in your step definitions, Cucumber will not enforce a match between the step keyword and the step definition function.

Even though the question in SO relates to cucumber-js, the same applies to the preprocessor.
