### ISSUE TITLE
run a scenario within hook

### ISSUE THREAD

**Issue by aj-sdet** [badeball/cypress-cucumber-preprocessor#990]
### Desired behavior

what I am trying to achieve is to trigger running certain scenario by putting it in the hook so all those steps run before my actual scenario

Scenario 1
Given something is done
...
...
...
Then something happened

@tagged
Scenario 2
Given scenario 2
...
...
...
Then scenario 2 validation

Before({ tags: '@tagged' }, () => {
    runScenario1();  //or some codde that will run scenario 1
});

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
Nothing of the sort exist. Why do you want this?

**Comment by aj-sdet** [comment]
``Imagine a scenario where I create a lead, and then I want to create a job, for me to create a job I need customer created so instead of pasting all of the steps from scenario where I create customer in front of creating a job I wanted to run it in before hook, essentially so my Scenarios are not way too long.

Another quick question, chatGPT spitted out this code snippet to me and it relies on deprecated cucumber-preprocessor, was wondering if this imported cucumber function is legit in that legacy repo, if so any chance this can be implemented in current preprocessor?


```
const cucumber = require('cypress-cucumber-preprocessor').default;

module.exports = (on, config) => {
  on('task', {
    runScenario(path, scenarioName) {
      return cucumber({
        ...config,
        browser: config.browser.name,
      }, {
        featurePath: path,
        scenarioName: scenarioName,
        ignoreTestHook: true,
      });
    }
  });
}
```

**Comment by badeball** [comment]
https://cucumber.io/docs/gherkin/reference#background

**Comment by badeball** [comment]
As for the chatgpt code, it's just bogus.
