### ISSUE TITLE
Report is missing an attachment

### ISSUE THREAD

**Issue by jokeks** [badeball/cypress-cucumber-preprocessor#994]
### Current behavior

The goal is to add a stacktrace to the Report. 

```javascript
# e2e.js

function attachError(error) {
    const message = error.codeFrame?.originalFile + '(' + error.codeFrame?.line + ') \n \n' +
        error.stack + '\n\n' +
        error.codeFrame?.frame

    attach(message, "text/plain");
}

Cypress.on('fail', (error, runnable) => {
    attachError(error);
    debugger;
    // throw error to have test still fail
    throw error
})
```

With two failing scenarios only the last one has an 'text/plain' attached, but the Cypress.on-failed is executed twice.

![grafik](https://user-images.githubusercontent.com/2502808/231411516-359243b4-b72d-4fc4-b4d4-09fd95d94f39.png)

### Desired behavior

Any attachment attached should show up. 

### Test code to reproduce
```javascript
# cypress.config.js
import {defineConfig} from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import preprocessor from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild.js";


export async function setupNodeEvents(on, config) {
    // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
    await preprocessor.addCucumberPreprocessorPlugin(on, config);

    on(
        "file:preprocessor",
        createBundler({
            // Allows the test failure to display the failing source code :)
            sourcemap: "inline",
            plugins: [createEsbuildPlugin.default(config)],
        })
    );

    // Make sure to return the config object as it might have been modified by the plugin.
    return config;
}

export default defineConfig({
    env: {},
    downloadsFolder: "result/downloads",
    screenshotsFolder: "result/screenshots",
    videosFolder: "result/videos",
    numTestsKeptInMemory: 5,
    defaultCommandTimeout: 10000,
    pageLoadTimeout: 90000,
    viewportWidth: 1024,
    viewportHeight: 768,
    video: false,
    download: false,
    screenshotOnRunFailure: true,
    chromeWebSecurity: false,
    watchForFileChanges: false,
    e2e: {
        setupNodeEvents,
        specPattern: "cypress/e2e/**/*.feature",
        baseUrl: "http://localhost:4200/"
    },
});

```

### Versions

* **Cypress version**: 12.9.0
* **Preprocessor version**: 16.0.3
* **Node version**: 16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
The `attach()` method will implicitly invoke a task. As explained in https://github.com/cypress-io/cypress/issues/1217#issuecomment-398461289, https://github.com/cypress-io/cypress/issues/6316#issuecomment-878445017 and many more, invoking any kind of command in fail handlers is disallowed in the sense that  the behavior is undefined. Cypresss will however silently accept it.

In other words, you can't / shouldn't invoke `attach()` there.
