### ISSUE TITLE
Error ENOENT no such file or directory appdate/cypress/cy/production/projects/custom-project-123456/bundles/cypress/e2e/featureFile.feature

### ISSUE THREAD

**Issue by jmjsdev** [badeball/cypress-cucumber-preprocessor#996]
### Current behavior

I have an error when I run a `.feature` file
I use vite.js latest version and cypress 12.9.0

```log
Error: ENOENT: no such file or directory, stat 'C:\Users\XXXXX\AppData\Roaming\Cypress\cy\production\projects\CustomProject-276ae7c194632a7be39c4de44a9223c4\bundles\cypress\e2e\featureFile.feature'
```
![cypresserror](https://user-images.githubusercontent.com/2287663/231755674-37465bb3-f178-485f-8600-d7b3281272cd.jpg)

### Desired behavior

Running the feature file inside the current directory of my project

### Test code to reproduce

my cypress.config.ts file is : 

```typescript
import { defineConfig } from "cypress";
import { getLocalChromium } from "./cypress/support/configUtils";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { createEsbuildPlugin } from "@badeball/cypress-cucumber-preprocessor/esbuild";
import cypressCucumberPreprocessor from "@badeball/cypress-cucumber-preprocessor";
import vitePreprocessor from "cypress-vite";
import path from "path";

const { addCucumberPreprocessorPlugin } = cypressCucumberPreprocessor;

export default defineConfig({
  viewportWidth: 1400,
  viewportHeight: 800,

  e2e: {
    baseUrl: "http://localhost:3000/",
    specPattern: "**/*.feature",
    experimentalStudio: false,
    // @ts-ignore
    setupNodeEvents: async (on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions): Promise<Cypress.PluginConfigOptions> => {
      await addCucumberPreprocessorPlugin(on, config);

      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );

      on("file:preprocessor", vitePreprocessor(path.resolve(process.cwd(), "./vite.config.ts")));
      const browsers = getLocalChromium(config);
      return {
        ...config,
        // @ts-ignore
        browsers,
      };
    },
  },
});

```

### Versions

* **Cypress version**: 12.9.0
* **Preprocessor version**: ^16.0.3
* **Node version**: v16.16.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by jmjsdev** [comment]
I close the issue because I update my node version to 18.19.0 and it works, now I have to find why my step deinitions are not recognized

**Comment by quinnturner** [comment]
I am also having a similar issue:

/Users/quinn/Library/Application Support/Cypress/cy/production/projects/cypress-1b5d9623b538800d601d3a0751d7a2d2/bundles/cypress/e2e/cypress.feature


Almost identical configuration.

**Comment by badeball** [comment]
@quinnturner, you need to provide a minimal, reproducible example as explained in the contribution guidelines.

**Comment by tuliacms** [comment]
I had the same problem. Finally I done that:

- remove -rf node_modules
- remove package-lock.json
- npm install

And problem vanished :)

**Comment by nsmorisset** [comment]
Hello

Same problem with the plugins @badeball/cypress-cucumber-preprocessor and cypress open

On my side the problem is linked to an **invalid import into a file**

For example
spec_1.feature with step_1.js  
spec_2.feature with step_2.js

In step_1.js, I imported a plugins but I had not done npm install [pluging]

When I tried to run the spec_2.feature tests, I got the error 

> Error ENOENT no such file or directory appdate/cypress/cy/production/projects/custom-project-123456/bundles/cypress/e2e/featureFile.feature

I have the impression that badeball executes the cache on error.
Now I deleted my import and it's OK.


Identifying the problem by running cypress from the command line

> npx cypress run --spec "cypress/e2e/features/[path_to_feature].feature" 

which tells me: "Build Failed with 1 error"

**Comment by badeball** [comment]
> I have the impression that badeball executes the cache on error.

This is a known issue with `@bahmutov/cypress-esbuild-preprocessor`.

**Comment by nids2307** [comment]
@badeball - Are there any further updates on this issue. I have run into this multiple times in the last few months and wondering if there is a specific badeball/cypress-cucumber-preprocessor, @bahmutov/cypress-esbuild-preprocessor and Cypress version that I should be sticking with to get this resolved.

**Comment by badeball** [comment]
> Are there any further updates on this issue.

This is a closed issue, in which I am not working on.

**Comment by nids2307** [comment]
It was open until a few mins ago hence I thought of checking.
Is there a fix available as apprently there is an issue with the esbuild processor

**Comment by badeball** [comment]
I am unfortunately not aware of any fix.

**Comment by sajeerk123** [comment]
I am also facing same issue. Could you please help me
My version and dependencies are 
`"dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^22.0.1",
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.0",
    "@shelex/cypress-allure-plugin": "^2.39.1",
    "@testing-library/cypress": "^10.0.1",
    "cypress": "^13.16.0",
    "cypress-cucumber-preprocessor": "^4.3.1",
    "cypress-if": "^1.10.5",
    "cypress-iframe": "^1.0.1",
    "cypress-real-events": "^1.11.0",
    "cypress-social-logins": "^1.14.1",
    "cypress-xpath": "^2.0.1",
    "esbuild": "^0.25.0",
    "multiple-cucumber-html-reporter": "^3.4.0",
    "pdf-parse": "^1.1.1"
  },
  "devDependencies": {
    "mocha": "^11.1.0"
  }`

![Image](https://github.com/user-attachments/assets/4074991e-e733-459c-84dc-16a76ac6d55b)
