### ISSUE TITLE
Availability of the options json.formatter and json.args

### ISSUE THREAD

**Issue by denissonp** [badeball/cypress-cucumber-preprocessor#997]
### Current behavior

The options json.formatter and json.args have been removed. With the native components, no child process is spawned.

### Desired behavior

Availability of the options json.formatter and json.args for other usage such as:
Adding a meta data to the cucumber HTML Report.

### Test code to reproduce

.cypress-cucumber-preprocessorrc.json file:
```json
{
  "json": {
    "enabled": true,
    "output": "cypress/cucumber-json/cucumber-json.json",
    "formatter": "node",
    "args": [
      "cypress/helper/setJsonMetaData.js"
    ]
  },
  "html": {
    "enabled": true
  },
  "filterSpecs": true,
  "omitFiltered": true
}
``` 

setJsonMetaData.js file:

```javascript
async function writeToFile(newNJson) {
    var fs = require('fs');
    fs.writeFileSync("cucumber-messages.ndjson", newNJson);
}

async function readJsonFromStdin() {
    let stdin = process.stdin
    let inputChunks = []
  
    stdin.resume()
    stdin.setEncoding('utf8')
  
    stdin.on('data', function (chunk) {
      inputChunks.push(chunk);
    });
  
    return new Promise((resolve, reject) => {
      stdin.on('end', function () {
        let inputJSON = inputChunks.join('')
        const jsonResult = `{"meta":{"implementation":{"name":"TestName","version":""},"runtime":{"name":"ABC","version":"Latest"},"os":{"name": "${process.platform}"}}}\n${inputJSON}`
        resolve(jsonResult)
      })
      stdin.on('error', function () {
        reject(Error('error during read'))
      })
      stdin.on('timeout', function () {
        reject(Error('timout during read'))
      })
    })
  }
  
  async function main() {
    let json = await readJsonFromStdin();
    await writeToFile(json)
  }
  
  main()
``` 

### Versions

* **Cypress version**: 12.7.0
* **Preprocessor version**: [16.0.0](https://github.com/badeball/cypress-cucumber-preprocessor/releases/tag/v16.0.0)
* **Node version**: 16.13.0

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
That option was never really intended for this usage. Instead, you should use life cycle methods to do post-processing, like shown below.

```js
const fs = require("node:fs/promises");
const { defineConfig } = require("cypress");
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");

async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config, {
    omitAfterRunHandler: true,
  });

  on("after:run", async () => {
    await preprocessor.afterRunHandler(config);

    await fs.writeFile(
      "cucumber-messages.ndjson",
      JSON.stringify({ meta: { os: { name: process.platform } } }) + "\n",
      { flag: "a" }
    );
  });

  on(
    "file:preprocessor",
    createBundler({
      plugins: [createEsbuildPlugin.default(config)],
    })
  );

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

module.exports = defineConfig({
  e2e: {
    specPattern: "**/*.feature",
    setupNodeEvents,
  },
});
```

**Comment by denissonp** [comment]
Thank you, @badeball , however this solution only works partially:

Only the ndjson file gets updated, not the cucumber-report.html.

In that case I would have to set the html.enable to false and find another way to generate the html file based on the updated ndjson.

**Comment by badeball** [comment]
You can move the post-processing above the call to `afterRunHandler`, that way the HTML report will be affected.
