### ISSUE TITLE
Step definitions configurations on `package.json` not working

### ISSUE THREAD

**Issue by ranitopus** [badeball/cypress-cucumber-preprocessor#999]
### Current behavior

When configuring the patterns to find the step definitions within your project's source code as described on [this docs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md), if you choose to put the configuration inside your `package.json` file, those configurations are ignored by the preprocessor. If you choose to configure these patterns in a `.cypress-cucumber-preprocessorrc.json` file, it works fine.

### Desired behavior

As the documentation describes, this configuration should work in both cases: when you choose to put it inside your `package.json`, or when you choose to put it inside a `.cypress-cucumber-preprocessorrc.json` file.

### Test code to reproduce

* In your project's `package.json` root scope, add (following [this docs](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md)):
```json
{
  ...
  "stepDefinitions": [
    "cypress/support/steps/**/*.{js,ts}"
  ]
  ...
}
```
* Don't add any extra configuration for your step definitions anywhere else
* Define your Cucumber step definitions inside the `cypress/support/steps` directory
* In a minimal project (any project using Cucumber/Gherkin for test scenarios with Cypress) use all the default configuration for the preprocessor [as defined in this documentation](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/quick-start.md)

### Versions

* **Cypress version**: 10.3.0
* **Preprocessor version**: 16.0.3
* **Node version**: 18.9.1

### Checklist

- [x] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [x] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [x] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/configuration.md
